### ISSUE TITLE
是否支持美团mpvue环境?

### ISSUE THREAD

**Issue by netbuffer** [NervJS/taro-ui#10]

**Comment by jimczj** [comment]
目前我们 Taro 框架组在尝试将 Taro 代码 直接编译成微信小程序原生引用方式的代码，如果这个特性完成，理论上可以做到这一点

**Comment by craigchencc** [comment]
> 目前我们 Taro 框架组在尝试将 Taro 代码 直接编译成微信小程序原生引用方式的代码，如果这个特性完成，理论上可以做到这一点

请问你们 Taro 框架组还打算实现这个功能吗
