### ISSUE TITLE
taro-ui中AtSwipeAction组件在h5页面上下滑动报错

### ISSUE THREAD

**Issue by modtwuji** [NervJS/taro-ui#1000]
![image](https://user-images.githubusercontent.com/51849466/77640298-1b79d180-6f95-11ea-9793-5b4ed846e5be.png)

**Comment by Garfield550** [comment]
麻烦给一个复现用例可以吗？
我尝试过把整个页面用很多 View 填充使它能滑动，也尝试过用 `ScrollView` 和 `scrollY scrollWithAnimation` 属性把它们包起来，没有出现这个问题。
我用的是 Taro 2.0.7 ，Taro UI 2.3.2 请问可以提供更详细的信息吗？
