### ISSUE TITLE
企业微信侧滑删除回弹

### ISSUE THREAD

**Issue by Wkevin8** [NervJS/taro-ui#1002]
**问题描述**
企业微信侧滑删除回弹

**复现步骤**
一个tabbar下有购物车，产品列表
在购物车没有数据的时候进入购物车，然后在从产品列表页中往购物车加入数据，在去购物车也中侧滑删除就会回弹，
如果是先在产品列表页加入数据到购物车，在进入到购物车，购物车里面有数据，删除就不会回弹

```js
// 这里可以贴代码
```

**期望行为**
侧滑删除不回弹

**报错信息**
无报错

**系统信息**
  Taro CLI 1.3.37 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.10.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.3.37 => 1.3.37 
      @tarojs/mobx: 1.3.37 => 1.3.37 
      @tarojs/mobx-h5: 1.3.37 => 1.3.37 
      @tarojs/mobx-rn: 1.3.37 => 1.3.37 
      @tarojs/plugin-babel: 1.3.37 => 1.3.37 
      @tarojs/plugin-csso: 1.3.37 => 1.3.37 
      @tarojs/plugin-less: 1.3.37 => 1.3.37 
      @tarojs/plugin-sass: 1.3.37 => 1.3.37 
      @tarojs/plugin-uglifyjs: 1.3.37 => 1.3.37 
      @tarojs/rn-runner: 1.3.37 => 1.3.37 
      @tarojs/router: 1.3.37 => 1.3.37 
      @tarojs/taro: 1.3.37 => 1.3.37 
      @tarojs/taro-alipay: 1.3.37 => 1.3.37 
      @tarojs/taro-h5: 1.3.37 => 1.3.37 
      @tarojs/taro-swan: 1.3.37 => 1.3.37 
      @tarojs/taro-tt: 1.3.37 => 1.3.37 
      @tarojs/taro-weapp: 1.3.37 => 1.3.37 
      @tarojs/webpack-runner: 1.3.37 => 1.3.37 
      eslint-config-taro: 1.3.37 => 1.3.37 
      eslint-plugin-taro: 1.3.37 => 1.3.37 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      stylelint-config-taro-rn: 1.3.37 => 1.3.37 
      stylelint-taro-rn: 1.3.37 => 1.3.37 
    npmGlobalPackages:
      typescript: 3.7.3

**补充信息**
线上问题、比较紧急，希望能赶紧修复，谢谢

**Comment by Wkevin8** [comment]
taro-ui 版本是2.2.1

**Comment by Garfield550** [comment]
群里你的截图还有跟老李的聊天我看了，不过我没模拟出你这样的复杂情况，麻烦可否给个复现项目或者是代码可以吗？
另外我测试了 Taro 2 上的 SwipeAction 没有问题，一会我会再测试一下 Taro 1 版本。
抱歉因为最近忙现在才回复。

**Comment by Garfield550** [comment]
Taro UI 2.3.2 和 Taro 1.3.40 没有复现
