### ISSUE TITLE
SwipeAction next版本, onOpened, onClosed事件无效

### ISSUE THREAD

**Issue by Singloo** [NervJS/taro-ui#1004]
**问题描述**
taro-ui next版本, SwipeAction   onOpened, onClosed事件无效

**复现步骤**
```js
<AtSwipeAction
      options={[
        {
          text: '取消',
          style: {
            backgroundColor: '#6190E8',
          },
        },
        {
          text: '确认',
          style: {
            backgroundColor: '#FF4949',
          },
        },
      ]}
      onClosed={(e) => console.warn('on closed', e)}
      onOpened={(e) => console.warn('on opened', e)}
    >
```
**系统信息**

taro-ui: 3.0.0-alpha.1

👽 Taro v3.0.0-beta.1

  Taro CLI 3.0.0-beta.1 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.0.2 - /usr/local/bin/fish
    Binaries:
      Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
      Yarn: 1.21.1 - ~/.nvm/versions/node/v12.13.1/bin/yarn
      npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm

**Comment by Garfield550** [comment]
Taro 的行为差异导致了 isOpened 行为相反
![image](https://user-images.githubusercontent.com/3471836/79569725-bd9b5e00-80ea-11ea-9cd4-70b5f3d01c45.png)
Taro Next:
![image](https://user-images.githubusercontent.com/3471836/79570892-d573e180-80ec-11ea-99a9-c48c58b8b4a2.png)
