### ISSUE TITLE
[3.0 alpha.1] NoticeBar 无法滚动

### ISSUE THREAD

**Issue by charmtiger** [NervJS/taro-ui#1005]
**问题描述**

因为pc端项目也需要这个组件，我就想着伸手 copy 出来使用，代码复制到 umi + react 中，滚动正常。但是组件同步到 taro 3 beta 2 时，动画不再滚动。正好交流群中另外一位同学使用 taro-ui 3 alpha1，也反馈此问题。

我尝试以下两步解决问题，供参考

1、问题 this.setState({ animationData: animation.export() });  render 中拿到的 animationData.action = [] 是个空数组，我尝试 const data = animation.export() ，然后再 setState ，render 就可以拿到值

2、https://github.com/NervJS/taro-ui/blob/v3.0.0-alpha.1/src/components/noticebar/index.tsx

```tsx
173 行
animation={{                  
  // eslint-disable-next-line @typescript-eslint/ban-ts-ignore
  // @ts-ignore
  actions: this.state.animationData
}}
// 改成
animation={this.state.animationData}
```

**Comment by Garfield550** [comment]
这个问题已知，Taro 2 和 Taro 3 的签名不一样，我没有改

**Comment by charmtiger** [comment]
> 1、问题 this.setState({ animationData: animation.export() }); render 中拿到的 animationData.action = [] 是个空数组，我尝试 const data = animation.export() ，然后再 setState ，render 就可以拿到值

@Garfield550  这个问题是否已知，如果存在那这个问题应该是 taro 的问题吧

**Comment by Garfield550** [comment]
这个问题我暂时还不清楚，需要研究一下，可以现看一下Taro 2 是否有这个问题

**Comment by Garfield550** [comment]
问题 2 里的 animation 定义问题要等 Taro beta 3 发布，beta 1 是对的我没改，beta 2 的又同步成了 Taro 2 的...

https://github.com/NervJS/taro/blob/v3.0.0-beta.2/packages/taro-components/types/common.d.ts

**Comment by charmtiger** [comment]
好的，看来一切都在掌握之中，辛苦了 😂

**Comment by Garfield550** [comment]
![image](https://user-images.githubusercontent.com/3471836/79588738-edf0f580-8106-11ea-8cff-49e67d1e649c.png)
我发现是我搞错了，Taro 2 的类型定义是正确的，如这个 issue 所说 https://github.com/NervJS/taro/issues/6025 ，Taro 的 animation.export() 类型错了，而且我当时看的微信小程序文档也错了。

**Comment by piecego** [comment]
@Garfield550 
遇到个类似于这个的问题，也是NoticeBar无法滚动，具体是因为使用`createSelectorQuery.boundingClientRect`查节点信息第一次无法查询到的宽高都为0，必须要执行两次查询才能查询到宽高。因为没有宽高所以就无法滚动，之前使用TaroJS v1实现这个组件时没发现这个问题，升级到v2才有这个问题

**Comment by Garfield550** [comment]
这些都算是 Taro 的问题，你可以提一个 issue 到那边吗？我会私聊一下老李

**Comment by piecego** [comment]
> 这些都算是 Taro 的问题，你可以提一个 issue 到那边吗？我会私聊一下老李

不是，我刚刚找了原因，是我自己的代码问题

**Comment by LightningVII** [comment]
请教诸位，我想让这个组件垂直滚动应该怎么处理啊
