### ISSUE TITLE
taro 2.1.3版本,按需引入taro-ui样式,根本没有效果

### ISSUE THREAD

**Issue by dreamthen** [NervJS/taro-ui#1006]
**问题描述**

taro 2.1.3版本,按需引入taro-ui样式,根本没有效果

**复现步骤**
下载最新版本的taro 2.1.3版本，根据taro-ui的文档，按需引入UI组件样式，然后使用生产环境命令run build:weapp打包，taro 2.1.0版本是好使的，到了2.1.3版本，就样式错乱

![image](https://user-images.githubusercontent.com/13704681/78894629-fa8aa380-7a9f-11ea-881a-f246d05a001a.png)

**期望行为**

希望taro-ui UI组件库兼容最新版本的taro框架，按需引入UI组件样式能恢复正常

**报错信息**

![image](https://user-images.githubusercontent.com/13704681/78894705-2574f780-7aa0-11ea-95cb-41435820bb16.png)

**系统信息**

taro v2.1.3
taro-ui v2.3.2

**Comment by Garfield550** [comment]
我看了下 Taro 的更新日志，没有发现有什么重大 Break Change，建议用 2.1.3 新建一个空项目再试一下

**Comment by dreamthen** [comment]
新版本已解决

**Comment by dreamthen** [comment]
刚刚遇到了，问题出在生产环境压缩处理之后，taro-ui会出现我说的这种问题问题

**Comment by dreamthen** [comment]
刚刚遇到了，问题出在生产环境压缩处理之后，taro-ui会出现我说的这种问题
