### ISSUE TITLE
taro-ui 3.0的目标是什么？

### ISSUE THREAD

**Issue by zwl1619** [NervJS/taro-ui#1007]
taro-ui 3.0的目标是什么？就是相比2.0，3.0计划在什么方面做出改变？能大概说一下吗？

**Comment by Garfield550** [comment]
Taro UI 2 是基于 Taro 1 和 2 开发的，Taro UI 3 是基于 Taro Next (3) 开发的，两者不能用在一起。
Taro UI 2 的生命周期在今年 6 月结束。

![image](https://user-images.githubusercontent.com/3471836/79042272-c098d900-7c28-11ea-9bdd-8bd666969cf9.png)
