### ISSUE TITLE
taro-cli3.0 下无法正常使用 taro-ui

### ISSUE THREAD

**Issue by changjingli** [NervJS/taro-ui#1008]
**问题描述**
taro-cli3.0 下无法正常使用 taro-ui
**复现步骤**
1. npm i -g @tarojs/cli@next
2. taro init app
3. cd app
4. yarn add taro-ui
5. yarn run dev:weapp

**期望行为**
taro-cli3.0 下可以正常使用 taro-ui

**报错信息**
> /usr/local/bin/node /usr/local/Cellar/yarn/1.22.4/libexec/bin/yarn.js run dev:weapp
yarn run v1.22.4
$ npm run build:weapp -- --watch
npm WARN lifecycle The node binary used for scripts is /var/folders/th/k59xj85n1154nfg9r6fzc0qm0000gp/T/yarn--1586510610908-0.8148722074588974/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> RitaMargaetMiniProgram@1.0.0 build:weapp /Users/cjl/UseeInfo/projects/RitaMargaetMiniProgram
> taro build --type weapp "--watch"

👽 Taro v3.0.0-beta.3

开始编译项目 RitaMargaetMiniProgram
生成  工具配置  dist/project.config.json

编译  发现入口  src/app.jsx
编译  发现页面  src/pages/home/index/index.jsx
编译  发现页面  src/pages/cart/index/index.jsx
编译  发现页面  src/pages/category/index/index.jsx
编译  发现页面  src/pages/share/index/index.jsx
编译  发现页面  src/pages/user/index/index.jsx
编译  发现页面  src/pages/user/setting/index.jsx
编译  发现页面  src/pages/user/userinfo/index.jsx
编译  发现页面  src/pages/user/address/index.jsx
编译  发现页面  src/pages/user/address/add.jsx
编译  发现页面  src/pages/user/invitation/index.jsx
编译  发现页面  src/pages/coupon/index/index.jsx
编译  发现页面  src/pages/order/index/index.jsx
编译  发现页面  src/pages/order/list/index.jsx
编译  发现页面  src/pages/comment/index/index.jsx
编译  发现页面  src/pages/service/index/index.jsx
编译  发现页面  src/pages/notice/index/index.jsx
编译  发现页面  src/pages/collect/index/index.jsx
编译  发现页面  src/pages/sample/index/index.jsx
编译  发现页面  src/pages/service/detail/index.jsx
编译  发现页面  src/pages/verify/index/index.jsx
编译  发现页面  src/pages/integral/index/index.jsx
编译  发现页面  src/pages/integral/shop/index/index.jsx
编译  发现页面  src/pages/receipt/index/index.jsx
编译  发现页面  src/pages/moneybag/index/index.jsx
编译  发现页面  src/pages/moneybag/couponlist/index.jsx
编译  发现页面  src/pages/moneybag/recodelist/index.jsx
编译  发现页面  src/pages/receipt/makeout/index.jsx
⠙ 正在编译...[BABEL] Note: The code generator has deoptimised the styling of /Users/cjl/UseeInfo/projects/RitaMargaetMiniProgram/node_modules/react-reconciler/cjs/react-reconciler.development.js as it exceeds the max of 500KB.
🙅   编译失败.

./node_modules/taro-ui/dist/weapp/common/component.tsx
Module build failed (from ./node_modules/@tarojs/mini-runner/node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/cjl/UseeInfo/projects/RitaMargaetMiniProgram/node_modules/taro-ui/dist/weapp/common/component.tsx: Unexpected token, expected "," (3:29)

  1 | import { Component } from '@tarojs/taro'
  2 | 
> 3 | const objectToString = (style: object | string): string => {
    |                              ^
  4 |   if (style && typeof style === 'object') {
  5 |     let styleStr = ''
  6 |     Object.keys(style).forEach(key => {

监听文件修改中...

**系统信息**

 - Taro 版本 [3.0.0-beta.3]
 - Taro UI 版本 [2.3.2]
 - 报错平台 [weapp]

  > Taro CLI 3.0.0-beta.3 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.0-beta.3 => 3.0.0-beta.3 
      @tarojs/taro: 3.0.0-beta.3 => 3.0.0-beta.3 
      @tarojs/webpack-runner: 3.0.0-beta.3 => 3.0.0-beta.3 
      eslint-config-taro: 3.0.0-beta.3 => 3.0.0-beta.3 
      react: ^16.10.0 => 16.13.1 

**补充信息**

**Comment by Garfield550** [comment]
在适配了，希望尝鲜的话可以提前试一下 taro-ui 的 3.0 版本
