### ISSUE TITLE
按需引入 canlendar 模块，样式不应该重复引入

### ISSUE THREAD

**Issue by linjackson78** [NervJS/taro-ui#1010]
**问题描述**
按官方文档介绍，像这样按需引入 canlendar 模块，在模拟器里查看元素样式，发现样式重复引用了。

```js
import { AtCalendar } from 'taro-ui'
```

```scss
@import "~taro-ui/dist/style/components/calendar.scss";
```

看了一下源码[这里](https://github.com/NervJS/taro-ui/blob/0bc30392a177bb7fdb5157903bdb5348829b30be/src/index.ts#L2)默认已经间接将 calendar.scss 给引入了。

这里是不是可以理解为，只要用 `import { AtCalendar } from 'taro-ui'` 的方式引用组件，就必然会将所有组件的样式都引入了？如果是的话，按需引入就没有意义了。

**复现步骤**
见上

**期望行为**
按需引入不应该重复引入样式

**报错信息**
这里可以看到样式重复引入了
![image](https://user-images.githubusercontent.com/8870680/79193834-fe327780-7e5d-11ea-82d5-04d9b987337a.png)

**系统信息**

```
Taro v2.1.3


  Taro CLI 2.1.3 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v10.16.0/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    npmPackages:
      @tarojs/cli: ^2.0.3 => 2.1.3
      @tarojs/components: ^2.0.3 => 2.1.3
      @tarojs/mini-runner: ^2.0.3 => 2.1.3
      @tarojs/plugin-babel: ^2.0.3 => 2.1.3
      @tarojs/plugin-csso: ^2.0.3 => 2.1.3
      @tarojs/plugin-sass: ^2.0.3 => 2.1.3
      @tarojs/plugin-uglifyjs: ^2.0.3 => 2.1.3
      @tarojs/router: ^2.0.3 => 2.1.3
      @tarojs/taro: ^2.0.3 => 2.1.3
      @tarojs/taro-alipay: ^2.0.3 => 2.1.3
      @tarojs/taro-h5: ^2.0.3 => 2.1.3
      @tarojs/taro-qq: ^2.0.3 => 2.1.3
      @tarojs/taro-swan: ^2.0.3 => 2.1.3
      @tarojs/taro-weapp: ^2.0.3 => 2.1.3
      @tarojs/webpack-runner: ^2.0.3 => 2.1.3
      eslint-config-taro: ^2.0.3 => 2.1.3
      nervjs: ^1.5.6 => 1.5.6
```

**Comment by Garfield550** [comment]
AtCalendar 源码里没有引入样式，是不是你在 app.scss 里引入过了

**Comment by linjackson78** [comment]
> AtCalendar 源码里没有引入样式，是不是你在 app.scss 里引入过了

确认是没有的。你看一下我提的这行代码，是不是这行代码默认就把所有组件样式给引入了。

https://github.com/NervJS/taro-ui/blob/0bc30392a177bb7fdb5157903bdb5348829b30be/src/index.ts#L2

**Comment by Garfield550** [comment]
这行代码在 Taro 2 里是不会被解析到的，Taro 2 不会去管 UI 组件库的样式文件。
你可以问一下老李

**Comment by Garfield550** [comment]
Taro 2.1.3 和 2.1.4 都有些跟样式有关的 Bug，尝试升级到 2.1.5 以上再看看。
先关闭了。
