### ISSUE TITLE
AtSwipeAction onClick无法阻止点击事件往下传递

### ISSUE THREAD

**Issue by huanxsd** [NervJS/taro-ui#1020]
**问题描述**

**复现步骤**

AtSwipeAction的onClick中的参数，不是原生的event。无法调用stopPropagation。

```js
        <AtSwipeAction
          autoClose
          options={[{ text: '删除' }]}
          onClick={(event) => {
            event.stopPropagation()
            Taro.showToast({ title: event.text })
          }}
        >
```

**期望行为**
可以获取到原生事件，以便于调用stopPropagation。
或者在控件内部，直接调用stopPropagation。

**报错信息**
Property 'stopPropagation' does not exist on type 'SwipeActionOption'.

**系统信息**
👽 Taro v2.1.5
  Taro CLI 2.1.5 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 3.8.3

**补充信息**
临时解决办法：增加一个state：isOpened，用来判断是否响应卡片点击事件。但是个人觉得这种解决方案并不优雅。

          onOpened={() => {
            this.setState({ isOpened: true })
          }}
          onClosed={() => {
            this.setState({ isOpened: false })
          }}

**Comment by huanxsd** [comment]
看过去临时解决方案也不会ugly，因为其他地方也要用到
```
      onOpened={() => {
        this.setState({ isOpened: true })
      }}
      onClosed={() => {
        this.setState({ isOpened: false })
      }}
```

**Comment by githubjin** [comment]
第三个参数是Event
function onClick(options, _, event) {
      event.stopPropagation()
}
