### ISSUE TITLE
range: 百度小程序下获取不到对应的dom

### ISSUE THREAD

**Issue by jsonz1993** [NervJS/taro-ui#1021]
```
taro-ui: 2.3.0
```

range组件在百度小程序下，[delayQuerySelector(..., 0)](https://github.com/NervJS/taro-ui/blob/dev/src/components/range/index.tsx#L103)获取不到对应的dom，微信小程序下不会，除了把延迟时间0改为300之外还有没有什么比较好的处理方式?

**Comment by Garfield550** [comment]
delayQuerySelector 本身就是一个 hack

**Comment by jsonz1993** [comment]
是啊....但是我总觉得这种碰运气形的加延迟时间，心里没啥谱，虽然本地测试微信和百度端300都没问题

**Comment by Garfield550** [comment]
小程序端各种行为表现都不一致，Taro UI 组件里有很多代码根据 Taro env 去做判断然后各种 hack。

如果各端表现一致一点就没有 delayQuerySelector 这种情况出现了，然后 Taro 的一个特殊点也是各端直接调用各端的 API，没有强制把各端 API 重新封装然后保持行为一致（这么做工作量太大），所以得框架自行按照各端处理。

**Comment by Garfield550** [comment]
开发工具 3.5.1 和基础库 3.170.10，Taro 2.1.5 可以在 0ms 延迟下获取到 DOM，不知道是不是你当时的 Taro 版本或者开发工具问题。

**Comment by Garfield550** [comment]
为了以防万一我改成 30ms 延迟，你下个版本再试一下吧。
