### ISSUE TITLE
 _taroAlipay2.default.atMessage is not a function

### ISSUE THREAD

**Issue by MisterWhoDevelopers** [NervJS/taro-ui#1026]
**问题描述**
使用AtMessage组件在编译支付宝小程序时报错

**复现步骤**
引用AtMessage

```js
Taro.atMessage({
        message: 'message',
        type: 'warning'
      })
```

**期望行为**

**报错信息**

**系统信息**
 Taro CLI 2.1.5 environment info:
    System:
      OS: macOS 10.14
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      npm: 6.13.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.1.5 => 2.1.5 
      @tarojs/components-qa: 2.1.5 => 2.1.5 
      @tarojs/mini-runner: 2.1.5 => 2.1.5 
      @tarojs/redux: 2.1.5 => 2.1.5 
      @tarojs/redux-h5: 2.1.5 => 2.1.5 
      @tarojs/router: 2.1.5 => 2.1.5 
      @tarojs/taro: 2.1.5 => 2.1.5 
      @tarojs/taro-alipay: 2.1.5 => 2.1.5 
      @tarojs/taro-h5: 2.1.5 => 2.1.5 
      @tarojs/taro-qq: 2.1.5 => 2.1.5 
      @tarojs/taro-quickapp: 2.1.5 => 2.1.5 
      @tarojs/taro-swan: 2.1.5 => 2.1.5 
      @tarojs/taro-tt: 2.1.5 => 2.1.5 
      @tarojs/taro-weapp: 2.1.5 => 2.1.5 
      @tarojs/webpack-runner: 2.1.5 => 2.1.5 
      eslint-config-taro: 2.1.5 => 2.1.5 
      eslint-plugin-taro: 2.1.5 => 2.1.5 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      stylelint-config-taro-rn: 2.1.5 => 2.1.5 
      stylelint-taro-rn: 2.1.5 => 2.1.5 
      taro-ui: ^2.3.3 => 2.3.3 

 - Taro 版本 2.1.5
 - Taro UI 版本 2.3.3
 - 报错平台 [alipay]

**补充信息**
是我配置不对吗？

**Comment by MisterWhoDevelopers** [comment]
不能在componentDidMount中使用

**Comment by pangwu86** [comment]
在componentDidShow中使用时同样报错

**Comment by linshuizhaoying** [comment]
直接使用也报错。。。
