### ISSUE TITLE
Progress组件的strokeWidth属性无效

### ISSUE THREAD

**Issue by sussertod891015** [NervJS/taro-ui#1028]
### Taro UI 版本信息

2.3.3

### 问题描述

设置Progress组件的strokeWidth属性不起作用
特别说明：没有使用taro UI

### 复现步骤

1. 写一个progress组件，并设置它的一些属性
2. 修改strokeWidth，无效

### 复现代码

<Progress
						activeColor="#ffd6c7"
						backgroundColor="#f68d6f"
						active
						percent={60}
						duration={100}
						strokeWidth={2}
					/>

### 报错信息

无报错

### 系统信息

 Taro v3.0.0-beta.4

  Taro CLI 3.0.0-beta.4 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.3.0 - ~/.nvm/versions/node/v13.3.0/bin/node
      npm: 6.13.1 - ~/.nvm/versions/node/v13.3.0/bin/npm
    npmPackages:
      @tarojs/components: 3.0.0-beta.4 => 3.0.0-beta.4 
      @tarojs/taro: 3.0.0-beta.4 => 3.0.0-beta.4 
      @tarojs/webpack-runner: 3.0.0-beta.4 => 3.0.0-beta.4 
      eslint-config-taro: 3.0.0-beta.4 => 3.0.0-beta.4 
      nervjs: ^1.5.0 => 1.5.6

**Comment by Garfield550** [comment]
这个应该去 Taro 那边提，先关闭了。
