### ISSUE TITLE
Unable to resolve ./components/article/index.scss" from ".//node_modules/taro-ui/dist/weapp/index.js`: The module `./components/article/index.scss` could not be found"

### ISSUE THREAD

**Issue by mindfocus** [NervJS/taro-ui#104]
### 重现步骤
新建工程后加入taro-ui
运行： 
`yarn run build:rn --watch`
### 依赖的版本号
taro-ui 1.2.3
### 预期结果
正常运行
### 实际结果
Unable to resolve ./components/article/index.scss" from ".//node_modules/taro-ui/dist/weapp/index.js`: The module `./components/article/index.scss` could not be found"
实际查看后，缺少article目录

**Comment by jimczj** [comment]
目前 RN 端还在适配中，还不能使用

**Comment by mindfocus** [comment]
无法使用没问题，但是缺文件和能不能使用还是两回事吧？

**Comment by jimczj** [comment]
编译 RN 的时候，加载的是weapp 文件夹的文件，当然无法使用，目前我们还未在 RN 上运行过，所以先别进行尝试
