### ISSUE TITLE
如何覆盖 default.scss 里面的 $hd 变量 ?

### ISSUE THREAD

**Issue by jamieYou** [NervJS/taro-ui#105]
### 重现步骤
我项目的设计稿是 375 的，所以配置了
```js
{
designWidth: 375,
  deviceRatio: {
    '375': 0.5,
  },
}
```

### 依赖的版本号
 - 操作系统: [e.g. macOS 10.13.6]
 - Taro 版本 [e.g. v.1.0.7]
 - taro-ui [1.2.3]
 - Node.js 版本 [e.g. v10.0.0]

### 预期结果
组件的样式大小跟文档一致

### 实际结果
组件展示的大小是文档上的两倍。我看了代码，大部分 px 都做了乘以 $hd 的处理，导致 px 都比较大。不过奇怪是，用 h5 编译，大小反而是正常。我之前用过 antd-mobile，知道这个是高清方案。
想知道有什么解决方法。
PS：个人推荐可以像 antd-mobile 那样使用 less 写 taro-ui，这样就可以支持用外部变量覆盖内部 less 的变量，从而实现自定义主题。

**Comment by koppthe** [comment]
首先说一下设计稿的问题，一般来说如果是以 iPhone8 的尺寸做的设计稿，都会采用 @2x 的尺寸来设计的，也就是 750x1334 的尺寸，designWidth 应当设置成 750。 `taro-ui` 的组件尺寸是以 @2x 的形式输出的，暂时还不支持修改成 @1x

关于自定义主题功能，近期还在跟 taro 这边配合修改，所以暂时是不支持用 sass 变量覆盖的方式来更改主题的。

**Comment by koppthe** [comment]
next 版本已支持自定义主题功能，可以尝尝鲜
```bash
npm install taro-ui@next
```
