### ISSUE TITLE
taro-ui打包后运行在微信小程序开发工具报错：Component is not found in path "npm/taro-ui/dist/weapp/components/button/index"

### ISSUE THREAD

**Issue by wulianglaoge** [NervJS/taro-ui#1052]
### Taro UI 版本信息

2.3.4

### 问题描述

打包后报错，taro版本2.3.4，升级完就不能用了

### 复现步骤

npm run dev:weapp ,所有taro组件打包后都无法使用

### 复现代码

Component is not found in path "npm/taro-ui/dist/weapp/components/button/index" (using by "pages/main/main")

### 报错信息

Component is not found in path "npm/taro-ui/dist/weapp/components/button/index" (using by "pages/main/main")

### 系统信息

 Taro CLI 2.0.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
      npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD

### 补充信息

taro-cli最新版本，报错，降低了taro-ui版本还是报错，希望官方处理下，目前报错导致页面不出来，没有办法继续开发了

**Comment by Garfield550** [comment]
你的 Taro CLI 是 2.0.6，升级一下看看？

**Comment by wulianglaoge** [comment]
> 你的 Taro CLI 是 2.0.6，升级一下看看？

� Taro v2.2.3


  Taro CLI 2.2.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.2.0 - D:\Program Files (x86)\node\node.EXE
      npm: 6.14.4 - D:\Program Files (x86)\node\npm.CMD

升级最新版不行，之前是最新版开始报这个错误，后来尝试降低版本运行项目，发现仍然是这个问题

**Comment by Garfield550** [comment]
2.2.x 不行的话试一下 2.1.x？

**Comment by Garfield550** [comment]
这个问题可能与 #1051 是一样的问题，回退 2.1.6 试一下。

Taro 2.2.x 有破坏性修改，可能你需要去 Taro 提一下这个问题，他们去查看一下。
