### ISSUE TITLE
AtTabBar 层级问题

### ISSUE THREAD

**Issue by jiangzeyin** [NervJS/taro-ui#106]
### 重现步骤
 
![image](https://user-images.githubusercontent.com/16408873/46651437-93eaa800-cbd2-11e8-98fc-717ffaadb7d1.png)

![image](https://user-images.githubusercontent.com/16408873/46651455-a9f86880-cbd2-11e8-8fb8-b0f57d20740d.png)

### 依赖的版本号
taro-ui 1.2.3

**Comment by jiangzeyin** [comment]
> "留言内容" 这个也有层级吗？

没有设置，是taro-ui 的 AtTextarea 控件

**Comment by jiangzeyin** [comment]
> "留言内容" 这个也有层级吗？

小程序开发工具预览没有问题，微信真机调试有问题

**Comment by jimczj** [comment]
@jiangzeyin 能贴下代码吗

**Comment by jimczj** [comment]
已发现问题，AtTextarea 其实只是对 微信自带对 textarea 进行了一层很小的，这是微信官方的bug，而且不管 tabbar 层级调多高，都无法覆盖

**Comment by jiangzeyin** [comment]
> 已发现问题，AtTextarea 其实只是对 微信自带对 textarea 进行了一层很小的，这是微信官方的bug，而且不管 tabbar 层级调多高，都无法覆盖

现在有解决方法吗？

**Comment by jimczj** [comment]
https://developers.weixin.qq.com/miniprogram/dev/component/native-component.html


![image](https://user-images.githubusercontent.com/13499146/46719070-9d8e1180-cc9f-11e8-908b-040567d5b568.png)

微信官方文档这样说明，目前我们将尝试自己实现 placeholder 看看是否能解决问题

**Comment by jimczj** [comment]
@jiangzeyin 刚才尝试了下，即使 placeholder 自己实现了，value 的值也无法覆盖，所以这个应该是无解的

**Comment by jiangzeyin** [comment]
@jimczj 那有点尴尬了，这种效果比较通用

**Comment by jimczj** [comment]
@jiangzeyin 只能求微信的同学来填坑。层级盖不住，点击也是会穿透的

**Comment by jimczj** [comment]
因该问题属于微信官方问题，故关闭 issues

**Comment by felix9ia** [comment]
卧槽，坐等微信官方
