### ISSUE TITLE
AtTabBar 组件自定义图标能否支持自定义图片

### ISSUE THREAD

**Issue by iNathan-yanboo** [NervJS/taro-ui#107]
目前可以自定义 iconfont，但是 iconfont 对多色以及渐变色的支持不佳，项目中想使用这类图标，只能使用自定义图片，这个能否新增支持呢？

**Comment by dsitn201703** [comment]
同问，可以tabbar上的小图标能否支持引用本地图片？

**Comment by jimczj** [comment]
已添加此特性
