### ISSUE TITLE
电脑版微信打开TaroUI示例小程序白屏不显示任何东西

### ISSUE THREAD

**Issue by jiabochao** [NervJS/taro-ui#1083]
**问题描述**
电脑版微信打开TaroUI小程序示例白屏不显示任何东西

**复现步骤**
1. 打开PC版微信
2. 点击左下角的小程序按钮
3. 打开TaroUI示例小程序

```js
// 这里可以贴代码
```

**期望行为**

**报错信息**

**系统信息**

**补充信息**

**Comment by github-zhang** [comment]
微信小程序 基础库的版本改一下，不要2.30 以上
