### ISSUE TITLE
taro 中使用taro-ui报错

### ISSUE THREAD

**Issue by alwaysRemember** [NervJS/taro-ui#1099]
**问题描述**
使用taro init myApp，创建项目后按照文档使用taro-ui报错,
```
🙅   编译失败.

./node_modules/_taro-ui@2.3.4@taro-ui/dist/style/index.scss 6:0
Module parse failed: Unexpected character '@' (6:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| /* Variables */
> @import './variables/default.scss';
| 
| /* Mixin */
```

**复现步骤**
1. cnpm install -g @tarojs/cli
2. taro init myApp
3. cnpm install taro-ui
4. 在app.tsx中使用 **import 'taro-ui/dist/style/index.scss'**导入样式报错。

**期望行为**
为什么会报错，有什么解决办法

**报错信息**
![image](https://user-images.githubusercontent.com/26773809/85120407-c8db4900-b255-11ea-9f2e-a1a1323a0d6e.png)

**系统信息**
- Taro v2.2.9
- taro-ui: ^2.3.4 => 2.3.4
- typescript: 3.1.6
- 微信小程序

**补充信息**

**Comment by alwaysRemember** [comment]
经安装**@tarojs/plugin-sass**后并在config/index.js中的plugins使用，解决问题，但是由于是全局使用的情况，开启cssModules后样式失效了。。

**Comment by lzxgh** [comment]
taro的关系，不关taro-ui。我今天升级项目也遇到了，查看taro文档发现taro自2.2.8之后不再处理除.css后缀以外的样式文件，scss样式需要手动引入插件`@tarojs/plugin-sass`。

**以下是[文档](https://nervjs.github.io/taro/docs/styles-processor/)中的描述：**
> 自 Taro 2.2.8 开始，Taro 默认只能处理 CSS 为后缀的样式文件，当然，Taro 也提供了使用 Sass、Less 等 CSS 预处理器的方式，但是需要用户额外引入相关插件或者通过 Taro 的 webpackChain 配置来实现对这些 CSS 与处理器的支持。

**Comment by alwaysRemember** [comment]
这个问题我发现了 所以后面我引入了这个插件，但是由于我全局引入的taro-ui的sass的情况，开启cssModules后造成样式失效，所以这个问题就很尴尬，要么不用cssModules 用的话就要按需在页面中使用taro-ui @lzxgh

**Comment by lzxgh** [comment]
试试用webpack-chain配置自己的css loader，移除taro自带的postcss，将taro-ui的全局样式文件设为例外，应该就可以了

**Comment by iceMusic** [comment]
在页面中按需使用，写在页面对应的less文件中，比如`@import "~taro-ui/dist/style/components/image-picker.scss";`
还是会报错，请问你是怎么解决的呢？

**Comment by iceMusic** [comment]
我遇到一样的问题，安装@tarojs/plugin-sass后，taro UI的样式一直出不来

**Comment by alwaysRemember** [comment]
> 我遇到一样的问题，安装@tarojs/plugin-sass后，taro UI的样式一直出不来

报错信息给一下

**Comment by lxerxa** [comment]
搞了一天也没搞定，快奔溃了。。。
