### ISSUE TITLE
原生组件层级问题，微信开发社区有人提出一个解决方案

### ISSUE THREAD

**Issue by jiangzeyin** [NervJS/taro-ui#110]
_Originally posted by @jimczj in https://github.com/NervJS/taro-ui/issues/106#issuecomment-428478490_

![image](https://user-images.githubusercontent.com/16408873/46775743-15f5e080-cd3b-11e8-8b3a-d0c97465fb7a.png)

**Comment by jimczj** [comment]
可以试试
