### ISSUE TITLE
AtSearchBar 输入与占位符重影

### ISSUE THREAD

**Issue by huangguozhen** [NervJS/taro-ui#111]
![1762170119](https://user-images.githubusercontent.com/5688889/46784274-03da6900-cd60-11e8-8f6d-75d8931f5756.jpg)

### 依赖的版本号

Node        10.11.0
Taro          1.0.7
Taro-UI      1.3.1

**Comment by jimczj** [comment]
请展示代码

**Comment by huangguozhen** [comment]
@jimczj 组件按非受控组件使用就会出现。例如：
```
<AtSearchBar placeholder='搜索' />
```
看了源码，对占位符的显示控制是通过`value.length`来判别的。这里文档应该要说明一些，或者优化`AtSearchBar`组件，在非受控情况下也正常。
