### ISSUE TITLE
AtIcon的size未跟随配置转换为rpx

### ISSUE THREAD

**Issue by StingKo** [NervJS/taro-ui#112]
### 重现步骤
使用AtIcon组件定义size始终保持单位为px，未转换为rpx，导致在某些设备（如大屏ipad）上icon大小与界面其他组件大小不协调，taro-ui官方演示程序也是如此。

### 依赖的版本号
Taro v1.3.1

### 预期结果
AtIcon与其他组件一样size单位随配置转换为rpx

### 实际结果
AtIcon的size固定为px

**Comment by koppthe** [comment]
这个确实是个问题，感谢反馈~

**Comment by muumlover** [comment]
同样遇到这个问题，期待解决。

**Comment by foreverpw** [comment]
@jimczj   
```javascript
-fontSize: `${size}px`,
+fontSize: `${Taro.pxTransform(parseInt(size) * 2)}`,
```
请问为啥其他组件都是Taro.pxTransform(parseInt(size) )，icon非要*2，不应该统一单位吗，要么都用Px，要么都用rpx/rem。
