### ISSUE TITLE
taro-ui编译后的引用不正确

### ISSUE THREAD

**Issue by Enginebeck** [NervJS/taro-ui#1123]
**问题描述**
通过yarn安装的taro-ui中weapp中引用scss地址不正确

**复现步骤**
```js
yarn add taro-ui
```
文件目录：`node_modules/taro-ui/dist/weapp/index.ts` 2到四行是这样的：
```js
import './style/index.scss'
import './style/themes/red.scss'
import './style/themes/purple.scss'
```

**期望行为**
引用前少了一个点，实际应该是这样的：
```js
import '../style/index.scss'
import '../style/themes/red.scss'
import '../style/themes/purple.scss'
```

**报错信息**

![image](https://user-images.githubusercontent.com/9574537/86510706-ad129e00-be24-11ea-9318-25f6d667525b.png)

**系统信息**
👽 Taro v3.0.2

  Taro CLI 3.0.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

**Comment by adamliuxy** [comment]
hi @Enginebeck，
如果你用`taro v3.0.2`，要指定taro-ui版本才能兼容taro，代码如下：
`yarn add taro-ui@v3.0.0-alpha.3`。（希望官方快点出正式版～～）

使用`npm install taro-ui`  or `yarn add taro-ui`，现在默认是安装`2.3.4`版本，不兼容`taro v3.x`的。
```
➜  ~ npm view taro-ui

taro-ui@2.3.4 | MIT | deps: 6 | versions: 72
UI KIT for Taro
https://taro-ui.aotu.io

keywords: taro, taro-ui, ui

dist
.tarball: https://registry.npmjs.org/taro-ui/-/taro-ui-2.3.4.tgz
.shasum: a7a2cdd67b2b4a49d10c351d89def4d28b9bb192
.integrity: sha512-qjAGO75bIvBGaOlpbnRKecTjmQIzJZjieFuz2UsfSJHnyGgOhlFviWWHPLQQGE2tFcjC0Zol0BDnO4r87JjdSw==
.unpackedSize: 817.0 kB

dependencies:
@types/react: ^16.7.3   classnames: ^2.2.6      lodash: ^4.17.10
bind-decorator: ^1.0.11 dayjs: ^1.7.7           prop-types: ^15.6.2

maintainers:
- garfield550 <npmjs@550.moe>
- koppt <kopptsoft@gmail.com>

dist-tags:
latest: 2.3.4        next: 3.0.0-alpha.3

published 2 months ago by garfield550 <npmjs@550.moe>
```

**Comment by Enginebeck** [comment]
> hi @Enginebeck，
> 如果你用`taro v3.0.2`，要指定taro-ui版本才能兼容taro，代码如下：
> `yarn add taro-ui@v3.0.0-alpha.3`。（希望官方快点出正式版～～@Garfield550 ）
> 
> 使用`npm install taro-ui` or `yarn add taro-ui`，现在默认是安装`2.3.4`版本，不兼容`taro v3.x`的。
> 
> ```
> ➜  ~ npm view taro-ui
> 
> taro-ui@2.3.4 | MIT | deps: 6 | versions: 72
> UI KIT for Taro
> https://taro-ui.aotu.io
> 
> keywords: taro, taro-ui, ui
> 
> dist
> .tarball: https://registry.npmjs.org/taro-ui/-/taro-ui-2.3.4.tgz
> .shasum: a7a2cdd67b2b4a49d10c351d89def4d28b9bb192
> .integrity: sha512-qjAGO75bIvBGaOlpbnRKecTjmQIzJZjieFuz2UsfSJHnyGgOhlFviWWHPLQQGE2tFcjC0Zol0BDnO4r87JjdSw==
> .unpackedSize: 817.0 kB
> 
> dependencies:
> @types/react: ^16.7.3   classnames: ^2.2.6      lodash: ^4.17.10
> bind-decorator: ^1.0.11 dayjs: ^1.7.7           prop-types: ^15.6.2
> 
> maintainers:
> - garfield550 <npmjs@550.moe>
> - koppt <kopptsoft@gmail.com>
> 
> dist-tags:
> latest: 2.3.4        next: 3.0.0-alpha.3
> 
> published 2 months ago by garfield550 <npmjs@550.moe>
> ```

好的，非常感谢，问题已解决

**Comment by huangyanxiong01** [comment]
taro 2.2.8  taro-ui 2.3.4    也有同样的问题， @Enginebeck 使用的是什么版本

**Comment by Enginebeck** [comment]
> taro 2.2.8 taro-ui 2.3.4 也有同样的问题， @Enginebeck 使用的是什么版本

看这个：

> 👽 Taro v3.0.2
> 
> Taro CLI 3.0.2 environment info:
> System:
> OS: Windows 10
> Binaries:
> Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
> Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
> npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

**Comment by daifee** [comment]
这兼容问题乱七八糟的。
