### ISSUE TITLE
AtActivityIndicator不显示

### ISSUE THREAD

**Issue by YeomanYe** [NervJS/taro-ui#114]
### 重现步骤
AtTab第一个页面能显示加载器，页面切换时加载器AtActivityIndicator不显示，只显示白屏，
### 依赖的版本号

node v8.9.0
"@tarojs/taro": "^1.0.7",
"taro-ui": "^1.2.3"
### 预期结果
使用AtTab切换页面时希望显示完加载器后再显示内容
### 实际结果
显示白屏直到数据加载成功
### 相关链接
TopicTabPanel 页
```html
<AtTabsPane current={curIndex} index={index}>
        {this.props.isLoading ?
          <View style={`height:${height - 45}px`}>
            <AtActivityIndicator content='加载中' mode='center'/>
          </View> :
          <ScrollView
            className='scrollview'
            scrollY
            scrollWithAnimation
            style={`height:${height - 45}px`}
            scrollTop={0}
            enableBackToTop={true}
            lowerThreshold={50}
            upperThreshold={50}
            onScrollToLower={this.onLower}
          >
            {datas.map(data => <Topic key={data.id} data={data}/>)}
          </ScrollView>}
      </AtTabsPane>
```
引用
```html
<View className='index'>
        <AtTabs
          current={curTab}
          swipeable
          onClick={this.onTabClick}
          tabList={tabList}>
          {tabList.map((data,i) => <TopicTabPanel index={i} curIndex={curTab} key={data.tab} datas={showTopics} tab={data.tab}/>)}
        </AtTabs>
      </View>
```

**Comment by jimczj** [comment]
审查下元素截图看看

**Comment by YeomanYe** [comment]
@jimczj 好的，我是在小程序中发现这个问题的，rn目前还没测
![qq 20181014193109](https://user-images.githubusercontent.com/18027354/46916077-30a0b180-cfe8-11e8-9801-7e43796710bb.png)
从图中可以看出只有第一个tab下有加载器，其他的tab下是重复了scroll-view。我的代码写法应该是没有问题的吧

**Comment by jimczj** [comment]
`<AtActivityIndicator content='加载中' mode='center'/>` 换成 `<Text>加载中</Text>`，去排查是不是 AtActivityIndicator 的问题，还是你代码逻辑的问题

**Comment by SzHeJason** [comment]
@YeomanYe 你只用了一次`AtActivityIndicator`,所以只有一个是对的 
如果你是想 `AtTabs` 下面的 `AtTabsPane` 公用一个 `AtActivityIndicator` 那这个 `AtActivityIndicator` 应该放在合适的地方上

**Comment by YeomanYe** [comment]
@jimczj 改成了text发现结构是正常的
![qq 20181015215136](https://user-images.githubusercontent.com/18027354/46955055-982c2f00-d0c4-11e8-82cc-e7981f83056d.png)
切换页面时能显示加载中

**Comment by YeomanYe** [comment]
@SzHeJason 我不只使用了一次，你看我贴的代码的引用部分应该也能发现AtActivityIndicator是根据列表的tabList数量生成的。

**Comment by SzHeJason** [comment]
我看代码里面 isLoading 一直为 `false` 怎么会渲染 `AtActivityIndicator ` 呢？

**Comment by SzHeJason** [comment]
@YeomanYe  `mode='center'` 使用的是绝对定位 所以三个会被合在一起 你需要给 `AtActivityIndicator` 的父容器提供 `position: relative`

**Comment by YeomanYe** [comment]
@SzHeJason 感谢，成功解决了问题
