### ISSUE TITLE
初始化新项目 引入taro-ui 编译报错

### ISSUE THREAD

**Issue by xujihua** [NervJS/taro-ui#1144]
**问题描述**
引入taro-ui 后编译报错，./node_modules/taro-ui/dist/weapp/index.ts
Module not found: Can't resolve './style/index.scss' in 'D:***node_modules\taro-ui\dist\weapp'

**复现步骤**

1. 初始化项目   taro init myApp
      选择框架：Nerv
      是否需要使用 TypeScript ？ Y
      请选择 CSS 预处理器（Sass/Less/Stylus） (Use arrow keys)：Sass
     请选择模板 (Use arrow keys)： 默认模板

2. 安装依赖
    cd myApp       
   npm install taro-ui

3. 引入依赖
    src/app.scss
   @import "~taro-ui/dist/style/index.scss";

4. 使用组件

 src/pages/index/index.tsx
 import { AtButton } from 'taro-ui'
 render () {
    return (
      <View className='index'>
        <Text>Hello world!</Text>
        <AtButton></AtButton>
      </View>
    )
   }

5. 编译报错
   Module not found: Can't resolve './style/index.scss' in 'D:***node_modules\taro-ui\dist\weapp'

```js
import Nerv, { Component } from 'nervjs'
import { AtButton } from 'taro-ui'
import { View, Text } from '@tarojs/components'
import './index.scss'

export default class Index extends Component {

  componentWillMount () { }

  componentDidMount () { }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  render () {
    return (
      <View className='index'>
        <Text>Hello world!</Text>
        <AtButton></AtButton>
      </View>
    )
  }
}

```

**期望行为**
期望编译成功
**报错信息**
./node_modules/taro-ui/dist/weapp/index.ts
Module not found: Can't resolve './style/index.scss' in 'D:\frontProject\wechat\gymNote\node_modules\taro-ui\dist\weapp'

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gymNote@1.0.0 build:weapp: `taro build --type weapp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gymNote@1.0.0 build:weapp script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\haha\AppData\Roaming\npm-cache\_logs\2020-07-20T07_00_30_705Z-debug.log

**系统信息**
  Taro CLI 3.0.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 11.10.1 - C:\Program Files\nodejs\node.EXE
      npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD

**补充信息**

**Comment by Wluyao** [comment]
> **问题描述**
> 引入taro-ui 后编译报错，./node_modules/taro-ui/dist/weapp/index.ts
> Module not found: Can't resolve './style/index.scss' in 'D:***node_modules\taro-ui\dist\weapp'
> 
> **复现步骤**
> 
> 1. 初始化项目   taro init myApp
>    选择框架：Nerv
>    是否需要使用 TypeScript ？ Y
>    请选择 CSS 预处理器（Sass/Less/Stylus） (Use arrow keys)：Sass
>    请选择模板 (Use arrow keys)： 默认模板
> 2. 安装依赖
>    cd myApp
>    npm install taro-ui
> 3. 引入依赖
>    src/app.scss
>    @import "~taro-ui/dist/style/index.scss";
> 4. 使用组件
> 
> src/pages/index/index.tsx
> import { AtButton } from 'taro-ui'
> render () {
> return (
> 
> Hello world!
> 
> 
> )
> }
> 
> 1. 编译报错
>    Module not found: Can't resolve './style/index.scss' in 'D:***node_modules\taro-ui\dist\weapp'
> 
> ```js
> import Nerv, { Component } from 'nervjs'
> import { AtButton } from 'taro-ui'
> import { View, Text } from '@tarojs/components'
> import './index.scss'
> 
> export default class Index extends Component {
> 
>   componentWillMount () { }
> 
>   componentDidMount () { }
> 
>   componentWillUnmount () { }
> 
>   componentDidShow () { }
> 
>   componentDidHide () { }
> 
>   render () {
>     return (
>       <View className='index'>
>         <Text>Hello world!</Text>
>         <AtButton></AtButton>
>       </View>
>     )
>   }
> }
> ```
> 
> **期望行为**
> 期望编译成功
> **报错信息**
> ./node_modules/taro-ui/dist/weapp/index.ts
> Module not found: Can't resolve './style/index.scss' in 'D:\frontProject\wechat\gymNote\node_modules\taro-ui\dist\weapp'
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! gymNote@1.0.0 build:weapp: `taro build --type weapp`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the gymNote@1.0.0 build:weapp script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\haha\AppData\Roaming\npm-cache_logs\2020-07-20T07_00_30_705Z-debug.log
> 
> **系统信息**
> Taro CLI 3.0.2 environment info:
> System:
> OS: Windows 10
> Binaries:
> Node: 11.10.1 - C:\Program Files\nodejs\node.EXE
> npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
> 
> **补充信息**

初始化项目中taro用的是3.0版本，但是taro-ui默认安装的是2.0的版本，所以需要指定版本：yarn add taro-ui@3.0.0-alpha

**Comment by xujihua** [comment]
-   **#@******

**Comment by GreatAuk** [comment]
为什么文档上没有声明 taro 3.0 需要对应 taro-ui@3.0.0-alpha ？
