### ISSUE TITLE
Button按钮的边框去除不了，怎么回事？

### ISSUE THREAD

**Issue by zhou1992zg** [NervJS/taro-ui#115]
在页面中加入了Button按钮 
默认的边框去除不了

**Comment by koppthe** [comment]
你是怎么去除边框的？

**Comment by zhou1992zg** [comment]
`<Button>提交</Button>`
我代码这样写
然后在小程序预览样式
<img width="386" alt="2018-10-14 1 44 56" src="https://user-images.githubusercontent.com/29066081/46913015-a3ddff80-cfb7-11e8-9d0e-92e03319c893.png">
就是想把上图中的提交按钮的边框去掉
我想尝试button样式覆盖的方法 但是没有找到有类似于border的属性设置；
下图是微信开发者工具的button样式表截图：
<img width="352" alt="2018-10-14 1 45 34" src="https://user-images.githubusercontent.com/29066081/46913026-d7b92500-cfb7-11e8-952b-da65dd0a90fe.png">
我应该怎么做呢？

**Comment by SzHeJason** [comment]
你是用 `Button` 对吧？ 而不是 `AtButton`  在after 和 before 那里 微信开发工具看不到的

**Comment by zhou1992zg** [comment]
好吧！弄好了
