### ISSUE TITLE
小程序中AtSearchBar组件聚焦会抖动

### ISSUE THREAD

**Issue by YES-Lee** [NervJS/taro-ui#1151]
**问题描述**

AtSearchBar组件聚焦会抖动，iOS上使用正常，android上不能正常弹出键盘。最后面有动图演示
**复现步骤**

点击搜索框，在聚焦后一瞬间会失去焦点，然后再次聚焦。iOS设备上能正常弹出键盘，但是android设备无法正常弹出键盘

```js
// 这里可以贴代码
<AtSearchBar
  value={searchName}
  onChange={setSearchName}
  placeholder='输入名称查找'
  onActionClick={handleSearch}
/>
```

**期望行为**

搜索框聚焦正常，不发生抖动
**报错信息**

**系统信息**

Taro CLI 3.0.3 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    npmPackages:
      @tarojs/components: 3.0.3 => 3.0.3 
      @tarojs/mini-runner: 3.0.3 => 3.0.3 
      @tarojs/react: 3.0.3 => 3.0.3 
      @tarojs/runtime: 3.0.3 => 3.0.3 
      @tarojs/taro: 3.0.3 => 3.0.3 
      @tarojs/webpack-runner: 3.0.3 => 3.0.3 
      babel-preset-taro: 3.0.3 => 3.0.3 
      eslint-config-taro: 3.0.3 => 3.0.3 
      react: ^16.10.0 => 16.13.1 
      taro-ui: 3.0.0-alpha.3 => 3.0.0-alpha.3 
    npmGlobalPackages:
      typescript: 3.7.5

**补充信息**

模拟器效果
![image](http://qiniu-cdn.johnsonlee.site/simulator.GIF)
安卓设备效果
![image](http://qiniu-cdn.johnsonlee.site/android.GIF)
iOS设备效果
![image](http://qiniu-cdn.johnsonlee.site/ios.GIF)

**Comment by YES-Lee** [comment]
调试后发现是Input组件的问题，改issue应该提到Taro仓库中

**Comment by iceMusic** [comment]
这个问题请问是怎么解决的

**Comment by wjl57713** [comment]
请问问题解决了吗
