### ISSUE TITLE
迫切想知道支持 taro3的 taro-ui什么时候可以出正式版本 因为后续小程序想用(公司主 Vue) 不然所有的 ui 都要写 好麻烦 

### ISSUE THREAD

**Issue by wangjun521** [NervJS/taro-ui#1159]
**这个功能解决了什么问题？**

**你期望的功能是怎样的？**

**补充信息**

**Comment by Garfield550** [comment]
Vue 的话有 https://github.com/psaren/taro-ui-vue 可以用

**Comment by vapao** [comment]
+1

**Comment by remember-5** [comment]
+2

**Comment by hemengke1997** [comment]
在taroui不支持taro3的情况下就推出了taro3， 不知道作者是怎么想的.. 而且没有看到有说taroui是否会支持taro3 什么时候支持taro3，搞得都不想用taro3了...

**Comment by luxiaojie322** [comment]
开源不是义务，用与不用视自己的情况而定

**Comment by polichan** [comment]
开源不是义务，用与不用视自己的情况而定
