### ISSUE TITLE
Noticebar  建议

### ISSUE THREAD

**Issue by jiangzeyin** [NervJS/taro-ui#118]
### 依赖的版本号

1.3.1
### 预期结果

想能指定背景色，字体色。字体大小

**Comment by koppthe** [comment]
你的需求属于「自定义主题」，目前只能使用样式覆盖的方法，可参考文档 https://taro-ui.aotu.io/#/docs/customizetheme

> 通过 sass 变量修改主题的方法正在开发中，后面会发布
