### ISSUE TITLE
Tabs标签页组件怎么修改选中的文字颜色以及下划线颜色

### ISSUE THREAD

**Issue by BadRonmance** [NervJS/taro-ui#119]
![image](https://user-images.githubusercontent.com/28837779/46933528-081bc480-d087-11e8-95d6-584c4fc89783.png)
![image](https://user-images.githubusercontent.com/28837779/46933537-0c47e200-d087-11e8-88d7-cbe930cf9302.png)
![image](https://user-images.githubusercontent.com/28837779/46933540-0e11a580-d087-11e8-902d-3965b9ffa9f2.png)

**Comment by koppthe** [comment]
可参考文档：https://taro-ui.aotu.io/#/docs/customizetheme
