### ISSUE TITLE
TabBar icon不渲染，点击切换tab第一次会报错，onClick事件时不时触发

### ISSUE THREAD

**Issue by BurnhamZhang** [NervJS/taro-ui#12]
### 依赖的版本号

node v8.11.2
taro 1.0.0-beta.16
taro-ui 1.0.1

### 相关链接
<img width="664" alt="2018-08-28 12 10 15" src="https://user-images.githubusercontent.com/5702449/44700399-75659d00-aabb-11e8-9bb0-239b343cb04d.png">
<img width="895" alt="2018-08-28 12 10 38" src="https://user-images.githubusercontent.com/5702449/44700416-87474000-aabb-11e8-8af2-2c3366fb5bf4.png">

**Comment by BurnhamZhang** [comment]
<img width="437" alt="2018-08-28 12 12 59" src="https://user-images.githubusercontent.com/5702449/44700504-f7ee5c80-aabb-11e8-8d14-c6769b004f2c.png">

少贴一张图

**Comment by jimczj** [comment]
将 taro 更新到1.0.0-beta.18 试试

**Comment by jimczj** [comment]
`this.handleClick` 改写成 `this.handleClick.bind(this)` 试试

**Comment by jimczj** [comment]
升级完后，还会有什么问题吗

**Comment by BurnhamZhang** [comment]
在开发者工具上还是上面的问题，真机上没问题
