### ISSUE TITLE
input clear属性会在输入一个字符后收起键盘

### ISSUE THREAD

**Issue by 77629296** [NervJS/taro-ui#1201]
### Taro UI 版本信息

3.0.0-alpha.3

### 问题描述

taro版本3.0.10

### 复现步骤

input组件增加clear属性即可复现

### 复现代码

<AtInput title='用户名'
          placeholderClass='init-color'
          type='text'
          name="username"
          placeholder='请输入用户名'
          border={false}
          value={username}
          onChange={(val) => { setValue(val, 'username') }}
          clear
        />

### 报错信息

无

### 系统信息

Taro v3.0.10

  Taro CLI 3.0.10 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.17.0 - ~/.nvm/versions/node/v12.17.0/bin/node
      Yarn: 1.19.1 - ~/.nvm/versions/node/v10.15.3/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.17.0/bin/npm
    npmPackages:
      @tarojs/components: 3.0.10 => 3.0.10 
      @tarojs/mini-runner: 3.0.10 => 3.0.10 
      @tarojs/react: 3.0.10 => 3.0.10 
      @tarojs/runtime: 3.0.10 => 3.0.10 
      @tarojs/taro: 3.0.10 => 3.0.10 
      @tarojs/taro-h5: 3.0.10 => 3.0.10 
      @tarojs/webpack-runner: 3.0.10 => 3.0.10 
      babel-preset-taro: 3.0.10 => 3.0.10 
      eslint-config-taro: 3.0.10 => 3.0.10 
      eslint-plugin-taro: 3.0.10 => 3.0.10 
      react: ^16.10.0 => 16.13.1 
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.3

### 补充信息

taro v2.2.7  taro-ui v2.3.4 表现正常

升级后出现此问题

升级后版本 taro v3.0.10  taro-ui v3.0.0-alpha.3
移除clear属性 表现正常
增加clear属性 输入一个字符就收起键盘 后续输入正常

模拟器、安卓oppoR15均复现

**Comment by u10k** [comment]
让我以为我发了两遍

**Comment by 77629296** [comment]
重复了

**Comment by panyu97py** [comment]
focus 给个 null 就可以了。 已经给官方提了pr

**Comment by panyu97py** [comment]
> ### Taro UI 版本信息
> 3.0.0-alpha.3
> 
> ### 问题描述
> taro版本3.0.10
> 
> ### 复现步骤
> input组件增加clear属性即可复现
> 
> ### 复现代码
> <AtInput title='用户名'
> placeholderClass='init-color'
> type='text'
> name="username"
> placeholder='请输入用户名'
> border={false}
> value={username}
> onChange={(val) => { setValue(val, 'username') }}
> clear
> />
> 
> ### 报错信息
> 无
> 
> ### 系统信息
> Taro v3.0.10
> 
> Taro CLI 3.0.10 environment info:
> System:
> OS: macOS 10.15.6
> Shell: 3.2.57 - /bin/bash
> Binaries:
> Node: 12.17.0 - ~/.nvm/versions/node/v12.17.0/bin/node
> Yarn: 1.19.1 - ~/.nvm/versions/node/v10.15.3/bin/yarn
> npm: 6.14.4 - ~/.nvm/versions/node/v12.17.0/bin/npm
> npmPackages:
> @tarojs/components: 3.0.10 => 3.0.10
> @tarojs/mini-runner: 3.0.10 => 3.0.10
> @tarojs/react: 3.0.10 => 3.0.10
> @tarojs/runtime: 3.0.10 => 3.0.10
> @tarojs/taro: 3.0.10 => 3.0.10
> @tarojs/taro-h5: 3.0.10 => 3.0.10
> @tarojs/webpack-runner: 3.0.10 => 3.0.10
> babel-preset-taro: 3.0.10 => 3.0.10
> eslint-config-taro: 3.0.10 => 3.0.10
> eslint-plugin-taro: 3.0.10 => 3.0.10
> react: ^16.10.0 => 16.13.1
> taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.3
> 
> ### 补充信息
> taro v2.2.7 taro-ui v2.3.4 表现正常
> 
> 升级后出现此问题
> 
> 升级后版本 taro v3.0.10 taro-ui v3.0.0-alpha.3
> 移除clear属性 表现正常
> 增加clear属性 输入一个字符就收起键盘 后续输入正常
> 
> 模拟器、安卓oppoR15均复现

focus 给个 null 就可以了。 已经给官方提了pr
