### ISSUE TITLE
modal 可否增加一个 点击遮罩关闭modal 的小功能

### ISSUE THREAD

**Issue by kscript** [NervJS/taro-ui#121]
我的 modal 里只有一个供用户选择的列表, 并不需要确认和取消按钮.
参考效果: https://codepen.io/luren/pen/NOyKEZ

**Comment by SzHeJason** [comment]
支持的啊 你是如何使用 `Modal` 呢？

**Comment by SzHeJason** [comment]
因为在交互这块 `Modal` 是一个强概念的 所以暂不提供 点击遮罩关闭 你可以定义 `AtModalHeader` 来提供关闭  具体的支不支持我们会讨论下

**Comment by koppthe** [comment]
@kscript 感谢提议，我们内部讨论了一下，决定增加一个 Alert 组件，至于 Modal 组件，还是需要有点击遮罩可以关闭 Modal 框的功能。

BTW, 你示例里面的场景，推荐用 ActionSheet 来做

以下是一些参考文档：
https://developer.apple.com/design/human-interface-guidelines/ios/views/alerts/
https://www.quora.com/Whats-the-difference-between-a-modal-a-popover-and-a-popup/answer/Harrison-Shoff
