### ISSUE TITLE
H5中的AtTextarea事件支持不完整问题

### ISSUE THREAD

**Issue by tourze** [NervJS/taro-ui#122]
目前测试，onChange方法可以触发，但是每次只能拿到当次输入的一个字符，如图：
![image](https://user-images.githubusercontent.com/13899502/47066654-5cef4480-d219-11e8-8b0f-f137f9f60590.png)

onConfirm没办法触发。

另外不知道是不是因为这些事件没处理好，AtTextarea的maxlength这些属性也不生效
![image](https://user-images.githubusercontent.com/13899502/47066711-84dea800-d219-11e8-95fa-566f3e85adfb.png)

**Comment by jimczj** [comment]
Taro 基础库问题，已反馈

**Comment by jimczj** [comment]
已修复，请升级 taro 最新版本

**Comment by tourze** [comment]
> 已修复，请升级 taro 最新版本

升级到 taro版本1.1.0-beta.11，taro-ui 1.3.4，实测问题依然存在

**Comment by jimczj** [comment]
请使用以下代码来改变state
`
handleChange (event) {
   this.setState({ value: event.target.value)}
}
`
