### ISSUE TITLE
新的3.0.0库引入，编译报错

### ISSUE THREAD

**Issue by fuxinruming** [NervJS/taro-ui#1226]
**问题描述**
引入最新的taroUI3.0库，编译报错

**复现步骤**
按照官方文档的步骤一步步走，选择的vue模板，选择的支持Typescript
app.ts  里  import 'taro-ui/dist/style/index.scss'
补充信息里是vue组件内容

**期望行为**
期望可以编译成功

**报错信息**
Module not found: Error: Can't resolve 'react' in 'E:\小程序测试\myApp\node_modules\_taro-ui@3.0.0-alpha.3@taro-ui\dist'
resolve 'react' in 'E:\小程序测试\myApp\node_modules\_taro-ui@3.0.0-alpha.3@taro-ui\dist'
  Parsed request is a module
  using description file: E:\小程序测试\myApp\node_modules\_taro-ui@3.0.0-alpha.3@taro-ui\package.json (relative path: ./dist)
    resolve as module
      E:\小程序测试\myApp\node_modules\_taro-ui@3.0.0-alpha.3@taro-ui\dist\node_modules doesn't exist or is not a directory
      E:\小程序测试\myApp\node_modules\node_modules doesn't exist or is not a directory
      E:\小程序测试\node_modules doesn't exist or is not a directory
      E:\node_modules doesn't exist or is not a directory
      looking for modules in E:\小程序测试\myApp\node_modules\_taro-ui@3.0.0-alpha.3@taro-ui\node_modules
        using description file: E:\小程序测试\myApp\node_modules\_taro-ui@3.0.0-alpha.3@taro-ui\package.json (relative path: ./node_modules)
          using description file: E:\小程序测试\myApp\node_modules\_taro-ui@3.0.0-alpha.3@taro-ui\package.json (relative path: ./node_modules/react)
            no extension
              E:\小程序测试\myApp\node_modules\_taro-ui@3.0.0-alpha.3@taro-ui\node_modules\react doesn't exist
      looking for modules in E:\小程序测试\myApp\node_modules
        using description file: E:\小程序测试\myApp\package.json (relative path: ./node_modules)
          using description file: E:\小程序测试\myApp\package.json (relative path: ./node_modules/react)
            no extension
              E:\小程序测试\myApp\node_modules\react doesn't exist
            .js
              E:\小程序测试\myApp\node_modules\_taro-ui@3.0.0-alpha.3@taro-ui\node_modules\react.js doesn't exist
            .js
              E:\小程序测试\myApp\node_modules\react.js doesn't exist
            .jsx
              E:\小程序测试\myApp\node_modules\_taro-ui@3.0.0-alpha.3@taro-ui\node_modules\react.jsx doesn't exist
            .jsx
              E:\小程序测试\myApp\node_modules\react.jsx doesn't exist
            .ts
              E:\小程序测试\myApp\node_modules\_taro-ui@3.0.0-alpha.3@taro-ui\node_modules\react.ts doesn't exist
            .ts
              E:\小程序测试\myApp\node_modules\react.ts doesn't exist
            .tsx
              E:\小程序测试\myApp\node_modules\_taro-ui@3.0.0-alpha.3@taro-ui\node_modules\react.tsx doesn't exist
            .tsx
              E:\小程序测试\myApp\node_modules\react.tsx doesn't exist
            .mjs
              E:\小程序测试\myApp\node_modules\_taro-ui@3.0.0-alpha.3@taro-ui\node_modules\react.mjs doesn't exist
            .mjs
              E:\小程序测试\myApp\node_modules\react.mjs doesn't exist
            .vue
              E:\小程序测试\myApp\node_modules\_taro-ui@3.0.0-alpha.3@taro-ui\node_modules\react.vue doesn't exist
            .vue
              E:\小程序测试\myApp\node_modules\react.vue doesn't exist
            as directory
              E:\小程序测试\myApp\node_modules\_taro-ui@3.0.0-alpha.3@taro-ui\node_modules\react doesn't exist
            as directory
              E:\小程序测试\myApp\node_modules\react doesn't exist
      looking for modules in E:\小程序测试\myApp\node_modules
        using description file: E:\小程序测试\myApp\package.json (relative path: ./node_modules)
          using description file: E:\小程序测试\myApp\package.json (relative path: ./node_modules/react)
            no extension
              E:\小程序测试\myApp\node_modules\react doesn't exist
            .js
              E:\小程序测试\myApp\node_modules\react.js doesn't exist
            .jsx
              E:\小程序测试\myApp\node_modules\react.jsx doesn't exist
            .ts
              E:\小程序测试\myApp\node_modules\react.ts doesn't exist
            .tsx
              E:\小程序测试\myApp\node_modules\react.tsx doesn't exist
            .mjs
              E:\小程序测试\myApp\node_modules\react.mjs doesn't exist
            .vue
              E:\小程序测试\myApp\node_modules\react.vue doesn't exist
            as directory
              E:\小程序测试\myApp\node_modules\react doesn't exist

**系统信息**

 - Taro 版本 [v.30.15]
 - Taro UI 版本 [v.3.0.0]
 - 报错平台 [微信开发者工具]

**补充信息**

<template>
  <view class="index">
    <text>{{ msg }}</text>
    <AtCalendar/>
  </view>
</template>

<script>
import './index.scss'
import { AtCalendar } from 'taro-ui'
export default {
  components:{AtCalendar},
  data () {
    return {
      msg: 'Hello world!'
    }
  }
}
</script>

**Comment by jobn123** [comment]
Taro UI 3 目前仍在开发中，在 next 分支，已经支持到 Taro v3.0.0-alpha.3，如体验，安装命令 npm i —save taro-ui@next

安装taro-ui@next这个版本就可以啦

**Comment by fuxinruming** [comment]
已经解决，主要是因为我引的是taro-ui-vue，建项目的时候需要选上支持typescript，就好了，我重新建了个项目就没这问题了
