### ISSUE TITLE
AtSearchBar 开启 fixed情况下，开启下拉刷新导致未知错误

### ISSUE THREAD

**Issue by HuChundong** [NervJS/taro-ui#123]
### 依赖的版本号

Taro 1.0.7
Taro-UI 1.3.1
### 预期结果
正常显示
### 实际结果
显示错位
![image](https://user-images.githubusercontent.com/3194932/47109377-acb52680-d280-11e8-9bd9-06faf6c28d94.png)

**Comment by jimczj** [comment]
已知bug，已修改此问题，将在今天或明天发版本，感谢反馈

**Comment by HuChundong** [comment]
最新版本已修复
