### ISSUE TITLE
ui库日历组件marks使用

### ISSUE THREAD

**Issue by MY-orb** [NervJS/taro-ui#1235]
### 问题描述
日历组件在使用marks的时候不能正确显示标记点
### 复现步骤
使用下面方式
```<AtCalendar marks={ [ { value: '2018/11/11' } ] } />```

### 修改建议
```
 {item.marks && item.marks.length > 0 && (
                <View className='extra-marks'>
                  {item.marks.map((mark, key) => (
                    <Text key={key} className='mark'>
                      {mark?.value}
                    </Text>
                  ))}
                </View>
              ) }
```

**Comment by MY-orb** [comment]
重复提交 但是问题没有好像没改

**Comment by luvletterldl** [comment]
+1

**Comment by luvletterldl** [comment]
求修复啊啊啊啊啊啊啊

**Comment by MY-orb** [comment]
自己改吧 我都搞到本地自己改了 
| |
王以栋
|
|
wyd_4219@163.com
|
签名由网易邮箱大师定制


在2021年02月4日 17:58，ldl<notifications@github.com> 写道：

求修复啊啊啊啊啊啊啊

**Comment by StarksJohn** [comment]
可直接用 https://github.com/zkytech/taro-calendar-customizable 这个库解决
