### ISSUE TITLE
className 自定义的样式在小程序里面不生效

### ISSUE THREAD

**Issue by blueskink** [NervJS/taro-ui#125]
### 描述
比如AtButton、AtIcon等组件通过className自定义的样式在h5里生效，在小程序里不生效。
### 依赖的版本号
Taro：1.0.3
Taro-UI : 1.2.3

**Comment by SzHeJason** [comment]
addGlobalClass 这个API 只能在 page 上的 class 才能覆盖组件的 class

**Comment by SzHeJason** [comment]
@blueskink  暂时关闭 Issue 如还有问题可随时打开
