### ISSUE TITLE
自定义组件中添加的addGlobalClass ，但是page 中的 css 还是 对 子组件无效？

### ISSUE THREAD

**Issue by JoMartinezZhu** [NervJS/taro-ui#126]
自定义组件中添加的addGlobalClass ，但是page 中的 css 还是 对 子组件无效，
addGlobalClass 的 配置到底应该添加到哪里？

**Comment by cos2004** [comment]
注意基础库版本要>=2.2.3

**Comment by SzHeJason** [comment]
@JoMartinezZhu 暂时关闭这个 issue 如有问题可随时打开
