### ISSUE TITLE
AtDrawer show=true时在真机上不能正常显示

### ISSUE THREAD

**Issue by eruca** [NervJS/taro-ui#1266]
Taro 3.0.21
Taro-UI@3.0.0.alpha7
真机：OnePlus 7 pro
Android: 10, 版本号：Hydrogen OS 10.0.10.GM21
情景：
就是打开页面时设置AtDrawer的show=true,
在微信开发工具上可以正常显示，可是在上述真机上是关闭状态的，没有打开状态

**Comment by Jeff-Tian** [comment]
我也碰到同样的情况，不过是因为用了 attabs。然后把 drawer 放在了 pane 下。后来发现其实 drawer 在的，不过位置出乎意料。

比如下面的结构，当第二个 Pane 被选中时，就看不到 drawer 了。

```
layout:

<Layout>
<Drawer />
</Layout>

<AtTabs>
<Pane><Layout /></Pane>
<Pane><Layout /></Pane>
</AtTabs>
```

![image](https://user-images.githubusercontent.com/3367820/154254033-53934879-b69b-462c-b94a-d894c8afb446.png)


![image](https://user-images.githubusercontent.com/3367820/154253900-3dcddb83-afe2-4dce-a982-2e64ae3a28df.png)
