### ISSUE TITLE
安装taro-ui报错

### ISSUE THREAD

**Issue by starm328** [NervJS/taro-ui#127]
### 重现步骤
$ npm install -g @tarojs/cli
$ taro init myApp
npm install taro-ui
安装然后 运行，就会报错
![image](https://user-images.githubusercontent.com/17894731/47143323-749cfa80-d2f7-11e8-85b8-a5a3c01ef068.png)

### 依赖的版本号

node  V8.9.4
taro:V1.0.7
taro-ui: V1.3.1

**Comment by starm328** [comment]
这是install taro-ui之后
运行项目报的错
 npm run dev:weapp
运行这个之后报的错

**Comment by SzHeJason** [comment]
有重新试试下 npm install 或者 cnpm install 吗？看报错就就是包没装上而已
