### ISSUE TITLE
AtActionSheet 能否增加 点击遮罩层是否关闭的选项

### ISSUE THREAD

**Issue by HuChundong** [NervJS/taro-ui#130]
### 重现步骤
点击遮罩部分
### 依赖的版本号
Taro-UI 1.3.2

### 预期结果
组件增加选项，点击遮罩是否允许关闭
### 实际结果
无该选项

**Comment by koppthe** [comment]
不支持哦，ActionSheet 点击遮罩层关闭是个常规操作。

**Comment by jiadabaihua** [comment]
很差劲，人家antd都是可以支持配置的，我们蒙层关闭是有二次确认的，你们非得自己给关闭了和点击叉号行为不一致
