### ISSUE TITLE
taro-UI 日历组件直接报错 官方看到后请解决

### ISSUE THREAD

**Issue by LoveMuZiLi** [NervJS/taro-ui#1312]
app.js:1 Error: Date Interval Error
    at Picker.handlePrpos (0.js:1)
    at new Picker (0.js:1)
    at mountComponent (app.js:1)
    at ComponentWrapper.init (app.js:1)
    at createElement (app.js:1)
    at mountChild (app.js:1)
    at mountVNode$1 (app.js:1)
    at createElement (app.js:1)
    at mountVNode (app.js:1)
    at mountComponent (app.js:1)
(anonymous) @ app.js:1
Promise.catch (async)
updateComponent @ app.js:1
componentDidMount @ app.js:1
(anonymous) @ app.js:1
errorCatcher @ app.js:1
(anonymous) @ app.js:1
flushMount @ app.js:1
updateComponent @ app.js:1
rerender @ app.js:1
Promise.then (async)
nextTick @ app.js:1
enqueueRender @ app.js:1
setState @ app.js:1
push @ app.js:1
componentDidMount @ app.js:1
(anonymous) @ app.js:1
errorCatcher @ app.js:1
(anonymous) @ app.js:1
flushMount @ app.js:1
render @ app.js:1
(anonymous) @ app.js:1
__webpack_require__ @ app.js:1
(anonymous) @ app.js:1
__webpack_require__ @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1

**Comment by jiangyh123** [comment]
> app.js:1 Error: Date Interval Error
> at Picker.handlePrpos (0.js:1)
> at new Picker (0.js:1)
> at mountComponent (app.js:1)
> at ComponentWrapper.init (app.js:1)
> at createElement (app.js:1)
> at mountChild (app.js:1)
> at mountVNode$1 (app.js:1)
> at createElement (app.js:1)
> at mountVNode (app.js:1)
> at mountComponent (app.js:1)
> (anonymous) @ app.js:1
> Promise.catch (async)
> updateComponent @ app.js:1
> componentDidMount @ app.js:1
> (anonymous) @ app.js:1
> errorCatcher @ app.js:1
> (anonymous) @ app.js:1
> flushMount @ app.js:1
> updateComponent @ app.js:1
> rerender @ app.js:1
> Promise.then (async)
> nextTick @ app.js:1
> enqueueRender @ app.js:1
> setState @ app.js:1
> push @ app.js:1
> componentDidMount @ app.js:1
> (anonymous) @ app.js:1
> errorCatcher @ app.js:1
> (anonymous) @ app.js:1
> flushMount @ app.js:1
> render @ app.js:1
> (anonymous) @ app.js:1
> **webpack_require** @ app.js:1
> (anonymous) @ app.js:1
> **webpack_require** @ app.js:1
> (anonymous) @ app.js:1
> (anonymous) @ app.js:1

17天前？我今天用了H5跟小程序都没有问题，你能说清楚版本吗？

**Comment by FinchJohnRen** [comment]
官网都是错的！

**Comment by huanlirui** [comment]
官网实例都跑不起，空白一片的，我服了

![image](https://user-images.githubusercontent.com/40491203/117786102-c1f76380-b277-11eb-81a4-0c84bd61bf32.png)

**Comment by LoveMuZiLi** [comment]
是你们那个taro-ui官网，点击日历组件就报错，一直没有修复



At 2021-04-02 11:00:56, "隔壁小甜" ***@***.***> wrote:

app.js:1 Error: Date Interval Error
at Picker.handlePrpos (0.js:1)
at new Picker (0.js:1)
at mountComponent (app.js:1)
at ComponentWrapper.init (app.js:1)
at createElement (app.js:1)
at mountChild (app.js:1)
at mountVNode$1 (app.js:1)
at createElement (app.js:1)
at mountVNode (app.js:1)
at mountComponent (app.js:1)
(anonymous) @ app.js:1
Promise.catch (async)
updateComponent @ app.js:1
componentDidMount @ app.js:1
(anonymous) @ app.js:1
errorCatcher @ app.js:1
(anonymous) @ app.js:1
flushMount @ app.js:1
updateComponent @ app.js:1
rerender @ app.js:1
Promise.then (async)
nextTick @ app.js:1
enqueueRender @ app.js:1
setState @ app.js:1
push @ app.js:1
componentDidMount @ app.js:1
(anonymous) @ app.js:1
errorCatcher @ app.js:1
(anonymous) @ app.js:1
flushMount @ app.js:1
render @ app.js:1
(anonymous) @ app.js:1
webpack_require @ app.js:1
(anonymous) @ app.js:1
webpack_require @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1

17天前？我今天用了H5跟小程序都没有问题，你能说清楚版本吗？
