### ISSUE TITLE
taro-ui 本地调试开发疑惑

### ISSUE THREAD

**Issue by Onlylonger** [NervJS/taro-ui#1314]
**问题描述**
taro-ui 本地可视化调试开发疑惑🤔

**复现步骤**
```sh
# A sh 窗口
git clone git@github.com:NervJS/taro-ui.git
cd taro-ui
yarn install
yarn run bootstrap

cd packages/taro-ui
yarn run dev
# B sh 窗口
cd packages/taro-ui-demo
yarn run dev:h5
```
![image](https://user-images.githubusercontent.com/19505200/112284247-fe6d0100-8cc3-11eb-9d01-2215347a5796.png)

看 taro-ui `package.json dependencies` 的 taro-ui 确实是 file:../taro-ui ;  但是在 taro-ui 里面，ts.config 配置产出目录只会有lib. 没有 dist; 请问 平时你们自身是怎么进行开发的哦？
**期望行为**
正常进行开发调试

**报错信息**
![image](https://user-images.githubusercontent.com/19505200/112284247-fe6d0100-8cc3-11eb-9d01-2215347a5796.png)

**系统信息**
taro-ui `next` 分支;
commit dc8c8cd662c306b903c5839f1d80eca99d5d1bbf

**Comment by ZWkang** [comment]
可以尝试添加一个script 在 taro-ui-demo 内
例如
```
"build:rollup:watch": "rollup --config ./config/rollup.config.js --watch"
```

**Comment by Onlylonger** [comment]
@ZWkang 这种可以正常进行 h5 可视化调试，每次小调整耗费时间较长（可能是全量构建+io输入），应该不是官方的 调试模式吧；

![image](https://user-images.githubusercontent.com/19505200/112413205-c369dc80-8d5a-11eb-8299-bb58c0666667.png)

@Garfield550 @koppthe

**Comment by Onlylonger** [comment]
👋anyone?

**Comment by Pines-Cheng** [comment]
在项目根目录安装依赖，然后运行：

```
yarn bootstrap
yarn build
```
link 包的依赖，构建 dist 就行了。
