### ISSUE TITLE
AtSlider设置value无效。

### ISSUE THREAD

**Issue by huangguozhen** [NervJS/taro-ui#135]
### 依赖的版本号

Node: 10.11.0
Taro: 1.0.7
Taro-UI: 1.3.3

### 预期结果
AtSlider根据设置的`value`正确显示滑块的位置。
### 实际结果
改变AtSlider传入的`value`值，AtSlider滑块的位置并没有按预期改变。
### 原因
AtSlider内部实现使用了`state._value`来设置小程序原生slider的`value`。但是在`props.value`发送改变的时候并没有重新设置`state._value`。

**Comment by koppthe** [comment]
已修复，麻烦升级到 v1.3.5 版本
