### ISSUE TITLE
h5的demo日历组件打不开

### ISSUE THREAD

**Issue by cshenger** [NervJS/taro-ui#1351]
h5 的demo 日历组件打不开，页面提示错误
![image](https://user-images.githubusercontent.com/5855865/119069971-afb8ba80-ba19-11eb-8ed8-92751cc209c8.png)

地址： https://taro-ui.aotu.io/h5/index.html#/pages/advanced/calendar/index

**Comment by JackieCoo** [comment]
请问一下项目中使用有解决方案吗？
