### ISSUE TITLE
样式文件的 引入问题

### ISSUE THREAD

**Issue by zhaoyunchong** [NervJS/taro-ui#1359]
![微信截图_20210621213902](https://user-images.githubusercontent.com/52824245/122771781-545c3f80-d2d9-11eb-9d61-aad2fec3e7bf.png)
最近项目中  依赖文件 发生了更改就重新下载了， 然后 index.scss文件模块一直报 找不到    这个路径 是不是 有问题呢    应该是 ../style/indesc.scss 少了个 .
我看最近 项目也没做什么更新吧

**Comment by zhaoyunchong** [comment]
node_modules 文件中

**Comment by zhoustudent** [comment]
同学，你这个问题现在修复了么？如果修复，能告知怎么解决的么？
