### ISSUE TITLE
AtCard 缩略图可以稍微大一点，目前的确太小了

### ISSUE THREAD

**Issue by kenberkeley** [NervJS/taro-ui#136]
![image](https://user-images.githubusercontent.com/13287948/47278234-fb611880-d612-11e8-9d22-233579fd2676.png)

**Comment by kenberkeley** [comment]
参考 AtListItem 的比例就相当适合

![image](https://user-images.githubusercontent.com/13287948/47278260-319e9800-d613-11e8-84ca-922fe10476bf.png)

**Comment by SzHeJason** [comment]
这个是使用者主观的感觉  因为实在是满足不了所有人的大小规定  如果你觉得小了点 可以用样式覆盖来完成  @koppthe 这块评估下需不需要改？

**Comment by koppthe** [comment]
缩略图的大小这个得看具体使用场景了，可大可小。我们目前的 AtCard 组件的缩略图倾向于小尺寸的图标，如果需要更改大小的话，可以试试 globalClass 自定义样式

**Comment by kenberkeley** [comment]
how to?

**Comment by koppthe** [comment]
参考这个文档： https://taro-ui.aotu.io/#/docs/customizetheme

**Comment by z-Listening** [comment]
> 参考这个文档： https://taro-ui.aotu.io/#/docs/customizetheme

请问AtCard的thumb不支持引用本地图片吗？还是不支持svg？怎么引不到啊。。

**Comment by vinurs** [comment]
我也发现不支持引用本地图片，不知道咋去解决这个问题
