### ISSUE TITLE
关于手动切换AtInput的type值在‘text’和‘password’间转换的问题

### ISSUE THREAD

**Issue by InkoiWong** [NervJS/taro-ui#137]
### 重现步骤
![image](https://user-images.githubusercontent.com/24976100/47281564-46c4f800-d60e-11e8-8b0b-d78625553df9.png)
![image](https://user-images.githubusercontent.com/24976100/47281772-28abc780-d60f-11e8-9277-50f9471ffd60.png)
![image](https://user-images.githubusercontent.com/24976100/47281633-8390ef00-d60e-11e8-90a0-764a220bd1b1.png)
![image](https://user-images.githubusercontent.com/24976100/47281665-b0dd9d00-d60e-11e8-9813-a2c95cd3e55d.png)
![image](https://user-images.githubusercontent.com/24976100/47281668-b6d37e00-d60e-11e8-9bcf-c7178ef4f121.png)

### 依赖的版本号

node: 8.12.0
taro: 1.0.7
taro-ui: 1.3.3

### 预期结果
在手机上使用时，能够点击该“眼睛”控制该input的type值在‘text’和‘password’间切换

### 实际结果
在开发者工具上使用鼠标点击为正常，点击该“眼睛”后该input的type能够马上触发，使其显示或隐藏；可是在手机上使用时，当手指点击该“眼睛后”，该input没有变化，只有当再次点击该input使input聚焦后，该input的type才生效，隐藏或者显示

**Comment by jimczj** [comment]
在真机上，input 组件是原生组件，可能有问题

**Comment by jimczj** [comment]
该问题涉及到小程序底层组件的实现，具体看小程序官方的解答
https://developers.weixin.qq.com/community/develop/doc/0004c884bf4478f331b62674356000
