### ISSUE TITLE
引入Modal组件，'@tarojs/components' does not contain an export named 'OpenData'

### ISSUE THREAD

**Issue by leehavin** [NervJS/taro-ui#1376]
"dependencies": {
    "@babel/runtime": "^7.7.7",
    "@tarojs/cli": "3.3.1",
    "@tarojs/components": "3.3.1",
    "@tarojs/runtime": "3.3.1",
    "@tarojs/taro": "3.3.1",
    "lodash": "4.17.15",
    "@tarojs/react": "3.3.1",
    "react": "^17.0.0",
    "react-dom": "^17.0.0",
    "taro-ui": "^3.0.0-alpha.3"
  },
  "devDependencies": {
    "@babel/core": "^7.8.0",
    "@tarojs/mini-runner": "3.3.1",
    "@tarojs/webpack-runner": "3.3.1",
    "@types/webpack-env": "^1.13.6",
    "babel-preset-taro": "3.3.1",
    "eslint": "^6.8.0",
    "eslint-config-taro": "3.3.1",
    "stylelint": "9.3.0",
    "@typescript-eslint/parser": "^4.15.1",
    "@typescript-eslint/eslint-plugin": "^4.15.1",
    "typescript": "^4.1.0",
    "@types/react": "^17.0.2",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-react-hooks": "^4.2.0"
  }

![image](https://user-images.githubusercontent.com/12468518/127603885-566be21e-3ea1-4eda-8f2a-e42327b16af6.png)

**Comment by bai-wenli** [comment]
解决了吗 哥

**Comment by meiqinLiu** [comment]
@leehavin 题主请问这个问题你有解决了吗，我现在版本是 安装也遇到这个问题 
``` "@tarojs/cli": "^3.3.12",
    "@tarojs/components": "3.3.12",
    "@tarojs/plugin-html": "^3.3.12",
    "@tarojs/react": "3.3.12",
    "@tarojs/runtime": "3.3.12",
    "@tarojs/taro": "3.3.12",
    "@tarojs/taro-alipay": "^2.2.10",
    "core-js": "^3.17.3",
    "nervjs": "^1.5.7",
    "react": "^17.0.0",
    "react-dom": "^17.0.0",
    "taro-ui": "^3.0.0-alpha.10"
```

**Comment by lupingW** [comment]
请问解决了吗

**Comment by bj-houzhenyu** [comment]
请问解决了吗，我也遇到了，微信没报这个警告，钉钉在报

**Comment by bj-houzhenyu** [comment]
开始摆烂了是吧
taro-ui/dist/index.esm.js 里面第二行
`import { View, Text, OpenData, Image, Button, Form, Switch, ScrollView, Label, Input, Textarea, Slider, MovableArea, MovableView, Swiper, SwiperItem, Picker } from '@tarojs/components';
`
openData 引自 @tarojs/components

@tarojs/components/mini/index.js 里就没有导出这个
19年开始就出现的问题，都不给解决了吗
虽然是个警告⚠️，但是issues多少人在提了，看也不看是吧

我已经给出你们解决方法了，能改一下吗？？？？
