### ISSUE TITLE
请问后续有开源设计稿（Sketch）和原型图（Axure）的计划吗？

### ISSUE THREAD

**Issue by billyma128** [NervJS/taro-ui#138]
### 重现步骤

Thank you guys for all of your awesome work!

### 依赖的版本号

Taro-UI v1.3.4

### 预期结果
提供设计稿、原型图，方便 MVP 产品定制和团队沟通

### 实际结果

Not yet

### 相关链接

参考 [Ant Design](https://ant.design/docs/spec/download-cn)

**Comment by koppthe** [comment]
暂时没有这个计划哦

**Comment by hqman** [comment]
试试这个
[Taro UI.zip](https://github.com/NervJS/taro-ui/files/3384758/Taro.UI.zip)

**Comment by koppthe** [comment]
设计资源：https://taro-ui.aotu.io/#/docs/resource
