### ISSUE TITLE
官方文档：calendar示例报错

### ISSUE THREAD

**Issue by happy-func** [NervJS/taro-ui#1381]
### Taro UI 版本信息

v2.3.4

### 问题描述

[错误链接](https://taro-ui.jd.com/#/docs/calendar)
```
Error: Date Interval Error
    at Picker.handlePrpos (0.js:1)
    at new Picker (0.js:1)
    at mountComponent (app.js:1)
    at ComponentWrapper.init (app.js:1)
    at createElement (app.js:1)
    at mountChild (app.js:1)
    at mountVNode$1 (app.js:1)
    at createElement (app.js:1)
    at mountVNode (app.js:1)
    at mountComponent (app.js:1)
(anonymous) @ app.js:1
Promise.catch (async)
updateComponent @ app.js:1
componentDidMount @ app.js:1
(anonymous) @ app.js:1
......
```

### 复现步骤

1.点击这个网址：https://taro-ui.jd.com/#/docs/calendar
2.打开浏览器调试

**Comment by happy-func** [comment]
![image](https://user-images.githubusercontent.com/46747508/129293993-37b1b8b3-93f2-4198-93d3-ab071fc1961d.png)

**Comment by happy-func** [comment]
还有就是你们的issue-helper只能选择ui版本v2.3.4,是之前的版本的bug全都解决了吗?

**Comment by P4X666** [comment]
要不试一下这个呢 [https://www.npmjs.com/package/custom-calendar-taro](https://www.npmjs.com/package/custom-calendar-taro)

**Comment by P4X666** [comment]
@happy-func 官方貌似都不管3.0之前的了

**Comment by happy-func** [comment]
@P4X666 主要是这个是Taro-UI官网演示案例的错误，这是完全不应该的。看来是KPI的风头过了，没人管了
