### ISSUE TITLE
taro init 选择的是less 但是taro-ui 统一使用的是 scss 这个 怎么处理

### ISSUE THREAD

**Issue by NiceWa** [NervJS/taro-ui#1395]
请问下taro init 选择的是less 但是taro-ui 统一使用的是 scss 这个 怎么处理

**Comment by shinken008** [comment]
google covert sass to less 的方法

**Comment by liyanging** [comment]
> 请问下taro init 选择的是less 但是taro-ui 统一使用的是 scss 这个 怎么处理

感觉这个还是挺。。。。不好用！！！！
