### ISSUE TITLE
AtInputNumber问题

### ISSUE THREAD

**Issue by wandiao** [NervJS/taro-ui#141]
AtInputNumber小程序端最大值限制无效

### 重现步骤
设置max=10
输入框输入30，显示值变为10，再输入0，值变为100，再输入0，值变为1000

### 预期结果
输入框输入30，显示值变为10，再输入0，值依然为10

**Comment by jimczj** [comment]
请设置 handleChange 来更新 state 值

**Comment by wandiao** [comment]
又测试了一下感觉是Input组件的问题， 小程序动态修改Input的value值, 只有第一次生效，之后再修改就没有效果了

**Comment by jimczj** [comment]
@wandiao 贴一下你的代码

**Comment by wandiao** [comment]
```javascript
<Input onInput={this.handleInput} value={this.state.value}></Input>

handleInput = (e) => {
    if (e.detail.value > 10) {
      this.setState({
        value: 10
      })
    }
  }
```

**Comment by jimczj** [comment]
@wandiao 额，你都设置 `e.detail.value > 10` 才触发了，那肯定只触发一次
