### ISSUE TITLE
AtTextarea onChange 回调函数只获取到字符串第一个字符

### ISSUE THREAD

**Issue by MingBuGaiJue** [NervJS/taro-ui#1420]
### 相关平台
H5

**浏览器版本: Chrome 96**
**使用框架: React**

### 复现仓库
https://github.com/MingBuGaiJue/taro-issue-demo.git

### 复现步骤
在AtTextarea中输入

### 期望结果
能获取完整的输入信息

### 实际结果
只获取到第一个字符

### 环境信息
```
  Taro CLI 3.2.0 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
      Yarn: 1.21.0 - /usr/local/bin/yarn
      npm: 8.2.0 - ~/.nvm/versions/node/v14.16.0/bin/npm
    npmPackages:
      @tarojs/components: 3.3.17 => 3.3.17
      @tarojs/mini-runner: 3.3.17 => 3.3.17
      @tarojs/react: 3.3.17 => 3.3.17
      @tarojs/runtime: 3.3.17 => 3.3.17
      @tarojs/taro: 3.3.17 => 3.3.17
      @tarojs/webpack-runner: 3.3.17 => 3.3.17
      babel-preset-taro: 3.3.17 => 3.3.17
      eslint-config-taro: 3.3.17 => 3.3.17
      react: ^17.0.0 => 17.0.2
      taro-ui: 3.0.0-alpha.10 => 3.0.0-alpha.10
```

**Comment by MingBuGaiJue** [comment]
Taro 3.3.6版本不会有问题，升级到Taro 3.3.16或者 3.3.17 才会出现。看了一下Taro-ui，也是封装的Taro的 Textarea

**Comment by MingBuGaiJue** [comment]
Taro 3.3.6版本不会有问题，升级到Taro 3.3.16或者 3.3.17 才会出现。看了一下Taro-ui，也是封装的Taro的 Textarea
node_modules/taro-ui/lib/components/textarea/index.js
![image](https://user-images.githubusercontent.com/14308879/146895086-0ecaa627-9fd4-456f-83cc-17dc0a7799a6.png)

**Comment by shinken008** [comment]
去 [taro](https://github.com/NervJS/taro) 提 issue 了？

**Comment by shinken008** [comment]
https://github.com/NervJS/taro/issues/11062
