### ISSUE TITLE
AtButton组件里 full属性无效

### ISSUE THREAD

**Issue by lian8** [NervJS/taro-ui#1428]
### Taro UI 版本信息

v3.1.0-beta.2-rn

### 问题描述

AtButton组件里 full属性无效

### 复现步骤

 full属性设置为true无效，  AtButton 都是占满一行的

### 复现代码

` <AtButton type='primary' full={false} >按钮文案</AtButton> `

### 报错信息

宽度依然100%

### 系统信息

v3.3.20

### 补充信息

https://taro-ui.jd.com/#/docs/button
文档右侧的 小按钮， demo中没有给出。 full属性无效

还想问，能不能自定义Button的宽度和背景色？  谢谢

**Comment by shinken008** [comment]
@lian8 传 customStyle: React.CSSProperties 属性，

**Comment by shinken008** [comment]
AtButton 默认是 display: block | flex，所有它是占满一行的，full 这个是设置 width: 100%，且没有 border 的

**Comment by lian8** [comment]
> customStyle:

customStyle="width:100px;"  设置宽度成功，谢谢
