### ISSUE TITLE
AtAccordion 不存在？

### ISSUE THREAD

**Issue by JoMartinezZhu** [NervJS/taro-ui#143]
![image](https://user-images.githubusercontent.com/43346131/47419015-e076db80-d7ad-11e8-9bc4-e524d42d81cd.png)
![image](https://user-images.githubusercontent.com/43346131/47419049-f84e5f80-d7ad-11e8-9100-ea6b75e7fa00.png)

**Comment by jimczj** [comment]
请升级到最新版本
![image](https://user-images.githubusercontent.com/13499146/47420490-21242400-d7b1-11e8-975b-f69ec6064dce.png)
