### ISSUE TITLE
taro-ui的AtButton组件，加了类名，h5和小程序下显示不一

### ISSUE THREAD

**Issue by shenck215** [NervJS/taro-ui#144]
taro-ui的AtButton组件，加了类名，h5和小程序下显示不一

### 重现步骤

taro-ui的AtButton组件，添加了类名，less文件里用这个类名来控制按钮颜色。编译成h5
一切正常；编译成小程序，Wxml里相应dom类名并没有加上。

### 依赖的版本号

node 10.12.0;Taro 1.0.7；Taro-UI 1.3.5

### 预期结果
h5和小程序效果一致

### 实际结果
h5效果正常，小程序不对

### 相关链接

![image](https://user-images.githubusercontent.com/20554664/47421537-60537480-d7b3-11e8-8406-8ad858b0ceb8.png)
![image](https://user-images.githubusercontent.com/20554664/47421582-7c571600-d7b3-11e8-85ce-6b06a4abeb08.png)

**Comment by jimczj** [comment]
不清楚问题

**Comment by shenck215** [comment]
> 不清楚问题
刚问题没描述完，误点了回车。现在是完整的

**Comment by jimczj** [comment]
在继续往下面审查元素，小程序的组件化是 shadow-dom

**Comment by shenck215** [comment]
@jimczj 
![image](https://user-images.githubusercontent.com/20554664/47470788-d8647d80-d839-11e8-8d6d-4b7e160b9245.png)
类名有了，样式取不到

**Comment by jimczj** [comment]
@shenck215 你的样式要定义在page 页面才能生效，不能在通过自定义组件增加了，globalClass 要全局

**Comment by jimczj** [comment]
@shenck215 展示一下代码

**Comment by shenck215** [comment]
![image](https://user-images.githubusercontent.com/20554664/47471742-56c31e80-d83e-11e8-94de-9b28044beed6.png)
![image](https://user-images.githubusercontent.com/20554664/47471758-66426780-d83e-11e8-9c9d-326b2b3b136c.png)
![image](https://user-images.githubusercontent.com/20554664/47471785-7b1efb00-d83e-11e8-8b93-4f8eece2a64d.png)
加载组件上的my-button my-button-last的样式不生效

**Comment by jimczj** [comment]
这个特性从小程序基础库版本 2.2.3 开始支持。看看是不是

**Comment by shenck215** [comment]
@jimczj 切换成2.2.3可以了
![image](https://user-images.githubusercontent.com/20554664/47472459-6728c880-d841-11e8-9dfb-4b9fedf850cb.png)
