### ISSUE TITLE
input组件web端border-bottom不能清除

### ISSUE THREAD

**Issue by hnsxxscyx** [NervJS/taro-ui#145]
### 依赖的版本号
"@tarojs/taro": "^1.0.7",
"@tarojs/taro-h5": "^1.0.7",
taro-ui: "^1.33"

### 预期结果
border设为false后下划线边框不显示
### 实际结果
微信小程序端正常，web端下划线依然存在。
*分析为at-input--without-border类设置的boder:none 不能影响到::after, 建议增加一层选择器*
### 相关链接
![image](https://user-images.githubusercontent.com/13851292/47473029-7741a780-d843-11e8-91d0-d6a1f01e9f62.png)
![image](https://user-images.githubusercontent.com/13851292/47473044-8cb6d180-d843-11e8-84a6-1daaa5cbaf81.png)

**Comment by jimczj** [comment]
升级到 1.3.5就可以了
