### ISSUE TITLE
AtListItem 中的thumb样式经常加载不进去

### ISSUE THREAD

**Issue by xiaoxingchao** [NervJS/taro-ui#146]
![image](https://user-images.githubusercontent.com/20487037/47487912-f5b73d00-d875-11e8-8688-e2821980884e.png)
![image](https://user-images.githubusercontent.com/20487037/47487945-08317680-d876-11e8-88dd-19d67c58c2e5.png)

**Comment by SzHeJason** [comment]
经常加载不进去？ 重现次数频繁吗？

**Comment by xiaoxingchao** [comment]
不怎么频繁,一天出现几次

**Comment by SzHeJason** [comment]
观察了几天 并没有重现出来 建议可以 升级 taro 的版本 这个我想应该是编译的问题  另外 不建议给 View 写样式

**Comment by xiaoxingchao** [comment]
好的.谢谢..

**Comment by SzHeJason** [comment]
@xiaoxingchao 你好 taro 最新版已经发布了 请问你升级之后还会看到这个问题吗？

**Comment by xiaoxingchao** [comment]
没了...
