### ISSUE TITLE
At input 禁用在Ios不生效

### ISSUE THREAD

**Issue by LlanHao** [NervJS/taro-ui#1465]
**问题描述**
微信小程序，Taro UI 使用 Atinput 组件设置 editable 后在iOS真机依旧可以编辑，在微信开发者工具是不可以编辑的。

**复现步骤**
1. 页面内引用 import {AtInput, AtForm} from 'taro-ui'
2. 调用 <AtInput editable={false} placeholder='企业名称' value={this.state.xxx}/>

```jsx
<AtForm>
     <Text className="input-icon">*</Text><Text className="company-name">企业名称</Text>
     <AtInput editable={false} placeholder='企业名称' value={this.state.financeApply.enterpriseName}/>
 </AtForm>
```

**期望行为**
input 禁用，并且置灰
<img width="573" alt="image" src="https://user-images.githubusercontent.com/56375728/164400262-41b601cc-0af2-47bd-8978-ba2a888f86e6.png">

**系统信息**
👽 Taro v3.3.9

  Taro CLI 3.3.9 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.5.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.2.9 => 3.2.9
      @tarojs/mini-runner: 3.2.9 => 3.2.9
      @tarojs/react: 3.2.9 => 3.2.9
      @tarojs/runtime: 3.2.9 => 3.2.9
      @tarojs/taro: 3.2.9 => 3.2.9
      @tarojs/webpack-runner: 3.2.9 => 3.2.9
      babel-preset-taro: 3.2.9 => 3.2.9
      eslint-config-taro: 3.2.9 => 3.2.9
      react: ^17.0.0 => 17.0.2
      taro-ui: ^3.0.0-alpha.10 => 3.0.0-alpha.10
    npmGlobalPackages:
      typescript: 4.3.5

异常平台 [weapp] 微信小程序 iOS 真机

**Comment by tiancaizs** [comment]
同问，这什么bug啊。突然就有了

**Comment by hjhwel** [comment]
是因为taroui 的input 没有传disabled,我之前修了下，就是直接改包里的input

**Comment by LlanHao** [comment]
https://github.com/NervJS/taro-ui/pull/1474/commits/1764b8997750e44fe680582de9aa285cc83797be

**Comment by LlanHao** [comment]
> 同问，这什么bug啊。突然就有了

看记录是修复了，https://github.com/NervJS/taro-ui/pull/1471

**Comment by LlanHao** [comment]
> 是因为taroui 的input 没有传disabled,我之前修了下，就是直接改包里的input

能提供下改了那个node包吗

**Comment by hjhwel** [comment]
我是放在公司git 上了，就修改了这个disabled 和 输入框启用clear 后聚焦失效的`AtInput.defaultProps = {
    className: '',
    customStyle: '',
    value: '',
    name: '',
    placeholder: '',
    placeholderStyle: '',
    placeholderClass: '',
    title: '',
    cursorSpacing: 50,
    confirmType: 'done',
    cursor: 0,
    selectionStart: -1,
    selectionEnd: -1,
    adjustPosition: true,
    maxlength: 140,
    type: 'text',
    disabled: false,
    border: true,
    editable: true,
    error: false,
    clear: false,
    autoFocus: false,
    focus: null,//从false 改成null
    required: false,
    // eslint-disable-next-line @typescript-eslint/no-empty-function
    onChange: function () { }
};`

**Comment by shinken008** [comment]
https://github.com/NervJS/taro-ui/blob/next/packages/taro-ui/src/components/input/index.tsx#L170

应该修复了
