### ISSUE TITLE
https://taro-ui.jd.com/  打开是 403, 有同学遇到过吗

### ISSUE THREAD

**Issue by zhangshichuan** [NervJS/taro-ui#1476]
**问题描述**

**复现步骤**

```js
// 这里可以贴代码
```

**期望行为**

**报错信息**

**系统信息**

**补充信息**

**Comment by zhangshichuan** [comment]
![image](https://user-images.githubusercontent.com/8280832/169754634-3f47ea85-ba35-41bf-bd7a-f565b050cbf3.png)

**Comment by Lemonreds** [comment]
应该是服务挂掉了，有人处理吗

**Comment by xuchao996** [comment]
+1

**Comment by xcc1995** [comment]
+1

**Comment by zhangshichuan** [comment]
可以用了, 我关 issue 了
