### ISSUE TITLE
taro-ui  beta版本目前还不支持百度小程序么

### ISSUE THREAD

**Issue by pokerII** [NervJS/taro-ui#148]

**Comment by pokerII** [comment]
![_58d86afe-6380-457f-a46f-f2485e4497bc](https://user-images.githubusercontent.com/17977712/47619014-b0fd0180-db14-11e8-9dfb-f1aad86bfbe5.png)

**Comment by pokerII** [comment]
修改了  index里面的运行 npm run dev:swan 就报sass变量没有定义 但是 执行 npm run dev:weapp 就不会报错

**Comment by jimczj** [comment]
目前还未进行适配

**Comment by pokerII** [comment]
@jimczj 好的  那我先自己实现 后期研究下适配。
