### ISSUE TITLE
Taro项目（H5端）启动后，真机访问时报错：SyntaxError: Unexpected token 'if':undefined:undefined

### ISSUE THREAD

**Issue by Jiexiansen** [NervJS/taro-ui#1483]
### Taro UI 版本信息

v3.1.0-beta.2

### 问题描述

1. 原有Taro项目（H5端）启动后，在PC端访问一切正常，但在真机中报错；
2. 新建Taro项目亦可复现该问题。（taro init myApp）

### 复现步骤

1. npm run dev:h5
2. 运行后即报错

### 复现代码

taro init myApp

### 报错信息

Error 1 of 4

SyntaxError
Unexpected token 'if'

Call Stack
  undefined
      SyntaxError: Unexpected token 'if':undefined:undefined

### 系统信息

👽 Taro v3.4.10

  Taro CLI 3.4.10 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    npmPackages:
      @tarojs/components: 3.4.8 => 3.4.8 
      @tarojs/mini-runner: 3.4.8 => 3.4.8 
      @tarojs/plugin-framework-react: 3.4.8 => 3.4.8 
      @tarojs/react: 3.4.8 => 3.4.8 
      @tarojs/runtime: 3.4.8 => 3.4.8 
      @tarojs/taro: 3.4.8 => 3.4.8 
      @tarojs/webpack-runner: 3.4.8 => 3.4.8 
      babel-preset-taro: 3.4.8 => 3.4.8 
      eslint-config-taro: 3.4.8 => 3.4.8 
      react: ^17.0.0 => 17.0.2 

### 补充信息

**报错界面**
<img width="481" alt="image" src="https://user-images.githubusercontent.com/26481272/173317950-332500c1-0ca7-457e-ac4e-12daaeee6ecb.png">

**新建可复现问题项目的选项**
<img width="606" alt="image" src="https://user-images.githubusercontent.com/26481272/173318010-72c75923-03e8-4bc1-9f7c-e02ce734175e.png">

**Comment by shinken008** [comment]
去taro 项目提 issue
