### ISSUE TITLE
Taro UI 样式不起作用

### ISSUE THREAD

**Issue by riveram** [NervJS/taro-ui#1489]
### Taro UI 版本信息

v2.3.4

### 问题描述

我将Taro从1.x升级到2.2.18后，Taro UI的样式全失效了，然后我也升级了Taro UI版本到2.3.4，然后也按照Taro UI的快速上手文档操作了（我搜多到了这个问题：https://github.com/NervJS/taro-ui/issues/536），也还是不行。然后我重新创建了一个Taro项目，然后仅仅只安装了Taro UI，然后在app.scss中加入了@import "~taro-ui/dist/style/index.scss";，然后在入口页面使用了AtButton，然后编译运行后也是一样没有样式的，这个问题已经困扰我很久了，实在是没有别的办法，麻烦你们指导下，谢谢。

### 复现步骤

因为我是创建的一个新的工程，所以代码很简单，只是在入口页面加了一个AtButton的使用
1.编译运行。
2.进入首页

### 复现代码

import Taro, { Component } from '@tarojs/taro'
import { View, Text } from '@tarojs/components'
import './index.scss'
import { AtButton } from 'taro-ui'

export default class Index extends Component {

  componentWillMount () { }

  componentDidMount () { }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  config = {
    navigationBarTitleText: '首页'
  }

  render () {
    return (
      <View className='index'>
         <AtButton type='primary'>按钮文案</AtButton>
      </View>
    )
  }
}

### 报错信息

页面上显示了“按钮文案”四个字，没有任何的按钮样式。

### 系统信息

Taro v2.2.18

  Taro CLI 2.2.18 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.19.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.16 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.2.18 => 2.2.18
      @tarojs/components-qa: 2.2.18 => 2.2.18
      @tarojs/mini-runner: 2.2.18 => 2.2.18
      @tarojs/plugin-sass: 2.2.18 => 2.2.18
      @tarojs/plugin-terser: 2.2.18 => 2.2.18
      @tarojs/router: 2.2.18 => 2.2.18
      @tarojs/taro-alipay: 2.2.18 => 2.2.18
      @tarojs/taro-qq: 2.2.18 => 2.2.18
      @tarojs/taro-quickapp: 2.2.18 => 2.2.18
      @tarojs/taro-rn: 2.2.18 => 2.2.18
      @tarojs/taro-swan: 2.2.18 => 2.2.18
      @tarojs/taro-tt: 2.2.18 => 2.2.18
      @tarojs/taro-weapp: 2.2.18 => 2.2.18
      @tarojs/webpack-runner: 2.2.18 => 2.2.18
      eslint-config-taro: 2.2.18 => 2.2.18
      eslint-plugin-taro: 2.2.18 => 2.2.18
      nerv-devtools: ^1.5.5 => 1.5.7
      stylelint-config-taro-rn: 2.2.18 => 2.2.18
      stylelint-taro-rn: 2.2.18 => 2.2.18
      taro-ui: ^2.3.4 => 2.3.4

**Comment by shinken008** [comment]
升到最新版看看呢  3.1.0-beta.3
