### ISSUE TITLE
 form 表单小程序提交事件报错

### ISSUE THREAD

**Issue by sendy-dev** [NervJS/taro-ui#1491]
版本：taro-ui 3.1.0-beta.2
 form 表单组件提交事件onSubmit，H5就可以正常使用，运行小程序报错，
![image](https://user-images.githubusercontent.com/56161847/179142803-37ef3ffa-e252-420b-8883-8d10524890fb.png)

![image](https://user-images.githubusercontent.com/56161847/179142844-dac41bcf-7110-4074-8869-b61e7e691299.png)

**Comment by whqgo** [comment]
同问 如何解决

**Comment by halodong** [comment]
箭头函数改为普通函数是否可以解决 @whqgo @sendy-dev
