### ISSUE TITLE
微信小程序编译报错

### ISSUE THREAD

**Issue by ys2rice2yangsong** [NervJS/taro-ui#1492]
**问题描述**

**复现步骤**
1，在app.scss文件夹中全局引入scss文件就包警告
                                        

这仅仅是其中一个警告

```js
//在app.scss中： @import "~taro-ui/dist/style/index.scss";
```

**期望行为**

**报错信息**

Recommendation: math.div($col, 12) or calc($col / 12)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
119 │     $width: ($col / 12) * 100%;
    │              ^^^^^^^^^
    ╵
    node_modules\taro-ui\dist\style\components\flex.scss 119:14  @import
    node_modules\taro-ui\dist\style\components\index.scss 6:9    @import
    node_modules\taro-ui\dist\style\index.scss 12:9              @import
    src\app.scss 1:9                                             root stylesheet       

Deprecation Warning: Using / for division outside of calc() is deprecated and will be r
emoved in Dart Sass 2.0.0.

Recommendation: math.div($at-avatar-size-md, 2.5) or calc($at-avatar-size-md / 2.5)    

More info and automated migrator: https://sass-lang.com/d/slash-div

  ╷
8 │   font-size: $at-avatar-size-md / 2.5;
  │              ^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
    node_modules\taro-ui\dist\style\components\avatar.scss 8:14  @import
    node_modules\taro-ui\dist\style\components\index.scss 11:9   @import
    node_modules\taro-ui\dist\style\index.scss 12:9              @import
    src\app.scss 1:9                                             root stylesheet       

Deprecation Warning: Using / for division outside of calc() is deprecated and will be r
emoved in Dart Sass 2.0.0.

Recommendation: math.div($at-avatar-size-lg, 2.5) or calc($at-avatar-size-lg / 2.5)    

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
26 │     font-size: $at-avatar-size-lg / 2.5;
   │                ^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules\taro-ui\dist\style\components\avatar.scss 26:16  @import
    node_modules\taro-ui\dist\style\components\index.scss 11:9    @import
    node_modules\taro-ui\dist\style\index.scss 12:9               @import
    src\app.scss 1:9                                              root stylesheet      

Deprecation Warning: Using / for division outside of calc() is deprecated and will be r
emoved in Dart Sass 2.0.0.

Recommendation: math.div($at-avatar-size-sm, 2.5) or calc($at-avatar-size-sm / 2.5)    

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
33 │     font-size: $at-avatar-size-sm / 2.5;
   │                ^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules\taro-ui\dist\style\components\avatar.scss 33:16  @import
    node_modules\taro-ui\dist\style\components\index.scss 11:9    @import
    node_modules\taro-ui\dist\style\index.scss 12:9               @import
    src\app.scss 1:9                                              root stylesheet      

Deprecation Warning: Using / for division outside of calc() is deprecated and will be r
emoved in Dart Sass 2.0.0.

Recommendation: math.div($at-button-height, 2) or calc($at-button-height / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
87 │     border-radius: $at-button-height / 2;
   │                    ^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules\taro-ui\dist\style\components\button.scss 87:20  @import
    node_modules\taro-ui\dist\style\components\index.scss 13:9    @import
    node_modules\taro-ui\dist\style\index.scss 12:9               @import
    src\app.scss 1:9                                              root stylesheet      

Warning: 16 repetitive deprecation warnings omitted.

**系统信息**

F:\react\witkey_study_redux>taro info
👽 Taro v3.4.13

  Taro CLI 3.4.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.15.0 - F:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - F:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 8.5.5 - F:\Program Files\nodejs\npm.CMD

**补充信息**

**Comment by whqgo** [comment]
npm install -g sass-migrator
进入项目node_modules文件
执行sass-migrator division **/*.scss

原文： https://blog.csdn.net/qq_36657291/article/details/121995360

**Comment by LiucCheng** [comment]
我按照上面方法执行了sass-migrator后，依然还是编译失败
![image](https://user-images.githubusercontent.com/29134803/206398583-1c1bcca2-4b5d-4614-8de5-c1c390d6fa78.png)
