### ISSUE TITLE
taro小程序不认识原生websocket构造函数？

### ISSUE THREAD

**Issue by sendy-dev** [NervJS/taro-ui#1494]
打包小程序websocket报错，h5可以正常使用

 "react": "^17.0.0",
  "react-dom": "^17.0.0",
  "taro-ui": "^3.1.0-beta.2"
 "typescript": "^4.1.0"
 "@tarojs/cli": "3.4.12",
  "@tarojs/components": "3.4.12",
  "@tarojs/plugin-framework-react": "3.4.12",
  "@tarojs/react": "3.4.12",
  "@tarojs/runtime": "3.4.12",
  "@tarojs/taro": "3.4.12",

![5d40a3170a7c65e5fc950d0be82de76](https://user-images.githubusercontent.com/56161847/180585738-4b929c94-f75a-49e3-80d2-4836907e82f2.jpg)
![c11a9b1c69b9176c88c49233d532dfa](https://user-images.githubusercontent.com/56161847/180585741-741a8a89-8ca4-4213-9fdb-e802620d7b6d.jpg)

**Comment by shinken008** [comment]
小程序没有这个Websocket对象

https://developers.weixin.qq.com/miniprogram/dev/wxcloudrun/src/development/websocket/miniprogram.html
