### ISSUE TITLE
flex布局存在多余代码

### ISSUE THREAD

**Issue by Jiangxxxxxxx** [NervJS/taro-ui#1495]
![image](https://user-images.githubusercontent.com/88698337/180677627-997eaa98-6562-4797-af4c-f2d67fab6ca3.png)
![image](https://user-images.githubusercontent.com/88698337/180677656-3d10c344-c40b-4431-b699-5f6a015dbf58.png)
src/components/flex中的样式文件是否为多余的，看起来直接从src/style/components/flex引用即可，并且外部引用时也是引用style/components/flex

**Comment by shinken008** [comment]
把多余的代码删了提个 pr

**Comment by Jiangxxxxxxx** [comment]
pr已提交，https://github.com/NervJS/taro-ui/pull/1514/commits/0a3d354b29ab7fe523bccaa96a80799ef4c77bc1
