### ISSUE TITLE
AtButton组件ts类型错误

### ISSUE THREAD

**Issue by alwaysRemember** [NervJS/taro-ui#1497]
### Taro UI 版本信息

v3.1.0-beta.2

### 问题描述

AtButton组件使用的时候报错

### 复现步骤

无

### 复现代码

<AtButton
            className={styles['btn']}
            type='primary'
            circle
            size='small'
          >
            复制微信号
          </AtButton>

### 报错信息

不能将类型“{ children: string; className: any; type: "primary"; circle: true; size: "small"; }”分配给类型“IntrinsicAttributes & IntrinsicClassAttributes<Component<AtButtonProps, any, any>> & Readonly<AtButtonProps>”。
  类型“IntrinsicAttributes & IntrinsicClassAttributes<Component<AtButtonProps, any, any>> & Readonly<AtButtonProps>”上不存在属性“children”。

### 系统信息

$ taro info
👽 Taro v3.5.1

  Taro CLI 3.5.1 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.5.2 - ~/.nvm/versions/node/v16.14.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.1 => 3.5.1
      @tarojs/components: 3.5.1 => 3.5.1
      @tarojs/helper: 3.5.1 => 3.5.1
      @tarojs/plugin-framework-react: 3.5.1 => 3.5.1
      @tarojs/plugin-platform-alipay: 3.5.1 => 3.5.1
      @tarojs/plugin-platform-jd: 3.5.1 => 3.5.1
      @tarojs/plugin-platform-qq: 3.5.1 => 3.5.1
      @tarojs/plugin-platform-swan: 3.5.1 => 3.5.1
      @tarojs/plugin-platform-tt: 3.5.1 => 3.5.1
      @tarojs/plugin-platform-weapp: 3.5.1 => 3.5.1
      @tarojs/react: 3.5.1 => 3.5.1
      @tarojs/router: 3.5.1 => 3.5.1
      @tarojs/runtime: 3.5.1 => 3.5.1
      @tarojs/shared: 3.5.1 => 3.5.1
      @tarojs/taro: 3.5.1 => 3.5.1
      @tarojs/taro-h5: 3.5.1 => 3.5.1
      babel-preset-taro: 3.5.1 => 3.5.1
      eslint-config-taro: 3.5.1 => 3.5.1
      react: ^18.0.0 => 18.2.0
      taro-ui: ^3.1.0-beta.2 => 3.1.0-beta.2

**Comment by NgChiKin** [comment]
taro版本 3.5.4，taro-ui 版本 3.1.0-beta.2 一样类型报错，并且编译后连按钮都没有了，查看页面结构只有 view

![image](https://user-images.githubusercontent.com/57823909/187656604-ab95009b-c33b-4438-ac20-02caf51e32bf.png)

**Comment by mcWang66** [comment]
一样类型报错
![8340ccae1ac4a80b745c7267c33a3ee](https://user-images.githubusercontent.com/17886159/190087506-1fa4d6d1-421d-424d-ad79-fd7d07ee1835.jpg)

**Comment by greenking19** [comment]
> 一样类型报错 ![8340ccae1ac4a80b745c7267c33a3ee](https://user-images.githubusercontent.com/17886159/190087506-1fa4d6d1-421d-424d-ad79-fd7d07ee1835.jpg)

好兄弟， 你解决了吗？

**Comment by Miroxyz** [comment]
xdm，你们解决了吗？

**Comment by greenking19** [comment]
> xdm，你们解决了吗？

弃用吧， 好像这个插件已经被遗弃了。 我用了官方的TDesign了
