### ISSUE TITLE
弹框有点丑

### ISSUE THREAD

**Issue by MinJieLiu** [NervJS/taro-ui#15]
弹框中间的边框感觉不是 1px ，过渡效果感觉一股山寨气息，不如不要过渡效果了

**Comment by SzHeJason** [comment]
@MinJieLiu 边框的1px 并不是 实际的1px ,想要画出真正的1px(对于小程序是 1rpx)在h5 的 部分机型上会丢失样式 目前是折中方案 以后会支持。 至于过渡效果 我们会参考 大家的意见 可以讨论下
