### ISSUE TITLE
AtTabs标签fontSize、fixed字段配置不生效

### ISSUE THREAD

**Issue by gayshub** [NervJS/taro-ui#1521]
### Taro UI 版本信息

v3.1.0-beta.3

### 问题描述

AtTabs标签fontSize字段配置不生效

### 复现步骤

1.直接贴代码上去即可

### 复现代码

`
<AtTabs current={currentTab} fontSize={13} tabList={tabList} onClick={handleChangeTab} fixed={true}> `

### 报错信息

无

### 系统信息

👽 Taro v3.5.2

  Taro CLI 3.5.2 environment info:
    System:
      OS: Windows 8.1
    Binaries:
      Node: 12.22.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD

**Comment by gayshub** [comment]
哎，还是退回使用原生微信小程序了

**Comment by shinken008** [comment]
https://taro-ui.jd.com/#/docs/tabs

没有 fontSize 和 fixed 配置，自己写 style 或者class写样式
