### ISSUE TITLE
一大堆bug

### ISSUE THREAD

**Issue by gujiwuqing** [NervJS/taro-ui#1527]
<img width="795" alt="image" src="https://user-images.githubusercontent.com/44566835/188266744-3d1a9923-e2b6-4cf8-af8b-79dc4d7a0df7.png">
没看懂 为什么taro创建完项目，引入taro ui，一大堆bug，根本用不了

**Comment by kilicmu** [comment]
@gujiwuqing 碰到同样问题，看起来像是类型冲突了，最后您是怎么解决的呢？
