### ISSUE TITLE
Atcalendar 顶部的年月无法显示

### ISSUE THREAD

**Issue by hugyu** [NervJS/taro-ui#1528]
**问题描述**

我在用taro-ui@3.0.0-alpha.3 的Atcalendar组件时 在微信开发者工具预览的时候 顶部的年月无法显示

**复现步骤**

```js
// 这里可以贴代码
return (
    <View className=".calendar-page">
    
      <AtCalendar
        currentDate={chooseCityStore.cityInfos.dptDate}
        minDate={MIN_DATE}
        maxDate={MAX_date}
        onSelectDate={onDateSelect}
        monthFormat={"YYYY年MM月"}
      />
      
    </View>
```

**期望行为**

可以显示出顶部的年月

**报错信息**

![image](https://user-images.githubusercontent.com/92319342/188314830-6c129354-5785-4876-a54d-981ccb439524.png)

**系统信息**

**补充信息**
![image](https://user-images.githubusercontent.com/92319342/188314921-343a023f-b659-4b9f-b00d-0e7d2e6e4673.png)

**Comment by wanglihuaya** [comment]
老哥解决了吗，我也有这个问题

**Comment by wanglihuaya** [comment]
最后的结局办法是，将taro-ui源码拿下来，单独讲日历组件代码拿出来放在项目里作为组件来用，就显示出来了，css还是按之前的饮用就可以

**Comment by hugyu** [comment]
啥意思

**Comment by LiMao00** [comment]
也遇到了 无解

**Comment by wanglihuaya** [comment]
> 也遇到了 无解

![image](https://user-images.githubusercontent.com/49522285/197146086-032d2c14-e804-4993-a9b3-704e1edd8b13.png)
复制zhan tie粘贴过来

**Comment by wanglihuaya** [comment]
> 啥意思

taro-ui/packages/taro-ui/src/components/calendar/
从源码中复制过来，粘贴到自己的代码中

**Comment by LiMao00** [comment]
不用了 想找找别的组件库 感觉taro-ui不是团队维护的重点 累积的issue那么多

**Comment by wanglihuaya** [comment]
> 不用了 想找找别的组件库 感觉taro-ui不是团队维护的重点 累积的issue那么多

老哥 找到了喊我，还有什么好用的组件库

**Comment by LiMao00** [comment]
![image](https://user-images.githubusercontent.com/99939885/197147324-e33d5ed9-3241-4248-a9fc-c85561f67a71.png)
额外有[NeteaseYanxuan/OSSA](https://github.com/NeteaseYanxuan/OSSA)

**Comment by j10ccc** [comment]
#1555 直接把组件拆出来可以解决，最终解决方案还是改 webpack 配置
