### ISSUE TITLE
AtModal 发现 Modal 模态框 一个bug

### ISSUE THREAD

**Issue by EForinaJ** [NervJS/taro-ui#154]
我页面初始化的数据isOpened为false，
![qq 20181031231538](https://user-images.githubusercontent.com/22424208/47798295-13e3d800-dd63-11e8-97ea-d0025a30e203.png) 然后我在判断这个登录缓存状态的时候，把这个isOpened 设置为true了，控制台打印出来也是true
![qq 20181031231554](https://user-images.githubusercontent.com/22424208/47798368-337b0080-dd63-11e8-85d3-28a90a9f7ef8.png)

![qq 20181031231615](https://user-images.githubusercontent.com/22424208/47798425-4f7ea200-dd63-11e8-8149-f4de873d4ea9.png)

而且我下面AtModal的isOpened 也没写错  为什么这个模态框 state改变后不能出现呢？只有在初始化的时候设置为true 才能弹出来 这个 模态框 setState 后 就不见弹出来了

![qq 20181031231945](https://user-images.githubusercontent.com/22424208/47798539-8ce32f80-dd63-11e8-9519-63056fd9e9b9.png)

**Comment by SzHeJason** [comment]
taro-ui 的版本是啥？ 另外 如果你的 isOpened 为 true 那么 你再把他设置为 true 是不会触发的 因此 Modal 提供了 onClose 这个事件来帮助你完成 state 的同步

**Comment by SzHeJason** [comment]
? 如果长时间没有回复的话 我将关闭这个 issue 了？

**Comment by JackPu** [comment]
至今仍在，设置为 false , 会重新打开一次后又隐藏

**Comment by HeMiaoQ** [comment]
我也遇到这个问题了，有解决方案吗
