### ISSUE TITLE
大家不要问了，kpi项目到期，所有的回答均为请遵守issue规则

### ISSUE THREAD

**Issue by Tenodec** [NervJS/taro-ui#1544]
看都不看问题描述，就直接回答，有全部问的是代码问题吗

**Comment by Tenodec** [comment]
机器人回答

**Comment by Garfield550** [comment]
这个 UI 框架交给社区维护了，希望有能力的大家一起来维护。

说来惭愧，作为 2019 年加入的社区维护者，因为工作原因，我已经离开微信小程序开发一年半了。

**Comment by swm188** [comment]
... `AtButton` 组件 连个 `color` 属性都没有哎

**Comment by Garfield550** [comment]
可以去申请成为社区维护者，给项目提 PR。

**Comment by ctcx** [comment]
建议删库吧，有能力的开发者再重新造轮子。
