### ISSUE TITLE
input 、checkbox框底部出现边框

### ISSUE THREAD

**Issue by jiangzeyin** [NervJS/taro-ui#155]
### 依赖的版本号

taro 👽 Taro v1.1.0-beta.15

taro-ui 1.3.5

### 预期结果

没有边框

### 实际结果

![image](https://user-images.githubusercontent.com/16408873/47899762-7fd65580-deb5-11e8-9105-c745006655b6.png)

![image](https://user-images.githubusercontent.com/16408873/47899773-8e247180-deb5-11e8-94f6-a34197c5bcb1.png)

这个边框重写不掉。不知道怎么解决

**Comment by jiangzeyin** [comment]
我将编译后的那段 ： border-bottom-width: 1PX; 删除后就没有线了。

**Comment by jimczj** [comment]
input 设置`border = {false}`，可去掉边框，checkbox 默认有，可自己审查元素覆盖
