### ISSUE TITLE
taro-ui 组件无法使用：“AtButton”不能用作 JSX 组件。

### ISSUE THREAD

**Issue by yao378186268** [NervJS/taro-ui#1553]
![image](https://user-images.githubusercontent.com/84838562/199918905-a178b639-9e70-4304-bdad-21e624c86710.png)
![image](https://user-images.githubusercontent.com/84838562/199918945-530dab93-a5bf-4175-b1c1-d4ca5310c252.png)
![image](https://user-images.githubusercontent.com/84838562/199919099-65796b14-e18f-4713-89df-f8048e8b664e.png)

**Comment by melon95** [comment]
建议不要使用这个  react版本还是16的

**Comment by leezhian** [comment]
原因是taro 3 使用的是 react 18，而taro ui 2使用的是16版本，其实主要是 @types/react 版本不一致导致。
要么使用 taro ui3版本要么通过 `package.json` `resolutions` 锁定版本（yarn）

**Comment by robinv8** [comment]
安装最新版 `taro-ui`
```bash
npm install taro-ui@latest
```
