### ISSUE TITLE
taro ui 组件AtInput不展示

### ISSUE THREAD

**Issue by ghost** [NervJS/taro-ui#1554]
![image](https://user-images.githubusercontent.com/15712613/200465931-cb0e8960-d350-4519-b5a9-b51572bab6c5.png)
使用的官方文档中的例子，但是微信小程序开发工具中没有显示
![image](https://user-images.githubusercontent.com/15712613/200466349-b3d28ec0-1ca7-4133-848a-efb76311ed3f.png)

taro 版本： 3.5.7
taro-ui 版本 ^3.1.0-beta.4
taro项目使用模版 react-native

**Comment by goldcoast** [comment]
这种问题在新版本貌似非常普遍了，但taro-ui的回答始终就是上面的内容，越来越官僚了

**Comment by vanswang** [comment]
> 这种问题在新版本貌似非常普遍了，但taro-ui的回答始终就是上面的内容，越来越官僚了

唉，也没有什么回复。。。

**Comment by Symous** [comment]
这么明显的bug没人修复么，小程序端未渲染input控件，h5正常。

如果在页面中加入一个@tarojs/components的Input组件，没显示出来的AtInput也可以显示出来了，奇葩。

**Comment by maxbitcoin** [comment]
#1555 看我在这个问题下面的回答

**Comment by wh77572** [comment]
> 

对头  涉及input的都是这样   属实奇葩

**Comment by wh77572** [comment]
> > 
> 
> 对头 涉及input的都是这样 属实奇葩

翻了几个issue  加上compiler: {
    type: 'webpack5',
    prebundle: {
      exclude: ['ossaui']
    }
  },这个就可以了  但还是有点问题

**Comment by leapx-ai** [comment]
遇到这个问题就知道taro-ui的质量了，不敢恭维，用起来添堵，莫名其妙的问题，最后还是选择自己封装了

**Comment by LisaBiuBiu** [comment]
> > > 
> > 
> > 
> > 对头 涉及input的都是这样 属实奇葩
> 
> 翻了几个issue 加上compiler: { type: 'webpack5', prebundle: { exclude: ['ossaui'] } },这个就可以了 但还是有点问题

试了一下还是不行

**Comment by robinv8** [comment]
应该是在 webpack5 上出现了该问题，可以修改下配置：
```
{
    compiler: {
        type: "webpack5",
        prebundle: {
            exclude: ["taro-ui"],
        },
    }
}
```
