### ISSUE TITLE
AtForm 里面的内容不显示出来

### ISSUE THREAD

**Issue by chesongsong** [NervJS/taro-ui#1555]
**问题描述**
AtForm 组件在小程序中不显示出来

**复现步骤**

```js
import React from 'react'
import { AtButton, AtForm, AtInput, AtToast } from 'taro-ui'
import { View } from '@tarojs/components'
import Taro from '@tarojs/taro'

interface PageFormState {
  value1: string
  value2: string
  text: string
  isOpened: boolean
  [key: string]: string | boolean
}

export default class PageForm extends React.Component<{}, PageFormState> {
  public config: Taro.PageConfig = {
    navigationBarTitleText: 'Taro UI'
  }

  public constructor(props: any) {
    super(props)
    this.state = {
      value1: '',
      value2: '',
      text: '',
      isOpened: false
    }
  }

  private handleChange(stateName: string, value: any): void {
    this.setState({
      [stateName]: value
    })
  }

  private handleSubmit(): void {
    const { value1, value2, value3 } = this.state
    if (!value1 || !value2) {
      this.setState({
        isOpened: true,
        text: `表单必填项未填写完整`
      })
    } else {
      this.setState({
        isOpened: true,
        text: `${value1} / ${value2}`
      })
    }
    this.closeToast()
  }

  private closeToast(): void {
    setTimeout(() => {
      this.setState({
        isOpened: false
      })
    }, 2000)
  }

  private handleReset(): void {
    this.setState({
      isOpened: true,
      text: `表单已被重置`,
      value1: '',
      value2: '',
    })
    this.closeToast()
  }

  public render(): JSX.Element {
    return (
      <View className='page'>
        <View className='doc-body'>
          {/* 表单提交与重置 */}
          <View className='panel'>
            <View className='panel__title'>表单提交与重置</View>
            <View className='panel__content no-padding'>
              <View className='component-item'>
                <AtForm
                  onSubmit={this.handleSubmit.bind(this)}
                  onReset={this.handleReset.bind(this)}
                >
                  <AtInput
                    required
                    name='value1'
                    title='文本'
                    type='text'
                    placeholder='单行文本'
                    value={this.state.value1}
                    onChange={this.handleChange.bind(this, 'value1')}
                  />
                  <AtInput
                    required
                    name='value2'
                    title='密码'
                    type='password'
                    placeholder='请输入密码'
                    value={this.state.value2}
                    onChange={this.handleChange.bind(this, 'value2')}
                  />
                  <View className='component-item__btn-group'>
                    <View className='component-item__btn-group__btn-item'>
                      <AtButton type='primary' formType='submit'>
                        提交
                      </AtButton>
                    </View>
                    <View className='component-item__btn-group__btn-item'>
                      <AtButton formType='reset'>重置</AtButton>
                    </View>
                  </View>
                </AtForm>
              </View>
            </View>
          </View>
        </View>
        <AtToast
          text={this.state.text}
          isOpened={this.state.isOpened}
        ></AtToast>
      </View>
    )
  }
}
```

**期望行为**
AtForm组件内的内容全部展示

**报错信息**
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/21020093/200728300-bf2ca880-5118-45e2-96a6-aff526b78ba4.png">
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/21020093/200728356-68dfd9cb-2a57-4268-8953-b193920f416a.png">

**系统信息**
{
  "name": "water-demo",
  "version": "1.0.0",
  "private": true,
  "description": "",
  "templateInfo": {
    "name": "taro-ui",
    "typescript": true,
    "css": "sass"
  },
  "scripts": {
    "build:weapp": "taro build --type weapp",
    "build:swan": "taro build --type swan",
    "build:alipay": "taro build --type alipay",
    "build:tt": "taro build --type tt",
    "build:h5": "taro build --type h5",
    "build:rn": "taro build --type rn",
    "build:qq": "taro build --type qq",
    "build:jd": "taro build --type jd",
    "build:quickapp": "taro build --type quickapp",
    "dev:weapp": "npm run build:weapp -- --watch",
    "dev:swan": "npm run build:swan -- --watch",
    "dev:alipay": "npm run build:alipay -- --watch",
    "dev:tt": "npm run build:tt -- --watch",
    "dev:h5": "npm run build:h5 -- --watch",
    "dev:rn": "npm run build:rn -- --watch",
    "dev:qq": "npm run build:qq -- --watch",
    "dev:jd": "npm run build:jd -- --watch",
    "dev:quickapp": "npm run build:quickapp -- --watch"
  },
  "browserslist": [
    "last 3 versions",
    "Android >= 4.1",
    "ios >= 8"
  ],
  "author": "",
  "dependencies": {
    "@babel/runtime": "^7.7.7",
    "@tarojs/components": "3.5.6",
    "@tarojs/helper": "3.5.6",
    "@tarojs/plugin-framework-react": "3.5.6",
    "@tarojs/plugin-platform-alipay": "3.5.6",
    "@tarojs/plugin-platform-jd": "3.5.6",
    "@tarojs/plugin-platform-qq": "3.5.6",
    "@tarojs/plugin-platform-swan": "3.5.6",
    "@tarojs/plugin-platform-tt": "3.5.6",
    "@tarojs/plugin-platform-weapp": "3.5.6",
    "@tarojs/react": "3.5.6",
    "@tarojs/router": "3.5.6",
    "@tarojs/runtime": "3.5.6",
    "@tarojs/shared": "3.5.6",
    "@tarojs/taro": "3.5.6",
    "@tarojs/taro-h5": "3.5.6",
    "lodash": "4.17.15",
    "qs": "^6.11.0",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "taro-ui": "^3.1.0-beta.2"
  },
  "devDependencies": {
    "@babel/core": "^7.8.0",
    "@pmmmwh/react-refresh-webpack-plugin": "^0.5.5",
    "@tarojs/cli": "3.5.6",
    "@tarojs/webpack5-runner": "3.5.6",
    "@types/react": "^18.0.0",
    "@types/webpack-env": "^1.13.6",
    "@typescript-eslint/eslint-plugin": "^5.20.0",
    "@typescript-eslint/parser": "^5.20.0",
    "babel-preset-taro": "3.5.6",
    "eslint": "^8.12.0",
    "eslint-config-taro": "3.5.6",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-react-hooks": "^4.2.0",
    "react-refresh": "^0.11.0",
    "stylelint": "9.3.0",
    "typescript": "^4.1.0",
    "webpack": "5.69.0"
  }
}

**补充信息**

**Comment by vanswang** [comment]
我也遇到这个问题了，我还以为是我代码写的有问题呢。。。。查了半天

**Comment by yao378186268** [comment]
俺也一样，百度一上午了。支付宝小程序正常没有问题，微信小程序就不显示。
![image](https://user-images.githubusercontent.com/84838562/201815325-86df0b9a-b5de-4ab7-a899-0a278219ac82.png)
加一个原生的Form 就能出来了，不知道为啥。

**Comment by goldcoast** [comment]
把 taro 的版本切回 3.4.13 后， taro-ui 的最新版本就可以了

**Comment by maxbitcoin** [comment]
我来解释一下为什么切换taro3.4.13版本就显示正常的原因，而且build没问题但dev不显示，我也遇到同样的问题，在快要放弃taro-ui的时候，看到taro首页广告栏里的OSSA网易严选的组件库，里边有这样一段话：

   

>  “在taro3.5之后的版本中，在开启prebundle(默认开启)的情况下，会导致ossaui所引用的@taro/components组件没有被打进最终的bundle中，导致页面表现异常。”[手动将ossaui排除在prebundle列表之外](https://ossa.miaode.com/docs/start)

随后搜索taro文档：
> [compiler.prebundle](https://taro-docs.jd.com/docs/config-detail#compilerprebundle)，“是否开启依赖预编译功能。开启后首次编译 Taro 会把项目的 node_modules 依赖打包为模块联邦的 Remote 应用，二次编译时 Webpack 只需要编译项目源码，从而提升编译速度。”“默认值：生产环境为 false，开发环境为 true”

所以当taro版本>=3.5时，taro项目使用taro-ui的正确的配置方式是在config/index.js文件中排除taro-ui


``` javascript
// config/index.js
module.exports = {
  framework: 'react',
  compiler: {
    type: 'webpack5',
    prebundle: {
      exclude: ['taro-ui']
    }
  },
}

**Comment by zhangxinyong12** [comment]
666666666666666666666、官网能否更新一下文档。直接劝退

**Comment by YueHua46** [comment]
> 我来解释一下为什么切换taro3.4.13版本就显示正常的原因，而且build没问题但dev不显示，我也遇到同样的问题，在快要放弃taro-ui的时候，看到taro首页广告栏里的OSSA网易严选的组件库，里边有这样一段话：
> 
> > “在taro3.5之后的版本中，在开启prebundle(默认开启)的情况下，会导致ossaui所引用的@taro/components组件没有被打进最终的bundle中，导致页面表现异常。”[手动将ossaui排除在prebundle列表之外](https://ossa.miaode.com/docs/start)
> 
> 随后搜索taro文档：
> 
> > [compiler.prebundle](https://taro-docs.jd.com/docs/config-detail#compilerprebundle)，“是否开启依赖预编译功能。开启后首次编译 Taro 会把项目的 node_modules 依赖打包为模块联邦的 Remote 应用，二次编译时 Webpack 只需要编译项目源码，从而提升编译速度。”“默认值：生产环境为 false，开发环境为 true”
> 
> 所以当taro版本>=3.5时，taro项目使用taro-ui的正确的配置方式是在config/index.js文件中排除taro-ui
> 
> ```js
> // config/index.js
> module.exports = {
>   framework: 'react',
>   compiler: {
>     type: 'webpack5',
>     prebundle: {
>       exclude: ['taro-ui']
>     }
>   },
> }
> ```

666666，大佬牛逼

**Comment by NaturalGao** [comment]
AtSwipeAction 也显示不出来，长度和宽度都为0，排除了  taro-ui  宽度还是 0

**Comment by janedge** [comment]
> ```js
>    prebundle: {
>       exclude: ['taro-ui']
>     }
> ```
nb，解决了

**Comment by loveminimal** [comment]
> 我来解释一下为什么切换taro3.4.13版本就显示正常的原因，而且build没问题但dev不显示，我也遇到同样的问题，在快要放弃taro-ui的时候，看到taro首页广告栏里的OSSA网易严选的组件库，里边有这样一段话：
> 
> > “在taro3.5之后的版本中，在开启prebundle(默认开启)的情况下，会导致ossaui所引用的@taro/components组件没有被打进最终的bundle中，导致页面表现异常。”[手动将ossaui排除在prebundle列表之外](https://ossa.miaode.com/docs/start)
> 
> 随后搜索taro文档：
> 
> > [compiler.prebundle](https://taro-docs.jd.com/docs/config-detail#compilerprebundle)，“是否开启依赖预编译功能。开启后首次编译 Taro 会把项目的 node_modules 依赖打包为模块联邦的 Remote 应用，二次编译时 Webpack 只需要编译项目源码，从而提升编译速度。”“默认值：生产环境为 false，开发环境为 true”
> 
> 所以当taro版本>=3.5时，taro项目使用taro-ui的正确的配置方式是在config/index.js文件中排除taro-ui
> 
> ```js
> // config/index.js
> module.exports = {
>   framework: 'react',
>   compiler: {
>     type: 'webpack5',
>     prebundle: {
>       exclude: ['taro-ui']
>     }
>   },
> }
> ```

💡 确实如此，另外需要注意的是，如果你引用的是其它的 UI ，如 `taro-ui-vue3` ，就需要替换成对应的，如下：

```js
compiler: {
  type: 'webpack5',
  prebundle: {
    exclude: ['taro-ui-vue3']
  }
},
```

**Comment by wandouni** [comment]
> 

为什么我这样配置会报错【Taro 配置有误】呀？
![image](https://github.com/NervJS/taro-ui/assets/16540246/08fad9a0-c8ae-4351-b4b1-ee5a6c00e759)

**Comment by wangcheng2005** [comment]
@wandouni 俺也一样, 请问怎么解决的啊

**Comment by dendoink** [comment]
> @wandouni 俺也一样, 请问怎么解决的啊

直接用 webpack4 没这个问题

**Comment by HyperClockUp** [comment]
@wandouni @wangcheng2005 
把所有taro相关的降级到`3.5.4`，删除node_modules重新安装，然后再依照前文改成下面这样就可以了
再加上
```
  compiler: {
    type: "webpack5",
    prebundle: {
      exclude: ["taro-ui"]
    }
  },
```

**Comment by dendoink** [comment]
> @wandouni @wangcheng2005 
> 
> 把所有taro相关的降级到`3.5.4`，删除node_modules重新安装，然后再依照前文改成下面这样就可以了
> 
> 再加上
> 
> ```
> 
>   compiler: {
> 
>     type: "webpack5",
> 
>     prebundle: {
> 
>       exclude: ["taro-ui"]
> 
>     }
> 
>   },
> 
> ```

感谢，但是已经换到了webpack 4 明天再试试

**Comment by JuvenileQ** [comment]
> 我来解释一下为什么切换taro3.4.13版本就显示正常的原因，而且build没问题但dev不显示，我也遇到同样的问题，在快要放弃taro-ui的时候，看到taro首页广告栏里的OSSA网易严选的组件库，里边有这样一段话：
> 
> > “在taro3.5之后的版本中，在开启prebundle(默认开启)的情况下，会导致ossaui所引用的@taro/components组件没有被打进最终的bundle中，导致页面表现异常。”[手动将ossaui排除在prebundle列表之外](https://ossa.miaode.com/docs/start)
> 
> 随后搜索taro文档：
> 
> > [compiler.prebundle](https://taro-docs.jd.com/docs/config-detail#compilerprebundle)，“是否开启依赖预编译功能。开启后首次编译 Taro 会把项目的 node_modules 依赖打包为模块联邦的 Remote 应用，二次编译时 Webpack 只需要编译项目源码，从而提升编译速度。”“默认值：生产环境为 false，开发环境为 true”
> 
> 所以当taro版本>=3.5时，taro项目使用taro-ui的正确的配置方式是在config/index.js文件中排除taro-ui
> 
> ```js
> // config/index.js
> module.exports = {
>   framework: 'react',
>   compiler: {
>     type: 'webpack5',
>     prebundle: {
>       exclude: ['taro-ui']
>     }
>   },
> }
> ```

怎么能避免这个问题？或者是有其他办法解决吗？

**Comment by ONE-0508** [comment]
> 我来解释一下为什么切换taro3.4.13版本就显示正常的原因，而且build没问题但dev不显示，我也遇到同样的问题，在快要放弃taro-ui的时候，看到taro首页广告栏里的OSSA网易严选的组件库，里边有这样一段话：
> 
> > “在taro3.5之后的版本中，在开启prebundle(默认开启)的情况下，会导致ossaui所引用的@taro/components组件没有被打进最终的bundle中，导致页面表现异常。”[手动将ossaui排除在prebundle列表之外](https://ossa.miaode.com/docs/start)
> 
> 随后搜索taro文档：
> 
> > [compiler.prebundle](https://taro-docs.jd.com/docs/config-detail#compilerprebundle)，“是否开启依赖预编译功能。开启后首次编译 Taro 会把项目的 node_modules 依赖打包为模块联邦的 Remote 应用，二次编译时 Webpack 只需要编译项目源码，从而提升编译速度。”“默认值：生产环境为 false，开发环境为 true”
> 
> 所以当taro版本>=3.5时，taro项目使用taro-ui的正确的配置方式是在config/index.js文件中排除taro-ui
> 
> ```js
> // config/index.js
> module.exports = {
>   framework: 'react',
>   compiler: {
>     type: 'webpack5',
>     prebundle: {
>       exclude: ['taro-ui']
>     }
>   },
> }
> ```

我靠 大脑牛逼
