### ISSUE TITLE
怎么使用这个版本？3.6.0-beta.3-rn

### ISSUE THREAD

**Issue by tianlinzx** [NervJS/taro-ui#1558]
[v3.6.0-beta.3-rn](https://github.com/NervJS/taro-ui/releases/tag/v3.6.0-beta.3-rn)

![WechatIMG96](https://user-images.githubusercontent.com/1411754/202377541-7ad56c82-5765-4bc4-b0e6-db18a9b2b680.png)

NPM里面找不到这个版本的库。

**Comment by tianlinzx** [comment]
@zhiqingchen

**Comment by zhiqingchen** [comment]
这个是 demo 的预览用的，不是 taro-ui 的版本，不要使用。

**Comment by zhiqingchen** [comment]
已更新为 prerelease 版本

**Comment by tianlinzx** [comment]
@zhiqingchen Tony大神，有没有可用的Taro-UI RN的例子？？给个链接参考一下？

**Comment by zhiqingchen** [comment]
https://github.com/NervJS/taro-ui/tree/feat/rn-69/packages/taro-ui-demo-rn

https://github.com/NervJS/taro-ui/tree/feat/rn-70/packages/taro-ui-demo-rn

https://github.com/zhiqingchen/taro-ui-rn-demo

**Comment by tianlinzx** [comment]
@zhiqingchen  https://github.com/NervJS/taro-ui/tree/feat/rn-70/packages/taro-ui-demo-rn
这个分支在不同环境，mac、linux都试过，还是报错啊，用不了。

**Comment by zhiqingchen** [comment]
> @zhiqingchen  https://github.com/NervJS/taro-ui/tree/feat/rn-70/packages/taro-ui-demo-rn
> 
> 这个分支在不同环境，mac、linux都试过，还是报错啊，用不了。

这个是没问题的，是不是用错版本的playground预览了，这个是0.70的，需要1.8.0的playground app
