### ISSUE TITLE
model的问题及建议

### ISSUE THREAD

**Issue by cmideal** [NervJS/taro-ui#156]
### 相关链接

建议如下：
可以选择点击overlay 是否关闭通过设置onclose函数判断

content不要设置最小高度180px

**Comment by SzHeJason** [comment]
在最新的版本里面 ovelay 是可以关闭的 建议升级一发
至于内容最小高度 @koppthe 看看？

**Comment by SzHeJason** [comment]
@cmideal  请问还有啥反馈的吗？

**Comment by cmideal** [comment]
你好，model 点击mask时候，是否关闭弹窗这个建议做成配置型，
现在打击直接就关闭了，无法阻止关闭。

**Comment by SzHeJason** [comment]
哦 刚好跟 1.4.0 的版本错开了~ 目前 dev 是存在 closeOnClickOverlay 这个属性来控制的 近期会发布新版本
