### ISSUE TITLE
taro-ui 官网无法打开

### ISSUE THREAD

**Issue by ZSY1373798806** [NervJS/taro-ui#1561]
**问题描述**

taro-ui 官网无法打开
https://taro-ui.jd.com/

**报错信息**
![image](https://user-images.githubusercontent.com/18542620/203275694-5711ef94-577b-4f10-974a-988cc83e32d5.png)

**Comment by yoyo837** [comment]
https://github.com/NervJS/taro-ui/issues/1565#issuecomment-1324711630
