### ISSUE TITLE
Taro-ui文档页面无法访问

### ISSUE THREAD

**Issue by hwmiao** [NervJS/taro-ui#1562]
**问题描述**
https://taro-ui.jd.com/ 无法访问，返回403

**复现步骤**
1.访问https://taro-ui.jd.com
2.页面显示403

**期望行为**
期望能正常访问taro-ui页面

**报错信息**
![image](https://user-images.githubusercontent.com/3120488/203451935-ab95399c-9f4d-4992-a1ea-21467c79e7a9.png)

**系统信息**

**补充信息**

**Comment by yoyo837** [comment]
https://github.com/NervJS/taro-ui/issues/1565#issuecomment-1324711630
