### ISSUE TITLE
taro ui官网无法打开

### ISSUE THREAD

**Issue by MACMarion** [NervJS/taro-ui#1563]
**问题描述**

打开 https://taro-ui.jd.com/ 后403

**复现步骤**

**期望行为**

**报错信息**

![图片](https://user-images.githubusercontent.com/99861682/203456847-c49f111d-3e82-4b45-ba4e-560682b0abca.png)

**系统信息**

**补充信息**

**Comment by yoyo837** [comment]
https://github.com/NervJS/taro-ui/issues/1565#issuecomment-1324711630
