### ISSUE TITLE
taro-ui.jd.com 403

### ISSUE THREAD

**Issue by Germxu** [NervJS/taro-ui#1564]
### Taro UI 版本信息

v3.2.0-beta.0-rn

### 问题描述

website  403

### 复现步骤

visit https://taro-ui.jd.com/ failed

### 复现代码

none

### 报错信息

403

### 系统信息

none

### 补充信息

maintainer

**Comment by yoyo837** [comment]
https://github.com/NervJS/taro-ui/issues/1565#issuecomment-1324711630
