### ISSUE TITLE
taro ui 官网403

### ISSUE THREAD

**Issue by nocodig** [NervJS/taro-ui#1565]
### Taro UI 版本信息

v3.2.0-beta.0-rn

### 问题描述

官网进不去了？不维护了？

### 复现步骤

进入https://taro-ui.jd.com/

### 复现代码

无

### 报错信息

403

### 系统信息

mac

**Comment by yoyo837** [comment]
内部服务调整，需要点时间迁移... 先将就用这个 https://taro-ui.taro.zone/#/

**Comment by nocodig** [comment]
> 内部服务调整，需要点时间迁移... 先将就用这个 https://taro-ui.taro.zone/#/

OK

**Comment by yoyo837** [comment]
先打开, 关了的话后面进来的人issue第一页看不见又会创建新的.大家都习惯不搜索.

**Comment by BJ4501** [comment]
提议：未来有没有可能提供一个离线版的文档，在遇到这种在线文档无法使用的情况下作为备用方案？

**Comment by yoyo837** [comment]
文档也在代码里.

**Comment by yoyo837** [comment]
https://taro-ui.jd.com/#/ 已恢复.
