### ISSUE TITLE
Taro 3 只能配合使用 taro-ui@next 版本

### ISSUE THREAD

**Issue by gostrithe** [NervJS/taro-ui#1578]
### Taro UI 版本信息

v2.3.4

### 问题描述

按照taro-ui的官方文档，快速上手中安装使用一步步操作，但是引入组件和样式就会报错，项目无法运行。

### 复现步骤

1.  npm install taro-ui
2. // page.js
     import { AtButton } from 'taro-ui'
3. // app.js
     import 'taro-ui/dist/style/index.scss'

### 复现代码

1.  npm install taro-ui
2. // page.js
     import { AtButton } from 'taro-ui'
3. // app.js
     import 'taro-ui/dist/style/index.scss'

### 报错信息

源码映入的路径有误，找不到样式scss文件。
错误的导入{ Component }，taro并无Component的暴露导出

### 系统信息

�👽 Taro v3.5.

  Taro CLI 3.5.11 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.16.0 - D:\Program Files (x86)\nodejs\node.EXE
      npm: 8.11.0 - D:\Program Files (x86)\nodejs\npm.CMD

### 补充信息

解决方案：
    Taro 3 只能配合使用 taro-ui@next 版本
    安装命令： npm i taro-ui@next

**Comment by szl-shalom** [comment]
Taro 版本3+ 以上 需要下载taro-ui@next 亲测有效
