### ISSUE TITLE
AtTextarea组件报错 无法显示

### ISSUE THREAD

**Issue by GitLe2019** [NervJS/taro-ui#1584]
**问题描述**
      通过脚手架创建的项目使用AtTextarea和AtInput组件报错

      <AtTextarea value='123' onChange={() => {}}></AtTextarea>
```js
// 这里可以贴代码
```

**期望行为**

**报错信息**
     
![image](https://user-images.githubusercontent.com/54802703/217514022-66c1ec6a-5b55-4593-a362-a343dc2234d2.png)

**系统信息**

**补充信息**

**Comment by zhouhai1993** [comment]
[我也遇到了这个问题，我在其它issue](https://github.com/NervJS/taro-ui/issues/1555)
中找到了一个解决方案，但是没有生效，你那边解决这个问题了吗

**Comment by robinv8** [comment]
@zhouhai1993 taro 和 taro-ui 版本分别是多少

**Comment by robinv8** [comment]
跟 webpack5 有关，这里提供了具体的解决办法
https://github.com/NervJS/taro-ui/issues/1555#issuecomment-1611347768
