### ISSUE TITLE
建议支持百度小程序

### ISSUE THREAD

**Issue by binz-i** [NervJS/taro-ui#159]
### 重现步骤
百度小程序和weapp可以用同一个 建议把判断加上

**Comment by KaierChou** [comment]
附议 支付宝小程序

**Comment by cmideal** [comment]
现在的支持进度如何了

**Comment by koppthe** [comment]
@cmideal  有个 Bug 在等百度小程序修复，他们官方反馈说今天会全量发 bugfix，我们 Taro UI 这边下周会继续做适配，时间点暂时不立 Flag 了😆

**Comment by XiaogeTek** [comment]
请问目前进展如何了？😆

**Comment by koppthe** [comment]
@XiaogeTek  还是上面说的，等百度小程序官方修复自定义组件传参的问题，他们最新的版本依旧有问题
