### ISSUE TITLE
SassError: SassError: Undefined operation "var(--nutui-font-size-2, 14px) * 1.5".

### ISSUE THREAD

**Issue by wukaipeng-dev** [NervJS/taro-ui#1594]
**问题描述**
按钮 taro-ui 后，在 app.scss 中全量引入：`@import "~taro-ui/dist/style/index.scss";`，运行之后报错。

**期望行为**
引入 SCSS 正常

**报错信息**

<img width="947" alt="image" src="https://user-images.githubusercontent.com/68799055/227815259-7823b9bc-2939-4cd9-b9c1-20f3eb01a157.png">

**系统信息**

 Taro CLI 3.6.2 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.2 => 3.6.2 
      @tarojs/components: 3.6.2 => 3.6.2 
      @tarojs/helper: 3.6.2 => 3.6.2 
      @tarojs/plugin-framework-react: 3.6.2 => 3.6.2 
      @tarojs/plugin-html: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-alipay: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-h5: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-jd: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-qq: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-swan: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-tt: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-weapp: 3.6.2 => 3.6.2 
      @tarojs/react: 3.6.2 => 3.6.2 
      @tarojs/runtime: 3.6.2 => 3.6.2 
      @tarojs/shared: 3.6.2 => 3.6.2 
      @tarojs/taro: 3.6.2 => 3.6.2 
      @tarojs/webpack5-runner: 3.6.2 => 3.6.2 
      babel-preset-taro: 3.6.2 => 3.6.2 
      eslint-config-taro: 3.6.2 => 3.6.2 
      react: ^18.0.0 => 18.2.0 
      taro-ui: 3.1.0-beta.4 => 3.1.0-beta.4 
    npmGlobalPackages:
      typescript: 5.0.2

**Comment by shinken008** [comment]
css 变量是一个变量，不可计算，用 calc

**Comment by iShawnWang** [comment]
@shinken008 报错的位置是 taro-ui/dist 里面的 scss, 不是开发者写的样式
