### ISSUE TITLE
支持rn的新包什么时候发？

### ISSUE THREAD

**Issue by spadeACE7** [NervJS/taro-ui#1595]
**这个功能解决了什么问题？**

 "taro-ui": "^3.1.0-beta.4",
 版本一直在3.1.0-beta.4 
 新的 [v3.6.0-beta.3-rn](https://github.com/NervJS/taro-ui/releases/tag/v3.6.0-beta.3-rn)
 啥时候发布呀
**你期望的功能是怎样的？**

更新最新的库
**补充信息**

**Comment by robinv8** [comment]
安装最新版
```
npm install taro-ui@next
```
