### ISSUE TITLE
AtSearchBar 组件无法输入

### ISSUE THREAD

**Issue by inhand1** [NervJS/taro-ui#1599]
`  "dependencies": {
    "@babel/runtime": "^7.7.7",
    "@tarojs/components": "3.6.4",
    "@tarojs/helper": "3.6.4",
    "@tarojs/plugin-framework-react": "3.6.4",
    "@tarojs/plugin-html": "^3.6.4",
    "@tarojs/plugin-platform-alipay": "3.6.4",
    "@tarojs/plugin-platform-h5": "3.6.4",
    "@tarojs/plugin-platform-jd": "3.6.4",
    "@tarojs/plugin-platform-qq": "3.6.4",
    "@tarojs/plugin-platform-swan": "3.6.4",
    "@tarojs/plugin-platform-tt": "3.6.4",
    "@tarojs/plugin-platform-weapp": "3.6.4",
    "@tarojs/react": "3.6.4",
    "@tarojs/runtime": "3.6.4",
    "@tarojs/shared": "3.6.4",
    "@tarojs/taro": "3.6.4",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-redux": "^8.0.5",
    "react-router-dom": "5.3.4",
    "redux": "^4.2.1",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.4.2",
    "taro-ui": "^3.1.0-beta.4"
  },`
[
![image](https://user-images.githubusercontent.com/128669014/231069087-60cbb0fa-bd60-4344-8696-472237adc096.png)
](url)

**Comment by robinv8** [comment]
@inhand1 可以提供个 demo，方便快速复现问题。或者提供下部分相关代码

**Comment by robinv8** [comment]
经测试未发现问题
![test](https://github.com/NervJS/taro-ui/assets/12277531/11435b85-c51b-4774-b3b0-2fea9b0799bb)
