### ISSUE TITLE
建议官方文档补充颜色、字体、布局等内容

### ISSUE THREAD

**Issue by Fnine59** [NervJS/taro-ui#160]
无关技术的小建议而已，现在貌似只能通过小程序示例查看到官方推荐色值？
希望可以在官方文档中提供色板，点击可复制色值，方便开发时使用~

**Comment by koppthe** [comment]
嗯嗯，也不是不可以，我最近版本加一下

**Comment by Jarryxin** [comment]
> 嗯嗯，也不是不可以，我最近版本加一下

你好 ，请问 开发规范，类似阿里ant design的设计语言什么时候能更新，给设计人员看的文档，谢谢

**Comment by chareice** [comment]
有进展吗？

**Comment by koppthe** [comment]
设计资源页面：https://taro-ui.aotu.io/#/docs/resource

**Comment by yuanrui** [comment]
Axure 8.1 加载失败，能否提供下低版本的rplib不呢。 @koppthe
