### ISSUE TITLE
v3.6.4 Input标签打包之后没有显示，是不是不兼容

### ISSUE THREAD

**Issue by wangyuan0108** [NervJS/taro-ui#1600]
**问题描述**

**复现步骤**

```js
// 这里可以贴代码
```

**期望行为**

**报错信息**

**系统信息**

**补充信息**

**Comment by robinv8** [comment]
@wangyuan0108 taro-ui 版本多少，taro 版本多少

**Comment by wangcheng2005** [comment]
我也遇到相同的问题, Input不显示, <AtForm>也不会显示 
    "@tarojs/taro": "3.6.8",
    "react": "^18.0.0",

**Comment by JHaoW** [comment]
同样遇到了这个问题，现在有解决吗

**Comment by robinv8** [comment]
如果用了 webpack5，可以修改下配置：
```
{
    compiler: {
        type: "webpack5",
        prebundle: {
            exclude: ["taro-ui"],
        },
    }
}
```
