### ISSUE TITLE
taro-ui项目在内部被放弃了吗？知情人士能否明示一下

### ISSUE THREAD

**Issue by liuwawa** [NervJS/taro-ui#1602]
**问题描述**
taro-ui已经四个月没有更新了，beta版本也没有合并到主分支。体验taro-ui整个视觉效果确实不错，并且交互反应速度极佳，比nutui体验起来好。知情人士能否明示一下该项目被放弃了吗？

**Comment by ctcx** [comment]
同问

**Comment by yiki17** [comment]
同问，现在微信交流群也加不上，不知道怎么样了

**Comment by liuwawa** [comment]
对比了市面上其他react组件库，nutUi-react、vant-react，大家都是完全自绘组件，比如一个基础的Button都是完全自绘，没有直接引用taro-component中的Button，最终转一圈发现，还是taro自带的性能高的多，大家可以分别打开这几家UI的小程序版本，对比页面加载速度、过渡效果、动画效果。肉眼可见的，taro-ui完全可以摔他们一条街！其实taro-ui就是引用的taro-Component组件库的组件，更不更新自己稍微改造下，也挺容易的。
下图是nutUI Button的实现方式，其他家也类似。
<img width="875" alt="image" src="https://user-images.githubusercontent.com/15793388/234296699-97f3516f-5476-4ef1-9ad5-541000951691.png">

**Comment by robinv8** [comment]
不可能被放弃，应该是分身乏术。如果有感兴趣的小伙伴，可以一起维护该项目~

**Comment by spadeACE7** [comment]
放弃就放弃呀，也不通知下，bug也不修了，功能也不完善了

**Comment by yoyo837** [comment]
有意向接手的社区贡献者或团队请联系...

**Comment by dadaxian** [comment]
taro 3 react 用 taro ui好多问题，折磨的好难受，还是换到了nutui，不过taroui确实好看呀

**Comment by wangyuan0108** [comment]
同问，现在taro3.x确实没有一个好用的ui，写业务很是难受啊

**Comment by dadaxian** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Me-UserName** [comment]
希望别放弃

**Comment by XcodeFish** [comment]
同问，关键是除了taroUI好用一些，其他的很一般啊

**Comment by yoyo837** [comment]
Duplicate of #1614

**Comment by dadaxian** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
