### ISSUE TITLE
taro-ui功能不再迭代了，能不能把bug修复下呀

### ISSUE THREAD

**Issue by spadeACE7** [NervJS/taro-ui#1603]
**这个功能解决了什么问题？**

taro-ui不功能迭代了，能不能把bug修复下呀
修复的bug 能不能发下新包

**你期望的功能是怎样的？**

bug修复下
**补充信息**

**Comment by robinv8** [comment]
@spadeACE7 处理中

**Comment by spadeACE7** [comment]
> 



> @spadeACE7 处理中

都三周了😭

**Comment by yoyo837** [comment]
Duplicate of https://github.com/NervJS/taro-ui/issues/1614
