### ISSUE TITLE
项目有没有人维护了？和最新版的taro不兼容了

### ISSUE THREAD

**Issue by guwan** [NervJS/taro-ui#1614]
**这个功能解决了什么问题？**
和最新版的taro不兼容了，项目有没有维护了？

也没看到不维护的公告。

**Comment by guwan** [comment]
测试版本:taro-ui@next才能和taro一起使用。最新版啥时候能用呢？

**Comment by robinv8** [comment]
> 测试版本:taro-ui@next才能和taro一起使用。最新版啥时候能用呢？

新版本已经开始内测了

**Comment by chenweijianGZ** [comment]
我这边也希望能继续使用taro-ui和rn版本，有接下来的开发路线图么？我们可能会深度使用，看看是否有东西可以反哺到taro这边

**Comment by yoyo837** [comment]
@robinv8 已经接手了，欢迎有兴趣的贡献者一起参与。

**Comment by guwan** [comment]
> > 测试版本:taro-ui@next才能和taro一起使用。最新版啥时候能用呢？
> 
> 新版本已经开始内测了

好的，谢谢，如果没人维护就不敢用了。

**Comment by robinv8** [comment]
> 我这边也希望能继续使用taro-ui和rn版本，有接下来的开发路线图么？我们可能会深度使用，看看是否有东西可以反哺到taro这边

正在测试并解决依赖更新后的一些问题，等该版本发布后，后期会有 roadmap

**Comment by JoshYuJump** [comment]
`taro-ui@next` 实际使用基本是兼容的

**Comment by csyaonie** [comment]
搞啥啊 ，这个ui 更新速度跟不上啊 ，哭死

**Comment by JoshYuJump** [comment]
@csyaonie 哪个版本呢？我这边一直在用 `taro-ui@next`，暂时没有遇到问题呢。
