### ISSUE TITLE
Taro 3.6.8 + Taro-ui 3.1.0-beta.5 启动报错

### ISSUE THREAD

**Issue by hbwow** [NervJS/taro-ui#1620]
Taro 配置有误，请检查！ (/Users/lengkaixin/Projects/urumqi/psp-mobile-new/config/index.js)
  [✗] rn.resolve 的值 {"include":["taro-ui"]} 不是 "array" 类型
<img width="764" alt="image" src="https://github.com/NervJS/taro-ui/assets/119321896/42767837-dc0c-4a0d-b8e4-30d89b3543cc">

**Comment by robinv8** [comment]
目测跟 RN 有关，目前最新版 taro-ui 版本是 3.3.0，先安装最新版试试，如果还有问题，麻烦尝试如下 demo

https://github.com/robinv8/taro-rn-webpack5-demo.git
