### ISSUE TITLE
taro 升级到3.2.13引入components input组件报错，3.2.13以前的版本都不会

### ISSUE THREAD

**Issue by vuehao** [NervJS/taro-ui#1623]
<img width="441" alt="image" src="https://github.com/NervJS/taro-ui/assets/38458627/cef00dad-5ab4-4bcd-9a4a-69b55c3e4ecc">

<img width="1179" alt="image" src="https://github.com/NervJS/taro-ui/assets/38458627/4b908d5f-6432-46cc-a4ad-bd851d4a2d27">

**Comment by robinv8** [comment]
@vuehao 安装 `taro-ui@next` 版本试试
