### ISSUE TITLE
taro默认^3.0版本与taro-ui默认^2.0版本不兼容

### ISSUE THREAD

**Issue by bawawa** [NervJS/taro-ui#1624]
**问题描述**
taro初始化项目后，默认使用taro3，安装taro-ui时，默认安装taro-ui 2的版本，不兼容会导致scss引用报错

**复现步骤**
1.taro init test
2.npm i taro-ui
3.app.scss引入@import "~taro-ui/dist/style/index.scss";

```js
// 这里可以贴代码
```

**期望行为**
taro与taro-ui默认版本保持一致

**Comment by robinv8** [comment]
可以使用先安装 `next` 版本
```
npm i taro-ui@next
```
