### ISSUE TITLE
tabs横向滚动时，会把页面撑开

### ISSUE THREAD

**Issue by nyrf** [NervJS/taro-ui#163]
### 重现步骤
扫的首页上二维码，在ios10微信6.7.3中，tabs页，我自己写的也是这个问题，如果有个横向的tabs带滚动的，且页面往下超过一屏，那就出现这种页面撑开，出现滚动条

![wechatimg4](https://user-images.githubusercontent.com/299532/48180026-cb2cb000-e35c-11e8-9537-9af992ade15a.jpeg)

**Comment by nyrf** [comment]
得，，刚看了下公司这个测试机，版本居然是8.3，用了我自己的12，试了没这个问题，这种老版本不管了

**Comment by nyrf** [comment]
试了其它几个ui，wux-weapp或者iview或者youzan的，都没有这个情况，好像这还是个问题，不过我在其它手机上没出现。

**Comment by jimczj** [comment]
已修复，将在 1.4 版本发布
