### ISSUE TITLE
在微信小程序中AtInput组件title不显示

### ISSUE THREAD

**Issue by thunder-night** [NervJS/taro-ui#1638]
### Taro UI 版本信息

v3.1.0-beta.4

### 问题描述

AtInput组件title不显示

### 复现步骤

1. 使用 npx @tarojs/cli init testApp 创建 taro-ui的版本
2. 在 项目中 加入AtInput组件， 示例如 复现代码

### 复现代码
```
import { Component } from 'react'
import { View, Text, Label } from '@tarojs/components'
import { AtButton, AtInput } from 'taro-ui'

import "taro-ui/dist/style/components/button.scss" // 按需引入
import "taro-ui/dist/style/components/input.scss" // 按需引入
import './index.less'

export default class Index extends Component {
  componentDidMount () { }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  render () {
    return (
      <View className='index'>
		<AtInput title='666666' placeholder='ceshi' type='text' value='999'/>
        <Text>Hello world!</Text>
        <AtButton type='primary'>I need Taro UI</AtButton>
        <Text>Taro UI 支持 Vue 了吗？</Text>
        <AtButton type='primary' circle={true}>支持</AtButton>
        <Text>共建？</Text>
        <AtButton type='secondary' circle={true}>来</AtButton>
      </View>
    )
  }
}
```
### 报错信息

无

### 系统信息

👽 Taro v3.6.8

  Taro CLI 3.6.8 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 16.14.0 - D:\NodeJs\node-v16.14.0\node.EXE
      Yarn: 1.22.17 - D:\NodeJs\node-v16.14.0\node_global\yarn.CMD
      npm: 8.3.1 - D:\NodeJs\node-v16.14.0\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.8 => 3.6.8
      @tarojs/components: 3.6.8 => 3.6.8
      @tarojs/helper: 3.6.8 => 3.6.8
      @tarojs/plugin-framework-react: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-alipay: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-h5: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-jd: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-qq: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-swan: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-tt: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-weapp: 3.6.8 => 3.6.8
      @tarojs/react: 3.6.8 => 3.6.8
      @tarojs/runtime: 3.6.8 => 3.6.8
      @tarojs/shared: 3.6.8 => 3.6.8
      @tarojs/taro: 3.6.8 => 3.6.8
      @tarojs/taro-loader: 3.6.8 => 3.6.8
      @tarojs/webpack5-runner: 3.6.8 => 3.6.8
      babel-preset-taro: 3.6.8 => 3.6.8
      eslint-config-taro: 3.6.8 => 3.6.8
      react: ^18.0.0 => 18.2.0
      taro-ui: ^3.1.0-beta.2 => 3.1.0-beta.7

**Comment by robinv8** [comment]
应该是在 webpack5 上出现了该问题，可以修改下配置：
```
{
    compiler: {
        type: "webpack5",
        prebundle: {
            exclude: ["taro-ui"],
        },
    }
}
```

同问  #1646
