### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by hooliy** [NervJS/taro-ui#1642]
**问题描述**

![image](https://github.com/NervJS/taro-ui/assets/3368691/00f9e654-d4cd-4d97-9c6c-9df8c0575e05)

**系统信息**

![image](https://github.com/NervJS/taro-ui/assets/3368691/8138051c-3a7f-474b-bc92-a09debb55520)

**补充信息**

**Comment by robinv8** [comment]
@hooliy `taro@3.3.12` 与 `taro-ui@^3.1.0-beta.7` 不兼容，建议使用 `taro-ui@^2.3.4`
