### ISSUE TITLE
日历组件，没有显示完整，使用社区模板初始化的

### ISSUE THREAD

**Issue by Jimjmlv** [NervJS/taro-ui#1646]
**操作步骤**
`
taro init test
选择react+ts+less+wepack+taroUI
yarn dev:weapp
`
![image](https://github.com/NervJS/taro-ui/assets/139189664/5616e0cc-78b9-46d5-ba53-265a922544f3)

### 版本信息
`
  "dependencies": {
    "@babel/runtime": "^7.7.7",
    "@tarojs/components": "3.6.11",
    "@tarojs/helper": "3.6.11",
    "@tarojs/plugin-platform-weapp": "3.6.11",
    "@tarojs/plugin-platform-alipay": "3.6.11",
    "@tarojs/plugin-platform-tt": "3.6.11",
    "@tarojs/plugin-platform-swan": "3.6.11",
    "@tarojs/plugin-platform-jd": "3.6.11",
    "@tarojs/plugin-platform-qq": "3.6.11",
    "@tarojs/plugin-platform-h5": "3.6.11",
    "@tarojs/runtime": "3.6.11",
    "@tarojs/shared": "3.6.11",
    "@tarojs/taro": "3.6.11",
    "@tarojs/plugin-framework-react": "3.6.11",
    "lodash": "4.17.15",
    "taro-ui": "^3.1.0-beta.2",
    "@tarojs/react": "3.6.11",
    "react": "^18.0.0",
    "react-dom": "^18.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.8.0",
    "@tarojs/cli": "3.6.11",
    "postcss": "^8.4.18",
    "webpack": "^5.78.0",
    "@tarojs/taro-loader": "3.6.11",
    "@tarojs/webpack5-runner": "3.6.11",
    "@pmmmwh/react-refresh-webpack-plugin": "^0.5.5",
    "react-refresh": "^0.11.0",
    "@types/webpack-env": "^1.13.6",
    "babel-preset-taro": "3.6.11",
    "eslint": "^8.12.0",
    "eslint-config-taro": "3.6.11",
    "stylelint": "9.3.0",
    "@typescript-eslint/parser": "^5.20.0",
    "@typescript-eslint/eslint-plugin": "^5.20.0",
    "typescript": "^4.1.0",
    "@types/react": "^18.0.0",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-react-hooks": "^4.2.0",
    "ts-node": "^10.9.1",
    "@types/node": "^18.15.11"
  }
`

**Comment by robinv8** [comment]
我跟进下

**Comment by Jimjmlv** [comment]
有劳了，团队最近一直在找一款可以跨平台的日历组件，看到Taro-ui的不错，兼容h5/weapp/rn，结果h5报错，小程序显示故障，rn还没试，希望可以全面测试一下，谢谢了。

还有个疑问，最近看到Taro官方群半年也没几条信息，有点秋风瑟瑟的感觉，团队有人提出正在考虑转到满是坑的uniApp，希望官方给个定心丸，谢谢了

**Comment by Jimjmlv** [comment]
或者哪个版本的日历组件可以正常使用，我们先用旧版本代替一下，等修复好了，再换新版。
demo是哪个版本？taro版本+taroUI版本，谢谢

**Comment by robinv8** [comment]
试一下近期更新的版本
```
npm i taro-ui@3.1.0-beta.7
```

**Comment by web525** [comment]
"taro-ui": "^3.1.0-beta.7"， 还是一样的错报错

### 基础库 2.33.0
![image](https://github.com/NervJS/taro-ui/assets/15317085/3ba35baa-9c35-45ce-be02-02669088eabf)

### 基础库3.0.0
![image](https://github.com/NervJS/taro-ui/assets/15317085/21e4c4c5-d094-4e87-a03e-baafdea6d690)

**Comment by robinv8** [comment]
今天我排查下

**Comment by robinv8** [comment]
应该是在 webpack5 上出现了该问题，可以修改下配置：
```
{
    compiler: {
        type: "webpack5",
        prebundle: {
            exclude: ["taro-ui"],
        },
    }
}
```
