### ISSUE TITLE
微信小程序input渲染错误

### ISSUE THREAD

**Issue by CloudyBao** [NervJS/taro-ui#1648]
**问题描述**
微信小程序input渲染错误，不会完全渲染。

**复现步骤**

`<AtInput name="phone" type="text" placeholder="请输入手机号码" />`
样式已经在app.scss中引入
```
@import "~taro-ui/dist/style/components/icon.scss";
@import "~taro-ui/dist/style/components/input.scss";
```

**期望行为**
完全显示input框

**报错信息**
![image](https://github.com/NervJS/taro-ui/assets/23521135/fff28ef2-229e-4dc8-969a-a825dcdab4b0)

**系统信息**
 - Taro 版本 3.6.11
 - Taro UI 版本 3.1.0-beta.7
 - 报错平台 weapp

**Comment by mjw-git** [comment]
我也遇到这问题，好像是要降taro版本。。我就没搞了

**Comment by robinv8** [comment]
临时解决方案 #1646

**Comment by CloudyBao** [comment]
> 临时解决方案 #1646

我没有用这个解决方案，我看到了另一个解决方法，修改webpack的打包方式

**Comment by robinv8** [comment]
@BaoXianSheng 哈喽，可以把你的方案贴出来吗？

**Comment by CloudyBao** [comment]
> @BaoXianSheng 哈喽，可以把你的方案贴出来吗？

`  compiler: {
    type: "webpack5",
    prebundle: {
      exclude: ["taro-ui"],
    },
  },`
