### ISSUE TITLE
AtInput editable 无法正常切换

### ISSUE THREAD

**Issue by kenberkeley** [NervJS/taro-ui#165]
AtInput 的 `editable` 属性无法从 `false` 切换回 `true`

1. 初始状态，默认可编辑 `editable={true}`，表现正常
![image](https://user-images.githubusercontent.com/13287948/48243583-3c3f9680-e435-11e8-894a-d94ca222052f.png)

2. 点击按钮，输入框无法编辑 `editable={false}`，表现正常
![image](https://user-images.githubusercontent.com/13287948/48243586-45306800-e435-11e8-9cde-83d83182b531.png)

3. 再点击按钮，输入框依然保持无法编辑状态 `editable={true}`，表现异常
![image](https://user-images.githubusercontent.com/13287948/48243597-4c577600-e435-11e8-8f76-fa3aff95ded0.png)

**Comment by kenberkeley** [comment]
顺便说一句，`disabled` 属性的表现一切正常

**Comment by jimczj** [comment]
发现小程序的 disabled 只在初始值的时候有效，近期会在editable={false} 的时候切换成view来重新实现

**Comment by jimczj** [comment]
已修复，等待发版
