### ISSUE TITLE
[swipeAction]建议：左右滑动的时候禁止上下滑动以优化体验

### ISSUE THREAD

**Issue by xiguazhiPrince** [NervJS/taro-ui#1651]
**期望行为**
微信小程序中，左右滑动的时候禁止上下滑动以优化体验

**补充信息**
我给隔壁tdesign-miniprogram团队提了这个建议，人家隔天就pr这个问题了，就看咱们凹凸团队了！！！
加油！！
https://github.com/Tencent/tdesign-miniprogram/issues/2276

**Comment by robinv8** [comment]
安装 `next` 版
```
npm install taro-ui@next
```

**Comment by yurentle** [comment]
列表项过多需要上下滑动，你这禁止了那还怎么滚动？
