### ISSUE TITLE
项目初始化出错

### ISSUE THREAD

**Issue by csyaonie** [NervJS/taro-ui#1657]
### Taro UI 版本信息

v3.1.0

### 问题描述

运行taro init myApp 选择使用 taro-ui 的模板 ，运行  npm run dev:alipay启动报错

### 复现步骤

1.taro init myApp
2.选择使用 taro-ui 的模板
3.npm run dev:alipay

### 复现代码

不需要写代码，初始化并启动项目就出错，h5和微信不会报错，支付宝会报错

### 报错信息

✘ [ERROR] No matching export in "node_modules/@tarojs/plugin-platform-alipay/dist/components-react.js" for import "OpenData"

    node_modules/taro-ui/dist/index.esm.js:2:21:
      2 │ import { View, Text, OpenData, Image, Button, Switch, ScrollView, F...
        ╵                      ~~~~~~~~

检测到依赖编译错误，已跳过 taro-ui 依赖预编译。 
    > 可以通过手动配置 compiler.prebundle.exclude (​https://nervjs.github.io/taro-docs/docs/next/config-detail#compilerprebundleexclude​) 忽略该提示

### 系统信息

"@tarojs/cli": "3.6.14",

**Comment by csyaonie** [comment]
给个回复吧 朋友

**Comment by robinv8** [comment]
> 

这需要我排查下，如果着急先使用默认的模板，然后再安装 `taro-ui`

**Comment by robinv8** [comment]
找到问题了，我处理下，可以先通过 npm install taro-ui@latest 安装最新版

相同问题：#1732
