### ISSUE TITLE
使用文档直接跳转京东了

### ISSUE THREAD

**Issue by Silentdoer** [NervJS/taro-ui#1658]
**问题描述**

**复现步骤**

```js
// 这里可以贴代码
```

**期望行为**

**报错信息**

**系统信息**

**补充信息**

**Comment by robinv8** [comment]
可以正常访问
![image](https://github.com/NervJS/taro-ui/assets/12277531/530aebb5-4ab2-443b-9c13-1da0c8293b0f)
