### ISSUE TITLE
taro-ui 3.1.0 无法在RN下正常启动

### ISSUE THREAD

**Issue by carrot7454** [NervJS/taro-ui#1660]
**问题描述**
最近尝试在taro中使用taro-ui的时候发现如下问题：
1. 如果在最新版taro中使用taro-ui3.1.0版本run dev:rn的时候，会直接报rn.resolve 的值 {"include":["taro-ui"]} 不是 "array" 类型
2. 示例库中package.json文件（https://github.com/NervJS/taro-ui/blob/dc77a8aea76b179cf5f21fbf250ed75b14918162/packages/taro-ui-demo-rn/package.json），既然已经更新了3.1.0版本，为何示例中还用的是3.1.0 beta4的版本；
3. 将示例库中metro.config.js，package.json中全部内容，以及config/index.ts中rn和alias相关配置替换后，重新安装，编译后rn后，提示以下错误：
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find com.facebook.react:react-native:0.71.13.
     Required by:
         project :app
         project :app > project :react-native-picker_picker

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 47s

    at makeError (E:\work\taro\taro_app_2\node_modules\execa\index.js:174:9)
    at E:\work\taro\taro_app_2\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (E:\work\taro\taro_app_2\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:82:7)
    at async Command.handleAction (E:\work\taro\taro_app_2\node_modules\@react-native-community\cli\build\index.js:108:9)

**复现步骤**
1. 将https://github.com/NervJS/taro-ui/blob/dc77a8aea76b179cf5f21fbf250ed75b14918162/packages/taro-ui-demo-rn/package.json示例中metro.config.js，package.json中全部内容，以及config/index.ts中rn和alias相关配置粘贴到本地
2. 将node_modules目录以及yarn.lock文件删除。
3. yarn安装
4. npm run dev:rn

**期望行为**
能够正常在rn内编译并在页面展示taro-ui相关组件

**系统信息**
 - Taro 版本 [ 3.6.5-canary.1]
 - Taro UI 版本 [3.1.0]
 - 报错平台 [rn]

**Comment by robinv8** [comment]
在最新版的 taro 中未发现报错
https://github.com/robinv8/taro-rn-webpack5-demo
![](https://github.com/NervJS/taro-ui/assets/12277531/2e3adc7c-1f63-4d42-9c07-5649ca1140c2)

**Comment by carrot7454** [comment]
下载您给的demo，没改动任何文件，仅build:rn，就有以下报错：
error node_modules\taro-ui\rn\style\components\countdown.scss: Jest worker encountered 4 child process exceptions, exceeding retry limit.
Error: Jest worker encountered 4 child process exceptions, exceeding retry limit
    at ChildProcessWorker.initialize (E:\work\taro\taro-rn-webpack5-demo-main\node_modules\jest-worker\build\workers\ChildProcessWorker.js:185:21)
    at ChildProcessWorker._onExit (E:\work\taro\taro-rn-webpack5-demo-main\node_modules\jest-worker\build\workers\ChildProcessWorker.js:269:12)
    at ChildProcess.emit (node:events:514:28)
分别在node版本18.17.1,18.9.0,16.19.0下运行，都报该问题，请问您那边能正常运行的环境是多少？这个问题如何解决？

**Comment by robinv8** [comment]
我这边 node 16.17.1

**Comment by carrot7454** [comment]
按您给的版本，用nvm全新安装了node 16.17.1版本，全局只安装了yarn以及taro-cli，重新跑了一下build，依然报同样的错误，然后我通过taro-cli重新安装了rn的模板，确保在没有taro-ui的前提下可以正常运行，然后对比了package.json，发现多出expo，react-native的好多依赖项，删除后，重新yarn->build未果。然后发现config.js中，有关taro-ui的配置有变化：
... 
compiler: {
    type: 'webpack5',
    prebundle: {
      exclude: ['taro-ui']
    }
  },
...
我将全新安装的框架中配置添加上述字段，build并未出现问题，但是在dev:rn的时候缺少组件expo-modules-core/expo-av/expo-asset，安装后重新编译后，弹出如下错误：
![微信图片_20230904163804](https://github.com/NervJS/taro-ui/assets/47313062/a61e6181-4fe4-4419-ac27-c6644b82acf6)

**Comment by robinv8** [comment]
@carrot7454 
![image](https://github.com/NervJS/taro-ui/assets/12277531/1323eebd-35bf-4d67-bf1b-5a4911a10410)
进 taro-ui 的群

**Comment by robinv8** [comment]
@carrot7454 发现你这是 windows 设备，咱们环境不一样，我再试试

**Comment by carrot7454** [comment]
> @carrot7454 发现你这是 windows 设备，咱们环境不一样，我再试试

是的，win10家庭中文版22H2版本，感谢大佬

**Comment by robinv8** [comment]
> 

目前在出差，周五晚上回去我试试

**Comment by robinv8** [comment]
发现问题了，正在处理中

**Comment by robinv8** [comment]
在 config 中增加配置：
```
alias: {
    '~taro-ui/dist': `~taro-ui/rn`,
  },
```
