### ISSUE TITLE
taro3编译报错

### ISSUE THREAD

**Issue by Feahter** [NervJS/taro-ui#1661]
**问题描述**
Taro v3.6.15打包异常
**报错信息**
<img width="940" alt="image" src="https://github.com/NervJS/taro-ui/assets/13764431/dae6386a-2049-4a7f-9c65-37c4caf58edb">
<img width="774" alt="image" src="https://github.com/NervJS/taro-ui/assets/13764431/68610fe1-ebd7-4e24-9517-56fad1d7c3ab">
**系统信息**
 - Taro 版本 [v3.6.15]
 - Taro UI 版本 [e.g. v.3.1.1]
 - 报错平台 [weapp、lark、dd]

**Comment by liuwawa** [comment]
刚在taro里看人提出，试下  "@tarojs/webpack5-runner": "3.6.13",引入webpack5可以解决
