### ISSUE TITLE
编译错误 SassError: Undefined operation: "calc($col / 12) times 100%".

### ISSUE THREAD

**Issue by vulgarLover** [NervJS/taro-ui#1662]
`{
   "dependencies": {
      "@babel/runtime": "^7.7.7",
      "@tarojs/cli": "3.2.5",
      "@tarojs/components": "3.2.5",
      "@tarojs/runtime": "3.2.5",
      "@tarojs/taro": "3.2.5",
      "@tarojs/react": "3.2.5",
      "big.js": "^6.1.0",
      "echarts-taro3-react": "^1.0.13",
      "react": "^17.0.2",
      "react-dom": "^17.0.0",
      "taro-skeleton": "^2.0.4",
      "taro-ui": "^3.0.0-alpha.3",
      "weapp-qrcode": "^1.0.0"
   },
   "devDependencies": {
      "@babel/core": "^7.8.0",
      "@tarojs/mini-runner": "3.2.1",
      "@tarojs/webpack-runner": "3.2.1",
      "@types/react": "^17.0.2",
      "@types/webpack-env": "^1.13.6",
      "@typescript-eslint/eslint-plugin": "^4.15.1",
      "@typescript-eslint/parser": "^4.15.1",
      "babel-preset-taro": "3.2.1",
      "eslint": "^6.8.0",
      "eslint-config-taro": "3.2.1",
      "eslint-plugin-import": "^2.12.0",
      "eslint-plugin-react": "^7.8.2",
      "eslint-plugin-react-hooks": "^4.2.0",
      "stylelint": "9.3.0",
      "taro-iconfont-cli": "^3.2.1",
      "typescript": "^4.1.0"
   }
}
`

![image](https://github.com/NervJS/taro-ui/assets/45785738/a87d9b10-ff6c-4f95-ad2e-9a76a3b4b67d)

npm run dev:weapp
�   编译失败. 2023/9/5 上午11:05:08

./src/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined operation: "calc($col / 12) times 100%".
        on line 120 of node_modules/taro-ui/dist/style/components/flex.scss
        from line 1 of D:\Code\Web\zmall-store\src\app.scss
>>     $width: calc($col / 12) * 100%;

   ------------^

**Comment by vulgarLover** [comment]
windows  node13.14.0

**Comment by robinv8** [comment]
升级taro 底层 3.4.x 即可解决
这是由于taro底层升级 node sass 导致的

**Comment by tuomiu** [comment]
> 升级taro 底层 3.4.x 即可解决 这是由于taro底层升级 node sass 导致的

升级到3.6.15，taro-ui 3.1.1，还是有这个问题

**Comment by robinv8** [comment]
@tuomiu 我本地 node 版本 `v16.17.1`，你可以通过 [nvs](https://github.com/jasongin/nvs) 切换 node 版本试试，最好也提供一个 demo，我运行看看

**Comment by vulgarLover** [comment]
升级3.4不好使啊，新的错误，目前这个问题在同事的mac上都没有，我两个windows都会有同样的问题

**Comment by vulgarLover** [comment]
https://gitee.com/ysar/test-taro
@robinv8 可以帮忙看下吗，放了个demo，windows环境

**Comment by robinv8** [comment]
晚上回去试试

**Comment by vulgarLover** [comment]
@robinv8 怎么样

**Comment by robinv8** [comment]
@vulgarLover 卡在 npm install 报错上了

**Comment by kurtisjuwensx** [comment]
@robinv8 hello，这问题有进展么？我是`3.6.17`版本的taro，搭配`3.1.1`的taro-ui，现在也是启动就报错，node也换了`v16.17.1`，还是没用

**Comment by pinguo-zhonghuran** [comment]
请问问题解决了么  3.3.8 的 Taro 版本 ，搭配3.1.1的taro-ui，现在也是启动就报错

**Comment by pinguo-zhonghuran** [comment]
"taro-ui": "3.0.0-alpha.10"  这个版本解决问题

**Comment by pinguo-zhonghuran** [comment]
> @robinv8 hello，这问题有进展么？我是`3.6.17`版本的taro，搭配`3.1.1`的taro-ui，现在也是启动就报错，node也换了`v16.17.1`，还是没用

"taro-ui": "3.0.0-alpha.10"  这个版本解决问题

**Comment by robinv8** [comment]
> 请问问题解决了么 3.3.8 的 Taro 版本 ，搭配3.1.1的taro-ui，现在也是启动就报错

taro@3.3.8 不能使用 taro-ui@3.1.1，从 taro-ui@3.1.0 开始对依赖库进行了大版本升级

**Comment by canyueduhong** [comment]
同样的报错，"taro-ui": "^3.0.0-alpha.1"，  "@tarojs/cli": "3.4.1",

node 14.17.0 ，16.17.1都试了，不行

**Comment by robinv8** [comment]
@canyueduhong 提供个可以完整可以复现的 demo，今晚试试

**Comment by canyueduhong** [comment]
> @canyueduhong 提供个可以完整可以复现的 demo，今晚试试
[taro——测试代码.zip](https://github.com/NervJS/taro-ui/files/13669543/taro.zip)

好的，上面是我的项目代码，感谢大佬指点

**Comment by yoyo837** [comment]
“提供可复现的代码”重点在“可复现”，和有没有项目代码没关系, run 起来能看到错误即可，你可以删减你的代码，给到最小可复现，给个部分代码，还需要人去填的不叫复现，何况根本不知道怎么填。

**Comment by canyueduhong** [comment]
> “提供可复现的代码”重点在“可复现”，和有没有项目代码没关系, run 起来能看到错误即可，你可以删减你的代码，给到最小可复现，给个部分代码，还需要人去填的不叫复现，何况根本不知道怎么填。

已经改好了最小可复现版本，多谢提醒

**Comment by robinv8** [comment]
@canyueduhong 
在 `package.json` devDependencies 同级添加锁定 sass 版本的配置
```
"devDependencies"： {
……
},
// 锁定 sass 版本
"resolutions": {
    "sass": "1.62.0"
 },
```

**Comment by canyueduhong** [comment]
好嘞，我试下，感谢

**Comment by canyueduhong** [comment]
> devDependencies

请问咱node版本是多少？我试了下还是同样的报错，代码结构为  "resolutions": {
    "sass": "1.62.0"
  },
  "devDependencies": {
    
  },

**Comment by robinv8** [comment]
node@14.18.0
![image](https://github.com/NervJS/taro-ui/assets/12277531/5a945e57-2b09-48f2-81a1-c7be53e8adb5)

**Comment by canyueduhong** [comment]
![image](https://github.com/NervJS/taro-ui/assets/28993317/7522db24-ee30-4d28-9b8a-0fc9e1d1280f)
难道是m3芯片不行吗，哎

**Comment by robinv8** [comment]
那明早我用公司电脑试试

**Comment by canyueduhong** [comment]
找了一个以前能跑起来的node_modules压缩包，是好用的，我再研究研究，应该还是我的环境哪里导致的，跪谢大佬帮助！

**Comment by robinv8** [comment]
我在 M1 试了，添加我的配置也不会报错

**Comment by ly827** [comment]
折腾了一晚上各种升降版本，都没解决，最终还是改代码好了
node_modules/taro-ui/dist/style/components/flex.scss 120:13

`$width: calc($col / 12) * 100%;` => `$width: calc(#{$col / 12} * 100%);`

**Comment by robinv8** [comment]
> > @canyueduhong 提供个可以完整可以复现的 demo，今晚试试
> > [taro——测试代码.zip](https://github.com/NervJS/taro-ui/files/13669543/taro.zip)
> 
> 好的，上面是我的项目代码，感谢大佬指点

根据以上 demo 已找到解决办法。

## 报错原因
由于 taro 底层升级 node sass 导致的

## 解决方案

方案一：降低 sass 版本

在 package.json 中添加如下配置
```
"resolutions": {
    "sass": "1.62.0"
 },
```

方案二：升级 taro 相关依赖

在 package.json 中批量替换 taro 相关依赖版本 v3.4.5 及以上版本

示例如下：
https://github.com/NervJS/taro-ui/tree/next/examples/about-sass-version

**Comment by canyueduhong** [comment]
> > > @canyueduhong 提供个可以完整可以复现的 demo，今晚试试
> > > [taro——测试代码.zip](https://github.com/NervJS/taro-ui/files/13669543/taro.zip)
> > 
> > 
> > 好的，上面是我的项目代码，感谢大佬指点
> 
> 根据以上 demo 已找到解决办法。
> 
> ## 报错原因
> 由于 taro 底层升级 node sass 导致的
> 
> ## 解决方案
> 方案一：降低 sass 版本
> 
> 在 package.json 中添加如下配置
> 
> ```
> "resolutions": {
>     "sass": "1.62.0"
>  },
> ```
> 
> 方案二：升级 taro 相关依赖
> 
> 在 package.json 中批量替换 taro 相关依赖版本 v3.4.5 及以上版本
> 
> 示例如下： https://github.com/NervJS/taro-ui/tree/next/examples/about-sass-version

可以了，感谢大佬帮助

**Comment by canyueduhong** [comment]
在我的项目中其实还有其他的代码报错，是因为taro-hooks的版本不兼容导致，后来我把版本号改成1.5.8就好了，这个提供给大家，如有遇到可做参考
![image](https://github.com/NervJS/taro-ui/assets/28993317/30f5d4b6-6283-45c3-85be-b430c66532be)
