### ISSUE TITLE
button需要添加新的open-type合法值和对应的事件处理方法

### ISSUE THREAD

**Issue by StarlightUnion** [NervJS/taro-ui#1663]
**问题描述**
微信小程序官方组件更新，添加了新的组件属性，taro-ui的button组件目前缺少相关属性，如open-type新增了agreePrivacyAuthorization合法值，并且增加了与之对应的事件处理属性bindagreeprivacyauthorization。

详见：https://developers.weixin.qq.com/miniprogram/dev/component/button.html

需要注意的是，从基础库 2.32.3版本起，open-type可支持耦合使用，如：
```js
<button open-type="getPhoneNumber|agreePrivacyAuthorization"> 或 <button open-type="getRealtimePhoneNumber|agreePrivacyAuthorization">
```
<img width="1440" alt="Snipaste_2023-09-07_09-40-50" src="https://github.com/NervJS/taro-ui/assets/43316114/0567154d-86fb-4c23-a44e-e1344649c677">

详见：https://developers.weixin.qq.com/miniprogram/dev/framework/user-privacy/PrivacyAuthorize.html

**复现步骤**
每次都可复现

**期望行为**
button组件新增对应的合法值和事件处理函数

**报错信息**
暂无

**系统信息**
👽 Taro v3.5.5

  Taro CLI 3.5.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.8 => 3.5.8
      @tarojs/components: 3.5.8 => 3.5.8
      @tarojs/helper: 3.5.8 => 3.5.8
      @tarojs/mini-runner: 3.5.8 => 3.5.8
      @tarojs/plugin-framework-react: 3.5.8 => 3.5.8
      @tarojs/plugin-platform-alipay: 3.5.8 => 3.5.8
      @tarojs/plugin-platform-jd: 3.5.8 => 3.5.8
      @tarojs/plugin-platform-qq: 3.5.8 => 3.5.8
      @tarojs/plugin-platform-swan: 3.5.8 => 3.5.8
      @tarojs/plugin-platform-tt: 3.5.8 => 3.5.8
      @tarojs/plugin-platform-weapp: 3.5.8 => 3.5.8
      @tarojs/react: 3.5.8 => 3.5.8
      @tarojs/rn-runner: 3.5.8 => 3.5.8
      @tarojs/router: 3.5.8 => 3.5.8
      @tarojs/runtime: 3.5.8 => 3.5.8
      @tarojs/shared: 3.5.8 => 3.5.8
      @tarojs/taro: 3.5.8 => 3.5.8
      @tarojs/taro-h5: 3.5.8 => 3.5.8
      @tarojs/taro-rn: 3.5.8 => 3.5.8
      @tarojs/webpack-runner: 3.5.8 => 3.5.8
      babel-preset-taro: 3.5.8 => 3.5.8
      eslint-config-taro: 3.5.8 => 3.5.8
      expo: ~45.0.4 => 45.0.8
      react: ^18.0.0 => 18.2.0
      react-native: ^0.68 => 0.68.3
      taro-ui: ^3.1.1 => 3.1.1
    npmGlobalPackages:
      typescript: 5.0.2

**补充信息**
见问题描述

**Comment by robinv8** [comment]
需要将 taro 升级到 3.6.16 以上即可支持
