### ISSUE TITLE
ListItem 组件，接受的 title/extractText 等都不应该是 string 类型，不方便扩展和自定义

### ISSUE THREAD

**Issue by axetroy** [NervJS/taro-ui#1667]
**这个功能解决了什么问题？**

https://github.com/NervJS/taro-ui/blob/68d4a00f75a85f3939b5daaeb03573bd3f920237/packages/taro-ui/src/components/list/item/index.tsx#L41-L53

只接受 String 类型，不方便扩展，不满足需求，比如想给 extra 加上一个 icon 都没有办法

**你期望的功能是怎样的？**

参数应该接受 `JSX.Element`

**补充信息**

**Comment by robinv8** [comment]
如果既支持 `string` 类型，又支持 `JSX` 会更好

**Comment by axetroy** [comment]
> 如果既支持 `string` 类型，又支持 `JSX` 会更好

JSX.Element 本身就包含了 string，这并没有对原有的功能有破坏性

**Comment by robinv8** [comment]
哈哈，是我反应慢了
