### ISSUE TITLE
基础的项目, 编译rn, 预览报错

### ISSUE THREAD

**Issue by gaokun** [NervJS/taro-ui#1675]
**问题描述**

taro init了最基础的项目, 只引用了taro-ui的一个button, 编译到h5, weapp都ok

![image](https://github.com/NervJS/taro-ui/assets/7044628/1d21c3c4-5249-4e96-8f56-e7fa90d8f2fc)

但是编译到rn, 预览后报错
![image](https://github.com/NervJS/taro-ui/assets/7044628/418f11f7-24d1-4613-94ae-b9f942c273b9)

**复现步骤**

这是可重现的工程:  https://github.com/gaokun/taro-test

`pnpm dev:rn --qr` 来编译, 然后使用taro-playground来预览的

**期望行为**

**报错信息**

**系统信息**

**补充信息**

**Comment by robinv8** [comment]
可以参考 https://github.com/NervJS/taro-ui/issues/1660

**Comment by gaokun** [comment]
在metro.config.js中添加了上面提到的alias配置, 已解决, thx

```js
const { mergeConfig } = require("metro-config");
const { getMetroConfig } = require("@tarojs/rn-supporter");

module.exports = (async function () {
  return mergeConfig(
    {
      // custom your metro config here
      // https://facebook.github.io/metro/docs/configuration
      resolver: {},
      alias: {
        "~taro-ui/dist": `~taro-ui/rn`,
      },
    },
    await getMetroConfig()
  );
})();

```
