### ISSUE TITLE
AtListItem 开启isSwitch 后 Switch 页面没渲染

### ISSUE THREAD

**Issue by 5312** [NervJS/taro-ui#1679]
### Taro UI 版本信息

v3.2.0-beta.0-rn

### 问题描述

微信小程序 使用 AtListItem 开启isSwitch 后Switch 页面没渲染

### 复现步骤

1. dev:weapp 启动taro
2. 打开微信开发者工具

### 复现代码
```
import { View } from "@tarojs/components";
import { AtList, AtListItem } from "taro-ui";
 

export default function Parameters() {
  /* switch click */
  function handleVChange() {}
  function handleEChange() {}
  return (
    <View>
      <AtList>
       
      
        <AtListItem
          title="低电压降功率保护电池"
          note="(1代表开启，0代表关闭，建议开启)"
          isSwitch={true}
          onSwitchChange={handleVChange}
        />
      
        <AtListItem
          title="显示统计曲线"
          note="(1代表显示,0代表隐藏)"
          isSwitch={true}
          onSwitchChange={handleEChange}
        />
      </AtList>
    </View>
  );
}

```
### 报错信息

/base.wxml
 Template `tmpl_0_61` not found.

### 系统信息

👽 Taro v3.6.8

  Taro CLI 3.6.8 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 14.19.3 - D:\tools\nodejs\node.EXE
      npm: 6.14.17 - D:\tools\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.6 => 3.6.6
      @tarojs/components: 3.6.6 => 3.6.6
      @tarojs/helper: 3.6.6 => 3.6.6
      @tarojs/plugin-framework-react: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-alipay: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-h5: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-jd: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-qq: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-swan: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-tt: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-weapp: 3.6.6 => 3.6.6
      @tarojs/react: 3.6.6 => 3.6.6
      @tarojs/runtime: 3.6.6 => 3.6.6
      @tarojs/shared: 3.6.6 => 3.6.6
      @tarojs/taro: 3.6.6 => 3.6.6
      @tarojs/webpack5-runner: 3.6.6 => 3.6.6
      babel-preset-taro: 3.6.6 => 3.6.6
      eslint-config-taro: 3.6.6 => 3.6.6
      react: ^18.0.0 => 18.2.0
      taro-ui: 3.1.1 => 3.1.1

**Comment by robinv8** [comment]
我在模拟器上未发现该问题，看你描述不确定 taro-ui 版本是 `v3.2.0-beta.0-rn` 还是 `3.1.1`
taro 版本：3.6.6
taro-ui 版本：3.1.1
<img width="389" alt="image" src="https://github.com/NervJS/taro-ui/assets/12277531/c8025bbc-2790-4f68-ae98-e5718c7f940b">

**Comment by iLoongDD** [comment]
我也遇到了这个问题，请问后面有解决方法吗。我的taro-ui版本是3.3.0，taro版本是3.6.22

**Comment by robinv8** [comment]
> 我也遇到了这个问题，请问后面有解决方法吗。我的taro-ui版本是3.3.0，taro版本是3.6.22

麻烦提供个可复现的 demo，方便排查
