### ISSUE TITLE
taro-rn使用taro-ui报错 there's already a module with namespace "math" 

### ISSUE THREAD

**Issue by wukongyang** [NervJS/taro-ui#1682]
## 版本信息如下 
"taro-ui": "^3.1.1"
"react-native": "^0.70.5",
"@tarojs/taro-rn": "3.6.8",
"webpack": "5.69.0"
"react": "^18.1.0",
 "react-dom": "^18.1.0",

## 现状
<img width="349" alt="image" src="https://github.com/NervJS/taro-ui/assets/54463146/5ba5a1c5-784d-4119-b515-06aca1a7295f">

**Comment by robinv8** [comment]
本地运行 https://github.com/robinv8/taro-rn-webpack5-demo 看看能否正常运行，或者提供能复现的 Demo

**Comment by robinv8** [comment]
已有解决方案，看这里 #1746
