### ISSUE TITLE
AtImagePicker在微信小程序无法使用

### ISSUE THREAD

**Issue by WonderYours** [NervJS/taro-ui#1689]
**问题描述**

在高版本基础库(大于2.21.0)的微信小程序端，点击AtImagePicker的加号没有任何反应以及报错
**复现步骤**

1. 在任意位置调用AtImagePicker
2. 运行npm run dev:weapp
3. 点击AtImagePicker的加号
```tsx
<AtImagePicker
              files={this.state.audio?.map(e => {
                let ret = { url: e }
                return ret
              }) as any}
              onChange={newAudio => {
                this.setState({
                  audio: newAudio.map(e => e?.url)
                })
              }}
            />
```

**期望行为**

点击加号弹出选择图片的弹窗
**报错信息**

没有任何的报错信息，因为wx.chooseImage方法被弃用了
**系统信息**

 - Taro 版本 [3.5.7]
 - Taro UI 版本 [3.1.1]
 - 报错平台 [weapp]

**补充信息**

而微信小程序在高于2.21.0的基础库不支持使用Taro.chooseImage方法，转而使用Taro.chooseMedia方法。
但是AtImagePicker调用了Taro.chooseImage方法，导致了这一bug的发生

**Comment by robinv8** [comment]
调整该 API 需要跟 [Taro](https://github.com/NervJS/taro) 团队做进一步确认，详情：https://github.com/NervJS/taro/issues/14772

**Comment by robinv8** [comment]
仔细看了下微信小程序文档，`chooseImage ` 只是停止维护而已。
> 从基础库 [2.21.0](https://developers.weixin.qq.com/miniprogram/dev/framework/compatibility.html) 开始，本接口停止维护，请使用 [wx.chooseMedia](https://developers.weixin.qq.com/miniprogram/dev/api/media/video/wx.chooseMedia.html) 代替

但由于 `chooseMedia` 在其他小程序上还不支持，建议继续用，如果无法使用，是跟小程序隐私政策有关，详情：https://developers.weixin.qq.com/community/develop/doc/00042e3ef54940ce8520e38db61801

**Comment by Lzengp** [comment]
@robinv8 @WonderYours 
我这边也发现了图片选择AtImagePicker点击没反应，同时官网给的组件也不行（建议更新下隐私协议），然后我这边设置了隐私协议就可以了
具体操作：
设置 - 服务内容声明 - 用户隐私保护指引 新增加“**选中的照片或者视频**”选项，同时，还需要把代码提交审核里面的 用户隐私保护指引设置 更新掉，然后发布生产
最近微信搞了这个隐私设置有点坑哦，之前一直能用的东西突然就不能用
![b714d716013d49f91ec5e627530d4a95](https://github.com/NervJS/taro-ui/assets/39240494/570d57f8-4cda-4292-9c89-89a9f33f160d)
![image](https://github.com/NervJS/taro-ui/assets/39240494/81687643-d1b1-4f48-910c-e3b3cdf5cccb)
