### ISSUE TITLE
如果要想在 tabs 组件上加上小圆点应该怎么做呢？

### ISSUE THREAD

**Issue by jswxwxf** [NervJS/taro-ui#169]
如果要想在 tabs 组件上加上小圆点应该怎么做呢？
现在只支持字符串吗？
tabList={[
    { title: '标签页1' },
    { title: '标签页2' },
    { title: '标签页3' },
    { title: '标签页4' },
    { title: '标签页5' },
    { title: '标签页6' }
  ]}

**Comment by jswxwxf** [comment]
<img width="335" alt="2018-11-12 8 06 41" src="https://user-images.githubusercontent.com/1768767/48320223-f27fc780-e651-11e8-87e9-a2db774c31ce.png">

像这样

**Comment by jimczj** [comment]
目前没有支持该特性

**Comment by tinico** [comment]
文档上有啊

**Comment by koppthe** [comment]
这类定制化的组件，建议自己实现哈
