### ISSUE TITLE
@use rules must be written before any other rules

### ISSUE THREAD

**Issue by wukongyang** [NervJS/taro-ui#1696]
<img width="327" alt="image" src="https://github.com/NervJS/taro-ui/assets/54463146/cbeaf09f-3985-4552-a8bb-47e23378b257">
**config/index.js**
<img width="833" alt="image" src="https://github.com/NervJS/taro-ui/assets/54463146/e72c0230-bff4-497a-b9de-9c50779222f1">

 "dependencies": {
    "@ant-design/react-native": "^5.0.4",
    "@babel/runtime": "^7.7.7",
    "@bam.tech/react-native-image-resizer": "~3.0.4",
    "@react-native-async-storage/async-storage": "~1.17.7",
    "@react-native-camera-roll/camera-roll": "~5.0.4",
    "@react-native-clipboard/clipboard": "~1.11.1",
    "@react-native-community/geolocation": "~3.0.2",
    "@react-native-community/netinfo": "~9.3.0",
    "@react-native-community/segmented-control": "^2.2.2",
    "@react-native-community/slider": "~4.3.2",
    "@react-native-masked-view/masked-view": "~0.2.7",
    "@react-native-picker/picker": "~2.4.2",
    "@tarojs/components": "3.6.17",
    "@tarojs/helper": "3.6.17",
    "@tarojs/plugin-framework-react": "3.6.17",
    "@tarojs/plugin-platform-alipay": "3.6.17",
    "@tarojs/plugin-platform-h5": "3.6.17",
    "@tarojs/plugin-platform-jd": "3.6.17",
    "@tarojs/plugin-platform-qq": "3.6.17",
    "@tarojs/plugin-platform-swan": "3.6.17",
    "@tarojs/plugin-platform-tt": "3.6.17",
    "@tarojs/plugin-platform-weapp": "3.6.17",
    "@tarojs/react": "3.6.17",
    "@tarojs/rn-supporter": "3.6.17",
    "@tarojs/runtime": "3.6.17",
    "@tarojs/runtime-rn": "3.6.17",
    "@tarojs/shared": "3.6.17",
    "@tarojs/taro": "3.6.17",
    "@tarojs/taro-rn": "3.6.17",
    "cache-loader": "^4.1.0",
    "expo": "~47.0.3",
    "expo-av": "~13.0.0",
    "expo-barcode-scanner": "~12.0.0",
    "expo-brightness": "~11.0.0",
    "expo-camera": "~13.0.0",
    "expo-file-system": "~15.1.1",
    "expo-image-picker": "~14.0.0",
    "expo-keep-awake": "~11.0.1",
    "expo-location": "~15.0.1",
    "expo-sensors": "~12.0.1",
    "lottie-ios": "3.4.0",
    "lottie-react-native": "^5.1.4",
    "react": "^18.1.0",
    "react-dom": "^18.1.0",
    "react-native": "^0.70.1",
    "react-native-device-info": "~10.3.0",
    "react-native-gesture-handler": "~2.9.0",
    "react-native-pager-view": "~6.0.1",
    "react-native-safe-area-context": "~4.4.1",
    "react-native-screens": "^3.18.2",
    "react-native-scrollable-tab-view": "^1.0.0",
    "react-native-splash-screen": "^3.3.0",
    "react-native-svg": "~13.7.0",
    "react-native-syan-image-picker": "0.5.3",
    "react-native-update": "8.x",
    "react-native-webview": "~11.23.0",
    "taro-lottie": "^1.0.2",
    "taro-plugin-compiler-optimization": "^1.0.4",
    "taro-ui": "^3.1.1",
    "thread-loader": "^4.0.2"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@pmmmwh/react-refresh-webpack-plugin": "^0.5.5",
    "@tarojs/cli": "3.6.17",
    "@tarojs/plugin-mini-ci": "^3.6.18",
    "@tarojs/rn-runner": "3.6.17",
    "@tarojs/taro-loader": "3.6.17",
    "@tarojs/webpack5-runner": "3.6.17",
    "@types/node": "^18.15.11",
    "@types/react": "^18.0.0",
    "@types/react-native": "^0.69.8",
    "@types/webpack-env": "^1.13.6",
    "@typescript-eslint/eslint-plugin": "^5.20.0",
    "@typescript-eslint/parser": "^5.20.0",
    "babel-preset-taro": "3.6.17",
    "eslint": "^8.12.0",
    "eslint-config-taro": "3.6.17",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-react-hooks": "^4.2.0",
    "install-peerdeps": "^3.0.3",
    "pod-install": "^0.1.23",
    "postcss": "^8.4.18",
    "react-refresh": "^0.11.0",
    "stylelint": "9.3.0",
    "ts-node": "^10.9.1",
    "typescript": "^4.1.0",
    "webpack": "^5.78.0"
  }

**Comment by robinv8** [comment]
@wukongyang 本地运行 https://github.com/robinv8/taro-rn-webpack5-demo 看看能否正常运行
