### ISSUE TITLE
Taro.request返回对象问题

### ISSUE THREAD

**Issue by chendiedie** [NervJS/taro-ui#1698]
<T = any, U = any>(option: Option<T, U>) => RequestTask<T>

以上是文档中定义的request方法，返回一个RequestTask对象，但实际返回的是一个promise，微信小程序原生wx.request方法返回的RequestTask对象不一致，因此Taro.request的返回值无法使用RequestTask的api

基础库版本：2.33.0

**Comment by robinv8** [comment]
提错位置了，去这里 https://github.com/NervJS/taro/issues

**Comment by chendiedie** [comment]
> 提错位置了，去这里 https://github.com/NervJS/taro/issues

哦，不好意思，切错浏览器标签了
