### ISSUE TITLE
为什么我会频繁出现 Component is not found in path 这样的错误呢？

### ISSUE THREAD

**Issue by jswxwxf** [NervJS/taro-ui#170]
然后只要手动编辑一下那个组件（随便怎么编辑 ）再保存一下就能找到了~

**Comment by jswxwxf** [comment]
<img width="888" alt="2018-11-12 11 54 43" src="https://user-images.githubusercontent.com/1768767/48325679-c8d69880-e671-11e8-85b2-ea0777e793ab.png">
像这种

**Comment by jswxwxf** [comment]
<img width="751" alt="2018-11-13 2 05 29" src="https://user-images.githubusercontent.com/1768767/48394110-33a8d200-e74d-11e8-97cf-98d1df454461.png">
现在又报这样的错，可我看了生成的目录，这个文件明明存在啊……

npm/taro-ui/dist/weapp/index.js

**Comment by SzHeJason** [comment]
可以做一个 简单的 DEMO 吗？ 或者排除下是哪块语法的问题 贴代码出来看看

**Comment by SzHeJason** [comment]
版本号带上

**Comment by jswxwxf** [comment]
不好意思，是我的代码的问题，原来在 taro 里用 HOC 这种模式会出问题……

**Comment by DreamPWJ** [comment]
依然会有这个问题

**Comment by s2265681** [comment]
请问怎么解决的呢 我也出现了这个问题 ，编译taro-ui出错

**Comment by georgezouq** [comment]
怎么解决的？

**Comment by aa-ziyi** [comment]
用的@tarojs/cli 2.2.2的版本确实有问题
重新装 npm install -g @tarojs/cli@1.3.12   的版本
重新init一个项目正常了，其他版本还没试
