### ISSUE TITLE
与 AtTabs 合用时，AtFloatLayout 应以根窗口为基弹出

### ISSUE THREAD

**Issue by kenberkeley** [NervJS/taro-ui#171]
点击按钮
![image](https://user-images.githubusercontent.com/13287948/48332228-30f3a180-e6a7-11e8-9c86-a9688161b923.png)

弹出，超出视图范围
![image](https://user-images.githubusercontent.com/13287948/48332238-381aaf80-e6a7-11e8-87a0-bb69af1ef994.png)

增大父容器高度
![image](https://user-images.githubusercontent.com/13287948/48332255-4cf74300-e6a7-11e8-96f6-b5b9094400c8.png)

弹出，表现稍微正常点
![image](https://user-images.githubusercontent.com/13287948/48332268-5680ab00-e6a7-11e8-84d1-bb2d25521c98.png)

***

不与 AtTabs/AtTabsPane 合用时完全正常

![image](https://user-images.githubusercontent.com/13287948/48332432-d7d83d80-e6a7-11e8-979d-b03deea2ab04.png)

**Comment by jimczj** [comment]
麻烦把代码粘贴一下，我们本地运行下

**Comment by kenberkeley** [comment]
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'
import { AtTabs, AtTabsPane, AtButton, AtFloatLayout } from 'taro-ui'

export default class Index extends Component {
  config = {
    navigationBarTitleText: 'FloatLayout 不应该以父组件为基'
  }

  constructor (props) {
    super(props)
    this.state = {
      isFloatLayoutVisible: false
    }
  }

  showFloatLayout = () => {
    this.setState({
      isFloatLayoutVisible: true
    })
  }

  hideFloatLayout = () => {
    this.setState({
      isFloatLayoutVisible: false
    })
  }

  render () {
    return (
      <View style='background: grey; height: 800px'>
        <AtTabs current={0} tabList={[{ title: '标签页 1' }, { title: '标签页 2' }]}>
          <AtTabsPane current={0} index={0}>
            <View style='margin-top: 10px; height: 200px; background: orange'>
              <AtButton type='primary' onClick={this.showFloatLayout}>
                打开 FloatLayout
              </AtButton>

              <AtFloatLayout
                title='标题'
                isOpened={this.state.isFloatLayoutVisible}
                onClose={this.hideFloatLayout}>
                <View style='width: 100%; height: 100%; background: yellow'>
                  这是内容区 随你怎么写这是内容区 随你怎么写这是内容区
                  随你怎么写这是内容区 随你怎么写这是内容区 随你怎么写这是内容区
                  随你怎么写
                  <AtButton type='secondary' onClick={this.hideFloatLayout}>
                    关闭 FloatLayout
                  </AtButton>
                  这是内容区 随你怎么写这是内容区 随你怎么写这是内容区
                  随你怎么写这是内容区 随你怎么写这是内容区 随你怎么写这是内容区
                  随你怎么写
                </View>
              </AtFloatLayout>
            </View>
          </AtTabsPane>
        </AtTabs>
      </View>
    )
  }
}

**Comment by kenberkeley** [comment]
按常理，FloatLayout 无论如何都应该从最底部滑起，不受外部限制

**Comment by SzHeJason** [comment]
@kenberkeley #174 与该 iSSUE 的问题一样 只能通过 优化DOM节点处理

**Comment by mancoxu** [comment]
这个问题解决了么？ `3.0.0-alpha.10` 还有这个问题

**Comment by web-linda** [comment]
同求解决方案
