### ISSUE TITLE
watch 模式下，无法正常显示AtInput title

### ISSUE THREAD

**Issue by linlijason** [NervJS/taro-ui#1711]
运行环境:
Taro CLI 3.6.19 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.17.0 - /usr/local/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 9.6.7 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.19 => 3.6.19 
      @tarojs/components: 3.6.19 => 3.6.19 
      @tarojs/helper: 3.6.19 => 3.6.19 
      @tarojs/plugin-framework-react: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-alipay: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-h5: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-jd: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-qq: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-swan: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-tt: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-weapp: 3.6.19 => 3.6.19 
      @tarojs/react: 3.6.19 => 3.6.19 
      @tarojs/runtime: 3.6.19 => 3.6.19 
      @tarojs/shared: 3.6.19 => 3.6.19 
      @tarojs/taro: 3.6.19 => 3.6.19 
      @tarojs/taro-loader: 3.6.19 => 3.6.19 
      @tarojs/webpack5-runner: 3.6.19 => 3.6.19 
      babel-preset-taro: 3.6.19 => 3.6.19 
      eslint-config-taro: 3.6.19 => 3.6.19 
      react: ^18.0.0 => 18.2.0 
      taro-ui: ^3.2.0 => 3.2.0 

问题描述: 在watch时，如果不显示的引入Label组件，无法正确显示AtInput的title.
复现的方式:
1. 页面的内容:
<img width="1135" alt="image" src="https://github.com/NervJS/taro-ui/assets/5846983/559a0282-7d0e-4ace-bf38-eb808b5d749c">

yarn dev:weapp 运行之后，如图所示：title显示不出来
<img width="371" alt="image" src="https://github.com/NervJS/taro-ui/assets/5846983/07b81797-98f3-4cab-af21-78a6224f1c00">
2. 当 我在另一个页面中（一个无用的页面）导入 Label并使用.
`import { View,Input,Button,Label } from "@tarojs/components"

    return (
        <View>
            <AtButton openType="getPhoneNumber" onGetPhoneNumber={ gggg}>测试</AtButton>
            <Input />
            <Button />
            <Label />
        </View>
    )
}`
之后，AtInput正常显示:
<img width="370" alt="image" src="https://github.com/NervJS/taro-ui/assets/5846983/5bff2ded-2875-4fa4-9180-45e741098bbe">

另外，此问题只在watch模式下出现。 不使用watch打包的结果能正常显示

**Comment by robinv8** [comment]
排查 config/index.js 中是否有如下配置，如果使用了 webpack 5，则需要如下修改成如下配置：
```
 compiler: {
      type: 'webpack5',
      prebundle: {
        exclude: ['taro-ui']
      }
    }
```

**Comment by linlijason** [comment]
解决了，谢谢
