### ISSUE TITLE
微信小程序全局引入样式不生效

### ISSUE THREAD

**Issue by xiaochun0311** [NervJS/taro-ui#1713]
**问题描述**

背景：打算使用taro+react+taro-ui重构项目，引入taro-ui后
全局引入taroui的样式文件：执行dev:weapp样式不生效，但是执行dev:h5正常显示
局部引入某一个组件样式文件：正常显示

无报错信息

**复现步骤**

![image](https://github.com/NervJS/taro-ui/assets/53181515/c88e2107-7a74-4260-b168-1b55cba8dd04)
![image](https://github.com/NervJS/taro-ui/assets/53181515/df2c1dda-8a85-4c31-894e-6802877be163)
![image](https://github.com/NervJS/taro-ui/assets/53181515/6fcafdcf-40c6-46d6-8aa2-436074e7585b)

```js
// 这里可以贴代码
```

**期望行为**

正常横向展示tabbar
**报错信息**

无
**系统信息**

![image](https://github.com/NervJS/taro-ui/assets/53181515/2756ad12-5272-4beb-a102-0e8ae96284cb)

- taro: 3.6.17
- taro-ui: 3.0.0-alpha.10
**补充信息**

**Comment by robinv8** [comment]
taro-ui 升级到 3.2.0 再试试，再确定下是否使用 webpack5，如果使用了 webpack5 则在 config/index.js 中修改配置：
```
 compiler: {
      type: 'webpack5',
      prebundle: {
        exclude: ['taro-ui']
      }
    }
```

**Comment by xiaochun0311** [comment]
@robinv8 
![image](https://github.com/NervJS/taro-ui/assets/53181515/ab9aca9e-371f-4e0c-b0f0-cfe2aa876c2a)

**Comment by xiaochun0311** [comment]
@robinv8 
升级taro-ui3.2.0会运行时存错，https://github.com/NervJS/taro-ui/issues/1662 这里提到过
![image](https://github.com/NervJS/taro-ui/assets/53181515/ee4f9d83-44d7-430f-b998-45e80993997b)
使用了webpack5，默认使用prebundle，我这边禁用掉了，如果不禁用，会出现下面这个问题
![image](https://github.com/NervJS/taro-ui/assets/53181515/5e1ae7d0-5487-4484-9935-351b0ad15ea5)
是不支持webpack5吗？

**Comment by robinv8** [comment]
在 taro3.5 之后的版本中，在开启 prebundle (默认开启)的情况下，会导致 taro-ui 所引用的 @taro/components 组件没有被打进最终的 bundle 中，导致页面表现异常。

**Comment by wojiaoshupian** [comment]
请问解决了吗
