### ISSUE TITLE
AtSwipeAction 组件报错

### ISSUE THREAD

**Issue by chutaozh** [NervJS/taro-ui#1715]
**问题描述**

搭建好Taro脚手架后（react），不做任何配置，首次安装 taro-ui，使用AtSwipeAction，一切正常，修改配置，只开启了cssModule，重新运行，开始报错，无法正常渲染

**复现步骤**

```js
// config/index.js  开启了cssModules
{
  ...,
  mini: {
      postcss: {
        pxtransform: {
          enable: true,
          config: {},
        },
        url: {
          enable: true,
          config: {
            limit: 1024, // 设定转换尺寸上限
          },
        },
        cssModules: {
          enable: true, // 默认为 false，如需使用 css modules 功能，则设为 true
          config: {
            namingPattern: "module", // 转换模式，取值为 global/module
            generateScopedName: "[name]__[local]___[hash:base64:5]",
          },
        },
      },
    },
}
```
![image](https://github.com/NervJS/taro-ui/assets/25075982/3295c05b-366f-4b65-b5b4-9686d3928d3f)

**期望行为**

**报错信息**

![image](https://github.com/NervJS/taro-ui/assets/25075982/e798c9fb-0c45-443e-98fc-a1802b8f3046)

**系统信息**

Taro 版本：v3.6.2
Taro UI 版本：v3.2.0
报错平台：weapp

window10
微信开发者工具 v1.06.2308310

**补充信息**

**Comment by robinv8** [comment]
麻烦提供可以完整运行的 demo，方便跟进问题

**Comment by chutaozh** [comment]
> 麻烦提供可以完整运行的 demo，方便跟进问题

仓库链接：https://github.com/chutao-zhang/taro-ui-sass.git

初始化时用的Taro默认模板，之后再安装taro-ui，引入AtSwipeAction组件后第一次运行正常，第二次开始便一直报错，期间没有改过config/...下的任何东西，另外，用的是yarn安装的包，不知道是否缺少什么配置才能使用taro-ui？

<img width="1265" alt="Snipaste_2023-12-08_15-57-34" src="https://github.com/NervJS/taro-ui/assets/25075982/9b76088e-e882-48a8-b453-5480ef35974f">
<img width="938" alt="Snipaste_2023-12-08_15-56-49" src="https://github.com/NervJS/taro-ui/assets/25075982/d64e4c58-8dd7-4e4f-9514-60a67cab9a10">

**Comment by chutaozh** [comment]
奇怪的是，用yarn build:weapp 打包后是正常的，
![image](https://github.com/NervJS/taro-ui/assets/25075982/c260ce90-3182-4eb6-96c4-868d1e53457b)
![image](https://github.com/NervJS/taro-ui/assets/25075982/22dc2c01-9021-4a8c-a7ee-79213a6b535e)


用yarn dev:weapp 本地调试就会报错
![image](https://github.com/NervJS/taro-ui/assets/25075982/e7467b9e-2eec-4a10-a704-02b129dc60b2)

**Comment by robinv8** [comment]
安装插件
```bash
npm i babel-plugin-import -D
```

按需加载组件需在.babelrc 或 babel.config.js 中添加配置：
```js
{
    plugins: [
    [
      "import",
      {
        libraryName: "taro-ui",
        customName: (name) => `taro-ui/lib/components/${name.slice(3)}`,
        customStyleName: (name) =>
          `taro-ui/dist/style/components/${name.slice(3)}.scss`,
      },
      "taro-ui",
    ],
  ],
}
```

**Comment by ZruiMay** [comment]
我看了他的仓库、当前问题没有得到解决，我这边遇到了一样的问题

**Comment by robinv8** [comment]
@ZruiMay 试试上面的配置

**Comment by ZruiMay** [comment]
@robinv8 
![WechatIMG582](https://github.com/NervJS/taro-ui/assets/35456577/cdf7b973-b542-42b4-a7b7-d24c98785b0d)
配置加入之后，启动直接报错了

**Comment by robinv8** [comment]
上面的 demo 添加配置后没问题啊，你提供个 demo 试试

**Comment by ZruiMay** [comment]
我目前刚使用taro-cli 创建的项目、和楼上的demo，是一样的，区别在于，我目前是mac环境、本地node 是16.15.0，其他没有差别。你这边可以使用它的这个demo地址，加入配置进行测试一下。
仓库链接：https://github.com/chutao-zhang/taro-ui-sass.git

**Comment by robinv8** [comment]
@ZruiMay 抱歉！是我之前没表述清楚。现已经添加 Demo 如下，其中也包含按需加载组件的说明
https://github.com/NervJS/taro-ui/tree/next/examples/lazy-load-component

**Comment by XL-shi** [comment]
> @ZruiMay 抱歉！是我之前没表述清楚。现已经添加 Demo 如下，其中也包含按需加载组件的说明 https://github.com/NervJS/taro-ui/tree/next/examples/lazy-load-component

按这个方式解决了！！问题和楼主遇到的一模一样。谢谢。（吐槽一下：一般性排查问题，太难解决这种问题了！）

**Comment by JuvenileQ** [comment]
我也遇到了，看别人说是：

> “在taro3.5之后的版本中，在开启prebundle(默认开启)的情况下，会导致ossaui所引用的@taro/components组件没有被打进最终的bundle中，导致页面表现异常。”[手动将ossaui排除在prebundle列表之外](https://ossa.miaode.com/docs/start)

随后搜索taro文档：

> [compiler.prebundle](https://taro-docs.jd.com/docs/config-detail#compilerprebundle)，“是否开启依赖预编译功能。开启后首次编译 Taro 会把项目的 node_modules 依赖打包为模块联邦的 Remote 应用，二次编译时 Webpack 只需要编译项目源码，从而提升编译速度。”“默认值：生产环境为 false，开发环境为 true”

所以当taro版本>=3.5时，taro项目使用taro-ui的正确的配置方式是在config/index.js文件中排除taro-ui

```
// config/index.js 
module.exports = {
  framework: 'react',
  compiler: {
    type: 'webpack5',
    prebundle: {
      exclude: ['taro-ui']
    }
  },
}
```


这是一种解决办法，不知道还有没有其他方式避免这个问题？

官方再后续版本会修复吗？
