### ISSUE TITLE
h5 可否像 weapp 那样把组件拆分到 components 子目录里?

### ISSUE THREAD

**Issue by cncolder** [NervJS/taro-ui#172]
### 重现步骤
```shell
la node_modules/taro-ui/dist/h5/
total 1200
drwxr-xr-x  3 colder  staff    96B 11 11 22:49 css
-rw-r--r--  1 colder  staff   599K 11 11 22:49 index.js
```

### 依赖的版本号

taro-ui@1.4.0

### 预期结果
希望 index.js 像 weapp 那样 `export * from './components/list`

### 实际结果
目前一个 index.js 就有600K

![2018-11-12 15 51 23](https://user-images.githubusercontent.com/127009/48333559-dfd9b280-e692-11e8-8dd4-6792e40ee353.png)

**Comment by jimczj** [comment]
近期会考虑怎么优化

**Comment by hugetiny** [comment]
@jimcj 先考虑和Taro支持同步的平台吧，优化我们可以先自己来

**Comment by koppthe** [comment]
v1.5.4 以及 next 版本已支持，可以尝尝鲜
```bash
npm install taro-ui@next
```
