### ISSUE TITLE
AtFloatLayout 浮动层，ios系统上拉到留白，会导致AtFloatLayout 内容显示

### ISSUE THREAD

**Issue by Chensonglin08** [NervJS/taro-ui#1729]
AtFloatLayout 浮动层，ios系统上拉到留白，会导致AtFloatLayout 内容显示

**Comment by Chensonglin08** [comment]
问题描述:ios系统上拉到底部留白，在isOpened为false的情况下，还是会导致AtFloatLayout里面的表单内容显示

**Comment by robinv8** [comment]
麻烦提供个可复现且可运行的 demo
