### ISSUE TITLE
Tarov3.6.21 安装 Taro-ui 依赖报错问题

### ISSUE THREAD

**Issue by 1609960351** [NervJS/taro-ui#1732]
![image](https://github.com/NervJS/taro-ui/assets/45301288/0845b784-ca92-4273-9d71-f1ecfba66d3a)

![image](https://github.com/NervJS/taro-ui/assets/45301288/7a8290f8-cd26-4727-9086-9aeebccb6944)

**Comment by robinv8** [comment]
找到问题了，我处理下，可以先通过 npm install taro-ui@latest 安装最新版
