### ISSUE TITLE
Cannot set property 'props' of undefined when using AtButton

### ISSUE THREAD

**Issue by iamphc** [NervJS/taro-ui#1735]
**问题描述**
using AtButton component in weapp page, got "Cannot set property 'props' of undefined".

**复现步骤**
1、use taro to create a miniapp
2、create a page
3、page code below:

```js
<template>
  <view>
    <AtButton>123</AtButton>
  </view>
</template>

<script lang="ts" name="News" setup>
import { AtButton } from "taro-ui";
</script>
```
4、console got Cannot set property 'props' of undefined

**期望行为**
show AtButton without error

**报错信息**
Cannot set property 'props' of undefined

**系统信息**
- taro-ui: 3.2.0
- vue: 3.2.24
- @tarojs/taro: 3.6.21
- platform: macos(arm)
- code platform: wechat miniapp

ps:
<img width="673" alt="image" src="https://github.com/NervJS/taro-ui/assets/51198179/21aee808-877a-4045-8fac-ca9fafd1d7dc">

**Comment by robinv8** [comment]
taro-ui 只支持 react 语法
