### ISSUE TITLE
按照官网步骤，无法安装 taro-ui

### ISSUE THREAD

**Issue by lishuncoder** [NervJS/taro-ui#1743]
**问题描述**
按照官网步骤，无法安装 taro-ui

```shell
npm install -g @tarojs/cli

#一路正常点，选择react代码，npm管理，默认模板
taro init myApp

cd myApp
npm install taro-ui@latest

#报错：
PS E:\mydemo\myApp> npm install taro-ui@latest
npm ERR! code ERESOLVE                                                                 
npm ERR! ERESOLVE unable to resolve dependency tree                                    
npm ERR!                                                                               
npm ERR! While resolving: myApp@1.0.0                                                  
npm ERR! Found: @tarojs/plugin-platform-alipay@3.6.22                                  
npm ERR! node_modules/@tarojs/plugin-platform-alipay                                   
npm ERR!   @tarojs/plugin-platform-alipay@"3.6.22" from the root project               
npm ERR!                                                                               
npm ERR! Could not resolve dependency:                                                 
npm ERR! peer @tarojs/plugin-platform-alipay@"3.6.6" from taro-ui@3.2.1                
npm ERR! node_modules/taro-ui                                                          
npm ERR!   taro-ui@"3.2.1" from the root project                                       
npm ERR!                                                                               
npm ERR! Fix the upstream dependency conflict, or retry                                
npm ERR! this command with --force, or --legacy-peer-deps                              
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.        
npm ERR!                                                                               
npm ERR! See C:\Users\LS\AppData\Local\npm-cache\eresolve-report.txt for a full report.
                                                                                       
npm ERR! A complete log of this run can be found in:                                   
npm ERR!     C:\Users\LS\AppData\Local\npm-cache\_logs\2024-01-04T14_48_19_339Z-debug-0.log
```

**复现步骤**

**期望行为**
能让我正常开始第一步...

**报错信息**

**系统信息**
PS E:\mydemo\myApp> taro info
👽 Taro v3.6.22

  Taro CLI 3.6.22 environment info:                   
    System:
      OS: Windows 10 10.0.19045
    Binaries:                                         
      Node: 16.20.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD  
      npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.22 => 3.6.22
      @tarojs/components: 3.6.22 => 3.6.22
      @tarojs/helper: 3.6.22 => 3.6.22
      @tarojs/plugin-framework-react: 3.6.22 => 3.6.22
      @tarojs/plugin-platform-alipay: 3.6.22 => 3.6.22
      @tarojs/plugin-platform-h5: 3.6.22 => 3.6.22
      @tarojs/plugin-platform-jd: 3.6.22 => 3.6.22
      @tarojs/plugin-platform-qq: 3.6.22 => 3.6.22
      @tarojs/plugin-platform-swan: 3.6.22 => 3.6.22
      @tarojs/plugin-platform-tt: 3.6.22 => 3.6.22
      @tarojs/plugin-platform-weapp: 3.6.22 => 3.6.22
      @tarojs/react: 3.6.22 => 3.6.22
      @tarojs/runtime: 3.6.22 => 3.6.22
      @tarojs/shared: 3.6.22 => 3.6.22
      @tarojs/taro: 3.6.22 => 3.6.22
      @tarojs/taro-loader: 3.6.22 => 3.6.22
      @tarojs/webpack5-runner: 3.6.22 => 3.6.22
      babel-preset-taro: 3.6.22 => 3.6.22
      eslint-config-taro: 3.6.22 => 3.6.22
      react: ^18.0.0 => 18.2.0

**补充信息**

**Comment by lishuncoder** [comment]
我大概知道原因，版本不适配，强行降级到3.6.6，可以进行 npm install taro-ui，但这不合适，是不是ui还没有支持到那么新？

**Comment by robinv8** [comment]
刚修复了，重新安装试试，最新版本是 3.2.2

**Comment by lishuncoder** [comment]
> 刚修复了，重新安装试试，最新版本是 3.2.2

你快的令我震惊

**Comment by robinv8** [comment]
哈哈哈，可以了吗？

**Comment by lishuncoder** [comment]
> 哈哈哈，可以了吗？

OK了，谢谢大佬

**Comment by Zhou-Yicheng** [comment]
这个问题是不是又复现了？

**Comment by Zhou-Yicheng** [comment]
> 这个问题是不是又复现了？

找到问题了，应该是因为React突然更新[18.3.0](https://github.com/facebook/react/releases/tag/v18.3.0)了

**Comment by heyuuuu** [comment]
> > 这个问题是不是又复现了？
> 
> 找到问题了，应该是因为React突然更新[18.3.0](https://github.com/facebook/react/releases/tag/v18.3.0)了

问题来了，请问有解决方案吗？

**Comment by inrtgdje** [comment]
小白新手按照https://taro-ui.jd.com/#/docs/quickstart 给的方法，又出现了报错，使用的gitee模版
报错信息
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: taro-demo@1.0.0
npm error Found: react@18.2.0
npm error node_modules/react
npm error   react@"^18.2.0" from the root project
npm error   peer react@">=16.13.0" from taro-ui@3.3.0
npm error   node_modules/taro-ui
npm error     taro-ui@"*" from the root project
npm error   10 more (@tarojs/react, @tarojs/taro-rn, ...)
npm error
npm error Could not resolve dependency:
npm error peer react@"^18.3.1" from react-dom@18.3.1
npm error node_modules/react-dom
npm error   react-dom@"^18.2.0" from the root project
npm error   peer react-dom@">=16.13.0" from taro-ui@3.3.0
npm error   node_modules/taro-ui
npm error     taro-ui@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
