### ISSUE TITLE
picker 添加title

### ISSUE THREAD

**Issue by q2209449302** [NervJS/taro-ui#1744]
![image](https://github.com/NervJS/taro-ui/assets/45119606/7a3dd660-b872-4bd8-87aa-af2ea28a382b)

希望可以在picker组件添加title显示

**Comment by robinv8** [comment]
`picker` 组件采用了 [weui](https://weui.io/) 方案，但[小程序端](https://developers.weixin.qq.com/miniprogram/dev/component/picker.html)也仅支持 android，为了组件统一性，故此暂不支持
