### ISSUE TITLE
RN端，项目配置config/index 中配置sass的全局样式文件后，RN端报错@use rules must be written before any other rules

### ISSUE THREAD

**Issue by wukongyang** [NervJS/taro-ui#1746]
<img width="369" alt="image" src="https://github.com/NervJS/taro-ui/assets/54463146/77d0ae8e-5fcf-4a1b-a5cd-93969de27a54">

## 版本信息：
taro-ui ："3.1.1,
taro："3.6.20",
sass："1.50.0",
sass-loader:"12.4.0",

## 复现步骤：
https://github.com/robinv8/taro-rn-webpack5-demo  这个项目在config/index配置一下sass全局注入，并在common.scss中加入自己的样式代码，使用例如：AtButton组件（使用了@use "sass:math"模块的组件），就可以复现
例如如下配置：
<img width="625" alt="image" src="https://github.com/NervJS/taro-ui/assets/54463146/04f2b2ec-910d-433a-a79b-9cbe3b8a9b44">

## 尝试：
将taro-ui/dist/style 中rn相关scss文件的@use "sass:math";注释掉，并在全局样式common.scss文件中加入@use "sass:math";依然报错如下
<img width="369" alt="image" src="https://github.com/NervJS/taro-ui/assets/54463146/441f074e-d93f-4ed6-825c-1a9f84c333ab">

## 期望
RN支持配置sass全局样式文件的同时使用taro-ui

**Comment by wukongyang** [comment]
RN端，无sass全局配置样式文件，可正常使用taro-ui

**Comment by robinv8** [comment]
已向 taro 提 PR 修复该问题，目前可以使用 patch-package 包给对应的包打补丁，方案如下：
1. 在项目根目录下创建 `patches` 文件夹
2. 创建文件名为`@tarojs+rn-style-transformer+{版本号}.patch`，将「版本号」换成当前 taro 的版本号，常规情况下 `@tarojs/rn-style-transformer` 版本号与 taro 版本号一致，如果不一致可以通过 lock 文件自行查找
3. 将[链接](https://github.com/robinv8/taro-rn-webpack5-demo/blob/main/patches/%40tarojs%2Brn-style-transformer%2B3.6.15.patch)中的内容粘贴到已创建的文件中
4. 安装 patch-package，并在 package.json scripts 下添加 `"postinstall": "patch-package"` 命令
5. 执行 install
