### ISSUE TITLE
开发工具中 AtModal 并没有被遮挡，但真机调试则会被遮挡

### ISSUE THREAD

**Issue by kenberkeley** [NervJS/taro-ui#175]
开发工具
![image](https://user-images.githubusercontent.com/13287948/48340711-63a99400-e6bf-11e8-81a9-021e47e81c9d.png)

![image](https://user-images.githubusercontent.com/13287948/48340695-542a4b00-e6bf-11e8-9bcf-7fa421bb390d.png)

iOS
![image](https://user-images.githubusercontent.com/13287948/48340614-1f1df880-e6bf-11e8-8918-56af782eae44.png)

Android
![image](https://user-images.githubusercontent.com/13287948/48340619-247b4300-e6bf-11e8-8f46-8bd0e28c1c57.png)

**Comment by SzHeJason** [comment]
[原生组件](https://developers.weixin.qq.com/miniprogram/dev/component/native-component.html?search-key=%E5%8E%9F%E7%94%9F%E7%BB%84%E4%BB%B6) 你看看是不是这个问题 目前无解

**Comment by kenberkeley** [comment]
呜呜呜

**Comment by SzHeJason** [comment]
@kenberkeley 你可以试试在modal 上面 覆盖一层 cover-view

**Comment by kenberkeley** [comment]
目前的解决方案是：利用[全局消息中心](https://nervjs.github.io/taro/docs/events.html#docsNav)，在打开弹框时发布一个事件（例如 `HIDE_CHART`），在图表组件中监听该事件，设置图表 `display: none`；关闭弹框时也发布一个事件（例如 `SHOW_CHART`），同样地图表组件中也监听该事件，取消设置 `display: none`

**Comment by kenberkeley** [comment]
更简单的还可以统一使用 `TOGGLE_CHART` 然后：

```js
Taro.eventCenter.on(TOGGLE_CHART_VISIBLE, () => {
  this.setState({
    isChartVisible: !this.state.isChartVisible
  })
})
```

**Comment by kenberkeley** [comment]
https://github.com/NervJS/taro-ui/issues/110
