### ISSUE TITLE
AtAccordion 内容区的高度不应该初始化时固定，否则懒加载将无法呈现

### ISSUE THREAD

**Issue by kenberkeley** [NervJS/taro-ui#176]
点击展开手风琴：
![image](https://user-images.githubusercontent.com/13287948/48392743-a96a6900-e760-11e8-8d2b-fd2545c5a0bf.png)

预期是：
![image](https://user-images.githubusercontent.com/13287948/48392770-be46fc80-e760-11e8-94d6-9b69d878e879.png)

结果却是：
![image](https://user-images.githubusercontent.com/13287948/48392753-b0917700-e760-11e8-954c-0ff7e3016d4a.png)

**Comment by kenberkeley** [comment]
Any news?

**Comment by kenberkeley** [comment]
在 [`componentDidMount`](https://github.com/NervJS/taro-ui/blob/dev/src/components/accordion/index.js#L54-L73) 就固定死了高度，之后的 `switch` 也只是简单地设置为 `bodyHeight` 或 `0`。根据[文档](https://taro-ui.aotu.io/#/docs/accordion)中的一般用法，若之后有追加的新列表项，也是无法呈现的，因为高度在渲染时就被固定

**Comment by jimczj** [comment]
你这样使用的场景是什么呢

**Comment by kenberkeley** [comment]
AcAccordion 里面包含 AtList 是很正常的，而 AtListItem 的增减也是很正常的

**Comment by kenberkeley** [comment]
目前 AtAccordion 的内容高度是初始化时就固定了，将导致追加的列表项『溢出』，无法呈现

**Comment by kenberkeley** [comment]
懒加载也同理

**Comment by jimczj** [comment]
这种实现方式确实有问题我们将改成 js 动画的方式

**Comment by szy0syz** [comment]
楼主，自己先动手解决吧。
我的解决方案：把AtAccordion的唯一子元素拿个ScrollView容器固定高度，给用户自己滚动看吧。如果item太少，嫌弃的话，就在fetch完再去修改ScrollView容器高度了。

**Comment by jimczj** [comment]
已修复，等 2.0.0-beta.3 发布
