### ISSUE TITLE
文档日历组件不显示

### ISSUE THREAD

**Issue by dodoto** [NervJS/taro-ui#1764]
![calendar](https://github.com/NervJS/taro-ui/assets/45391750/728eb6df-a722-4335-9ca4-a65c202d9924)

**Comment by robinv8** [comment]
最新地址 https://taro-ui.taro.zone/#/docs/calendar
![image](https://github.com/NervJS/taro-ui/assets/12277531/4a153332-0439-4800-aa02-b997678dfb5b)
