### ISSUE TITLE
可以将 Taro 代码 直接编译成微信小程序原生引用方式的代码吗？

### ISSUE THREAD

**Issue by iceMusic** [NervJS/taro-ui#1766]
**这个功能解决了什么问题？**
期望可以在已有的原生微信小程序项目中能够使用taro-UI

**你期望的功能是怎样的？**
打包产物中，组件包含js、json、wxml.、wcss文件，方便可以在原生微信小程序项目中进行使用

**Comment by robinv8** [comment]
目前还不支持

**Comment by robinv8** [comment]
由于 taro-ui 依赖 taro，无法直接在原生微信小程序中使用
