### ISSUE TITLE
AtSlider组件无法在页面中展示

### ISSUE THREAD

**Issue by Yionse** [NervJS/taro-ui#1769]
**问题描述**
使用AtSlider组件，在Vscode中没报错，但是在微信开发者工具中却啥也看不到

**复现步骤**
1、在当前页面中引入AtSlider组件
2、使用AtSlider组件，并且传入约定的属性
```ts
<Text>分割</Text>
<AtSlider value={50}></AtSlider>
<Text>分割</Text>
```

**期望行为**
在页面上正确展示进度条

**报错信息**
无报错

**系统信息**
Taro CLI 3.6.19 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 16.17.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: ^3.6.24 => 3.6.24 
      @tarojs/components: 3.6.24 => 3.6.24 
      @tarojs/helper: 3.6.24 => 3.6.24 
      @tarojs/plugin-framework-react: 3.6.24 => 3.6.24 
      @tarojs/plugin-platform-alipay: 3.6.24 => 3.6.24 
      @tarojs/plugin-platform-h5: 3.6.24 => 3.6.24 
      @tarojs/plugin-platform-jd: 3.6.24 => 3.6.24 
      @tarojs/plugin-platform-qq: 3.6.24 => 3.6.24
      @tarojs/plugin-platform-swan: 3.6.24 => 3.6.24
      @tarojs/plugin-platform-tt: 3.6.24 => 3.6.24
      @tarojs/plugin-platform-weapp: 3.6.24 => 3.6.24
      @tarojs/react: 3.6.24 => 3.6.24
      @tarojs/runtime: 3.6.24 => 3.6.24
      @tarojs/shared: 3.6.24 => 3.6.24
      @tarojs/taro: 3.6.24 => 3.6.24
      @tarojs/taro-loader: 3.6.24 => 3.6.24     
      @tarojs/webpack5-runner: 3.6.24 => 3.6.24 
      babel-preset-taro: 3.6.24 => 3.6.24       
      eslint-config-taro: 3.6.24 => 3.6.24      
      react: ^18.0.0 => 18.2.0
      taro-ui: ^3.3.0 => 3.3.0

**Comment by robinv8** [comment]
按照这个排查一下
https://github.com/NervJS/taro-ui/issues/1726
