### ISSUE TITLE
taro升级1.1.4后在H5下AtSearchBar在输入时，placeholder不会消失

### ISSUE THREAD

**Issue by misterch** [NervJS/taro-ui#177]
### 重现步骤
官方demo
### 依赖的版本号

**Taro:1.1.4**
**Taro-UI :1.4.0**
### 预期结果
输入内容的时候placeholder消失
### 实际结果
taro1.1.4修复了Input组件在ios下输入的问题后，taro ui的AtSearchBar组件的placeholder不消失，删除内容按钮不出现。只有点击确定后才可以。我觉得应该是从之前的onInput事件换成了onChange事件导致的

**Comment by jimczj** [comment]
只在 h5 中会吗

**Comment by misterch** [comment]
> 只在 h5 中会吗

是的

**Comment by jimczj** [comment]
代码展示一下可以吗，我这边没问题

**Comment by misterch** [comment]
> 代码展示一下可以吗，我这边没问题

重新看了下代码，原来是我的问题，没有把之前在h5下使用input标签获取内容的判断改回来导致Input组件实际没有获取到输入的内容！不好意思！！
