### ISSUE TITLE
日历组件样式混乱

### ISSUE THREAD

**Issue by mornFloyd** [NervJS/taro-ui#1781]
**问题描述**

问题1 最新版本nodejs无法下载taroui node版本21.7.3 通过使用node14.18.0版本成功下载 但是编译无法成功此时切换回 21.7.3 可以成功编译微信小程序
问题2 日历组件样式混乱
![image](https://github.com/NervJS/taro-ui/assets/58218613/267e7f4d-6288-4d30-a435-a73816ebcc29)
**复现步骤**

```js
<AtFloatLayout isOpened={isShowDateDrawer} onClose={closeDateDrawer}>
        <AtCalendar validDates={[{ value: "2020/01/01" }]} />
      </AtFloatLayout>
```

**期望行为**
1.正常展示日历组件
2.希望支持新版nodejs下载编译taroui

**报错信息**
无报错

**补充信息**

**Comment by mornFloyd** [comment]
compiler: {
    type: 'webpack5',
    prebundle: {
      exclude: ['taro-ui']
    }
  }, 已经添加这段代码

**Comment by robinv8** [comment]
使用 node 16，记得 rm node_modules 后重新 install
