### ISSUE TITLE
开发环境下taro ui组件无法在小程序开发者工具中渲染

### ISSUE THREAD

**Issue by wojiaoshupian** [NervJS/taro-ui#1784]
**问题描述**
taro3使用taro ui然后在微信开发者工具编译的时候组件无法渲染出来

**复现步骤**
1.yarn run dev:weapp
2.微信开发者工具编译

```js
      <AtForm onSubmit={onSubmit} onReset={onReset}>
        <AtInput
          name='value'
          title='文本'
          type='text'
          placeholder='单行文本'
          value={value}
          onChange={handleChange}
        />
        <AtButton formType='submit'>提交</AtButton>
        <AtButton formType='reset'>重置</AtButton>
      </AtForm>
```

**期望行为**

能正常渲染组件
**报错信息**

<img width="706" alt="image" src="https://github.com/NervJS/taro-ui/assets/38551450/cad1585c-1ee7-4f30-8c2e-e525c4b63923">

**系统信息**

**补充信息**

当我使用yarn run build:weapp就能正常渲染 因为生产环境默认开启了压缩 而开发环境没有.

**Comment by robinv8** [comment]
根据 https://github.com/NervJS/taro-ui/issues/1726 排查一下
