### ISSUE TITLE
taro自定义tabbar引入taro ui的tabbar组件样式不生效

### ISSUE THREAD

**Issue by wojiaoshupian** [NervJS/taro-ui#1787]
### Taro UI 版本信息

v3.3.0

### 问题描述

taro ui作为小程序的自定义tabbar组件 引入后样式都没有了
 compiler: 'webpack5',
  compiler:{
    prebundle:{
      exclude:['taro-ui']
    }
  },
按照以前的issue修改配置也不行

### 复现步骤

自定义tabbar

### 复现代码
```tsx
import { useState } from 'react';
import { AtTabBar } from 'taro-ui';
import Taro from '@tarojs/taro';

export default function CustomTabBar() {
    const [current, setCurrent] = useState(0);

    const handleTabClick = (value) => {
        console.log(value)
        setCurrent(value);

        // 跳转逻辑
        // Taro.switchTab(getPagePath(value));
    };

    return (
        <div>
            <AtTabBar
                fixed
                tabList={[
                    { title: '自定义图标', iconPrefixClass: 'fa', iconType: 'clock', text: 'new' },
                    { title: '拍照', iconType: 'camera' },
                    { title: '文件夹', iconType: 'folder', text: '100', max: 99 }
                ]}
                onClick={handleTabClick}
                current={current}
            />
        </div>
    );
}
```

### 报错信息

暂无

### 系统信息

👽 Taro v3.6.27

  Taro CLI 3.6.27 environment info:
    System:
      OS: macOS 12.7.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v18.19.0/bin/yarn
      npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.27 => 3.6.27 
      @tarojs/components: 3.6.27 => 3.6.27 
      @tarojs/helper: 3.6.27 => 3.6.27 
      @tarojs/mini-runner: ^3.6.28 => 3.6.28 
      @tarojs/plugin-framework-react: 3.6.27 => 3.6.27 
      @tarojs/plugin-html: ^3.6.28 => 3.6.28 
      @tarojs/plugin-platform-alipay: 3.6.27 => 3.6.27 
      @tarojs/plugin-platform-h5: 3.6.27 => 3.6.27 
      @tarojs/plugin-platform-jd: 3.6.27 => 3.6.27 
      @tarojs/plugin-platform-qq: 3.6.27 => 3.6.27 
      @tarojs/plugin-platform-swan: 3.6.27 => 3.6.27 
      @tarojs/plugin-platform-tt: 3.6.27 => 3.6.27 
      @tarojs/plugin-platform-weapp: 3.6.27 => 3.6.27 
      @tarojs/react: 3.6.27 => 3.6.27 
      @tarojs/runtime: 3.6.27 => 3.6.27 
      @tarojs/shared: 3.6.27 => 3.6.27 
      @tarojs/taro: 3.6.27 => 3.6.27 
      @tarojs/taro-loader: 3.6.27 => 3.6.27 
      @tarojs/webpack5-runner: 3.6.27 => 3.6.27 
      babel-preset-taro: 3.6.27 => 3.6.27 
      eslint-config-taro: 3.6.27 => 3.6.27 
      react: ^18.0.0 => 18.3.1 
      taro-ui: ^3.3.0 => 3.3.0

**Comment by wojiaoshupian** [comment]
<img width="722" alt="image" src="https://github.com/NervJS/taro-ui/assets/38551450/cf4d6f16-5d90-4382-b760-4d385217c5a2">

**Comment by robinv8** [comment]
![image](https://github.com/NervJS/taro-ui/assets/12277531/fcebf4a1-f787-4e5c-a0ee-43f2262ca02e)
这里写法有问题，参考 https://github.com/NervJS/taro-ui/issues/1726 排查下，顺便贴一下样式是如何引入的？

**Comment by wojiaoshupian** [comment]
> ![image](https://private-user-images.githubusercontent.com/12277531/328212951-fcebf4a1-f787-4e5c-a0ee-43f2262ca02e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMDg0MjIsIm5iZiI6MTcxNTAwODEyMiwicGF0aCI6Ii8xMjI3NzUzMS8zMjgyMTI5NTEtZmNlYmY0YTEtZjc4Ny00ZTVjLWEwZWUtNDNmMjI2MmNhMDJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDE1MDg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjOTM2ZDk0MjNhN2U0OGFjMjVhZjYwZmZiN2Y2ZWExNTU3YzM4OGU2NGJlNjVhZDZkMjcyNTJlZjc2MWJmZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W3BksqaGcfXJXQkojtK8KC9X18Ug-PUO4CAI0djxB0U) 这里写法有问题，参考 #1726 排查下，顺便贴一下样式是如何引入的？

<img width="1245" alt="image" src="https://github.com/NervJS/taro-ui/assets/38551450/671147b7-7e08-429d-8746-df70f3548290">

**Comment by wojiaoshupian** [comment]
刚试了 用babel插件的方式按需导入 样式是能生效的
