### ISSUE TITLE
文档网站支持暗黑模式

### ISSUE THREAD

**Issue by ianzone** [NervJS/taro-ui#1788]
**这个功能解决了什么问题？**

解决了大晚上看文档亮瞎眼的问题

**你期望的功能是怎样的？**

提供暗黑模式可选项，或者随系统主题变化

**补充信息**

稍微讲究开发体验的文档网站都有暗黑模式

**Comment by PeiXiaoMeng** [comment]
@robinv8 你好，有时间可以看下 #1795 

样式仿照的react官网，
通过动态添加className的方式实现了一下暗夜模式，
对于md文档，通过动态添加和删除style样式表的方式改变color，
localstorage缓存 暗夜 / 高亮 状态到本地

**Comment by robinv8** [comment]
非常感谢你的代码贡献
