### ISSUE TITLE
AtSearchBar无法聚焦

### ISSUE THREAD

**Issue by pj110** [NervJS/taro-ui#1805]
**问题描述**
AtSearchBar点击无法聚焦，无法改变其中的值

```js
// 这里可以贴代码

import { useState } from 'react'
import { View,} from '@tarojs/components'
import {  AtSearchBar } from 'taro-ui'

const Index = () => {
    const [searchBarState, setSearchBarState] = useState('')

    return (
        <View className='index'>
            <AtSearchBar
              className='index-search-bar'
              actionName='搜一下'
              value={searchBarState}
              onChange={(val) => {setSearchBarState(val)}}
            />

        </View>
    )
}
export default Index
```

**期望行为**

**报错信息**

![image](https://github.com/NervJS/taro-ui/assets/48553074/bc6224fc-6cfd-4151-88c5-f19ff7dc6838)

**系统信息**

👽 Taro v3.6.32

  Taro CLI 3.6.32 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
      npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.32 => 3.6.32
      @tarojs/components: 3.6.32 => 3.6.32
      @tarojs/helper: 3.6.32 => 3.6.32
      @tarojs/plugin-framework-react: 3.6.32 => 3.6.32
      babel-preset-taro: 3.6.32 => 3.6.32
      eslint-config-taro: 3.6.32 => 3.6.32
      react: ^18.0.0 => 18.3.1
      taro-ui: ^3.2.1 => 3.3.0

报错平台weapp

**补充信息**

**Comment by robinv8** [comment]
先参考该 issue 排查下 https://github.com/NervJS/taro-ui/issues/1726

**Comment by pj110** [comment]
> 先参考该 issue 排查下 #1726

谢谢，找到解决方法了
`module.exports = {
  // ...
  framework: 'react',
- compiler: 'webpack5'
+ compiler: {
+   type: 'webpack5',
+    prebundle: {
+     exclude: ['taro-ui']
+    }
+  },
}`

**Comment by pj110** [comment]
感谢，找到解决方法了
