### ISSUE TITLE
AtRadio 微信小程序中 onClick 回调没有取到值

### ISSUE THREAD

**Issue by mengqingshen** [NervJS/taro-ui#182]
### 重现步骤
1. 使用 AtRadio 组件
2. 编译微信小程序
3. 在微信开发工具中运行

### 依赖的版本号

Node: v8.9.4
Taro: v1.1.3
Taro-UI: 1.4.0

### 预期结果
微信小程序中 onClick 的回调函数能收到参数

### 实际结果
微信小程序中 onClick 的回调函数不能收到参数

**Comment by mengqingshen** [comment]
![image](https://user-images.githubusercontent.com/27054472/48526469-bb641d00-e8c2-11e8-871f-44119e0a0202.png)
这里说有返回参数，在微信小程序中有问题，返回参数总是为 undefined

**Comment by jimczj** [comment]
麻烦升级下 taro，我这边用最新版的，表现正常

**Comment by jimczj** [comment]
@mengqingshen 升级后是否还有异常
