### ISSUE TITLE
AtModal上添加className属性无效

### ISSUE THREAD

**Issue by navigatorOpera** [NervJS/taro-ui#183]
#RT：
![image](https://user-images.githubusercontent.com/23136421/48527646-dc2e7180-e8c6-11e8-9dbf-6127faa61565.png)
页面效果：
![image](https://user-images.githubusercontent.com/23136421/48527671-ef414180-e8c6-11e8-9f79-3b1155512749.png)
只有class而没有className

### 依赖的版本号
 taro-ui@1.3.5

**Comment by jimczj** [comment]
请往下截图，节点信息应该作用在 shadow-root 下面的

**Comment by navigatorOpera** [comment]
抱歉一直在处理版本问题
![image](https://user-images.githubusercontent.com/23136421/48706754-2b163700-ec38-11e8-8356-90db65fd8d96.png)

**Comment by jimczj** [comment]
@navigatorOpera 
![image](https://user-images.githubusercontent.com/13499146/48706836-67499780-ec38-11e8-8708-abd5a20a275f.png)

要看下面的节点，明显就是有作用的

**Comment by Mrxkcai** [comment]
goood
