### ISSUE TITLE
缺少 Taro.atMessage d.ts 支持

### ISSUE THREAD

**Issue by tomgao365** [NervJS/taro-ui#184]
### 重现步骤
在 vscode 中没有 Taro.atMessage 方法的代码提示，缺少相关的 d.ts
### 依赖的版本号
 - 操作系统: [Windows 10]
 - Taro 版本 [v.1.1.7]
 - Taro UI 版本 [v.1.4.0]
 - Node.js 版本 [v8.12.0]

**Comment by langlangbody** [comment]
同上 模块  taro-ui@1.4.0...type/index没有导出的成员“AtMessage”

**Comment by tomgao365** [comment]
@jimczj 没啥影响，现在是技术调研，用Taro和 Taro UI 做些demo练手。正好昨天我尝试仿照 AtMessage 简单封装了 AtModal 和 AtToast。后来发现挂在Taro有些麻烦，最后分别定义了 modal 和 toast挂载相应的调用方法，想到一块儿去了。比如 modal.alert、modal.cofrim、toast.success、toast.error。然后传递参数支持字符串或对象。

**Comment by tomgao365** [comment]
@jimczj message最适合根据type改成 message.info，message.success，message.error，message.warning 调用

**Comment by jimczj** [comment]
这个用户可以自己再自行封装一层，多一个 api 不如少一个，而且 d.ts 又要多写，用户可以自己 bind 一下

**Comment by tomgao365** [comment]
@jimczj  也好，更自由

**Comment by zhanghongyublog** [comment]
想问一下，怎么封装成 modal.alert、modal.cofrim、toast.success、toast.error这种形式的，一直在尝试，没有找到合适的方法@tomgao365

**Comment by tomgao365** [comment]
@zhanghongyublog 参考官方 [message](https://github.com/NervJS/taro-ui/blob/dev/src/components/message/index.js) 源码
