### ISSUE TITLE
taro-ui 本地构建，作为外部模块，无法正确引入

### ISSUE THREAD

**Issue by harrydengchao** [NervJS/taro-ui#186]
### 重现步骤

- 初始化 taro app `$ taro init taro_app`
- 将 `https://github.com/NervJS/taro-ui.git` clone 下来，执行本地构建 `npm run build:component`，将生成的 `taro-ui/dist/` 拷贝到 `taro_app/` 项目下，重命名为 `taro_app/ui/`
- 在 `taro_app/src/pages/index/index.js` 文件内引入 `import { AtButton } from '../../../ui/taro-ui'`
- 前述页面中添加 `<AtButton>按钮</AtButton>` 

### 依赖的版本号

```bash
$ node -v
v8.12.0

$ taro -v
👽 Taro v1.1.7

taro-ui: 1.4.0
```

### 预期结果
执行 H5 和 微信小程序 构建，均能正确引入组件与样式

### 实际结果

-  *`问题一：`* 在 `taro_app` 下执行 `npm run dev:h5`，页面内未能引入样式
- *`问题二：`* 在`taro_app` 下执行 `npm run dev:weapp`，提示 `错误  组件错误  组件AtButton路径错误，请检查！（可能原因是导出的组件名不正确）
错误  页面编译  页面D:\project_local\taro_app\src\pages\index\index编译失败！`

### 补充问题

如何像 webpack那样设置全局的 `alias` 别名？ 
文档 https://nervjs.github.io/taro/docs/config-detail.html#h5alias 只是针对 H5 设置的

---

![image](https://user-images.githubusercontent.com/13941171/48549305-5f24eb80-e90a-11e8-9181-ceb9dc69fffb.png)

**Comment by harrydengchao** [comment]
@SzHeJason  感谢回复。 因为有样式的定制需求，所以，是计划做本地构建的。

**Comment by harrydengchao** [comment]
我留意到 [taro文档打包命令](https://nervjs.github.io/taro/docs/ui-lib.html#%E6%89%93%E5%8C%85%E5%91%BD%E4%BB%A4)里面有提到 *`通过入口文件就能在不同的端内进行引用`*，所以，理论上应该是OK的吧？
或是，我使用姿势不对吗

![image](https://user-images.githubusercontent.com/13941171/48555973-8cc76000-e91d-11e8-9f32-d3c3b16bfc1a.png)

**Comment by SzHeJason** [comment]
好的 近期会看一下

**Comment by SzHeJason** [comment]
Taro v1.1.7 的版本没跑起来 但是 1.0.3 是试过是正常的
