### ISSUE TITLE
taro + taro-ui 引入组件后，在 webstorm 中会 ts 抛错

### ISSUE THREAD

**Issue by zoux** [NervJS/taro-ui#189]
### 重现步骤
用webstorm会出现下图所示的 ts 抛错。

webstrom 版本信息如下：
------
WebStorm 2018.1.6
Build #WS-181.5540.11, built on July 26, 2018
Licensed to lan yu
Subscription is active until May 4, 2019
JRE: 1.8.0_152-release-1136-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14
------

![image](https://user-images.githubusercontent.com/24969960/48634822-7abeed80-ea01-11e8-81a4-ab54f111c5b2.png)

测试过用 vscode 打开则不会出现抛错。

### 依赖的版本号

Node 10.9.0
Taro 1.1.8
Taro-ui 1.4.0

### 预期结果
解决 ts 抛错

### 实际结果
出现如上述图示的 ts 抛错

### 相关链接
无

**Comment by cos2004** [comment]
用起来没问题吧？没用过webstorm

**Comment by zoux** [comment]
> 用起来没问题吧？没用过webstorm

不影响编译使用到小程序端，仅仅只是告警～

**Comment by zoux** [comment]
测试在 windows 上的 webstorm 不报错。

怀疑是自己的 macOS 端 webstorm 的问题。
