### ISSUE TITLE
npm install 安装后报错

### ISSUE THREAD

**Issue by themevan** [NervJS/taro-ui#19]
按照文档，初始化项目之后（启用Redux），再npm install taro-ui --save, 会报以下错误。 很抱歉，一直做UI设计，前端新手，不知道是不是我哪步漏掉了。 即便我继续按照提示，npm install nervjs --save, 同样的方式安装redux， 也一直还是报以下错误。

`npm WARN @tarojs/components@1.0.0-beta.18 requires a peer of nervjs@^1.2.16 but none is installed. You must install peer dependencies yourself.
npm WARN @tarojs/redux-h5@1.0.0-beta.18 requires a peer of nervjs@^1.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN @tarojs/redux-h5@1.0.0-beta.18 requires a peer of redux@^2.0.0 || ^3.0.0 || ^4.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN @tarojs/taro-h5@1.0.0-beta.18 requires a peer of nervjs@^1.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN @tarojs/taro@1.0.0-beta.18 requires a peer of nervjs@^1.2.17 but none is installed. You must install peer dependencies yourself.
npm WARN @tarojs/router@1.0.0-beta.18 requires a peer of nervjs@^1.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN @tarojs/taro-h5@1.0.0-beta.18 requires a peer of nervjs@^1.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN @tarojs/taro@1.0.0-beta.18 requires a peer of nervjs@^1.2.17 but none is installed. You must install peer dependencies yourself.
npm WARN @tarojs/taro@1.0.0-beta.18 requires a peer of nervjs@^1.2.17 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! path /Users/.....PROJECT..../node_modules/.bin/lessc
npm ERR! code EEXIST
npm ERR! Refusing to delete /Users/....PROJECT../node_modules/.bin/lessc: is outside /Users/...PROJECT.../node_modules/less and not a link
npm ERR! File exists: /Users/......PROJECT.../node_modules/.bin/lessc
npm ERR! Move it away, and try again.`

初始化项目时，我启用的是SASS, 不清楚为什么会有这个错误： npm ERR! path /Users/.....PROJECT..../node_modules/.bin/lessc

### 依赖的版本号
node v10.8.0
npm  v6.2.0

Debug日志在这里： https://www.dropbox.com/s/l7xmjoqsbout2z9/2018-08-28T08_35_30_600Z-debug.log.txt?dl=0

感谢！！

**Comment by SzHeJason** [comment]
@themevan 麻烦把 package.json贴一下

**Comment by themevan** [comment]
```
{
  "name": "dewShop",
  "version": "1.0.0",
  "private": true,
  "description": "ECommerce Mobile APP",
  "main": "index.js",
  "scripts": {
    "build:weapp": "taro build --type weapp",
    "build:h5": "taro build --type h5",
    "dev:weapp": "npm run build:weapp -- --watch",
    "dev:h5": "npm run build:h5 -- --watch",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@tarojs/async-await": "^1.0.0-beta.17",
    "@tarojs/components": "^1.0.0-beta.17",
    "@tarojs/redux": "^1.0.0-beta.17",
    "@tarojs/redux-h5": "^1.0.0-beta.17",
    "@tarojs/router": "^1.0.0-beta.17",
    "@tarojs/taro": "^1.0.0-beta.17",
    "@tarojs/taro-h5": "^1.0.0-beta.17",
    "@tarojs/taro-weapp": "^1.0.0-beta.17",
    "nervjs": "^1.3.0",
    "redux": "^4.0.0",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "@types/react": "^16.4.8",
    "@types/webpack-env": "^1.13.6",
    "@tarojs/cli": "^1.0.0-beta.17",
    "@tarojs/plugin-babel": "^1.0.0-beta.17",
    "@tarojs/plugin-csso": "^1.0.0-beta.17",
    "@tarojs/plugin-sass": "^1.0.0-beta.17",
    "@tarojs/plugin-uglifyjs": "^1.0.0-beta.17",
    "@tarojs/webpack-runner": "^1.0.0-beta.17",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-jsx-stylesheet": "^0.6.5",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-eslint": "^8.2.3",
    "eslint": "^4.19.1",
    "eslint-config-taro": "^1.0.0-beta.17",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-taro": "^1.0.0-beta.17"
  }
}
```

**Comment by jimczj** [comment]
请升级 taro 和 taro-cli 到 `1.0.0-beta.18` 版本

**Comment by themevan** [comment]
已解决，忘记排查Taro版本了，感谢！

**Comment by zhang14725804** [comment]
package.json文件如下

{
  "name": "taro-mini-h5",
  "version": "1.0.0",
  "private": true,
  "description": "taro-mini-h5",
  "scripts": {
    "build:weapp": "taro build --type weapp",
    "build:swan": "taro build --type swan",
    "build:alipay": "taro build --type alipay",
    "build:tt": "taro build --type tt",
    "build:h5": "taro build --type h5",
    "build:rn": "taro build --type rn",
    "dev:weapp": "npm run build:weapp -- --watch",
    "dev:swan": "npm run build:swan -- --watch",
    "dev:alipay": "npm run build:alipay -- --watch",
    "dev:tt": "npm run build:tt -- --watch",
    "dev:h5": "npm run build:h5 -- --watch",
    "dev:rn": "npm run build:rn -- --watch"
  },
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@tarojs/components": "1.2.12",
    "@tarojs/router": "1.2.12",
    "@tarojs/taro": "1.2.12",
    "@tarojs/taro-alipay": "1.2.12",
    "@tarojs/taro-h5": "1.2.12",
    "@tarojs/taro-swan": "1.2.12",
    "@tarojs/taro-tt": "1.2.12",
    "@tarojs/taro-weapp": "1.2.12",
    "nervjs": "^1.3.9",
    "nerv-devtools": "^1.3.9"
  },
  "devDependencies": {
    "@types/react": "^16.4.6",
    "@types/webpack-env": "^1.13.6",
    "@tarojs/plugin-babel": "1.2.12",
    "@tarojs/plugin-csso": "1.2.12",
    "@tarojs/plugin-sass": "1.2.12",
    "@tarojs/plugin-uglifyjs": "1.2.12",
    "@tarojs/webpack-runner": "1.2.12",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-jsx-stylesheet": "^0.6.5",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-eslint": "^8.2.3",
    "eslint": "^4.19.1",
    "eslint-config-taro": "1.2.12",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-taro": "1.2.12"
  }
}


报错 如下：：

26124 warn @webpack-contrib/schema-utils@1.0.0-beta.0 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
26125 warn webpack-dev-middleware@3.4.0 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
26126 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\_chokidar@2.1.1@chokidar\node_modules\fsevents):
26127 warn enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\1work\taro-mini-h5\node_modules\.staging\fsevents-86de4209\node_modules\abbrev' -> 'D:\1work\taro-mini-h5\node_modules\.staging\abbrev-fba25b6b'
26128 verbose enoent SKIPPING OPTIONAL DEPENDENCY: This is related to npm not being able to find a file.
26128 verbose enoent SKIPPING OPTIONAL DEPENDENCY:
26129 verbose stack Error: ENOENT: no such file or directory, rename 'D:\1work\taro-mini-h5\node_modules\_color-convert@1.9.3@color-convert\node_modules\color-name' -> 'D:\1work\taro-mini-h5\node_modules\_color-convert@1.9.3@color-convert\node_modules\color-name'
26130 verbose cwd D:\1work\taro-mini-h5
26131 verbose Windows_NT 10.0.14393
26132 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "taro-ui"
26133 verbose node v8.12.0
26134 verbose npm  v6.4.1
26135 error path D:\1work\taro-mini-h5\node_modules\_color-convert@1.9.3@color-convert\node_modules\color-name
26136 error code ENOENT
26137 error errno -4058
26138 error syscall rename
26139 error enoent ENOENT: no such file or directory, rename 'D:\1work\taro-mini-h5\node_modules\_color-convert@1.9.3@color-convert\node_modules\color-name' -> 'D:\1work\taro-mini-h5\node_modules\_color-convert@1.9.3@color-convert\node_modules\color-name'
26140 error enoent This is related to npm not being able to find a file.
26141 verbose exit [ -4058, true ]

**Comment by koppthe** [comment]
@zhang14725804  依赖没装好，重新安装试试，不行的话用 cnpm

**Comment by zhang14725804** [comment]
> @zhang14725804 依赖没装好，重新安装试试，不行的话用 cnpm

解决了居然，谢谢大佬
