### ISSUE TITLE
AtForm表单 上下边框怎么去掉？

### ISSUE THREAD

**Issue by dengxue0** [NervJS/taro-ui#191]
### 重现步骤
使用的AtForm顶部和底部边框怎么去掉？
AtInput底部的边框为什么我的显示的很长，顶头了？

### 依赖的版本号
Node 的版本：8.11.1
Taro 的版本：1.1.7
Taro-UI 的版本：1.4.0

### 预期结果
能够去掉AtForm 顶部底部的边框
AtInput底部边框怎么修改变短。

### 实际结果
![image](https://user-images.githubusercontent.com/21215992/48692754-29d21380-ec12-11e8-940f-7fa35718a768.png)

**Comment by EpplaLee** [comment]
.at-form::after {
  border: none;
}

**Comment by EpplaLee** [comment]
.at-form::after {
  border: none !important;
}
