### ISSUE TITLE
A PR for bind click event on AtActionSheet instead of every AtActionSheetItem

### ISSUE THREAD

**Issue by fonture** [NervJS/taro-ui#193]
- What will it allow you to do that you can't do today?
     We can bind click event on AtActionSheet instead of on every AtActionSheetItem element
  - How will it make current work-arounds straightforward?
     We can bind click event once, unnecessary bind for every AtActionSheetItem element
  - What potential bugs and edge cases does it help to avoid?
     AtActionSheetItem element will be a sub element as AtActionSheet's, we'll use like this:   
     `const AtActionSheetItem = AtActionSheet.AtActionSheetItem`

**Comment by jimczj** [comment]
`const AtActionSheetItem = AtActionSheet.AtActionSheetItem` 这种写法 Taro 不支持，原本就是这样写的，后来改了

**Comment by fonture** [comment]
> `const AtActionSheetItem = AtActionSheet.AtActionSheetItem` 这种写法 Taro 不支持，原本就是这样写的，后来改了

even so, I can upgrade click event bind on AtActionSheet instead of AtActionSheetItem, and keep constant for the usage of AtActionSheet and AtActionSheetItem, OK?

**Comment by SzHeJason** [comment]
对于你说的方案是可以支持的 甚至可以给与一个简单的调用方式  有兴趣可以提个PR吗？或者我们将在下次版本支持这个功能 你可以使用临时解决方案
```JSX
render() {
    const array = [{ title: "item_1" }, { title: "item_2" }]
    return (
      <AtActionSheet
        cancelText="取消"
        isOpened={isOpened1}
        onClose={this.handleClose.bind(this, 1)}
      >
        {array.map((item, key) => {
          return (
            <AtActionSheetItem
              key={key}
              onClick={this.handleClick.bind.bind(this, key)}
            >
              {item.title}
            </AtActionSheetItem>
          )
        })}
      </AtActionSheet>
    )
  }
```

**Comment by fonture** [comment]
> 对于你说的方案是可以支持的 甚至可以给与一个简单的调用方式 有兴趣可以提个PR吗？或者我们将在下次版本支持这个功能 你可以使用临时解决方案
> 
> ```js-jsx
> render() {
>     const array = [{ title: "item_1" }, { title: "item_2" }]
>     return (
>       <AtActionSheet
>         cancelText="取消"
>         isOpened={isOpened1}
>         onClose={this.handleClose.bind(this, 1)}
>       >
>         {array.map((item, key) => {
>           return (
>             <AtActionSheetItem
>               key={key}
>               onClick={this.handleClick.bind.bind(this, key)}
>             >
>               {item.title}
>             </AtActionSheetItem>
>           )
>         })}
>       </AtActionSheet>
>     )
>   }
> ```

I have create a PR for this proposal

**Comment by SzHeJason** [comment]
#194
