### ISSUE TITLE
小程序端复写样式时，每次预览效果都需要重新 npm run dev:weapp 才能渲染出效果 

### ISSUE THREAD

**Issue by zoux** [NervJS/taro-ui#196]
### 重现步骤
复写 taro-ui 的组件样式，引入项目中后，虽然 watch 中看到文件发生了改变，但是微信开发工具内预览不到当前复写的效果，而需要重新 npm run dev:weapp 才能渲染出当前效果。

**Comment by jimczj** [comment]
自己确定下有没有把 css import 进页面咯

**Comment by zoux** [comment]
一直有引入到app.tsx中app.scss下面一行。。

问题在于每次更改后自动编译的渲染效果没有更新，而重新 run build 编译的渲染效果才更新。。

**Comment by jimczj** [comment]
这个问题建议去 Taro 项目提 issue

**Comment by RianMan** [comment]
我和你一样 也是这个问题 坑真的多 无语了
