### ISSUE TITLE
Picker 文档少了多列实例

### ISSUE THREAD

**Issue by sm0king** [NervJS/taro-ui#197]
### 预期结果

希望有代码实例，虽然右边有展示，但却没有代码实例，好奇怪。

另外，Picker 的range 不支持 key，value的形式却有value 表示index，也好奇怪，key value的形式岂不是更好，而且select 本来就是key与value的形式。
 
嗯，同时，提个另外一个地方，AtListItem的extraText 等信息，可以支持下node 有switchIsCheck 等信息，支持下自定义node也挺好吧。

初识 taro ~ 冒犯之处多多包涵。

### 相关链接

https://taro-ui.aotu.io/#/docs/picker

**Comment by SzHeJason** [comment]
支持node？ 是只支持传入 jsx 语法吗？ 很遗憾 微信是不允许动态改变节点的 另外 实际上Picker 实际上是Taro 的基础组件 并包含在 TaroUI 里面 为什么value 形式 却表示成 index 实际上是微信的标准 我们做的就是把 h5 小程序化

**Comment by SzHeJason** [comment]
还有问题吗？ 没有的话今天我就关了这个issue咯

**Comment by sm0king** [comment]
@SzHeJason   非常感谢，没有问题了。
