### ISSUE TITLE
怎么使用组件按需引用

### ISSUE THREAD

**Issue by Herryjoeson** [NervJS/taro-ui#199]
现在taro项目中app.js已经把ui全部打包进去了,已经到达600K了

**Comment by koppthe** [comment]
目前打包成 H5 的版本还不支持按需引入，小程序版本是支持的。现在 taro 正在做 UI 组件构建的优化，会跟自定义主题的功能一起上线，预计下个月初可以支持。

**Comment by pollux2015** [comment]
期待期待!! 希望能按需引入以及能够有个 sass 文件之类的可以自定义

**Comment by koppthe** [comment]
@pollux2015 会有的

**Comment by koppthe** [comment]
可以试试 v2.0.0-beta.1 版本，使用方式有变更，具体可以看看文档
```bash
npm install taro-ui@next
```

**Comment by giscafer** [comment]
![tim 20190122183237](https://user-images.githubusercontent.com/8676711/51657052-2b3b0600-1fde-11e9-80e8-5c901f1b187c.png)

taro info
👽 Taro v1.2.8

```
  Taro CLI 1.2.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.4.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.9.4 - C:\Users\nickbing\AppData\Roaming\npm\yarn.CMD
      npm: 6.1.0 - C:\Program Files\nodejs\npm.CMD
```
什么姿势不对吗。全量可以，按需引入报错

**Comment by crixusshen** [comment]
> 现在taro项目中app.js已经把ui全部打包进去了,已经到达600K了

#1328
