### ISSUE TITLE
AtSwipeActionProps 缺少 onClick点击事件

### ISSUE THREAD

**Issue by yujiaming890321** [NervJS/taro-ui#200]
interface AtSwipeActionProps 缺少 onClick点击事件

![tim 20181123165657](https://user-images.githubusercontent.com/13047250/48935072-4a1b0e80-ef41-11e8-81a8-29b0451bf0a3.png)

![tim 20181123165734](https://user-images.githubusercontent.com/13047250/48935081-52734980-ef41-11e8-876e-53677a20c470.png)

### 依赖的版本号
Taro-UI : 1.4.0

**Comment by koppthe** [comment]
已补全，请升级到 v1.5.0 版本
