### ISSUE TITLE
AtTabs组件AtTabsPane在h5和小程序下无法进行滚动

### ISSUE THREAD

**Issue by Herryjoeson** [NervJS/taro-ui#201]
### 重现步骤
`<AtTabsPane current={tab} index={0}>
                        {
                            coupon_un_user.map((item, index) => {
                                return (
                                    <View className={'coupon-item default-bg'} key={index}>
                                        <View className={'coupon-left'}>
                                            <Text className={'font_16'}>￥</Text>
                                            <Text className={'font_30'}>20</Text>
                                        </View>
                                        <View className={'coupon-right'}>
                                            <Text>满 49 元可用</Text>
                                            <Text className={'font_10'}>10月08日 - 10月31日有效</Text>
                                        </View>
                                    </View>
                                )
                            })
                        }
   </AtTabsPane>`
### 依赖的版本号

node v9.2.0
taro 1.1.9
ui 1.4.0

**Comment by koppthe** [comment]
无法滚动是指，AtTabsPane 里面的内容，还是指 Tabs 的选项无法滚动？

**Comment by Herryjoeson** [comment]
里面的内容无法活动，加了scrollview也不行

**Comment by Herryjoeson** [comment]
我又重新copy例子代码。在tabpane加入scrollview通过循环例子的view一样不能再h5 小程序中进行上下滚动

**Comment by jimczj** [comment]
@Herryjoeson 只在h5中有问题？

**Comment by Herryjoeson** [comment]
小程序 h5都不行

**Comment by Herryjoeson** [comment]
@jimczj @koppthe  大佬们。这个需要怎么解决

**Comment by jimczj** [comment]
@Herryjoeson 自己在 Tab 页面外面试怎么用scrollView，外面能滚动，放到里面照样能滚动

**Comment by jimczj** [comment]
试过了，可以滚动
![image](https://user-images.githubusercontent.com/13499146/49265350-b4293b80-f48c-11e8-84d2-3985ab5fef44.png)

**Comment by Herryjoeson** [comment]
如果外部不用scrollview内部使用了scrollview不设置他的height是更本无法滚动

**Comment by Herryjoeson** [comment]
@jimczj 
![image](https://user-images.githubusercontent.com/19682746/49302139-2cc9df80-f501-11e8-9a00-b81f01314315.png)
没有这个style属性内部就无法滚动了。并且就算设置是不可能写死的把。
如果要让他滚动起来就需要在最外层加scrollview,并且需要重写样式才能做到tab固定头部

**Comment by jimczj** [comment]
scrollView 本来就是需要定高的，你可以写 `height:100vh`

**Comment by zhang452064326** [comment]
内容滚动还是没法实现呢
