### ISSUE TITLE
在使用自定义icon时，开发工具能够出现图标，但是在手机预览的时候并不能出现，是什么原因？用的外部图标库是fontawesome

### ISSUE THREAD

**Issue by luojionghuang** [NervJS/taro-ui#202]
![image](https://user-images.githubusercontent.com/19617333/48991236-0e648c80-f16d-11e8-936d-7d50095675b3.png)
icon.less内容：
![image](https://user-images.githubusercontent.com/19617333/48991261-289e6a80-f16d-11e8-96fa-e30088062ab9.png)

**Comment by jimczj** [comment]
是否有导入样式到 app.tsx

**Comment by luojionghuang** [comment]
有导入到app.tsx

**Comment by luojionghuang** [comment]
在开发工具上能够正常显示，但是在手机上不能

**Comment by jethroHuang** [comment]
我也遇到了这个情况，在开发工具上能显示，手机上就显示一个X这样的未知符号。我试过本地引用和网络引用，都是只能在开发工具上显示

**Comment by jethroHuang** [comment]
> > 我也遇到了这个情况，在开发工具上能显示，手机上就显示一个X这样的未知符号。我试过本地引用和网络引用，都是只能在开发工具上显示
> 
> 那你最后是怎么处理的？

我放弃了，最后用png显示图标

**Comment by SzHeJason** [comment]
@jethroHuang @luojionghuang 研究了一下 需要把 font awesome 变成base64 格式

https://transfonter.org/

![image](https://user-images.githubusercontent.com/20609396/49625420-6a9e9a80-fa10-11e8-961e-fb08adddefba.png)

获取到转码之后的文件 合并成文件夹  放在 assets 目录下

把 stylesheet 的内容复制到 app.scss 里面，这样字体就加载成功了

参考 https://blog.csdn.net/qq_28988969/article/details/76633921

**Comment by SzHeJason** [comment]
https://github.com/NervJS/taro-ui-demo 该库新增了 FontAwesome 的使用案例
