### ISSUE TITLE
希望AtInputNumber H5 弹出数字键盘

### ISSUE THREAD

**Issue by GaoYuJian** [NervJS/taro-ui#203]
### 重现步骤
AtInputNumber 弹出默认键盘没有弹出数字键盘
### 依赖的版本号
node: 8.11.1
Taro: 1.1.8
Taro-UI: 1.1.4

### 预期结果
AtInputNumber 输入框弹出数字键盘
### 实际结果
弹出默认键盘

**Comment by jimczj** [comment]
AtInputNumber 需要输入小数，在 h5 没有对应数字键盘

**Comment by GaoYuJian** [comment]
能否吧input组件的props暴露出来

**Comment by jimczj** [comment]
可以考虑一下

**Comment by jimczj** [comment]
已增加 input type props，等待发版本，默认使用 number 类型，小数类型不支持数字输入框
