### ISSUE TITLE
Message 组件的一个 bug

### ISSUE THREAD

**Issue by jswxwxf** [NervJS/taro-ui#204]
### 重现步骤
如果多个页里有 AtMessage 组件，那么只要其中一个页面销毁了，那之前页面的 AtMessage 组件再也不会接收消息了，因为在 AtMessage 组件的 componentWillUnmount 里移除了全局监听。

```
  componentDidMount () {
    Taro.eventCenter.on('atMessage', (options = {}) => {
      options.isOpened = true
      this.setState(options)
      clearTimeout(this._timer)
      this._timer = setTimeout(() => {
        this.setState({
          isOpened: false
        })
      }, this.state.duration)
    })
    // 给 Taro 绑定全局消息事件
    Taro.atMessage = Taro.eventCenter.trigger.bind(Taro.eventCenter, 'atMessage')
  }

  componentWillUnmount () {
    Taro.eventCenter.off('atMessage')
  }
```

### 依赖的版本号

node v10.12.0
taro v1.1.9
taro-ui v1.4.0

**Comment by jimczj** [comment]
页面都销毁了，原来页面的 AtMessage 当然也不应该继续监听。应该在新的页面里面重新使用AtMessage，凡是用到的页面都需要在 render 函数使用 AtMessage

**Comment by jswxwxf** [comment]
我说的是历史页面啊，小程序又不是只有一个页面……

**Comment by jimczj** [comment]
那重新进入页面的时候，不会重新 componentDidMount 吗

**Comment by jswxwxf** [comment]
比如现在 有 Page1 上用了 AtMessage，点击某个按钮进入 Page2，Page2 里也用了 AtMessage，然后从 Page2 里返回 Page1，这时候因为 Page2 销毁了，所以 Page1 里的 AtMessage 也不工作了？

**Comment by jswxwxf** [comment]
当然不会啊， Page1 又没有销毁

**Comment by jimczj** [comment]
问题应该是在 componentDidShow 的时候需要重新绑定下监听事件，已修复

**Comment by jswxwxf** [comment]
额？是要我在自己的代码里重新绑定一下吗？

**Comment by jimczj** [comment]
不需要，Taro UI 发个包，继续按文档那样使用

**Comment by jswxwxf** [comment]
ok。谢谢

**Comment by xingwanyue** [comment]
1.5.2 版本依然有这个问题

依赖的版本号
node v10.13.0
taro v1.2.0-beta.3
taro-ui v1.5.2
