### ISSUE TITLE
AtTabBar 存在问题，苹果手机上出现点击不到问题

### ISSUE THREAD

**Issue by rainbowMorelhahahah** [NervJS/taro-ui#209]
Cannot read property 'offsetLeft' of undefined;[Exparser] [Error] [Component] Event Listener Error @ wx-view#(anonymous)
TypeError: Cannot read property 'offsetLeft' of undefined

**Comment by jimczj** [comment]
请展示代码与版本号

**Comment by koppthe** [comment]
@rainbowMorelhahahah  麻烦提供一下 taro, taro-ui 的版本号

**Comment by rainbowMorelhahahah** [comment]
> @rainbowMorelhahahah 麻烦提供一下 taro, taro-ui 的版本号

没事了 最新版 的 已经修复了

**Comment by rainbowMorelhahahah** [comment]
> 请展示代码与版本号

![image](https://user-images.githubusercontent.com/11493796/49640844-85d9cc00-fa49-11e8-86e2-d0a91d160de9.png)

**Comment by rainbowMorelhahahah** [comment]
> 请展示代码与版本号

没事了 最新版 的 已经修复了
