### ISSUE TITLE
【小程序】操作反馈-Toast轻提示，点击添加遮罩层后，其他的都点击不了

### ISSUE THREAD

**Issue by cfengdev** [NervJS/taro-ui#21]
进入 操作反馈-Toast轻提示，点击添加遮罩层Toast后，其他按钮都点击不了

**Comment by SzHeJason** [comment]
是否添加了 hasMask 属性

**Comment by cfengdev** [comment]
是扫描官方小程序二维码体验时发现的问题

**Comment by SzHeJason** [comment]
是的 目前官方的体验版上是前3个Button 的 Toast 不存在 `hasMask` 属性

**Comment by SzHeJason** [comment]
另外点击没反应 是因为 taro@beat-17版本之后的 `componentWillReceiveProps` 异常

**Comment by SzHeJason** [comment]
@cfengdev  目前Taro的小程序官方案例已经发布了修复版本, Taro-UI的新版本也会在今天发布
