### ISSUE TITLE
看更新计划里面有提到什么时候支持RN，那现在支持RN了吗？已经？

### ISSUE THREAD

**Issue by dxhuii** [NervJS/taro-ui#212]
看更新计划里面有提到什么时候支持RN，那现在支持RN了吗？已经？

**Comment by koppthe** [comment]
暂时还不支持，RN 的支持还没有排期，目前优先级更高的是自定义主题和百度、支付宝小程序适配的工作哦

**Comment by kenberkeley** [comment]
https://github.com/NervJS/taro-ui/issues/92

**Comment by dxhuii** [comment]
> #92

这个我看到了，那个时候还没有发1.4，1.5，我看了发了1.4，1.5，然后突然说去支持，支付宝和百度小程序，

我以为他们先适配的RN，后适配的支付宝百度这些小程序，以为是按顺序支持的，所来跑过来问一下。

**Comment by SzHeJason** [comment]
duplicate #92
