### ISSUE TITLE
AtInput真机调试中，删除input值的时候onChange获取value异常

### ISSUE THREAD

**Issue by xiazhangli** [NervJS/taro-ui#215]
### 重现步骤

使用AtInput组件的时候，输入   _**123456789**_，将光标定位至中间位置（假设定位在4后面）开始删除前面的数字，当   _**1234**_   都被删除后继续按删除键时，onChange获得的value值为   _**空**_   而不是   _**56789**_  。

**这个bug只在真机调试时会出现，微信开发工具当中调试则是正常的。**

### 依赖的版本号

Node: v8.12.0
Taro: 1.2.0-beta.2
Taro-UI: 1.4.0

### 预期结果
onChange获取value：56789

### 实际结果
onChange获取value：‘’

**Comment by jimczj** [comment]
这边调试正常，你是什么型号的手机，代码展示一下

**Comment by jimczj** [comment]
可是试一下 taro-ui 官方小程序，看看是否有此问题

**Comment by xiazhangli** [comment]
@jimczj ，你好。

以下是我调试官方小程序的结果，问题依然存在，就在handleInput增加console.log，使用真机调试从中间删除值就可以复现（我使用的手机是华为mate8）：
![502880715882624212](https://user-images.githubusercontent.com/8136395/49374565-b44f6280-f73c-11e8-916b-065e97cba516.png)
![inputbug](https://user-images.githubusercontent.com/8136395/49374567-b87b8000-f73c-11e8-9fe2-5bdbf507bf10.png)

如图，不断按删除键，输入框的值依然存在，但是handleInput获取的value值为空！

**Comment by jimczj** [comment]
这个问题应该是微信小程序 input 组件的问题，这个兼容性问题我们这里没办法解决，建议你反馈到微信小程序社区，你试一下原生 input，应该有一样的问题。我这边试了两个华为机型，复现不了

**Comment by xiazhangli** [comment]
@jimczj 谢谢回答，是微信版本的兼容性问题。
