### ISSUE TITLE
AtTabs、AtTabsPane内容放置Picker组件，不基于底部弹出

### ISSUE THREAD

**Issue by vipway** [NervJS/taro-ui#218]
![image](https://user-images.githubusercontent.com/38094234/49335839-a8767a00-f630-11e8-9f13-f397f259bdd7.png)

版本：1.4.0

**Comment by jimczj** [comment]
展示效果是 h5 还是小程序？

**Comment by SzHeJason** [comment]
不要把 position: fix 的组件放在 含有 transform  属性的容器里 
详情 : #174

**Comment by jimczj** [comment]
而且 picker 也没必要放置在 AtTabs、AtTabsPane 里面，放置在页面根节点下面行了

**Comment by damaohub** [comment]
> 而且 picker 也没必要放置在 AtTabs、AtTabsPane 里面，放置在页面根节点下面行了

什么意思，可以通过元素click事件来打开picker选择框吗？
