### ISSUE TITLE
Taro 开启CSS Modules 时taro-ui组件样式出错

### ISSUE THREAD

**Issue by GaoYuJian** [NervJS/taro-ui#219]
### 重现步骤
taro 开启CSS Modules taro-ui组件样式出错

### 依赖的版本号

Node: v8.11.1
Taro: 1.2.0.1.2.0-beta.4
Taro-UI: 1.5.0-beta.5 
weapp
### 预期结果
样式正确
### 实际结果
样式错误

**Comment by yinlsea** [comment]
发现同样问题，求解决

**Comment by felix9ia** [comment]
问过群里了，说是确实有影响。官方正在处理

**Comment by StingKo** [comment]
更新taro到1.2.0及以上版本
config里添加

> cssModules: {  
enable: true, 
          config: {
            **namingPattern: 'module',** // 转换模式，取值为 global/module
            generateScopedName: '[name]__[local]___[hash:base64:5]'
          }
}

[https://github.com/NervJS/taro/pull/1456](url)

**Comment by koppthe** [comment]
@StingKo  请问是配置这个之后就正常了？

**Comment by StingKo** [comment]
> @StingKo 请问是配置这个之后就正常了？

是的，原先的CSS Modules配置默认转换所有样式文件包括taro-ui，而taro-ui内的样式文件并未按照CSS Modules规范，导致组件样式出错，开启namingPattern: 'module'后仅转换后缀为module.[css|scss|less|styl]的样式文件。

**Comment by Garfield550** [comment]
Taro 1.3.19
Taro UI 2.2.2

H5 和 Weapp 下测试正常。
