### ISSUE TITLE
AtAccordion增加属性subtitle

### ISSUE THREAD

**Issue by tourze** [NervJS/taro-ui#220]
希望有个subtitle的属性可以让这个组件呈现的内容更丰富。

其实如果title支持传入element的话，这个问题估计就不存在。。。但是可能小程序支持会有问题？

**Comment by jimczj** [comment]
现在 Taro 出了新特性，可尝试看看支持传入 jsx

**Comment by tourze** [comment]
https://nervjs.github.io/taro/docs/children.html#%E7%BB%84%E5%90%88  应该是这个特性吧。感觉这个挺棒的。taro-ui如果大部分组件能使用上的话，很多个性化组件就能自由定制啦

**Comment by AwesomeDevin** [comment]
处理中
