### ISSUE TITLE
觉得组件尺寸偏大，能否支持统一配置尺寸？

### ISSUE THREAD

**Issue by kennylbj** [NervJS/taro-ui#221]
```泰罗```确实是最用心的小程序框架，但是最近在用```taro-ui```的时候，感觉组件尺寸有点偏大，比如对比有赞的[vant-weapp](https://github.com/youzan/vant-weapp)或者iViewUI可以明显感觉到偏大。

示例：
taro-ui:
<img src="https://user-images.githubusercontent.com/6435874/49482339-b3681f00-f869-11e8-9a0c-e8a72d775fc1.jpeg" alt="taro" width="300"/>

vant:
<img src="https://user-images.githubusercontent.com/6435874/49482344-b9f69680-f869-11e8-8bcc-df1a93237345.jpeg" alt="vant" width="300"/>

iview:
<img src="https://user-images.githubusercontent.com/6435874/49482349-bebb4a80-f869-11e8-9f4c-cccbf97139d6.jpeg" alt="vant" width="300"/>

taro-ui能不能提供一个统一的组件大小配置入口，否则的话对每一个组件都改动大小，会显得比较麻烦。

thx

**Comment by SzHeJason** [comment]
其实就是自定义主题的功能 目前还在适配中
