### ISSUE TITLE
引入taro-ui 然后在run dev:h5 就报错了, 是不是差什么包? v1.5

### ISSUE THREAD

**Issue by pollux2015** [NervJS/taro-ui#223]
![image](https://user-images.githubusercontent.com/11935278/49561612-1d102800-f953-11e8-9c51-f7c8c3e5e842.png)
![image](https://user-images.githubusercontent.com/11935278/49561721-9ad43380-f953-11e8-9a84-872168703afc.png)
![image](https://user-images.githubusercontent.com/11935278/49561735-a6bff580-f953-11e8-9234-1e8a231aef98.png)

### 依赖的版本号

Node: v10.13.0
Taro: v1.2.0-beta.9
Taro-UI: v1.5.1

**Comment by pollux2015** [comment]
![image](https://user-images.githubusercontent.com/11935278/49561936-6319bb80-f954-11e8-9544-33c17473e329.png)
![image](https://user-images.githubusercontent.com/11935278/49561944-68770600-f954-11e8-8eed-57fae634a401.png)

**Comment by koppthe** [comment]
v1.5.1 版本的 taro h5 有点问题，taro 还在解决，麻烦先将 taro-ui 降级回 v.1.5.0 版本使用。

**Comment by pollux2015** [comment]
好的

**Comment by pollux2015** [comment]
1.5也有问题

**Comment by pollux2015** [comment]
先退到1.3去了  等解决了再更新

**Comment by koppthe** [comment]
@pollux2015 你把 node_modules 删了，重新装回 v1.5.0 还会有问题吗？

**Comment by prettydog** [comment]
降到1.3了，还是报错

**Comment by SzHeJason** [comment]
试试 1.5.0 + taro@1.2.0-beta-10

**Comment by SzHeJason** [comment]
> 降到1.3了，还是报错

你的报错也是一样的吗

**Comment by prettydog** [comment]
> > 降到1.3了，还是报错
> 
> 你的报错也是一样的吗

是的

**Comment by koppthe** [comment]
@prettydog  你的 package.json 贴一下

**Comment by prettydog** [comment]
> @prettydog 你的 package.json 贴一下
抱歉。今天没带自己的电脑。项目在自己的笔记本上

**Comment by prettydog** [comment]
> > @prettydog 你的 package.json 贴一下
> > 抱歉。今天没带自己的电脑。项目在自己的笔记本上

https://github.com/NervJS/taro-ui-demo 这个项目clone下来，就启动有问题Module not found: Can't resolve 'taro-ui/dist/h5/css/index.css' in

**Comment by koppthe** [comment]
@prettydog  那是因为这个项目的 `package.json` 里面写的是
```
"taro-ui": "^1.5.0"
```

这么写还是装的 v1.5.1，所以才需要你贴一下 package.json，你得改成

```
"taro-ui": "1.5.0"
```

**Comment by koppthe** [comment]
麻烦升级到 v1.5.2 版本，问题已修复

**Comment by giscafer** [comment]
@koppthe 2.0.2有这个问题

监听文件修改中...

�   Failed to compile.

./.temp/components/FMLActionSheet/ShareTemplate.js
Module not found: Can't resolve 'taro-ui/dist/h5/css/index.css' in 'E:\gitlab\family-weapp\.temp\components\FMLActionSheet'

```
"dependencies": {
		"@tarojs/async-await": "1.2.22",
		"@tarojs/components": "1.2.22",
		"@tarojs/mobx": "^1.2.22",
		"@tarojs/mobx-h5": "^1.2.22",
		"@tarojs/mobx-rn": "^1.2.22",
		"@tarojs/rn-runner": "1.2.22",
		"@tarojs/router": "1.2.22",
		"@tarojs/taro": "1.2.22",
		"@tarojs/taro-alipay": "1.2.22",
		"@tarojs/taro-h5": "1.2.22",
		"@tarojs/taro-swan": "1.2.22",
		"@tarojs/taro-weapp": "1.2.22",
		"crypto-js": "^3.1.9-1",
		"fs-extra": "^7.0.1",
		"mobx": "^5.9.4",
		"nervjs": "^1.3.13",
		"prop-types": "^15.7.2",
		"taro-ui": "^2.0.2"
	},
```

**Comment by koppthe** [comment]
@giscafer 麻烦重新看一下「快速上手」的文档，样式引用的路径变了，你用的是 1.x 版本的写法
