### ISSUE TITLE
安装taro-ui报错一直报错，无法npm run dev:weapp

### ISSUE THREAD

**Issue by wananshine** [NervJS/taro-ui#230]
![image](https://user-images.githubusercontent.com/17999631/49643889-de14cc00-fa51-11e8-91d1-1ff7e943c50c.png)

一直出现这个错，每次重新安装都是

**Comment by SzHeJason** [comment]
这不是 babel-core 没装吗？ 出错自带库版本 我们好跟踪 

你可以试一下 删除 node_modules 在重新装一下 没翻墙的建议用 cnpm
