### ISSUE TITLE
文本域限制200长度，却只能输入140长度

### ISSUE THREAD

**Issue by JokerLoLgrey** [NervJS/taro-ui#231]
### 重现步骤
![image](https://user-images.githubusercontent.com/33446705/49664859-0cb09800-fa8e-11e8-98ae-479c9b91410a.png)

![image](https://user-images.githubusercontent.com/33446705/49664998-79c42d80-fa8e-11e8-8683-3250a742f38a.png)

### 预期结果
限制长度为多少可输入多少长度字符
### 实际结果
限制长度200却只能输入140长度

**Comment by SzHeJason** [comment]
@jimczj j
