### ISSUE TITLE
如何修改AtListItem下switch的背景颜色？

### ISSUE THREAD

**Issue by Geocld** [NervJS/taro-ui#235]
AtListItem没法把color传到内部的switch，看了下源码color是在AtListItem写死的，能否在AtListItem开放switch的color？

**Comment by liangyuanpeng** [comment]
我也想问类似的问题，希望修改``AtCheckbox``复选框``label``值的颜色

**Comment by liangyuanpeng** [comment]
@SzHeJason  请问这个可以怎么做

**Comment by SzHeJason** [comment]
@jimczj

**Comment by jimczj** [comment]
@liangyuanpeng 自行审查元素修改咯
