### ISSUE TITLE
原生的tabBar 是多个 page  公用一个，而AtTabBar 只能是一个爬个一个AtTabBar？

### ISSUE THREAD

**Issue by JoMartinezZhu** [NervJS/taro-ui#238]
原生的tabBar 是多个 page  公用一个，而AtTabBar 只能是一个爬个一个AtTabBar，那么 推荐 那种使用方式 ，是使用 原生的 还是 AtTabBar,AtTabBar是每个page 加载一个？

node：10.14.1，
Taro:1.2.0-beta.7
  taro-ui: ^1.5.1

**Comment by jimczj** [comment]
看自己的需求

**Comment by SzHeJason** [comment]
一般情况下 原生是比较好的，因为每个 `tab` 就是一个 `page` 把不同的需求放在不同的  `page` 这样方便维护，但是还是楼上的那句话 __看自己的需求__  这个 `issue` 我关咯 如果有啥问题的话 可以留言

**Comment by hick** [comment]
好像现在实际情况, 每个 page 一个 AtTabBar 会导致切换 tab 的时候 tabbar 可能闪一下?    是看不同机型的渲染不一样大家不会遇到么?   有时候比较明显感觉比较别扭

**Comment by seymoe** [comment]
@hick +1
