### ISSUE TITLE
npm run dev:h5编译报错

### ISSUE THREAD

**Issue by w280561543** [NervJS/taro-ui#239]
yarn run v1.12.3
$ npm run build:h5 -- --watch

> app_v2@1.0.0 build:h5 f:\git\job\doias\app_v2
> taro build --type h5 "--watch"

👽 Taro v1.2.0-beta.12

开始编译项目 app_v2
创建  发现文件  src\app.js
创建  发现文件  src\app.scss
创建  发现文件  src\index.html
创建  发现文件  src\actions\counter.js
创建  发现文件  src\constants\counter.js
创建  发现文件  src\reducers\counter.js
创建  发现文件  src\reducers\index.js
创建  发现文件  src\store\index.js
创建  发现文件  src\pages\index\index.js
创建  发现文件  src\pages\index\index.scss
创建  发现文件  src\components\common\TabBar\index.js
创建  发现文件  src\modules\mch\index\index.js
创建  发现文件  src\modules\order\index\index.js
创建  发现文件  src\pages\cart\index\index.js
创建  发现文件  src\pages\goods\find-all\index.js
创建  发现文件  src\pages\goods\find-one\index.js
创建  发现文件  src\pages\user\index\index.js

✅  Compiled successfully!

修改  文件变动  src\components\common\TabBar\index.js
🙅   Failed to compile.

./node_modules/taro-ui/dist/h5/components/pagination/index.js 101:11
Module parse failed: Unexpected token (101:11)
You may need an appropriate loader to handle this file type.
|     };
|
>     return <View className={classNames(rootClassName, classObject, this.props.className)} style={customStyle}>
|         <View className="at-pagination__operate">
|           <View className="at-pagination__btns">

**Comment by fatjiong** [comment]
我这边出现了同样的问题，只是我没有嵌入到项目，直接拿taro的demo来引入taro-ui，然后编译运行的时候报错。
环境：
```
Windows 10 x64
Node v11.2.0
npm 6.4.1
Taro v1.2.0-beta.11
```
执行:
```
npm run dev:h5
```
报错:
```
> goblog-app@1.0.0 dev:h5 E:\www\goblog-app
> npm run build:h5 -- --watch


> goblog-app@1.0.0 build:h5 E:\www\goblog-app
> taro build --type h5 "--watch"

👽 Taro v1.2.0-beta.11

开始编译项目 goblog-app
创建  发现文件  src\app.scss
创建  发现文件  src\app.tsx
创建  发现文件  src\index.html
创建  发现文件  src\pages\index\index.scss
创建  发现文件  src\pages\index\index.tsx

./node_modules/taro-ui/dist/h5/components/pagination/index.js 101:11
Module parse failed: Unexpected token (101:11)
You may need an appropriate loader to handle this file type.
|     };
|
>     return <View className={classNames(rootClassName, classObject, this.props.className)} style={customStyle}>
|         <View className="at-pagination__operate">
|           <View className="at-pagination__btns">
```
### 注: npm run dev:weapp正常

**Comment by SeptemberMaples** [comment]
同样的问题。

**Comment by vickymmf** [comment]
同样的问题

**Comment by fengchunsgit** [comment]
> ```
> Windows 10 x64
> Node v8.12.0
> Npm: v6.1.0
> Taro v1.2.0-beta.15
> ```
> 同样的问题

"taro-ui": "^1.5.1"

**Comment by koppthe** [comment]
刚好在发版本，待会再更新到 1.5.2 吧

**Comment by fengchunsgit** [comment]
> 刚好在发版本，待会再更新到 1.5.2 吧

thanks

**Comment by koppthe** [comment]
v1.5.2 版本已发布，麻烦升级到最新版

**Comment by kricsleo** [comment]
我现在用的是最新的2.0.2版本，编译成微信小程序是好的，编译成H5还是一直在报这个错

**Comment by geekape** [comment]
> 我现在用的是最新的2.0.2版本，编译成微信小程序是好的，编译成H5还是一直在报这个错

我也是一样的，最新版本
