### ISSUE TITLE
升级taro为v1.12.0-beta.13 taro-ui报错

### ISSUE THREAD

**Issue by LGpan** [NervJS/taro-ui#240]
### 重现步骤
升级taro最新后taro-ui路径报错
### 错误信息
![_15445121264119](https://user-images.githubusercontent.com/23379926/49783979-bcb82680-fd56-11e8-822f-b086f83213ac.png)

**Comment by Yeyc** [comment]
beta.13有问题可以先改回beta.12 
cnpm i -g @tarojs/cli@1.2.0-beta.12

**Comment by feong** [comment]
有相同的问题，新建的一个项目，依赖如下：
  "dependencies": {
    "@tarojs/components": "^1.2.0-beta.13",
    "@tarojs/router": "^1.2.0-beta.13",
    "@tarojs/taro": "^1.2.0-beta.13",
    "@tarojs/taro-alipay": "^1.2.0-beta.13",
    "@tarojs/taro-h5": "^1.2.0-beta.13",
    "@tarojs/taro-swan": "^1.2.0-beta.13",
    "@tarojs/taro-tt": "^1.2.0-beta.13",
    "@tarojs/taro-weapp": "^1.2.0-beta.13",
    "jssha": "^2.3.1",
    "nerv-devtools": "^1.3.9",
    "nervjs": "^1.3.9",
    "taro-ui": "^1.5.1"
  },

**Comment by SzHeJason** [comment]
把 taro-ui 的版本 锁死在 1.5.0 , 最近 Taro 在支持自定义主题 所有有点问题

**Comment by LGpan** [comment]
npm install -g @tarojs/cli@1.2.0-beta.7                  将taro降级到beta.7就可以了.........

**Comment by feong** [comment]
> npm install -g @tarojs/cli@1.2.0-beta.7 将taro降级到beta.7就可以了.........

或者把/dist/npm文件夹手动拷贝到/src/npm下边～因为/src/npm下面真的没有那个库

**Comment by koppthe** [comment]
已修复，麻烦升级到 v1.5.2 版本
