### ISSUE TITLE
表单 如何进行数据绑定？

### ISSUE THREAD

**Issue by youzipi** [NervJS/taro-ui#241]
Taro 的文档里面是用 taro 的组件 ，form 提交的时候可以带出表单的全部信息。
taro-ui 的 form 组件没有办法做到这一点。
taro-ui 和 taro 的这个issue 回复也给出了原因
https://github.com/NervJS/taro/issues/1264#issuecomment-441987851
想问下大家，如果表单项很多的话，有什么好的办法能够进行双向数据绑定，或者别的便捷的方案？

~~目前只想到 在每个表单项的 onchange 回调里面带上 form item name。~~
看到了  `declare type InputFunction = (value: string | number, event: BaseEvent) => void`，
回调的 第二个参数 event 里面可以取到 target 的 name，也就是 `form item name`.

之前开发vue 比较多，不知道 react 这边 大表单的数据监听绑定是怎么做的。
搜到了 `LinkedStateMixin ` 这个东西，但是已经废弃，官方不建议继续使用。

**Comment by jimczj** [comment]
使用 Taro-mobx
