### ISSUE TITLE
倒计时组件：切换页面后，倒计时器还在走!

### ISSUE THREAD

**Issue by cmideal** [NervJS/taro-ui#242]
### 依赖的版本号
ui 1.5.0

### 预期结果
倒计时组件在切换页面之后组件还在走
### 实际结果
切换页面后不要走了，性能影响

**Comment by jimczj** [comment]
已修复，增加了 `componentDidHide` 和 `componentDidShow` 这两个生命周期的处理，`componentDidHide` taro 有点问题，需等待 Taro `1.2.0-beta.15` 发版本才能正常使用
