### ISSUE TITLE
文档错误

### ISSUE THREAD

**Issue by jinxin0112** [NervJS/taro-ui#243]
taro-ui 文档中，  “Flex 弹性布局” 部分使用指南中的：
`if (process.env.TARO_ENV === "weapp") {
  require("taro-ui/dist/weapp/css/index.css")
} else if (process.env.TARO_ENV === "h5") {
  require("taro-ui/dist/h5/css/index.css")
}` 
在新版的taro-ui 中报错（找不到对应模块）。。。实际上 新版taro-ui 的目录层级都已变更。
希望更快修改这部分的说明， 以免对使用者造成误导

**Comment by koppthe** [comment]
感谢反馈，明天会更新一下文档

**Comment by kakaoG** [comment]
![image](https://user-images.githubusercontent.com/12584373/49850670-59db9380-fe19-11e8-976a-023ad9f6eee4.png)
![image](https://user-images.githubusercontent.com/12584373/49850697-6e1f9080-fe19-11e8-817c-c30d9c04b1fa.png)
现在这样引用， 文件找不到

**Comment by koppthe** [comment]
麻烦升级到 v1.5.2 版本，代码结构已恢复成以前的版本了
