### ISSUE TITLE
AtGrid内部各元素的onClick 事件如何相应啊，各种taro-ui组件的事件响应能不能给个小例子

### ISSUE THREAD

**Issue by EthanCui** [NervJS/taro-ui#247]
AtGrid内部各元素的onClick 事件如何相应啊，各种taro-ui组件的事件响应能不能给个小例子

**Comment by SzHeJason** [comment]
`AtGrid` 内部的内容会通过 click 的参数传递 
![image](https://user-images.githubusercontent.com/20609396/49862900-1c3b3280-fe3a-11e8-97bd-9276d7493cb4.png)
如果对事件参数有疑惑的建议看 d.ts 文件

**Comment by EthanCui** [comment]
> `AtGrid` 内部的内容会通过 click 的参数传递
> ![image](https://user-images.githubusercontent.com/20609396/49862900-1c3b3280-fe3a-11e8-97bd-9276d7493cb4.png)
> 如果对事件参数有疑惑的建议看 d.ts 文件
看不懂啊，怎么定义onClick事件呢？

**Comment by SzHeJason** [comment]
项目库里面的 page 有 Demo 代码呀 你看一下就知道了 

![image](https://user-images.githubusercontent.com/20609396/49910231-db383200-febc-11e8-944c-18987d20a219.png)
