### ISSUE TITLE
npm 包 缺少 TypeScript 的声明文件

### ISSUE THREAD

**Issue by tomgao365** [NervJS/taro-ui#25]
npm 或 yarn 安装 taro-ui 后，node_modules 目录没有 taro-ui 的声明文件，也无法通过 @types/taro-ui 安装

**Comment by koppthe** [comment]
项目里面是有 @types 文件的，只是 npm publish 的时候把文件漏了，今天会发版本补上

**Comment by tomgao365** [comment]
good

**Comment by SzHeJason** [comment]
1.1.0已修复
