### ISSUE TITLE
AtInputNumber 能否支持onBlur属性

### ISSUE THREAD

**Issue by GaoYuJian** [NervJS/taro-ui#251]
### 重现步骤
Input组件输入的数量有时要做过滤， 比如数量要求必须是11的倍数，这时step设置为11， 但是用Input组件直接输入没有合适的时机校正数量，如果可以提供onBlur属性则可以在onBlur时校正数量

### 依赖的版本号

Node: v8.11.1
Taro: 1.2.0-beta.9
Taro-UI: 1.5.2

**Comment by jimczj** [comment]
已增加，等待发版本
