### ISSUE TITLE
AtSearchBar 在 AtIndexes 中的使用问题

### ISSUE THREAD

**Issue by focus0802** [NervJS/taro-ui#255]
taro-ui 版本是最新的 1.5.1 版本

```
<AtIndexes
  list={list}
>
  <AtSearchBar
    value={searchText}
    onChange={this.handleTextChange}
  />
</AtIndexes>
```

需求是：根据 AtSearchBar 的值实时筛选 list 的值。
现在的情况是：可以根据 AtSearchBar 的值进行筛选，不过 AtSearchBar 输入2个英文字母或3个数字或1个汉字之后键盘就会自动关闭，如果需要继续输入就要再手动点击输入框进行输入。
需要解决的是：如何能让软键盘在输入过程中不会自动关闭。
谢谢🙃~

**Comment by jimczj** [comment]
看你的问题描述，跟嵌套在 AtIndexes 没有关系吧，你描述的问题，在官方 demo 中会出现吗。

**Comment by koppthe** [comment]
收不到回应~先暂时关闭该 issue~
