### ISSUE TITLE
调用了Taro.navigateTo方法后，tabBar有时会消失

### ISSUE THREAD

**Issue by hugetiny** [NervJS/taro-ui#257]
调用了Taro.navigateTo方法后
tabBar会消失
系统未报错

node:10.13.0
os:mac 10.13.6
浏览器：chrome

**Comment by koppthe** [comment]
麻烦贴一下具体的代码，然后 taro 和 taro-ui 的版本号写一下

**Comment by jimczj** [comment]
@hugetiny 你使用的是 AtTabBar 吗

**Comment by koppthe** [comment]
H5 下会消失应该是合理的吧，因为页面发生了跳转，重新渲染了。 taro 这边还在预研 SPA 的方案，得支持 SPA 之后，才能实现你需要的功能。

**Comment by yaimeet** [comment]
@koppthe 这个问题挺神奇的，此时此刻，当前，TabBar用的是 app.config.ts 配置的项。
然后，我正常理解的期望是，h5应该不会显示出来，正要准备定制使用 UI的TabBar组件在h5环境时，h5刷新页面竟然出现了，更神奇的是，刷新的时候，又没了，然后就是时有时无，具体有或无的场景，目前还没无法定位。

## Version
```json
{
"@tarojs/cli": "3.0.8",
"@tarojs/taro": "3.0.8",
"taro-ui": "^3.0.0-alpha.3"
}
```

项目使用 最新版 taro3 ，脚手架初始化出来的项目，项目模板采用的是：taro-ui。

**Comment by yaimeet** [comment]
这个问题有点 #797 ，所以现在我好奇的是，配置的 TabBar 在 h5 下面，正常是显示还是不显示呢？

**Comment by darkfiredarkhalo** [comment]
这么大的问题,为什么无缘无故就关了呢
