### ISSUE TITLE
npm 包 dist/webapp/index.js 文件中引用了不存在的样式文件

### ISSUE THREAD

**Issue by cncolder** [NervJS/taro-ui#263]
### 重现步骤
```js
import './components/article/index.scss'
```

这个文件是不存在的.

### 依赖的版本号

1.5.2

### 相关链接
https://unpkg.com/taro-ui@1.5.2/dist/weapp/index.js

**Comment by koppthe** [comment]
这个没有影响代码编译吧？

**Comment by cncolder** [comment]
我在尝试分组件加载, 以减小 h5 端打包体积, 看来我还是对 taro 编译过程不了解, 试了半天发现是徒劳.

**Comment by koppthe** [comment]
下个版本会支持自定义主题，同时会提供按需加载的引入方式，预计本周末发布，到时候再试试？
