### ISSUE TITLE
AtFloatLayout里面的isOpened和onClose属性关联性太强，太耦合

### ISSUE THREAD

**Issue by dreamthen** [NervJS/taro-ui#266]
### 重现步骤
不管是否在onClose里面去改变isOpened,都会触发onClose里面的异步代码,这不太合理吧
### 依赖的版本号

Node --version: v8.12.0
Taro --version: v1.2.0-beta.2
Taro-UI: v1.5.2
### 预期结果
在onClose里面去改变isOpened,不会触发onClose里面的代码
### 实际结果
在onClose里面去改变isOpened,确实是会触发onClose里面的代码
### 相关链接
<a href="https://taro-ui.aotu.io/#/docs/floatlayout">https://taro-ui.aotu.io/#/docs/floatlayout</a>

**Comment by dreamthen** [comment]
写错了，是不在onClose里面去改变isOpened，不触发onClose里面的代码

**Comment by SzHeJason** [comment]
你的意思是在用户 自己改变 isOpened 值的时候不应该出发 onClose 事件吗？

**Comment by dreamthen** [comment]
@SzHeJason 是的，我觉得应该聚焦于isOpened的值而不是onClose事件，假如我在AtFloatLayout内容里面写了一个Button，点击时将isOpened置为false，这时候为啥还要进入onClose事件呢？

**Comment by dreamthen** [comment]
@SzHeJason 且假如我的onClose事件里面也有一个将isOpened置为false的操作,这时候会造成死循环,会无限的进入onClose事件里面

**Comment by SzHeJason** [comment]
嗯 其实都有道理 从 UI 的角度来说你的确是 close 了这个组件，所以触发 onClose 无可厚非 主要是这个改动在不同的使用者看来都是可以解释的 但是我也觉得你这个逻辑比较好 会在下个版本修复
