### ISSUE TITLE
actionsheet 在小程序是view不是cover-view 不会覆盖canvas

### ISSUE THREAD

**Issue by JasonJie** [NervJS/taro-ui#267]

**Comment by SzHeJason** [comment]
暂时只能通过 监听 onOpened隐藏 canvas 来处理 主要是 CoverView 的限制太大了 并且无法渲染子节点 
![image](https://user-images.githubusercontent.com/20609396/50156011-97a05680-0308-11e9-8042-04f1d3d55fb1.png)
