### ISSUE TITLE
[建议] Toast 和 Modal 提供 api 调用版本

### ISSUE THREAD

**Issue by tomgao365** [NervJS/taro-ui#27]
建议 Toast 和 Modal 提供 api 调用版本，组件的方式有些繁琐。

**Comment by SzHeJason** [comment]
@tomgao365 之前写的时候就是像支持 `api` 模式的 但是目前的 `taro` 想完成这个功能只能通过 事件传递 这对于一个组件库来说 是有点诡异的 而且 `React` 的组件中 `Toast` 和 `Modal` 都是通过组件实现的。这个之后会评估 尽量会支持

**Comment by tomgao365** [comment]
@SzHeJason 👌

**Comment by tomgao365** [comment]
Message 已经通过 Taro 的 ``Taro.eventCenter`` 支持方法调用了，Toast 和 Modal  可以搞起来了。

**Comment by SzHeJason** [comment]
这个我们排期商量下 在第三方库使用 事件机制 是不友好的行为

**Comment by SzHeJason** [comment]
目前的方案都是使用 Taro.Event 这种事件广播实现的第三方库不适合加入这种实现
建议自己使用 Taro 的事件封装
