### ISSUE TITLE
输入框长度

### ISSUE THREAD

**Issue by js1121302139** [NervJS/taro-ui#273]
**问题描述**
输入框设置最大长度后输入中文时无法输入完整

**复现步骤**

[或者可以直接贴源代码，能贴文字就不要截图]

`
<AtInput
                            onChange={this.handleCreateTeamData.bind(this, 'name')}
                            maxlength={5}
                            value={name}
                            placeholder='请输入名称'></AtInput>
``js

**期望行为**
能够完整输入文字
**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
都是最新的
[根据你的调查研究，出现这个问题的原因可能在哪里？]
可能将正在输入的的字母也算上了

**Comment by jimczj** [comment]
经测试，该问题只在开发者工具会出现，真机测试不会，故忽略

**Comment by giscafer** [comment]
@jimczj @yuche 真机调试也不行。idcard也没有限制长度，加了maxLength也不起作用

```html
 <AtInput
              clear
              name='certificateNo'
              title='身份证号码'
              type='idcard'
              maxLength='18'
              border={false}
              placeholder='请输入身份证号码'
              disabled={canEditInput}
              value={this.state.certificateNo}
              onChange={this.handleChange.bind(this, 'certificateNo')}
            />
```

版本：`	"taro-ui": "^1.5.2"`
![1111](https://user-images.githubusercontent.com/8676711/51596011-fc1b8a80-1f32-11e9-8155-90fd14602ad1.jpg)

**Comment by koppthe** [comment]
@giscafer  taro-ui 版本升级一下吧，v1.5.2 是有这个问题

**Comment by giscafer** [comment]
@koppthe 

依赖是有 `^` ，自动下载到了 `1.5.4`版本

![tarointpu](https://user-images.githubusercontent.com/8676711/51599435-83b8c780-1f3a-11e9-8d78-7191c149e8ae.png)
