### ISSUE TITLE
SearchBar光标跳动问题

### ISSUE THREAD

**Issue by PyBeaner** [NervJS/taro-ui#275]
### 重现步骤
通过微信打开H5页面，SearchBar搜索框从文本中部删除文字时，光标会自动跳到文本尾部

### 依赖的版本号

Taro v1.2.0-beta.2
Taro-UI 1.4.0

### 实际结果
安卓、IOS都出现了该问题；在PC浏览器模拟时未出现该问题

**Comment by PyBeaner** [comment]
通过扫官网演示二维码，也是有这个问题的，应该和版本没有关系

**Comment by jimczj** [comment]
@PyBeaner @xueyida 升级 Taro 到 1.2.2，Taro UI 到 1.5.3 即可解决问题

**Comment by jimczj** [comment]
官网演示二维码的版本目前还未更新
