### ISSUE TITLE
升级Taro 1.2.1后AtInput失效

### ISSUE THREAD

**Issue by hugetiny** [NervJS/taro-ui#278]
升级Taro 1.2.1后AtInput失效
系统：Mac 10.13.6
node:10.13.0
Taro:1.2.1

**Comment by hugetiny** [comment]
onChange/onInput事件捕获不到

**Comment by koppthe** [comment]
今天会针对这个问题发个 bugfix 版本

**Comment by hugetiny** [comment]
@koppthe h5有这个问题，微信小程序没有

**Comment by yxyufo110** [comment]
onChange 里无法捕获事件，应该回退到哪个版本

**Comment by jimczj** [comment]
等今天发个版本修复下就行，打包的时候没更新到最新导致的

**Comment by hugetiny** [comment]
@jimczj  升级到1.5.3依旧不行

**Comment by jimczj** [comment]
Taro 基础库已修复，等待 Taro 发版本，Taro UI 会发 bugifx 版本

**Comment by hugetiny** [comment]
@jimczj @koppthe 最新Taro1.2.2升级后已经修复
