### ISSUE TITLE
为啥每个组件都加了background-color: #FFF ?

### ISSUE THREAD

**Issue by felix9ia** [NervJS/taro-ui#279]
### 依赖的版本号
Taro-UI 版本: 1.5.1

### 预期结果

我想做一个暗色系的风格

### 实际结果

可是Taro-UI每个组件都加
`background-color: #FFF `,没法用

### 疑惑
是组件只能这么写,我自己覆盖样式?
还是没考虑到这块?
是否考虑优化?
得等多久?

**Comment by koppthe** [comment]
你说的是「自定义主题」的功能，这两天会上线

**Comment by felix9ia** [comment]
@koppthe 爱你!

**Comment by hugetiny** [comment]
@koppthe 比起主题，更在乎各个平台的兼容性啊，我也做暗黑系的，样式已经都自己写了

**Comment by SzHeJason** [comment]
我们看看

**Comment by koppthe** [comment]
自定义主题版本已发布，可以尝尝鲜，至于开放哪些组件变量，还在梳理中。我这边近期也会出几套官方主题，稳定之后再正式发 v2.0.0
```bash
npm install taro-ui@next
```

**Comment by Tianyazz** [comment]
@koppthe 自定义主题，还是解决不了问题，我只是想改掉某一个组件的背景样式。这里不能做样式覆盖吗，我尝试了不生效
