### ISSUE TITLE
Tabs 标签页组件的tabList数组有多个元素时，会全部显示，没有可横向滑动效果。

### ISSUE THREAD

**Issue by missmimia** [NervJS/taro-ui#28]
### 依赖的版本号
 "taro-ui": "^1.0.1",

问题描述

https://nervjs.github.io/taro-ui/#/docs/tabs

Tabs 标签页组件的tabList数组有多个元素时，会全部显示，没有可横向滑动效果。

且title文字多时，文字无法完整显示，后面文本会被遮挡。

复现步骤

[或者可以直接贴源代码，能贴文字就不要截图]

            <View className="tabWrap">
              {category[0] && (
                <View>
                  <AtTabs
                    current={topIndex}
                    tabList={category}
                    onClick={this.tabChange.bind(this, category)}
                  />
                  {!!category[topIndex] &&
                    !!category[topIndex].childs && (
                      <AtTabs
                        current={secondIndex}
                        tabList={category[topIndex].childs}
                        onClick={this.childTabChange.bind(
                          this,
                          category[topIndex].childs
                        )}
                      />
                    )}
                </View>
              )}
            </View>

期望行为

每个tab应设置一个最低宽度，且tab宽度因由内容文本撑开，当长度超出可视区域宽度时，应可横向滑动。

**Comment by jimczj** [comment]
你好，当您的标签数量过多，或者标签不等宽的时候，建议加上参数 `scroll={true}`，应该能满足你的需求，我后续将完善文档，感谢您的提问

**Comment by missmimia** [comment]
阔以了~ 感谢♪(･ω･)ﾉ

**Comment by IFmiss** [comment]
> 你好，当您的标签数量过多，或者标

你好，我想问一下，设置可以滑动的时候，我在页面高度比较长的情况下（类似 tabs 瀑布流）这种布局，我左右滑动很容易误触为上下滑动， 有什么好的办法吗
