### ISSUE TITLE
Bug with AtCalendar onDayClick

### ISSUE THREAD

**Issue by ANDEMEN** [NervJS/taro-ui#280]
### 重现步骤
onDayClick 打印出的 item 值不对。
### 依赖的版本号

node v8.11.3 taro 1.2.1 taro-ui 1.5.1
### 预期结果
onDayClick 接收的 item 为 { value: '2018-12-24' }。
### 实际结果
onDayClick 接收的 item 为 { value: undefined }。
在 dist 的源码里打印接收到的 item，发现传入的是 event，并没有去拿实际的值。

**Comment by SzHeJason** [comment]
无论是 小程序 还是 h5 没有复现这个bug 建议提供多点复现信息

**Comment by SzHeJason** [comment]
#280 我相信你的问题应该与这个是一样的 版本库没一致
