### ISSUE TITLE
Taro UI加油啊，平台先支持起来

### ISSUE THREAD

**Issue by hugetiny** [NervJS/taro-ui#282]
Taro都支持到字节跳动了，Taro UI还只支持H5,微信小程序

**Comment by koppthe** [comment]
支付宝小程序马上就支持了，百度小程序还卡在官方的 Bug 上。而字节跳动的适配还在等待排期中~

**Comment by XiaogeTek** [comment]
加油，期待百度小程序尽快支持！！！！

**Comment by hugetiny** [comment]
@koppthe ReactNative以后有计划支持吗？

**Comment by koppthe** [comment]
@hugetiny  暂时没有这个规划，优先还是适配其他小程序

**Comment by mauvew** [comment]
@koppthe 想请问一下如果Taro UI不支持ReactNative的话，目前如果使用taro在开发微信小程序的同时想通过RN开发APP的话，有什么UI组件的可以使用呢？有什么推荐的解决方案吗？谢谢

**Comment by koppthe** [comment]
@mauvew  目前还没有同时支持小程序和 RN 的组件库，解决方案暂时只能是自己封装组件了

**Comment by Mihawk-zhao** [comment]
+1
