### ISSUE TITLE
Component is not found in path "pages/D:codeweixin......

### ISSUE THREAD

**Issue by liudonghua123** [NervJS/taro-ui#283]
### 重现步骤
在一个page页面中使用`AtModal`，提示如下错误信息
![image](https://user-images.githubusercontent.com/2276718/50399524-096e1980-07bb-11e9-9510-07e85b500326.png)

我检查了一下这个页面生成的js/json/wxml/wxss文件，其中我发现json文件中的有下面内容
```
{
  "usingComponents": {
    "at-modal": "D:\\code\\weixin\\training-mini-app\\src\\npm\\taro-ui\\dist\\weapp\\components\\modal\\index"
  },
  "navigationBarTitleText": "xxx"
}
```
如果我把`at-modal`改成下面的
```
"at-modal": "../npm/taro-ui/dist/weapp/components/modal/index"
```
就没问题

### 依赖的版本号

![image](https://user-images.githubusercontent.com/2276718/50399582-6c5fb080-07bb-11e9-8592-5436da79fbf8.png)

### 预期结果
可以正常工作

### 实际结果
```
Component is not found in path "pages/D:codeweixin	raining-mini-appsrc
pm	aro-uidistweappcomponentsmodalindex" (using by "pages/verification")
Error: Component is not found in path "pages/D:codeweixin	raining-mini-appsrc
pm	aro-uidistweappcomponentsmodalindex" (using by "pages/verification")
```

**Comment by liudonghua123** [comment]
我把package.json中taro相关的依赖包从`^1.2.0-beta.14`升级到`^1.2.1`就可以了

**Comment by koppthe** [comment]
嗯嗯，需要升级到最新版本，beta 版本存在一些问题
