### ISSUE TITLE
taro-ui  H5中 Taro.atMessage 假如 message没有消失前跳转了其他页面，返回来，message无法再触发显示

### ISSUE THREAD

**Issue by xingwen93** [NervJS/taro-ui#284]
taro-ui  H5中 Taro.atMessage 假如 message没有消失前跳转了其他页面，返回来，message无法再触发显示

taro-ui 1.5.2 

Taro v1.2.1

  Taro CLI 1.2.1 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.1.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm

**Comment by jimczj** [comment]
本地显示正常，无法复现
![image](https://user-images.githubusercontent.com/13499146/50465610-37c64180-09d3-11e9-8f31-0ed3a8f50718.png)

**Comment by xingwen93** [comment]
嗯嗯

**Comment by xingwen93** [comment]
H5中 是这样子的：
条件：A页面 存在 Taro.atMessage   B页面也存在 Taro.atMessage  单独页面中（不从A跳转到B）两者都可以显示message  .
表现bug步骤:  h5启动后，此时A页面不做任何操作，进入B页面，然后在B页面触发显示message ,然后无论 message有无消失完，返回到A页面，此时A页面触发message 无法显示出message.
taro 1.2.1 和 1.2.2应该同样存在bug 


 Taro v1.2.2


  Taro CLI 1.2.2 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.1.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm

taro-ui 1.5.3

**Comment by hblz** [comment]
对 我也出现了

**Comment by koppthe** [comment]
@hblz taro-ui 有升级到最新版本吗？

**Comment by hblz** [comment]
2.0.0版本

**Comment by LaughingZhu** [comment]
> 2.0.0版本
最后怎么操作的呀，我也遇到了这个情况

**Comment by cjtcjt999** [comment]
Taro UI AtMessage组件在当前页面navigateTo跳转到下一个页面后在点击返回后，当前页面的AtMessage失效了！！！

**Comment by ChunrunHan** [comment]
怎么解决的啊？

**Comment by chenyuhu** [comment]
还没有解决吗

**Comment by daguanren21** [comment]
这个问题还没有解决么

**Comment by WWThinking** [comment]
还没解决吗？

**Comment by tiancaizs** [comment]
> Taro UI AtMessage组件在当前页面navigateTo跳转到下一个页面后在点击返回后，当前页面的AtMessage失效了！！！

请问有解决吗？

**Comment by 2264805401songyunhai** [comment]
请问这个问题又解决方案了嘛

**Comment by WWThinking** [comment]
给组件AtMessage添加唯一key值试试



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NervJS/taro-ui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月1日(星期二) 晚上10:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NervJS/taro-ui] taro-ui  H5中 Taro.atMessage 假如 message没有消失前跳转了其他页面，返回来，message无法再触发显示 (#284)





 
请问这个问题又解决方案了嘛
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 594lzh** [comment]
有解决方案吗？3.0

**Comment by blue-fatty** [comment]
为啥问题没解决就被关闭了

**Comment by camellieeee** [comment]
这个问题有解决吗

**Comment by master1lan** [comment]
直到3.1版本该bug依旧没修复，原因在于虽然绑定了componentDidShow生命周期但是因为不是页面组件所以无法更新

https://github.com/NervJS/taro/issues/9314#issuecomment-844647901

如果封装一个wrapper组件的话，由于hooks的执行时机和class的生命周期处于不同的阶段，所以会导致在A，B页面都有AtMessage组件的情况下：
先进入A页面：A组件内部AtMessage didMount->A组件内部wrapper didShow
进入B页面：A组件内部wrapper didHide->A组件内部AtMessage willUnmount->B组件内部AtMessage didMount->B组件内部wrapper didShow
退出B页面返回A页面：A组件内部wrapper didShow->A组件内部AtMessage didMount->B组件内部AtMessage willUnmount
而在Atmessage组件内部有这么一段代码：
`componentWillUnmount() {
        Taro.eventCenter.off('atMessage');
    }`
这段代码导致由于B组件最后执行卸载，atMessage事件注销掉了。
