### ISSUE TITLE
taro ui 的倒计时组件秒数一秒跳了两下（两秒）

### ISSUE THREAD

**Issue by jxzlhy** [NervJS/taro-ui#285]
### 重现步骤
import Taro from '@tarojs/taro'
import { View } from '@tarojs/components'
import { AtCountDown } from 'taro-ui'
export default class CountDownPage extends Taro.Component {
  render () {
    return (
      <AtCountDown
        isShowDay
        day={2}
        hours={1}
        minutes={1}
        seconds={10}
      />
    )
  }
}
![image](https://user-images.githubusercontent.com/16329495/50411102-6956d580-0838-11e9-9da3-915e6a5dd949.png)

### 依赖的版本号
node: 10.13.0, Taro: 1.2.0 Taro-UI: 1.5.3

### 预期结果
一秒钟跳一下
### 实际结果
一秒钟跳两下
![gif](https://user-images.githubusercontent.com/16329495/50411058-f77e8c00-0837-11e9-89f0-717703317c17.gif)

**Comment by koppthe** [comment]
这个已经改了，还没发版。

**Comment by jxzlhy** [comment]
> 这个已经改了，还没发版。

尽快吧，老哥
