### ISSUE TITLE
必须要安装@tarojs/cli才能使用taro-ui吗？cra中使用taro-ui不行吗？

### ISSUE THREAD

**Issue by zwl1619** [NervJS/taro-ui#287]
根据[文档](https://taro-ui.aotu.io/#/docs/quickstart)，使用taro-ui要安装@tarojs/cli.

问题：
必须要安装@tarojs/cli才能使用taro-ui吗？cra中使用taro-ui不行吗？
如果只能在@tarojs/cli中使用，有pwa功能吗？

**Comment by koppthe** [comment]
taro-ui 目前只支持用 taro 开发的项目，不支持 PWA
