### ISSUE TITLE
AtGrid 中点击事件和文档中描写的不同，index值无法获取

### ISSUE THREAD

**Issue by quqingru** [NervJS/taro-ui#288]
### 重现步骤

  handleClick (item, index) {
     console.log(item);
     console.log(index);
  }
  render () {
    return (
      <View className='index'>
      <AtGrid 
        hasBorder
        onClick={this.handleClick.bind(this)}
        data={
        [
         {
          iconInfo:'333',
          id:"ee",
          index:1,
          image: 'https://img12.360buyimg.com/jdphoto/s72x72_jfs/t6160/14/2008729947/2754/7d512a86/595c3aeeNa89ddf71.png',
          value: '《教育学》'
        },
        {
          image: 'https://img20.360buyimg.com/jdphoto/s72x72_jfs/t15151/308/1012305375/2300/536ee6ef/5a411466N040a074b.png',
          value: '《教育心理学》'
        },
        {
          image: 'https://img10.360buyimg.com/jdphoto/s72x72_jfs/t5872/209/5240187906/2872/8fa98cd/595c3b2aN4155b931.png',
          value: '《教师职业道德》'
        },
        {
          image: 'https://img12.360buyimg.com/jdphoto/s72x72_jfs/t10660/330/203667368/1672/801735d7/59c85643N31e68303.png',
          value: '《教育法规概论》'
        },
        {
          image: 'https://img14.360buyimg.com/jdphoto/s72x72_jfs/t17251/336/1311038817/3177/72595a07/5ac44618Na1db7b09.png',
          value: '《教学技能理论实践》'
        },
        {
          image: 'https://img30.360buyimg.com/jdphoto/s72x72_jfs/t5770/97/5184449507/2423/294d5f95/595c3b4dNbc6bc95d.png',
          value: '《教学方法导论》'
        },
        {
          image: 'https://img30.360buyimg.com/jdphoto/s72x72_jfs/t5770/97/5184449507/2423/294d5f95/595c3b4dNbc6bc95d.png',
          value: '《学生与团队管理》'
        }
        ,
        {
          image: 'https://img30.360buyimg.com/jdphoto/s72x72_jfs/t5770/97/5184449507/2423/294d5f95/595c3b4dNbc6bc95d.png',
          value: '《职业道德解读》'
        }
        
        ] 
      }     
      />
      </View>
    )
### 预期结果
     console.log(index); //输出 用户选中的索引值
### 实际结果
console.log(index); //输出 NaN

**Comment by quqingru** [comment]
版本信息 
  "@tarojs/taro": "^1.2.0"
    "taro-ui": "^1.5.3"

**Comment by SzHeJason** [comment]
![2018-12-27 18 00 16](https://user-images.githubusercontent.com/20609396/50479016-51857a00-0a0f-11e9-89e2-a5b3608747e7.gif)
![image](https://user-images.githubusercontent.com/20609396/50479043-71b53900-0a0f-11e9-8368-f8fe7e0b6bce.png)
![image](https://user-images.githubusercontent.com/20609396/50479102-ceb0ef00-0a0f-11e9-8c0a-d4b690e5b041.png)

无法重现

**Comment by SzHeJason** [comment]
我看了一下你的库版本 实际上 你的 taro 版本是 ^1.2.0 并没有固定在 1.2.0 在下载的时候会自动升级到 最新版 所以 taro 全局版本与 项目的版本不匹配 导致了编译有问题
1. 将项目的 taro 版本 固定在 1.2.0 上 
2. 将 taro 全局版本 与 项目版本匹配
