### ISSUE TITLE
AtAvatar控件如何兼容taro的<OpenData type='userAvatarUrl' />

### ISSUE THREAD

**Issue by chinacoolboyzz** [NervJS/taro-ui#29]
AtAvatar控件如何兼容taro的<OpenData type='userAvatarUrl' />
taro里image属性无法传入 JSX 元素

**Comment by jimczj** [comment]
Taro 目前不支持传入 JSX 元素，image 属性只能传入 string，我们会考虑开放 openData 属性，感谢建议
