### ISSUE TITLE
AtIndexes组件点击右边的导航时出现：“VM341:5 id 属性值格式错误。如不能以数字开头。”

### ISSUE THREAD

**Issue by joomecow** [NervJS/taro-ui#290]
### 依赖的版本号

1.2.1

**Comment by koppthe** [comment]
可以麻烦提供详细一点的信息吗？taro 版本，taro-ui 版本都说明一下吧

**Comment by joomecow** [comment]
taro 1.2.0  
taro-ui 1.5.2

render () {
    const { students } = this.state;

    return (
      <View>
        <AtSearchBar actionName='搜索' value='' fixed isShowToast={false}
          onChange={this.onChangeSearch}
          onActionClick={this.onClickSearch}
        />
        <View style='margin-top:42px;'>
          <AtIndexes list={students} isVibrate={false} onClick={this.onClickIndex} />
        </View>
      </View>
    )
  }

点击右边的导航文字，微信工具上报错：
Wed Dec 26 2018 20:00:28 GMT+0800 (中国标准时间) 渲染层错误
VM341:5 id 属性值格式错误。如不能以数字开头。
(anonymous) @ VM341:5

**Comment by joomecow** [comment]
<View style='margin-top:42px;'>
  <AtIndexes list={students} isVibrate={false} isShowToast={true} onClick={this.onClickIndex} />
</View>

如果isShowToast为true会报下面的错误：

VM3302:1 thirdScriptError
Cannot read property 'key' of undefined; [Component] Event Handler Error @ npm/taro-ui/dist/weapp/components/indexes/index#(anonymous)
TypeError: Cannot read property 'key' of undefined
    at AtIndexes.jumpTarget (http://127.0.0.1:62866/appservice/npm/taro-ui/dist/weapp/components/indexes/index.js:185:48)
    at q.obj.(anonymous function) [as jumpTarget] (http://127.0.0.1:62866/appservice/npm/@tarojs/taro-weapp/dist/index.js:3272:36)
    at Object.r.safeCallback (http://127.0.0.1:62866/appservice/__dev__/WAService.js:1:552403)
    at http://127.0.0.1:62866/appservice/__dev__/WAService.js:1:632216
    at d (http://127.0.0.1:62866/appservice/__dev__/WAService.js:1:634434)
    at http://127.0.0.1:62866/appservice/__dev__/WAService.js:1:633746
    at n (http://127.0.0.1:62866/appservice/__dev__/WAService.js:1:257579)
    at e (http://127.0.0.1:62866/appservice/appservice?t=1545837196656:2269:20972)
    at r.registerCallback.t (http://127.0.0.1:62866/appservice/appservice?t=1545837196656:2269:21157)
    at l.forEach.t (http://127.0.0.1:62866/appservice/appservice?t=1545837196656:2269:1581)
console.error @ VM3302:1
errorReport @ WAService.js:1
thirdErrorReport @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
r.safeCallback @ WAService.js:1
r.call @ WAService.js:1
t.message @ WAService.js:1
r.safeCallback @ WAService.js:1
(anonymous) @ WAService.js:1
d @ WAService.js:1
(anonymous) @ WAService.js:1
n @ WAService.js:1
e @ appservice?t=1545837196656:2269
r.registerCallback.t @ appservice?t=1545837196656:2269
l.forEach.t @ appservice?t=1545837196656:2269
(anonymous) @ appservice?t=1545837196656:2269
s.onmessage @ appservice?t=1545837196656:2269
VM3402:4 Wed Dec 26 2018 23:13:23 GMT+0800 (中国标准时间) 渲染层错误
VM3402:5 id 属性值格式错误。如不能以数字开头。

**Comment by jimczj** [comment]
未能复现，请升级微信小程序基础库或者重启开发者工具试试 @joomecow

**Comment by joomecow** [comment]
@jimczj  已尝试你建议的操作，还是会报这些错
taro 1.2.2
taro-ui 1.5.3
基础库 2.4.3

**Comment by jimczj** [comment]
@joomecow 老哥，可以跑一下这个项目，看看会不会报错，看看代码差异，https://github.com/NervJS/taro-ui-demo

**Comment by jimczj** [comment]
无法复现，此 issue 关闭
