### ISSUE TITLE
AtList样式失效，如图所示

### ISSUE THREAD

**Issue by fsf11080612** [NervJS/taro-ui#291]
![image](https://user-images.githubusercontent.com/12817128/50448610-2d696080-095d-11e9-9c20-7f470e54a984.png)

下面是代码：
![image](https://user-images.githubusercontent.com/12817128/50448628-41ad5d80-095d-11e9-9e55-8b64ef19a6d3.png)

**Comment by koppthe** [comment]
麻烦描述清楚一些，版本号，环境之类的都提供一下，请按照 Issue 模板提交哈

**Comment by koppthe** [comment]
信息量太少，暂时关闭哈~
