### ISSUE TITLE
Typo flex prop dirction

### ISSUE THREAD

**Issue by cncolder** [NervJS/taro-ui#293]
### 重现步骤
应该是 direction, BREAKING CHANGE. 要考虑向后兼容.

### 相关链接
https://github.com/NervJS/taro-ui/blob/a85de1cd19cdfbf7ab218f5fb7375e6f02760985/src/components/flex/index.js#L36

**Comment by SzHeJason** [comment]
在开发阶段 是把 flex 作为组件的 但是后期发现 小程序无法实现 所以 flex 是以样式的形式出现的
https://taro-ui.aotu.io/#/docs/flex
