### ISSUE TITLE
关于AtInput

### ISSUE THREAD

**Issue by hugetiny** [NervJS/taro-ui#294]
微信小程序正常界面
![weapp2](https://user-images.githubusercontent.com/19659202/50465116-11eb6d80-09d0-11e9-8d01-3ed8257f2b1d.png)
支付宝界面
![aplipayapp1](https://user-images.githubusercontent.com/19659202/50465120-17e14e80-09d0-11e9-8a66-b4e863b887bd.png)

github:https://github.com/hugetiny/quit-smoking
我这个做了暗黑样式，没有任何border设置的情况下input框依然有白边，这个是什么问题？

**Comment by jimczj** [comment]
自行审查样式，自定义样式我们不负责

**Comment by SzHeJason** [comment]
是指支付宝页面 不符合预期吗 小程序页面才是对的？

**Comment by hugetiny** [comment]
其实问题分两个部分：1.支付宝页面 不符合预期
2.Taro UI的input在没有border的情况下也会有白边，这个可以等你们暗黑主题上线后再看
