### ISSUE TITLE
对于Taro ui选型的建议

### ISSUE THREAD

**Issue by hugetiny** [NervJS/taro-ui#295]
目前Taro UI的优先级是
H5,微信->其他小程序平台->RN
我认为不太恰当，因为对于CSS限制最多的是RN，很多不支持的属性，支持的有以下属性
  "alignContent",
  "alignItems",
  "alignSelf",
  "aspectRatio",
  "backfaceVisibility",
  "backgroundColor",
  "borderBottomColor",
  "borderBottomEndRadius",
  "borderBottomLeftRadius",
  "borderBottomRightRadius",
 "borderBottomStartRadius",
  "borderBottomWidth",
  "borderColor",
  "borderEndColor",
  "borderEndWidth",
  "borderLeftColor",
  "borderLeftWidth",
  "borderRadius",
  "borderRightColor",
  "borderRightWidth",
  "borderStartColor",
  "borderStartWidth",
  "borderStyle",
  "borderTopColor",
  "borderTopEndRadius",
  "borderTopLeftRadius",
  "borderTopRightRadius",
  "borderTopStartRadius",
  "borderTopWidth",
  "borderWidth",
  "bottom",
  "color",
  "decomposedMatrix",
  "direction",
  "display",
  "elevation",
  "end",
  "flex",
  "flexBasis",
  "flexDirection",
  "flexGrow",
  "flexShrink",
  "flexWrap",
  "fontFamily",
  "fontSize",
  "fontStyle",
  "fontVariant",
  "fontWeight",
  "height",
  "includeFontPadding",
  "justifyContent",
  "left",
  "letterSpacing",
  "lineHeight",
  "margin",
  "marginBottom",
  "marginEnd",
  "marginHorizontal",
  "marginLeft",
  "marginRight",
  "marginStart",
  "marginTop",
  "marginVertical",
  "maxHeight",
  "maxWidth",
  "minHeight",
  "minWidth",
  "opacity",
  "overflow",
  "overlayColor",
  "padding",
  "paddingBottom",
  "paddingEnd",
  "paddingHorizontal",
  "paddingLeft",
  "paddingRight",
  "paddingStart",
  "paddingTop",
  "paddingVertical",
  "position",
  "resizeMode",
  "right",
  "rotation",
  "scaleX",
  "scaleY",
  "shadowColor",
  "shadowOffset",
  "shadowOpacity",
  "shadowRadius",
  "start",
  "textAlign",
  "textAlignVertical",
  "textDecorationColor",
  "textDecorationLine",
  "textDecorationStyle",
  "textShadowColor",
  "textShadowOffset",
  "textShadowRadius",
  "textTransform",
  "tintColor",
  "top",
  "transform",
  "transformMatrix",
  "translateX",
  "translateY",
  "width",
  "writingDirection",
  "zIndex"

而RN转H5相对容易，
我的建议：https://github.com/react-native-training/react-native-elements
以开源的react-native-elements为基础，优先适配H5,RN然后再适配微信等小程序平台就容易多了，当然这个和Taro的适配优先级不一致，不过容易多了，望考虑

**Comment by koppthe** [comment]
谢谢你的建议，但是我们的项目是几个月前就启动了的，下面是我们考虑的一些点：
1. Taro UI 第一个版本发布的时候，Taro 还不支持 RN。
2. 大部分 Taro 用户是为了写小程序项目，才选择 Taro 框架的。
3. 如果逆向处理多端适配的问题，RN 的局限性会影响 Taro UI 适配多类小程序的初衷，单单从第二点出发，也应该先适配小程序端。
4. Taro UI 首要的任务是兼容各类小程序以及 H5

**Comment by hugetiny** [comment]
吼啊，Taro其实现在也主要支持微信小程序的API，其他平台的很少，加油吧。我的暗黑迅雷手机版就先用RN写了

**Comment by SzHeJason** [comment]
从兼容的角度这样的确合理
但是 Taro-UI 是服务 Taro 的 而 Taro 的应用场景以 小程序 为主 这样做本末倒置了 
另外 理想状态下 改动并不是很复杂 但是实际改动中肯定会有很多问题的 
也许我们之后会出一个新版本 但前提是 TaroUI 在小程序这方面已经做够好了

**Comment by hugetiny** [comment]
1年多后来做个预测，这个官方框架从一开始就不太支持RN，对应的UI框架也是直接放弃RN，最终必然玩不过Uni-app

**Comment by Garfield550** [comment]
Taro 跟 Uni-app 也不是竞争关系吧，Taro UI 对于 RN 的支持确实是个问题，但 RN 本身相对于 Weex 差距也很大。
