### ISSUE TITLE
AtTabsPane 问题

### ISSUE THREAD

**Issue by zzx0106** [NervJS/taro-ui#296]
"taro-ui": "^1.5.0"
"@tarojs/taro": "^1.2.0",
AtTabsPane

Warning: Failed prop type: Invalid prop `current` of type `object` supplied to `AtTabsPane`, expected `number`.

thirdScriptError
Cannot read property '0' of undefined; [Component] Event Handler Error @ npm/taro-ui/dist/weapp/components/tabs/index#(anonymous)
TypeError: Cannot read property '0' of undefined
    at AtTabs.handleTouchMove (http://127.0.0.1:65190/appservice/npm/taro-ui/dist/weapp/components/tabs/index.js:122:32)
    at q.obj.(anonymous function) [as handleTouchMove] (http://127.0.0.1:65190/appservice/npm/@tarojs/taro-weapp/dist/index.js:3270:36)
    at Object.r.safeCallback (

**Comment by zzx0106** [comment]
引起这个报错的原因是因为组件回调事件返回的这个，而不是文档中所提示的索引
![image](https://user-images.githubusercontent.com/23009081/50524363-3b131780-0b10-11e9-937c-b157fb124870.png)


 handleClick(value) {
    console.log(value);
    this.setState({
      current: value,
    });
  }


![image](https://user-images.githubusercontent.com/23009081/50524384-4fefab00-0b10-11e9-86ae-d6d430a575f7.png)

**Comment by jimczj** [comment]
升级Taro 到1.2.2 ，Taro UI 到 1.5.3 试试

**Comment by zzx0106** [comment]
@jimczj 我发现了这个问题，确实是因为版本的问题，我前几天下载的脚手架taro版本为1.2.0，今天下载了新的脚手架taro版本为1.2.2，我用1.2.2.+ui 1.5.3确实没问题了。昨天这个问题整的我头皮发麻，希望早点修复一波。
![image](https://user-images.githubusercontent.com/23009081/50533276-6a05a980-0b61-11e9-84c4-de373599841f.png)
