### ISSUE TITLE
AtAccordion 在二维数组的时候存在bug 

### ISSUE THREAD

**Issue by xingwen93** [NervJS/taro-ui#297]
![image](https://user-images.githubusercontent.com/16276222/50532303-9108af00-0b52-11e9-93db-e3ddc5237cd3.png)
此时报的异常为
![image](https://user-images.githubusercontent.com/16276222/50532308-98c85380-0b52-11e9-8c8c-118ee128673b.png)

假如改为单纯的View 不报异常，因此判定为taro-ui 的bug异常
![image](https://user-images.githubusercontent.com/16276222/50532333-de851c00-0b52-11e9-8d2d-590661c5479b.png)

👽 Taro v1.2.2

  Taro CLI 1.2.2 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.1.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm

      "taro-ui": "^1.5.3"

**Comment by koppthe** [comment]
taro 相关依赖升级到最新版本，不可复现问题
