### ISSUE TITLE
taro-ui 手风琴 AtAccordion 动态改变了数据后，导致高度没有变化

### ISSUE THREAD

**Issue by xingwen93** [NervJS/taro-ui#298]
taro-ui 手风琴 AtAccordion 动态改变了数据后，导致高度没有变化

第一加载数据时，数据 第一栏有2条数据  数据 第二栏有4条数据  紧接着，改变数据数组，变成了 数据 第一栏有1条数据  第二栏有2条数据 ，此时视图更改，手风琴的栏子列表的高度没有变化 导致如下截图
![image](https://user-images.githubusercontent.com/16276222/50534033-25820a00-0b71-11e9-9bc1-65cd6a5dba6a.png)

Taro CLI 1.2.2 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.1.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm

taro-ui 1.5.2

**Comment by destinyd** [comment]
同有此需求。
taro-ui 1.5.4 也未实现

**Comment by jimczj** [comment]
升级最新版，已修复问题
