### ISSUE TITLE
样式覆盖

### ISSUE THREAD

**Issue by Varavarforvar** [NervJS/taro-ui#3]
rt：怎么覆盖样式

**Comment by cos2004** [comment]
h5用的话可以覆盖，在你的组件js里import你的scss即可。小程序的不好覆盖，简单的样式如位置、margin等可以在组件外包裹一层节点，在外层节点写样式

**Comment by cos2004** [comment]
@Varavarforvar  h5用的话可以覆盖，在你的组件js里import你的scss即可。小程序的不好覆盖，简单的样式如位置、margin等可以在组件外包裹一层节点，在外层节点写样式
