### ISSUE TITLE
AtTabs 点击切换报错

### ISSUE THREAD

**Issue by karchinkong** [NervJS/taro-ui#300]
![image](https://user-images.githubusercontent.com/16110331/50536335-486ee700-0b8e-11e9-90b2-065bbb27a4b7.png)
Taro 当前版本为 1.2.2
Taro-ui 当前版本为 1.5.3

![Uploading image.png…]()
点击AtTabs切换tabs时会报上面图的错
查过相关的issue是说 升级可以解决 但我目前的版本是相符的 但依然报错

**Comment by jimczj** [comment]
删除一下 node_modules 重装试试，本地使用并无异常

**Comment by liudi200317** [comment]
请问这个错误是怎么解决的，我也出现了

**Comment by jimczj** [comment]
@liudi200317 你是 win 系统吗

**Comment by liudi200317** [comment]
我的是mac

**Comment by liudi200317** [comment]
我刚刚把node_modules这个删掉，重新装下，还不知道行不行

**Comment by liudi200317** [comment]
重新装也不行

**Comment by koppthe** [comment]
@liudi200317  代码贴一下

**Comment by liudi200317** [comment]
`import Taro from '@tarojs/taro'
import {View} from '@tarojs/components'
import {AtTabs, AtTabsPane} from 'taro-ui'

export default class Index extends Taro.Component {
  constructor() {
    super()
    this.state = {
      current: 0,
    }
  }

  handleClick(value) {
    console.log(value)
    this.setState({
      current: value
    })
  }

  render() {
    return (
      <AtTabs
        current={this.state.current}
        scroll
        tabList={[
          { title: '标签页1' },
          { title: '标签页2' },
          { title: '标签页3' },
          { title: '标签页4' },
          { title: '标签页5' },
          { title: '标签页6' }
        ]}
        onClick={this.handleClick.bind(this)}>
        <AtTabsPane current={this.state.current} index={0}>
          <View style='font-size:18px;text-align:center;height:100px;'>标签页一的内容</View>
        </AtTabsPane>
        <AtTabsPane current={this.state.current} index={1}>
          <View style='font-size:18px;text-align:center;height:100px;'>标签页二的内容</View>
        </AtTabsPane>
        <AtTabsPane current={this.state.current} index={2}>
          <View style='font-size:18px;text-align:center;height:100px;'>标签页三的内容</View>
        </AtTabsPane>
        <AtTabsPane current={this.state.current} index={3}>
          <View style='font-size:18px;text-align:center;height:100px;'>标签页四的内容</View>
        </AtTabsPane>
        <AtTabsPane current={this.state.current} index={4}>
          <View style='font-size:18px;text-align:center;height:100px;'>标签页五的内容</View>
        </AtTabsPane>
        <AtTabsPane current={this.state.current} index={5}>
          <View style='font-size:18px;text-align:center;height:100px;'>标签页六的内容</View>
        </AtTabsPane>
      </AtTabs>
    )
  }
}
`

**Comment by liudi200317** [comment]
```js
// 这里可以贴代码
import Taro from '@tarojs/taro'
import {View} from '@tarojs/components'
import {AtTabs, AtTabsPane} from 'taro-ui'

export default class Index extends Taro.Component {
  constructor() {
    super()
    this.state = {
      current: 0,
    }
  }

  handleClick(value) {
    console.log(value)
    this.setState({
      current: value
    })
  }

  render() {
    return (
      <AtTabs
        current={this.state.current}
        scroll
        tabList={[
          { title: '标签页1' },
          { title: '标签页2' },
          { title: '标签页3' },
          { title: '标签页4' },
          { title: '标签页5' },
          { title: '标签页6' }
        ]}
        onClick={this.handleClick.bind(this)}>
        <AtTabsPane current={this.state.current} index={0}>
          <View style='font-size:18px;text-align:center;height:100px;'>标签页一的内容</View>
        </AtTabsPane>
        <AtTabsPane current={this.state.current} index={1}>
          <View style='font-size:18px;text-align:center;height:100px;'>标签页二的内容</View>
        </AtTabsPane>
        <AtTabsPane current={this.state.current} index={2}>
          <View style='font-size:18px;text-align:center;height:100px;'>标签页三的内容</View>
        </AtTabsPane>
        <AtTabsPane current={this.state.current} index={3}>
          <View style='font-size:18px;text-align:center;height:100px;'>标签页四的内容</View>
        </AtTabsPane>
        <AtTabsPane current={this.state.current} index={4}>
          <View style='font-size:18px;text-align:center;height:100px;'>标签页五的内容</View>
        </AtTabsPane>
        <AtTabsPane current={this.state.current} index={5}>
          <View style='font-size:18px;text-align:center;height:100px;'>标签页六的内容</View>
        </AtTabsPane>
      </AtTabs>
    )
  }
}

```

**Comment by karchinkong** [comment]
@liudi200317  我把taro-ui降级到1.5.2版本了 主要好像是taro 1.2.x版本后那个点击回调函数的传参变了 你可以看看taro的更新日志

**Comment by vaggrant** [comment]
@karchinkong 我本来用的就是1.5.2。也不行。好悲惨

**Comment by vaggrant** [comment]
确认了。是  @tarojs/cli 版本过旧。更新下就行了。
至于自己的项目用的是多少版本，在 npm run dev的时候会打印出来。我一开始虽然以为自己装了最新的1.2.4.而实际项目中使用的却还是 1.0.的beta版

**Comment by jimczj** [comment]
@karchinkong @liudi200317  更新 Taro 跟 Taro cli 吧
