### ISSUE TITLE
taro init myApp taro项目后，引用taro-ui

### ISSUE THREAD

**Issue by tgy3300** [NervJS/taro-ui#302]
错误提示：
![image](https://user-images.githubusercontent.com/11471847/50569853-46826f00-0dac-11e9-91e4-a7331c4a6a79.png)

页面只是：
`import { AtButton } from 'taro-ui'`
`<AtButton type='primary'>按钮文案</AtButton>`

**Comment by tgy3300** [comment]
我可还没做任何开发，就按taro的快速上手教程和taro-ui快速上手做测试，就这样了，这可是官方的教程

**Comment by yourtion** [comment]
遇到同样的问题
![image](https://user-images.githubusercontent.com/1475301/50569985-9bc17f00-0db2-11e9-8051-156566489bcd.png)

**Comment by yourtion** [comment]
@tgy3300 找到问题了，要在 `config/index.js` 加上 `esnextModules: ['taro-ui'],`

https://github.com/NervJS/taro-ui-demo/blob/master/config/index.js#L75

**Comment by tgy3300** [comment]
还真是

> @tgy3300 找到问题了，要在 `config/index.js` 加上 `esnextModules: ['taro-ui'],`
> 
> https://github.com/NervJS/taro-ui-demo/blob/master/config/index.js#L75

**Comment by chenyongze** [comment]
🙅   Failed to compile.

./node_modules/taro-ui/dist/h5/components/pagination/index.js 101:11
Module parse failed: Unexpected token (101:11)
You may need an appropriate loader to handle this file type.
|     };
|
>     return <View className={classNames(rootClassName, classObject, this.props.className)} style={customStyle}>
|         <View className="at-pagination__operate">
|           <View className="at-pagination__btns">

**Comment by yourtion** [comment]
@chenyongze 加上我上面说那个就好了

**Comment by tgy3300** [comment]
嗯

**Comment by tgy3300** [comment]
嗯

**Comment by FangBoss** [comment]
我加了那一行，运行h5还是提示有问题

**Comment by yinlsea** [comment]
我也是，加了那一行，运行h5还是提示有问题，taro-ui：1.5.4，taro：1.2.3

**Comment by yinlsea** [comment]
![image](https://user-images.githubusercontent.com/21033870/50638768-ef41f180-0f99-11e9-80bc-2573d73207b6.png)
就是这个报错，刚试了下换成最新的2.0.0-beta.1，变成button报错了
![image](https://user-images.githubusercontent.com/21033870/50638814-0f71b080-0f9a-11e9-857f-3392ccc7439c.png)

**Comment by koppthe** [comment]
因为 taro build ui 的方式调整了，输出的是源码，所以需要增加一个 esnextModules 配置：
```js
h5: {
  esnextModules: ['taro-ui']
}
```
参考：https://taro-ui.aotu.io/#/docs/quickstart

**Comment by koppthe** [comment]
@yinlsea 加这个配置的地方，截图看看？

**Comment by yinlsea** [comment]
把node_module删除，用cnpm装了一次，不行，又删除，用npm装了一次，可以了

**Comment by zxjzhaoxuejun** [comment]
在confing/dev.js里面加h5: {
  esnextModules: ['taro-ui']
}

**Comment by JasonYan2015** [comment]
same problem
