### ISSUE TITLE
建议style的写法统一

### ISSUE THREAD

**Issue by fzero17** [NervJS/taro-ui#304]
**问题描述**
一部分组件支持 style 中定义样式，一部分组件只支持在 customStyle 中定义样式，建议统一。

**复现步骤**

```js
<AtTextarea customStyle={{ marginTop: '8px' }}  />

<View style={{marginRight: '8px'}}></View>

```

**期望行为**
建议样式的写法统一。

**报错信息**
无

**系统信息**
Taro v1.2.1

  Taro CLI 1.2.1 environment info:
    System:
      OS: OS X El Capitan 10.11.6
      Shell: 5.0.8 - /bin/zsh
    Binaries:
      Node: 10.14.1 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.1 => 1.2.1
      @tarojs/cli: 1.2.1 => 1.2.1
      @tarojs/components: 1.2.1 => 1.2.1
      @tarojs/plugin-babel: 1.2.1 => 1.2.1
      @tarojs/plugin-csso: 1.2.1 => 1.2.1
      @tarojs/plugin-sass: 1.2.1 => 1.2.1
      @tarojs/plugin-uglifyjs: 1.2.1 => 1.2.1
      @tarojs/redux: 1.2.1 => 1.2.1
      @tarojs/redux-h5: 1.2.1 => 1.2.1
      @tarojs/rn-runner: 1.2.1 => 1.2.1
      @tarojs/router: 1.2.1 => 1.2.1
      @tarojs/taro: 1.2.1 => 1.2.1
      @tarojs/taro-h5: 1.2.1 => 1.2.1
      @tarojs/taro-weapp: 1.2.1 => 1.2.1
      @tarojs/webpack-runner: 1.2.1 => 1.2.1
      eslint-config-taro: 1.2.1 => 1.2.1
      eslint-plugin-taro: 1.2.1 => 1.2.1

**Comment by jimczj** [comment]
view 是原生组件，所以默认是 style，自定义组件用 style 在小程序上属性值并不能传递到组件中，所以得自定义一个属性名来传递 style 变量
