### ISSUE TITLE
希望 AtNavBar 可以自定义导航栏颜色  

### ISSUE THREAD

**Issue by vkcyan** [NervJS/taro-ui#311]

**Comment by koppthe** [comment]
目前自定义主题的方式满足不了吗？
https://taro-ui.aotu.io/#/docs/customizetheme

**Comment by koppthe** [comment]
不客气，如果使用过程中有其他问题都可以提哈

**Comment by guoxiangwen** [comment]
@koppthe 如果想设置AtNavBar的背景颜色 该怎么设置呢？

**Comment by Mayandev** [comment]
设置背景色为何有一根灰色的线，怎么都删不掉
![image](https://user-images.githubusercontent.com/28648715/68223192-50f24280-0027-11ea-8865-d36d28c06ce0.png)
