### ISSUE TITLE
taro-ui1.5.4版本测试Button在H5平台报错，回退到1.5.3版本正常显示

### ISSUE THREAD

**Issue by qiuhd2015** [NervJS/taro-ui#314]
问题描述
taro-ui1.5.4版本测试Button在H5平台报错，回退到1.5.3版本正常显示

复现步骤
[复现问题的步骤]
1.taro inint myapp
2.npm install taro-ui
3.在项目config增加以下配置
h5: {
esnextModules: ['taro-ui']
}
4.在index.js 文件 增肌Button 相关代码
import { AtButton } from 'taro-ui'
<AtButton>按钮文案</AtButton>

期望行为
正常显示button

**报错信息**

> myapp@1.0.0 build:h5 E:\jxlwork\trunk\wechat\myapp
> taro build --type h5 "--watch"

� Taro v1.2.3

开始编译项目 myapp
创建  发现文件  src\app.js
创建  发现文件  src\app.scss
创建  发现文件  src\index.html
创建  发现文件  src\pages\index\index.js
创建  发现文件  src\pages\index\index.scss

�   Failed to compile.

./node_modules/_taro-ui@1.5.4@taro-ui/dist/h5/components/pagination/index.js 101
:11
Module parse failed: Unexpected token (101:11)
You may need an appropriate loader to handle this file type.
|     };
|
>     return <View className={classNames(rootClassName, classObject, this.props.
className)} style={customStyle}>
|         <View className="at-pagination__operate">
|           <View className="at-pagination__btns">

**系统信息**

Taro v1.2 及以上版本已添加 taro info 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
Taro v1.2.3
Taro CLI 1.2.3 environment info:
System:
OS: Windows 7
Binaries:
Node: 10.9.0 - C:\Program Files\nodejs\node.EXE
npm: 6.2.0 - C:\Program Files\nodejs\npm.CMD

Taro 版本 [1.2.3]
Taro UI 版本 [1.5.4]
报错平台 [h5]

**Comment by koppthe** [comment]
Duplicate of #313

**Comment by qiuhd2015** [comment]
> 是这个问题导致的，麻烦升级到 taro v1.2.4 版本
> [NervJS/taro#1796](https://github.com/NervJS/taro/pull/1796)

升级后正常了

**Comment by maskwang** [comment]
v1.2.16是坏的。。。

**Comment by nicholasxuu** [comment]
v1.2.19仍然是坏的

**Comment by koppthe** [comment]
麻烦将 taro-ui 升级到最新版本吧
