### ISSUE TITLE
[Improvement] Tabs 组件高度问题

### ISSUE THREAD

**Issue by vimcaw** [NervJS/taro-ui#32]
由于只是把别的 Tab 栏显示在屏幕外部，所以目前 Tab 栏每一项的高度是一样的，由最高的那个决定，这个体验很不好（见下图），而且对于滚动到底部加载的情况更是噩梦，希望能改进一下。

![2018-08-30_10-46-03_mini](https://user-images.githubusercontent.com/21964227/44826875-1b8fdf00-ac43-11e8-9aed-12634477727b.gif)

**Comment by jimczj** [comment]
bug已修复并发版，请安装最新版本并根据文档编写

**Comment by StarCarrol** [comment]
问题还存在啊"taro-ui": "^2.0.0-beta.2"

**Comment by StarCarrol** [comment]
问题还存在，版本"taro-ui": "^2.0.0-beta.2" 
![image](https://user-images.githubusercontent.com/32662238/51781860-d2907800-2159-11e9-8cf9-9d3838bbebac.png)
![image](https://user-images.githubusercontent.com/32662238/51781862-edfb8300-2159-11e9-93dc-ebe2abe43b6e.png)
tab项两边内容高度不一样，内容少的一边，会出现空白区域 @jimczj
