### ISSUE TITLE
tabs点击事件触发两次

### ISSUE THREAD

**Issue by shaodushu** [NervJS/taro-ui#321]
**问题描述**

点击tabs组件，onClick事件触发两次

代码：
![image](https://user-images.githubusercontent.com/26360246/50806261-d71ef900-1330-11e9-8490-133d82f762bf.png)

小程序效果:
![image](https://user-images.githubusercontent.com/26360246/50806433-9673af80-1331-11e9-8b60-ab76a9668a3f.png)

**复现步骤**
如上

**期望行为**
点击tabs组件，onClick事件触发一次

**报错信息**
无

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

👽 Taro v1.2.4

  Taro CLI 1.2.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 11.4.0 - D:\nodejs\node.EXE
      npm: 6.4.1 - D:\nodejs\npm.CMD

`
taro-ui
![image](https://user-images.githubusercontent.com/26360246/50806701-b657a300-1332-11e9-8213-5942b3751730.png)

**Comment by zhangzhengyou** [comment]
自己去改源码。componentWillReceiveProps(nextProps) {
    if (nextProps.scroll !== this.props.scroll) {
      this.getTabHeaderRef();
    }
   /* if (nextProps.current !== this.state.current) {
      this.handleClick(nextProps.current);
    } */
  }
注释掉就好了
