### ISSUE TITLE
AtInput onChange  在部分android手机获取不到值

### ISSUE THREAD

**Issue by Young1993** [NervJS/taro-ui#323]
"taro-ui":` "^1.5.4"
"@tarojs/taro": "^1.2.2"

android 手机为 android 8.0 
三星S6、荣耀9  
`<AtInput className= 'input-phone'
            name='value'
            title=''
            type='phone'
            maxLength="11"
            placeholder='请输入手机号'
            error = {this.state.error}
            value={this.state.value}
            onChange={this.handleChange.bind(this)}/>`
长度和 onChange都无效

**Comment by jimczj** [comment]
h5 还是小程序

**Comment by Young1993** [comment]
> h5 还是小程序

h5

**Comment by jinjinjin0731** [comment]
@Young1993  具体的 taro 版本号是？
