### ISSUE TITLE
AtFloatLayout 组件希望增加新的属性

### ISSUE THREAD

**Issue by guozilin** [NervJS/taro-ui#327]
1.希望当 title 为空的时候，title 行的背景色也不要出现，目前 title 为空，title 的 标签依旧存在
2.希望该组件可以支持传入一个组件，类似于一个 slot
3.希望该组件可以支持样式覆盖

**Comment by guozilin** [comment]
看了源码，里面从 props 接收一个 className, 借助这个实现了样式覆盖
![image](https://user-images.githubusercontent.com/17874134/50891592-94941400-1437-11e9-9f1f-c7350264ef0a.png)

**Comment by DreamPWJ** [comment]
希望添加设置高度的属性和title 背景颜色已经文本是否居中等属性，非常常用@SzheJason

**Comment by koppthe** [comment]
@DreamPWJ  样式的问题可以看看「自定义主题」的文档
