### ISSUE TITLE
示例小程序里在三级页面里的cell分割线有点粗

### ISSUE THREAD

**Issue by terranc** [NervJS/taro-ui#33]
正常的：
![img_1805](https://user-images.githubusercontent.com/224353/44831164-df1aae00-ac57-11e8-91b4-dd90402c0b71.PNG)

粗的：
![img_1806](https://user-images.githubusercontent.com/224353/44831179-f48fd800-ac57-11e8-9642-65d8ac8d525b.PNG)

**Comment by SzHeJason** [comment]
@terranc 可以看这个评论 [#15](https://github.com/NervJS/taro-ui/issues/15#issuecomment-416520032)

**Comment by terranc** [comment]
如果是暂时的计算方案问题，那为什么会有的粗有的细？
