### ISSUE TITLE
AtSearchBars输入时，placeholder重影

### ISSUE THREAD

**Issue by learn-js2016** [NervJS/taro-ui#339]
**问题描述**
AtSearchBars输入时，placeholder重影
![c09a268f2b0fa7d42f1b088d15bb7ce](https://user-images.githubusercontent.com/24432864/51071399-39f2f600-168b-11e9-8187-ca648adf01ea.jpg)

```js

      <AtSearchBar
            value={value}
             placeholder='请输入...'
             onChange={this.search}
         />
```

 - Taro v1.2.4
 - Taro UI  v1.5.2
 - 报错平台  weapp

**Comment by jimczj** [comment]
@learn-js2016 你似乎看不懂我的回答？都说了真机上不会。。。。，这是微信小程序开发者工具的问题，可以忽略

**Comment by learn-js2016** [comment]
@jimczj 我这就是用的真机微信扫你们小程序二维码 的截图  手机输入还是预览没确认的时候placeholder 没有隐藏  正常input 是会隐藏的

**Comment by jimczj** [comment]
@learn-js2016 你用的是什么手机，什么输入法，在没确定字符的时候，字符也会在输入框上面？

**Comment by learn-js2016** [comment]
@jimczj 我的是小米6， 讯飞输入法 中文手写，同事的iphone6，iphoneX 拼音也会出现这个问题，但是用你们的Input 组件是不会有这个问题的

**Comment by tomgao365** [comment]
使用 onChange value 属性使组件可控，可解决上述问题  😂

**Comment by jimczj** [comment]
@tomgao365 该组件本身就是受控组件，该问题的原因应该是，部分输入法输入的时候，未确定输入字符，不会触发 onInput 事件
