### ISSUE TITLE
AtSearchBar底部的横线是否能去掉？

### ISSUE THREAD

**Issue by Lin-jing** [NervJS/taro-ui#342]
**问题描述**
AtSearchBar底部有一条横线，项目原型不需要这条线，但是在less中加上 border: none !important;去不掉

```js
// 这里可以贴代码
   <AtSearchBar
          className="searchbar"
          value={this.state.value}
          placeholder={'请输入商品名称进行搜索'}
          onChange={this.onChange.bind(this)}
        />
```

**期望行为**
希望搜索栏底下没有这条横线

**报错信息**

![image](https://user-images.githubusercontent.com/31055918/51100733-5bcab500-1812-11e9-83ae-dbbb7e94aa65.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - Taro 版本 [v.1.2.4]
 - Taro UI 版本 [v.1.5.4]
 - 报错平台 [ weapp]

**Comment by jimczj** [comment]
覆盖这里的样式
![image](https://user-images.githubusercontent.com/13499146/51102029-45bff300-1818-11e9-8c88-e6e64e367c99.png)

**Comment by kennylbj** [comment]
请问怎么覆盖呢？
border: none没效果

我看源码里是用mixin 加了
``@include hairline-bottom();``

**Comment by kennylbj** [comment]
找到办法了
```
.search {
  .at-search-bar {
    &::after {
      border: none;
    }
  }
}
```
