### ISSUE TITLE
taro-ui 在Flex布局，苹果与安卓样式不同？at-row at-row--wrap   at-col at-col-1 at-col--auto

### ISSUE THREAD

**Issue by xingwen93** [NervJS/taro-ui#343]
如下写法，实现的是每一行中的子View都是不确定宽度，每一行铺满则自动换行，
<View className='at-row at-row--wrap'>
 <View className='at-col at-col-1 at-col--auto'>子View</View>
</View>

但是安卓微信小程序显示正常，苹果小程序则不正常了，没有铺满就立马换行，
之前的taro-ui是可以的，最近升级到了1.5.4,发现出现了此问题。

Taro v1.2.4

  Taro CLI 1.2.4 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.1.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm

taro-ui
1.5.4

**Comment by xingwen93** [comment]
<View className='at-row at-row--wrap'>
				<View  className='at-col at-col-1 at-col--auto'>子View</View>
                   </View>
![image](https://user-images.githubusercontent.com/16276222/51101617-4fe0f200-1816-11e9-97f2-9f3c1dea1f5e.png)

**Comment by SzHeJason** [comment]
意思是 `col` 要随着内容增大而不断增大 然后还可以自动换行？

**Comment by SzHeJason** [comment]
可以提供代码吗 没有重现

**Comment by koppthe** [comment]
因无后续，该 issue 暂时关闭~
