### ISSUE TITLE
支付宝小程序中表单无法提交和重置

### ISSUE THREAD

**Issue by yxb1987** [NervJS/taro-ui#345]
**问题描述**
[问题描述：支付宝小程序中表单无法提交和重置，按钮事件不能触发
**复现步骤**
[复现问题的步骤]
使用本文档的例子代码即可重现
https://taro-ui.aotu.io/#/docs/form
**期望行为**
希望大佬能给个回答

**报错信息**

无报错

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

  Taro CLI 1.2.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 8.11.4 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD

  "dependencies": {
    "@tarojs/components": "1.2.4",
    "@tarojs/router": "1.2.4",
    "@tarojs/taro": "1.2.4",
    "@tarojs/taro-alipay": "1.2.4",
    "@tarojs/taro-h5": "1.2.4",
    "@tarojs/taro-swan": "1.2.4",
    "@tarojs/taro-tt": "1.2.4",
    "@tarojs/taro-weapp": "1.2.4",
    "nerv-devtools": "^1.3.9",
    "nervjs": "^1.3.9",
    "taro-ui": "^1.5.4"
**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by koppthe** [comment]
麻烦升级到 2.0-beta.1 版本哈，v1.5.4 没做支付宝小程序的适配
