### ISSUE TITLE
小程序组件样式丢失

### ISSUE THREAD

**Issue by 100cm** [NervJS/taro-ui#346]
![image](https://user-images.githubusercontent.com/12691638/51163291-24bcd800-18d4-11e9-8040-4bf414546590.png)
请问下我在微信开发者工具里打开的时候组件样式丢失。已经引入了index.scss

在手机里打开是样式正常的。但是在开发者工具里不正常。请问下这是谁的锅。。

**Comment by koppthe** [comment]
你开发者工具里面的基础版本库是 2.2.3 以上的吗？

**Comment by 100cm** [comment]
@koppthe 谢谢 已经解决了。 不知道为什么今天升级了系统就变成2.0得了。要改成2.2.3以上
