### ISSUE TITLE
日历组件（支付宝小程序），时间范围第二次和第三次点击才能连接范围&&没有默认选中

### ISSUE THREAD

**Issue by cgxqd123** [NervJS/taro-ui#347]
**问题描述**
[问题描述：日历组件（支付宝小程序），时间范围第二次和第三次点击才能连接范围]

**复现步骤**
[复现问题的步骤]

**没有默认选中单前时间**
![image](https://user-images.githubusercontent.com/36787884/51167879-ad427500-18e2-11e9-8116-2ca189f5ad59.png)

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

版本
![image](https://user-images.githubusercontent.com/36787884/51166799-af570480-18df-11e9-81e0-e6ad22ab9d3f.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - Taro 版本 [v1.2.4]
 - Taro UI 版本 [2.0.0-beta.1]
 - 平台[支付宝小程序]

**补充信息**
[可选]
期望返回一个时间范围的数据

**Comment by SzHeJason** [comment]
目前看来是 Taro 在生命周期的处理上有点问题 正在定位

**Comment by SzHeJason** [comment]
@Chen-jj 提交了 麻烦标注下 issue

**Comment by SzHeJason** [comment]
Taro 升级到 1.2.8 即可
