### ISSUE TITLE
AtTabs 无法切换Tab标签

### ISSUE THREAD

**Issue by ZenoZhengs** [NervJS/taro-ui#348]
**问题描述**

将项目编译成微信小程序后,AtTabs点击切换Tab,无法切换.
后来将项目编译成H5后,发现可以切换.
然后将AtTabs onClick: (index: number, event: BaseEventOrig<any>) => void的回调参数打印到控制台,
发现H5端的index为正常返回结果,而微信小程序中的index的返回结果和event一样,两个客户端的返回参数的截图将在 **报错信息** 中给出

**复现步骤**

问题代码如下:

```ts
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'
import { AtTabs } from 'taro-ui'
import { BaseEventOrig } from '@tarojs/components/types/common';
import './index.scss'

interface IMyComponentProps {}

interface IMyComponentStates {
  current: number
}

export default class TestAtTabs extends Component<IMyComponentProps, IMyComponentStates> {
  
  constructor(props: any) {
    super(props)
    this.state = {
      current: 0
    }
  }

  onTabsClick = (index: number, event: BaseEventOrig<any>) => {
    console.log(" index: ", index, "\n event: ", event)
    this.setState({
      current: index
    })
  }

  render() {
    return (
      <View className="container">
        <AtTabs className="container-tabs"
          scroll={true}
          current={this.state.current}
          tabList={[
            {ID: 0, title: 'title0'},
            {ID: 1, title: 'title1'},
            {ID: 2, title: 'title2'},
            {ID: 3, title: 'title3'},
            {ID: 4, title: 'title4'},
            {ID: 5, title: 'title5'},
            {ID: 6, title: 'title6'},
            {ID: 7, title: 'title7'},
          ]}
          onClick={this.onTabsClick.bind(this)}>
        </AtTabs>
      </View>
    )
  }
}
```

**期望行为**

希望微信小程序端也可以正常切换

**报错信息**

微信小程序端控制台信息如下:
![image](https://user-images.githubusercontent.com/45112245/51177085-9f4c1e80-18f9-11e9-9328-aa3a11151770.png)

H5端控制台信息如下:
![image](https://user-images.githubusercontent.com/45112245/51177217-f6ea8a00-18f9-11e9-9254-bf2b760e5acd.png)

**系统信息**

taro info 如下:
![image](https://user-images.githubusercontent.com/45112245/51176855-00bfbd80-18f9-11e9-9d61-f764220b11f6.png)

与taro相关的npm包如下:
![image](https://user-images.githubusercontent.com/45112245/51177469-a1fb4380-18fa-11e9-9f69-59223f8d0891.png)

**补充信息**

在 taro: 1.2.3     taro-ui: 1.5.4版本时AtTabs可以正常使用

**Comment by jimczj** [comment]
本地测试并无异常，执行下`taro update self  taro update project `升级下

**Comment by ZenoZhengs** [comment]
> 本地测试并无异常，执行下
> 
> ```
> taro update self
> taro update project
> ```
> 升级下

OK,非常感谢,升级后已经解决了
