### ISSUE TITLE
AtToast 文档描述与代码不符

### ISSUE THREAD

**Issue by yujiaming890321** [NervJS/taro-ui#349]
**问题描述**
AtToast 文档描述与代码不符

toast/index.js 123行
直接使用默认样式，并没有像文档描述那样获取 iconSize，iconColor
```js
<AtIcon customStyle={{ fontSize: '50px' }} value={icon} color='white' />
```
@types/toast.d.ts 接收的参数也需要修改

**系统信息**
 - Taro UI 版本 [1.5.4]

**Comment by SzHeJason** [comment]
由于 自定义主题 的原因所以不再使用 AtIcon 所以有一些文档没改过来 想要改变颜色 大小 可参考样式覆盖的方式
