### ISSUE TITLE
AtAccordion alipay小程序 无法正常使用

### ISSUE THREAD

**Issue by neuyu** [NervJS/taro-ui#351]
**AtAccordion alipay小程序 无法正常使用**
支付宝小程序端在使用手风琴时，无法正常展示

**代码**
```
<AtAccordion title='标题' >
        <AtList hasBorder={false}>
                <AtListItem title='标题文字' />
                <AtListItem title='标题文字' />
                 <AtListItem title='标题文字' />
         </AtList>
</AtAccordion>
```
**系统信息**
  Taro CLI 1.2.7 environment info:
    System:
      OS: macOS Sierra 10.12
      Shell: 5.2 - /bin/zsh
    Binaries:
      Node: 10.11.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.2.7 => 1.2.7
      @tarojs/plugin-babel: 1.2.7 => 1.2.7
      @tarojs/plugin-csso: 1.2.7 => 1.2.7
      @tarojs/plugin-sass: 1.2.7 => 1.2.7
      @tarojs/plugin-uglifyjs: 1.2.7 => 1.2.7
      @tarojs/router: 1.2.7 => 1.2.7
      @tarojs/taro: 1.2.7 => 1.2.7
      @tarojs/taro-alipay: 1.2.7 => 1.2.7
      @tarojs/taro-h5: 1.2.7 => 1.2.7
      @tarojs/taro-swan: 1.2.7 => 1.2.7
      @tarojs/taro-tt: 1.2.7 => 1.2.7
      @tarojs/taro-weapp: 1.2.7 => 1.2.7
      @tarojs/webpack-runner: 1.2.7 => 1.2.7
      eslint-config-taro: 1.2.7 => 1.2.7
      eslint-plugin-taro: 1.2.7 => 1.2.7

**补充信息**
taro-ui版本 1.5.4

**Comment by koppthe** [comment]
taro-ui v2.0+ 才支持支付宝小程序哈
