### ISSUE TITLE
AtIndexes导入组件样式无法渲染

### ISSUE THREAD

**Issue by luoyelusheng** [NervJS/taro-ui#354]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
引入AtIndexes组件，并且引入AtIndexes组件样式，但是渲染之后却无法正常渲染成功
**复现步骤**
[复现问题的步骤]
js代码：
![image](https://user-images.githubusercontent.com/19357027/51308985-5ec9dd80-1a7e-11e9-89d4-55b6ed3f74e7.png)
css代码：
![image](https://user-images.githubusercontent.com/19357027/51309002-6b4e3600-1a7e-11e9-9ddd-5743c9f7e494.png)

[或者可以直接贴源代码，能贴文字就不要截图]

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]
正确渲染
**报错信息**

[这里请贴上你的**完整**报错截图或文字]
没渲染成功
![image](https://user-images.githubusercontent.com/19357027/51309090-9afd3e00-1a7e-11e9-91d2-719bf77149a7.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

   System:
      OS: macOS 10.14.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.2 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.2.1 => 1.2.4
      @tarojs/components: ^1.1.8 => 1.2.4
      @tarojs/plugin-babel: ^1.2.1 => 1.2.4
      @tarojs/plugin-csso: ^1.1.8 => 1.2.4
      @tarojs/plugin-sass: ^1.1.8 => 1.2.4
      @tarojs/plugin-uglifyjs: ^1.1.8 => 1.2.4
      @tarojs/router: ^1.1.8 => 1.2.4
      @tarojs/taro: ^1.1.8 => 1.2.4
      @tarojs/taro-alipay: ^1.1.8 => 1.2.4
      @tarojs/taro-h5: ^1.1.8 => 1.2.4
      @tarojs/taro-swan: ^1.1.8 => 1.2.4
      @tarojs/taro-weapp: ^1.2.1 => 1.2.4
      @tarojs/webpack-runner: ^1.1.8 => 1.2.4
      eslint-config-taro: ^1.1.8 => 1.2.4
      eslint-plugin-taro: ^1.1.8 => 1.2.4

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
假如直接导入全部样式，
```js
@import '~taro-ui/dist/style/index.scss';
```
则可以正常渲染，但是小程序本身有2mb的限制，引入后就超过了

**Comment by koppthe** [comment]
再 import 多一个样式吧
```scss
@import "~taro-ui/dist/style/components/list.scss";
```
