### ISSUE TITLE
自定义组件内不能附类名改写AtButton的样式，请问是什么原因

### ISSUE THREAD

**Issue by Lorrainelyp** [NervJS/taro-ui#359]
**问题描述**

- components目录下的自定义组件引用AtButton，给它附class改写样式，但不起作用；在pages目录下同样的操作可以改写样式；
- 若引用的是Button，则两个目录下都能用class改写样式；

**复现步骤**
[复现问题的步骤]

**期望行为**
请问下Taro-ui对小程序原生组件封装的原理，为何出现上诉现象

**报错信息**
无

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - Taro 版本 [1.2.3]
 - Taro UI 版本 [1.5.0]
 - 报错平台 [ weapp]

**补充信息**

**Comment by jimczj** [comment]
该问题在文档中有过说明，是微信小程序的限制
![image](https://user-images.githubusercontent.com/13499146/51364250-7f457680-1b16-11e9-8774-cb223e980893.png)
