### ISSUE TITLE
Picker 在AtTabs中编译成H5显示异常

### ISSUE THREAD

**Issue by neuyu** [NervJS/taro-ui#363]
**问题描述**
Picker 在AtTabs中编译成H5显示异常，微信小程序正常
**复现步骤**
[复现问题的步骤]
1. 定义2个tab,在第二个tab页，添加picker,
2. 点击picker，弹框
3. 弹框出现在第一个tab页

```js
<AtTabs current={this.state.current} tabList={this.tabList} onClick={this.handleClick.bind(this)}>
     <AtTabsPane current={this.state.current} index={0} >
          <LoanTab />
     </AtTabsPane>
     <AtTabsPane current={this.state.current} index={1}>
         <RewardTab />
     </AtTabsPane>
</AtTabs>

```

**期望行为**
在第二个tab页面，点击picker，应在第二个tab页弹框

**系统信息**
Taro UI版本 2.0.0-beta-2
👽 Taro v1.2.7

  Taro CLI 1.2.7 environment info:
    System:
      OS: macOS Sierra 10.12
      Shell: 5.2 - /bin/zsh
    Binaries:
      Node: 10.11.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.6.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.2.7 => 1.2.7
      @tarojs/plugin-babel: 1.2.7 => 1.2.7
      @tarojs/plugin-csso: 1.2.7 => 1.2.7
      @tarojs/plugin-sass: 1.2.7 => 1.2.7
      @tarojs/plugin-uglifyjs: 1.2.7 => 1.2.7
      @tarojs/router: 1.2.7 => 1.2.7
      @tarojs/taro: 1.2.7 => 1.2.7
      @tarojs/taro-alipay: 1.2.7 => 1.2.7
      @tarojs/taro-h5: 1.2.7 => 1.2.7
      @tarojs/taro-swan: 1.2.7 => 1.2.7
      @tarojs/taro-tt: 1.2.7 => 1.2.7
      @tarojs/taro-weapp: 1.2.7 => 1.2.7
      @tarojs/webpack-runner: 1.2.7 => 1.2.7
      eslint-config-taro: 1.2.7 => 1.2.7
      eslint-plugin-taro: 1.2.7 => 1.2.7

**Comment by jimczj** [comment]
你是将 picker 嵌套进去 AtTabs 吗，不要嵌套进去

**Comment by neuyu** [comment]
> 你是将 picker 嵌套进去 AtTabs 吗，不要嵌套进去

为什么不可以呢，AtTabs里面嵌套的是多个页面，各个页面里对应的着不同的组件

**Comment by jimczj** [comment]
该 issue 长期没有回复，将关闭

**Comment by LaughingZhu** [comment]
> > 你是将 picker 嵌套进去 AtTabs 吗，不要嵌套进去
> 
> 为什么不可以呢，AtTabs里面嵌套的是多个页面，各个页面里对应的着不同的组件，如果不进行嵌套，其他tab如何使用picker？

兄弟，你怎么解决的，我也遇到了这个问题

**Comment by LaughingZhu** [comment]
> 你是将 picker 嵌套进去 AtTabs 吗，不要嵌套进去
如果想实现类似的效果，有什么替代方案吗

**Comment by xiangcaozhu** [comment]
该问题，依然存在，不修复么？
