### ISSUE TITLE
请问有经验的大佬们下面这种多选的组件在微信小程序中该如何实现？

### ISSUE THREAD

**Issue by 419280377** [NervJS/taro-ui#364]
请问有经验的大佬们下面这种多选的组件该如何实现？
![image](https://user-images.githubusercontent.com/20454290/51477403-57c70600-1dc3-11e9-875e-be42281509c5.png)

**Comment by kennylbj** [comment]
Taro-UI的[Tag](https://taro-ui.aotu.io/#/docs/tag)

**Comment by 419280377** [comment]
> Taro-UI的[Tag](https://taro-ui.aotu.io/#/docs/tag)

灰常感谢！！
