### ISSUE TITLE
AtMessage嵌套在AtTabs 显示异常

### ISSUE THREAD

**Issue by neuyu** [NervJS/taro-ui#365]
**问题描述**
AtTabs有多个AtTabsPane，第二个或之后的页面中，使用AtMessage，显示异常
**复现步骤**
[复现问题的步骤]
1. 打开页面
2. 点击第二个tab或之后的tab页
3. 点击某个按钮触发AtMessage
4. 显示异常，提示会出现在第一个tab页

```js
<AtTabs current={this.state.current} tabList={this.tabList} onClick={this.handleClick.bind(this)}>
      <AtTabsPane current={this.state.current} index={0} >
            <LoanTab />
      </AtTabsPane>
      <AtTabsPane current={this.state.current} index={1}>
            <RewardTab />
      </AtTabsPane>
</AtTabs>

```

**期望行为**
在正确的tab页面，弹出正确的消息提示

**报错信息**

![2019-01-22 10 49 29](https://user-images.githubusercontent.com/16551927/51509268-5e8d6180-1e33-11e9-9998-06b9a95e4a45.png)

**系统信息**
 - Taro 版本 [v1.2.7]
 - Taro UI 版本 [v2.0.0-beta-2]
 - 报错平台 [h5, weapp]

**Comment by jimczj** [comment]
使用前请看一下文档，而且 message 组件放页面就好了，一个页面只允许出现一个
![image](https://user-images.githubusercontent.com/13499146/51509482-4b2ec600-1e34-11e9-8a6e-cda5daa38727.png)

**Comment by neuyu** [comment]
> 使用前请看一下文档，而且 message 组件放页面就好了，一个页面只允许出现一个
> ![image](https://user-images.githubusercontent.com/13499146/51509482-4b2ec600-1e34-11e9-8a6e-cda5daa38727.png)

AtTabs组件内嵌套message,toast,action-sheet,modal,picker 这不是其最常用的需求吗

**Comment by neuyu** [comment]
在tab标签下，提示消息通知，在对应tab页面下，让用户选择地址，这些应该算是常规需求，如果把message组件放在页面，就做不到将消息通知位置放在对应tab标签下方了

**Comment by jimczj** [comment]
message 组件是为全局提供，你这种需求需要自己想办法解决

**Comment by JDshi** [comment]
> 不是，因为这些组件是页面级别的，一个页面一个就够了，甚至如果做成单页应用，一个应用只需一个。不需要将这些组件嵌套进去 tabs 组件，这些组件都是相对屏幕去布局的，嵌套进去，有什么用？

在各个tab标签下 分别使用picker modal组件很常见啊

**Comment by chenlongwill** [comment]
![image](https://user-images.githubusercontent.com/10081616/71359115-3c154280-25c6-11ea-8784-b4ea67658318.png)
![image](https://user-images.githubusercontent.com/10081616/71359271-d5dcef80-25c6-11ea-83cb-644ce7bc804d.png)

第一次进入列表是可以的，点击进入详情页面，再回来，报错后，在列表页面消息提示就失效了，在详情页一直可以

**Comment by Panfen** [comment]
无论是功能还是代码编写上，都会遇到在AtTab里面嵌套Modal、Message等的场景，还是希望尽可能解决该问题，而不是让开发者自己想办法
