### ISSUE TITLE
AtInput maxLength 输入框长度无效

### ISSUE THREAD

**Issue by giscafer** [NervJS/taro-ui#369]
同#273 的问题，真机调试也不行。idcard也没有限制长度，加了maxLength也不起作用

```html
 <AtInput
              clear
              name='certificateNo'
              title='身份证号码'
              type='idcard'
              maxLength='18'
              border={false}
              placeholder='请输入身份证号码'
              disabled={canEditInput}
              value={this.state.certificateNo}
              onChange={this.handleChange.bind(this, 'certificateNo')}
            />
```
`maxLength={18}` 也试过不行

版本：`	"taro-ui": "1.5.4"`

![1111](https://user-images.githubusercontent.com/8676711/51596011-fc1b8a80-1f32-11e9-8155-90fd14602ad1.jpg)

![tarointpu](https://user-images.githubusercontent.com/8676711/51599625-0fcaef00-1f3b-11e9-9571-e56e0f6a93bf.png)

**Comment by jimczj** [comment]
升级到 2.0 以上版本试试

**Comment by giscafer** [comment]
@jimczj 2.0根据文档按需引入报错，全量引入可以。但是不想全量引入

![tim 20190122183237](https://user-images.githubusercontent.com/8676711/51656960-d7c8b800-1fdd-11e9-9a76-b5781b667749.png)

```
taro info
👽 Taro v1.2.8


  Taro CLI 1.2.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.4.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.9.4 - C:\Users\nickbing\AppData\Roaming\npm\yarn.CMD
      npm: 6.1.0 - C:\Program Files\nodejs\npm.CMD
```

**Comment by xsfxtsxxr** [comment]
3.0.0-alpha.3咋又不行啦

**Comment by xsfxtsxxr** [comment]
有个变通的方法，在onChange方法监听value的长度，如果value.length<maxLength,才可以setState()

**Comment by cat-kun** [comment]
3.0.0-alpha.3 maxlength 不生效。太坑了吧

**Comment by cocoyk** [comment]
3.0 alpha版本maxlength有拼写错误   有pull request了 还没合进去

**Comment by liuyunzyj** [comment]
3.0.0-alpha.9版本 使用maxlength 设置还是无效
