### ISSUE TITLE
ActionSheet组件在IPHONEX机型，会出现底部镂空情况。

### ISSUE THREAD

**Issue by SubinY** [NervJS/taro-ui#373]
**问题描述**
ActionSheet组件在IPHONEX机型，会出现底部镂空情况。
![image](https://user-images.githubusercontent.com/21135159/51722182-84af3d80-208f-11e9-8f36-9dfebc19f8bf.png)

**期望行为**

**报错信息**

**系统信息**

**Comment by koppthe** [comment]
这看着不像 taro-ui 里面的 ActionSheet

**Comment by JokerLoLgrey** [comment]
> **问题描述**
> ActionSheet组件在IPHONEX机型，会出现底部镂空情况。
> ![image](https://user-images.githubusercontent.com/21135159/51722182-84af3d80-208f-11e9-8f36-9dfebc19f8bf.png)
> 
> **期望行为**
> 
> **报错信息**
> 
> **系统信息**

这个不是bug吧，明显是故意做的兼容啊

**Comment by SubinY** [comment]
下图第二种写法就是我建的问题图片写法，但是直接用taro-ui的也会出现这种兼容问题，模拟器不会，IPHONEX真机会出现镂空
![image](https://user-images.githubusercontent.com/21135159/51956466-b73baa80-2482-11e9-90af-2f39723e4f9b.png)
![image](https://user-images.githubusercontent.com/21135159/51956492-ce7a9800-2482-11e9-924b-7a3a91d35c14.png)

**Comment by SzHeJason** [comment]
就像楼上所说 这不是 bug  使用的是对 IPHone X 的兼容模式constant(safe-area-inset-bottom)
