### ISSUE TITLE
ActivityIndicator, Button等Loading显示异常

### ISSUE THREAD

**Issue by ZenoZhengs** [NervJS/taro-ui#379]
**问题描述**

Loading显示异常,异常截图在**报错信息**中贴出, 测试代码工程地址在**复现步骤**贴出

**复现步骤**

https://github.com/ZenoZhengs/taro-test

**期望行为**

Loading显示正常

**报错信息**

![image](https://user-images.githubusercontent.com/45112245/51798528-d94ce700-224e-11e9-86f1-4884e5689546.png)

**系统信息**

![image](https://user-images.githubusercontent.com/45112245/51798537-144f1a80-224f-11e9-8dad-2b3aaeef4b97.png)

**Comment by koppthe** [comment]
因为少引入了一个样式文件
```
@import "~taro-ui/dist/style/components/loading.scss";
```
