### ISSUE TITLE
tabbar 切换异常以及AtBtton功能缺失

### ISSUE THREAD

**Issue by crper** [NervJS/taro-ui#38]
具体效果如下

**没有路由跳转的情况下,变动index是正常的**

![image](https://user-images.githubusercontent.com/8272877/44897377-080d7280-ad2e-11e8-90ad-81c14014bc24.png)

**加入路由跳转之后就不正常了,其他页面的构造函数初始化`current`无效,效果如下**

![image](https://user-images.githubusercontent.com/8272877/44897454-51f65880-ad2e-11e8-896b-b40570e37569.png)

---

首页和关于是两个页面,
都加载了tabbar这个组件. 都是在构造函数中初始化的
第一个页面的索引设置0 , 第二个页面设置1;
同一个页面变动state是正常的,
当从路由跳转过去的时候是不正常的

**Comment by crper** [comment]
还有`AtButton`目前不支持原生授权事件onGetUserInfo这些

**Comment by jimczj** [comment]
你好，如果你的 tabbar 是全局都用到的话，应该用全局变量或 redux 之类的去管理 current变量

**Comment by crper** [comment]
@jimczj 我试试在redux用 ...等会有问题再留言

**Comment by crper** [comment]
taro 似乎不能跨页面共享redux ??

在第一个页面已经变动的store,再第二个页面connect链接拿到的值都是store初始化的值...

是我理解不对么...redux不能做跨页面共享!! 只能类似浏览器内单页面的组件通讯!

**Comment by jimczj** [comment]
具体可以看文档 https://nervjs.github.io/taro/redux.html

**Comment by canfeit** [comment]
@jimczj AtButton的onGetUserInfo不生效，怎么解决

**Comment by jimczj** [comment]
请另外开 issue 提问，贴出代码，报错信息
