### ISSUE TITLE
使用习惯

### ISSUE THREAD

**Issue by 1617634** [NervJS/taro-ui#381]
能用api的形式调一些组件吗 比如 toast  modal  loading之类的
现在必须要在当前页面render里面 插入这个组件 然后通过改变state 触发 感觉这样好繁琐

![image](https://user-images.githubusercontent.com/40844332/51880853-c7388900-23b3-11e9-98e3-d0a061c0dac5.png)

不能直接 taro.Toast('123') 这样吗，render里面也别让插东西了 多方便

**Comment by SzHeJason** [comment]
这个我之前回复过 
1. React 的组件方式就是通过这样的 setState 处理的，其他 React 库有提供这种 API 的是通过 React.render 函数 (小程序不支持动态插入)
2. 第三方组件最好不要用 `消息机制` 的存在 因为使用者永远不知道这个消息的触发逻辑 

所以目前 Toast 是无法处理这个的需求，如何解决？
自己项目通过 [消息机制](https://nervjs.github.io/taro/docs/events.html#docsNav) 来处理
