### ISSUE TITLE
手风琴组件Accordion，当AtAccordion内容区的内容变化时，就会导致内容高度一直是零（类名为类似accordion-JBKMBEIJ）（）

### ISSUE THREAD

**Issue by wangxv** [NervJS/taro-ui#384]
**问题描述**
手风琴组件Accordion，当AtAccordion内容区的内容变化时，就会导致内容高度一直是零（类名为类似accordion-JBKMBEIJ）

**复现步骤**

1.写一个手风琴组件
2.点击某一项修改样式
3.点击其他箭头按钮
4.打不开

![image](https://user-images.githubusercontent.com/30195186/52039462-8c7b5000-256f-11e9-9d94-e3c9c438daea.png)
![image](https://user-images.githubusercontent.com/30195186/52039688-23e0a300-2570-11e9-9bed-b7546de63567.png)
![image](https://user-images.githubusercontent.com/30195186/52039717-39ee6380-2570-11e9-96f0-84865bdbbbbb.png)
![image](https://user-images.githubusercontent.com/30195186/52039753-55f20500-2570-11e9-82e1-0cf3b2d42fa0.png)
![image](https://user-images.githubusercontent.com/30195186/52039783-6efab600-2570-11e9-9977-649ddb2b43c0.png)

```js
  //点击视频跳转到相应页面
  clickVideo(id) {
    console.log(id)
    this.setState({
      currentLessonId: id
    })
  }
 //渲染章节列表
    const { currentLessonId, currentChapterId, initLessonId }: any = this.state
    const courseDom = courseChapter.map((item: any, index: number) => {
      let temLesson = item.lesson.map((lesson: any, index1: number) => {
        return (
          <View
            key={index1}
            onClick={this.clickVideo.bind(this, lesson.id)}
            className="lesson-content"
          >
            <View className="lesson-info">
              <View>
                <Image
                  className="lesson-img"
                  src={getIconUrl(
                    lesson.resource.type,
                    lesson.resource.progress
                  )}
                />
              </View>
              <View
                className={
                  currentLessonId == lesson.id
                    ? 'lesson-name course-select'
                    : 'lesson-name'
                }
              >
                {item.displayOrder + '-' + lesson.displayOrder}
                <Text
                  className={
                    currentLessonId == lesson.id
                      ? 'lesson-title course-select'
                      : 'lesson-title'
                  }
                >
                  {lesson.title}
                </Text>
              </View>
            </View>
            {lesson.resource.type !== 2 && (
              <View className="lesson-time">
                {this.getTime(lesson.resource.duration)}
              </View>
            )}
          </View>
        )
      })
      return (
        <View className="accordion-wrap" key={index}>
          <View className="accordion-num">
            {item.displayOrder > 10
              ? item.displayOrder
              : '0' + item.displayOrder}
          </View>
          <View className="accordion-content">
            <AtAccordion
              key={item.id}
              className="at-accordion"
              title={item.title}
              open={currentChapterId == item.id ? true : false}
            >
              <View className="lesson">{temLesson}</View>
            </AtAccordion>
          </View>
        </View>
      )
    })


    return (
      <View className="course-detail">

       {courseDom}
      </View>
    )
  }
}
```

**期望行为**
希望可以正常打开
**报错信息**
没有报错

**系统信息**

 - Taro 版本 [e.g. v.1.2.7]
 - Taro UI 版本 [e.g. v.2.0.0-beta.1]
 - 报错平台 [weapp]

**Comment by goodluck2018** [comment]
同样发现这个问题，动态改变AtAccordion下的内容就会出现无法展开的问题。

**Comment by koppthe** [comment]
Duplicate of #176

**Comment by wangxv** [comment]
已经更新到2.0.0在小程序开发工具上没有问题，但是在手机上测试就还是有这个问题

**Comment by wangxv** [comment]
![image](https://user-images.githubusercontent.com/30195186/52699605-19cb9500-2fb1-11e9-8c67-2e294c8c3176.png)
手机上显示requestAnimationFrame 没有定义

**Comment by jimczj** [comment]
已修复

**Comment by Snnny** [comment]
版本2.01 开发者工具遇到相同的情况，第一次能展开，修改再编译就无法打开了
`import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'
import { AtTabsPane, AtAccordion, AtList, AtListItem} from 'taro-ui'

class Course extends Component {
  constructor(props) {
    super(props)
    this.state = {
      number: 0,
    }
  }
  handleClick(index, value) {
    console.log(index, value)
    console.log('state', this.state, `accordion${index}`)
    this.setState({
      [`accordion${index}`]: value,
    })
  }

  render() {
    const data = [
      {
        time: '周一',
        course: [{
          title: '标题文字',
          note: '描述信息',
          thumb: 'https://img12.360buyimg.com/jdphoto/s72x72_jfs/t6160/14/2008729947/2754/7d512a86/595c3aeeNa89ddf71.png'
        },{
          title: '标题文字',
          note: '描述信息',
          thumb: 'https://img12.360buyimg.com/jdphoto/s72x72_jfs/t6160/14/2008729947/2754/7d512a86/595c3aeeNa89ddf71.png'
        },{
          title: '标题文字',
          note: '描述信息',
          thumb: 'https://img12.360buyimg.com/jdphoto/s72x72_jfs/t6160/14/2008729947/2754/7d512a86/595c3aeeNa89ddf71.png'
        }]
      },
      {
        time: '周二',
        course: [{
          title: '标题文字',
          note: '描述信息',
          thumb: 'https://img12.360buyimg.com/jdphoto/s72x72_jfs/t6160/14/2008729947/2754/7d512a86/595c3aeeNa89ddf71.png'
        },{
          title: '标题文字',
          note: '描述信息',
          thumb: 'https://img12.360buyimg.com/jdphoto/s72x72_jfs/t6160/14/2008729947/2754/7d512a86/595c3aeeNa89ddf71.png'
        }]
      }
    ]
    console.log(this.state)
    return(
      <View> 
        {
          data.map((accordion, index)=> {
            return <AtAccordion
            key={index}
            open={!!this.state[`accordion${index}`]}
            onClick={this.handleClick.bind(this, index)}
            title='标题一'
          >
            <AtList hasBorder={false}>
              {
                accordion.course.map((item, i)=> {
                  return <AtListItem
                    key={`${index}-${i}`}
                    title='标题文字'
                    arrow='right'
                    thumb='https://img12.360buyimg.com/jdphoto/s72x72_jfs/t6160/14/2008729947/2754/7d512a86/595c3aeeNa89ddf71.png'
                  />
                })
              }
            </AtList>
          </AtAccordion>
          })
        }
      </View>
    )
  }
}

export default Course
`
