### ISSUE TITLE
版本1.5.4使用AtList/AtListItem在h5情况下标题汉字会变为Unicode编码

### ISSUE THREAD

**Issue by xiaobao7830** [NervJS/taro-ui#385]
**问题描述**
使用列表组件(AtList/AtListItem)时,在运行H5情景下,汉字会变为Unicode编码

**复现步骤**
1.官网拷贝AtList/AtListItem 案例.到本地代码中
2.运行npm run dev:h5
3.打开对应页面,页面显示[%u4FEE%u6539%u5BC6%u7801]等Unicode编码
4.切换ui版本到2.0问题依旧

注:暂未测试微信小程序

```js
<View>
          <AtList>
            <AtListItem title='我的订单' arrow='right' iconInfo={{
              size: 25,
              color: '#FF4949', value: 'bullet-list',
            }} />
            <AtListItem title='消息中心' arrow='right' iconInfo={{
              size: 25,
              color: '#FF4949', value: 'message',
            }} />
            <AtListItem title='个人资料' arrow='right' iconInfo={{
              size: 25,
              color: '#FF4949', value: 'user',
            }} />
            <AtListItem title='修改密码' arrow='right' iconInfo={{
              size: 25,
              color: '#FF4949', value: 'alert-circle',
            }} />
            <AtListItem title='修改手机号' extraText="152******7108" arrow='right' iconInfo={{
              size: 25,
              color: '#FF4949', value: 'iphone',
            }} />
          </AtList>
        </View>
```
参考渲染后的页面
```html
<div class="at-list__item"><div class="at-list__item-container"><div class="at-list__item-icon item-icon"><span class="taro-text at-icon at-icon-user" style="color: rgb(255, 73, 73); font-size: 25px;"></span></div><div class="at-list__item-content item-content"><div class="item-content__info"><div class="item-content__info-title">%u4E2A%u4EBA%u8D44%u6599</div></div></div><div class="at-list__item-extra item-extra"><div class="item-extra__icon"><span class="taro-text at-icon at-icon-chevron-right" style="font-size: 24px; color: rgb(199, 199, 204);"></span></div></div></div></div>
```

**期望行为**
希望能正常显示中文

**报错信息**
控制台仅有警告提示
./node_modules/taro-ui/dist/h5/components/avatar/index.js 66:34-42
"export 'OpenData' was not found in '@tarojs/components'

**系统信息**
Taro v1.2.12

  Taro CLI 1.2.12 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 10.5.0 - /usr/local/bin/node
      Yarn: 1.12.3 - ~/tools/node-v10.5.0-linux-x64/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.12 => 1.2.12
      @tarojs/components: 1.2.12 => 1.2.12
      @tarojs/plugin-babel: 1.2.12 => 1.2.12
      @tarojs/plugin-uglifyjs: 1.2.12 => 1.2.12
      @tarojs/redux: 1.2.12 => 1.2.12
      @tarojs/redux-h5: 1.2.12 => 1.2.12
      @tarojs/router: 1.2.12 => 1.2.12
      @tarojs/taro: ^1.2.12 => 1.2.12
      @tarojs/taro-alipay: 1.2.12 => 1.2.12
      @tarojs/taro-h5: 1.2.12 => 1.2.12
      @tarojs/taro-swan: 1.2.12 => 1.2.12
      @tarojs/taro-tt: 1.2.12 => 1.2.12
      @tarojs/taro-weapp: 1.2.12 => 1.2.12
      nervjs: ^1.3.12 => 1.3.12

 - Taro 版本 1.2.12
 - Taro UI 版本 1.5.4
 - 报错平台 h5

**补充信息**
无

**Comment by koppthe** [comment]
Duplicate of #387

**Comment by koppthe** [comment]
麻烦升级 taro 至 v1.2.13
