### ISSUE TITLE
AtRadio onClick回调无法获取返回值

### ISSUE THREAD

**Issue by goodluck2018** [NervJS/taro-ui#386]
**问题描述**
如题，AtRadio返回值为undefined。

**相关代码**
```js
//data
const modeData = [
    { label: 'test0', value: '0' },
    { label: 'test1', value: '1' }
];

// method
handleModeData (value) {
    console.log('value', value); // undefined
}

// render
const { mode } = this.state;
<AtRadio
    options={modeData}
    value={mode}
    onClick={this.handleModeData.bind(this)}
/>
```

**期望行为**
根据文档，应当返回被点击的单项值。

**系统信息**
 - Taro 版本 [ v1.2.0-beta.2 ]
 - Taro UI 版本 [ 2.0.0-beta.2 ]
 - 报错平台 [weapp]

**类似的issue**
[issue 182](https://github.com/NervJS/taro-ui/issues/182#issue-380809108)

**Comment by koppthe** [comment]
taro 升级到最新版本试试

**Comment by UZIhuhuhu** [comment]
升级一下全局 taro 版本
taro 1.2.13
tao-ui 2.0.0

**Comment by goodluck2018** [comment]
> 升级一下全局 taro 版本
> taro 1.2.13
> tao-ui 2.0.0

将全局taro升级到1.2.13后，可以获取到数据了，谢谢:)
