### ISSUE TITLE
SegmentedControl onClick返回值无法获取索引值

### ISSUE THREAD

**Issue by goodluck2018** [NervJS/taro-ui#388]
**问题描述**
如题。

**相关代码**
```js
// method
handleChangeTab (value) {
    console.log('value', value);
}

// render
const { current } = this.state;

<AtSegmentedControl
    current={current}
    values={['tab1', 'tab2']}
    onClick={this.handleChangeTab.bind(this)}
/>
{/* 1.1 tab1 */}
{current === 0
    ? <AddProperty />
    : null
}
{/* 1.2 tab2 */}
{current === 1
      ? <AddRecord />
      : null
}
```

**实际输出**
![实际输出截图](http://github-doc.oss-cn-shenzhen.aliyuncs.com/issue/taro-ui-SegmentedControl%20onClick%E8%BF%94%E5%9B%9E%E5%80%BC%E6%97%A0%E6%B3%95%E8%8E%B7%E5%8F%96%E7%B4%A2%E5%BC%95%E5%80%BC.jpg)

**期望行为**
根据文档，SegmentedControl在onClick后应当能获取所点击的tab索引值。

**系统信息**
 - Taro 版本 [ v1.2.10 ]
 - Taro UI 版本 [ 2.0.0-beta.2 ]
 - 报错平台 [weapp]

**Comment by koppthe** [comment]
升级到最新版本的 taro 试试

**Comment by koppthe** [comment]
Duplicate of #386
