### ISSUE TITLE
引入taro-ui样式失败

### ISSUE THREAD

**Issue by ghyzx** [NervJS/taro-ui#393]
**问题描述**
若在app.js文件中通过 import 'taro-ui/dist/style/index.scss'  没有报错，也无任何效果；
若在app.css文件中通过 @import "~taro-ui/dist/style/index.scss";  直接报错
<img width="421" alt="error" src="https://user-images.githubusercontent.com/5229158/52703466-5d2a0180-2fb9-11e9-970d-75d8f2bff07e.png">

config/index.js 已经加入配置    esnextModules: ['taro-ui'],

taro info    信息如下：
👽 Taro v1.2.12

  Taro CLI 1.2.12 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.1 - /usr/local/bin/node
      npm: 6.7.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.2.12 => 1.2.12 
      @tarojs/plugin-babel: 1.2.12 => 1.2.12 
      @tarojs/plugin-csso: 1.2.12 => 1.2.12 
      @tarojs/plugin-sass: ^1.2.12 => 1.2.12 
      @tarojs/plugin-uglifyjs: 1.2.12 => 1.2.12 
      @tarojs/router: 1.2.12 => 1.2.12 
      @tarojs/taro: 1.2.12 => 1.2.12 
      @tarojs/taro-alipay: 1.2.12 => 1.2.12 
      @tarojs/taro-h5: 1.2.12 => 1.2.12 
      @tarojs/taro-swan: 1.2.12 => 1.2.12 
      @tarojs/taro-tt: 1.2.12 => 1.2.12 
      @tarojs/taro-weapp: 1.2.12 => 1.2.12 
      @tarojs/webpack-runner: 1.2.12 => 1.2.12 
      eslint-config-taro: 1.2.12 => 1.2.12 
      eslint-plugin-taro: 1.2.12

packag.json 信息如下：
"dependencies": {
    "@tarojs/components": "1.2.12",
    "@tarojs/router": "1.2.12",
    "@tarojs/taro": "1.2.12",
    "@tarojs/taro-alipay": "1.2.12",
    "@tarojs/taro-h5": "1.2.12",
    "@tarojs/taro-swan": "1.2.12",
    "@tarojs/taro-tt": "1.2.12",
    "@tarojs/taro-weapp": "1.2.12",
    "nerv-devtools": "^1.3.9",
    "nervjs": "^1.3.9",
    "taro-ui": "^2.0.0"
  },
  "devDependencies": {
    "@tarojs/plugin-babel": "1.2.12",
    "@tarojs/plugin-csso": "1.2.12",
    "@tarojs/plugin-sass": "^1.2.12",
    "@tarojs/plugin-uglifyjs": "1.2.12",
    "@tarojs/webpack-runner": "1.2.12",
    "@types/react": "^16.4.6",
    "@types/webpack-env": "^1.13.6",
    "babel-eslint": "^8.2.3",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-jsx-stylesheet": "^0.6.5",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "eslint": "^4.19.1",
    "eslint-config-taro": "1.2.12",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-taro": "1.2.12"
  }

**Comment by koppthe** [comment]
1. 微信基础库版本要设置成 v2.2.3+
2. 进 node_modules 里面确认一下 taro-ui 具体的版本号

**Comment by ghyzx** [comment]
感谢，   node_modules 里面确认taro-ui的版本是2.0.0
微信基础库版本设置成2.5.2 后，
1. 在app.js文件中通过 import 'taro-ui/dist/style/index.scss' 的方式 生效了；
2. 在app.css文件中通过 @import "~taro-ui/dist/style/index.scss"; 的方式 还是报上面 File not found 的错误；

**Comment by koppthe** [comment]
app.scss 里面 import 的代码可以截图看看吗？

**Comment by ghyzx** [comment]
<img width="1232" alt="css" src="https://user-images.githubusercontent.com/5229158/52758524-87c09c80-3043-11e9-9e33-e740123b96e9.png">

是说需要用app.scss，而不是app.css 吗？

**Comment by koppthe** [comment]
嗯嗯，怎么也得经过预处理吧
