### ISSUE TITLE
手风琴组件无法展开，手机上显示requestAnimationFrame 没有定义

### ISSUE THREAD

**Issue by wangxv** [NervJS/taro-ui#395]
**问题描述**
在微信开发工具中，可以展开没有错误，但是在手机中就会出现requestAnimationFrame 没有定义，手风琴无法展开
![image](https://user-images.githubusercontent.com/30195186/52699605-19cb9500-2fb1-11e9-8c67-2e294c8c3176.png) 

**复现步骤**
1.微信开发工具中选择，真机预览

**期望行为**
在手机端可以正常展开

**报错信息**
![image](https://user-images.githubusercontent.com/30195186/52699605-19cb9500-2fb1-11e9-8c67-2e294c8c3176.png) 

**系统信息**
 - Taro 版本 [e.g. v.1.2.7]
 - Taro UI 版本 [e.g. v.2.0.0]
 - 报错平台 [weapp]

**Comment by jimczj** [comment]
该问题已修复
