### ISSUE TITLE
h5端，引入Modal组件，'@tarojs/components' does not contain an export named 'OpenData'

### ISSUE THREAD

**Issue by vurtnr** [NervJS/taro-ui#398]
**问题描述**
项目引入Modal组件报错：
./node_modules/taro-ui/dist/h5/components/avatar/index.js 60:34-42
" '@tarojs/components' does not contain an export named 'OpenData'.
引入其他组件正常显示。

**复现步骤**
复制官网例子Modal组件，页面引入，保存报错。

**期望行为**
正常显示modal窗口

**报错信息**
![image](https://user-images.githubusercontent.com/8241528/52838837-f0d10e80-312e-11e9-8f37-c8847fef720c.png)

**系统信息**
![image](https://user-images.githubusercontent.com/8241528/52838859-06463880-312f-11e9-98b0-e392a74a07a2.png)

 - Taro 版本 [e.g. v.1.2.12]
 - Taro UI 版本 [e.g. v.2.0.0]
 - 报错平台 [h5]

**补充信息**
翻了node_modules里@tarojs的包，在1.2.12版本的@tarojs中未找到taro-ui2.0.0的avater组件需要使用OpenData组件。

**Comment by koppthe** [comment]
taro 升级到 v1.2.13 试试

**Comment by chengazhen** [comment]
### 怎么一直存在这个问题呢,使用的是 alpha10

**Comment by meiqinLiu** [comment]
> ### 怎么一直存在这个问题呢,使用的是 alpha10

请问您找到解决方案了吗，我现在用的也是  alpha10
