### ISSUE TITLE
style 不能作用于组件？

### ISSUE THREAD

**Issue by kenberkeley** [NervJS/taro-ui#4]
例如如下 style 无效

```jsx
<AtButton style="color: red">按钮文案</AtButton>
```

**Comment by cos2004** [comment]
@kenberkeley  大部分组件现在都没做 props style 的处理，但是很快会补全。可在外面包裹一层节点的方式去写样式

**Comment by kenberkeley** [comment]
布局啥可以外面包一层，但涉及到内部样式的修改则没办法

**Comment by jimczj** [comment]
@kenberkeley 内部样式可以定制化的，我们会开放`prop` 供用户自定义，单独在组件使用`style` 只能影响最外层节点样式

**Comment by amusiq** [comment]
外面包一层节点也改变不了taro UI 的样式，比如背景颜色和字体大小颜色之类的

**Comment by jimczj** [comment]
@amusiq 这些样式我们将根据组件特点，会去开放 props，外层 style 只能影响外层

**Comment by jimczj** [comment]
`1.2`版本后，传入 `customStyle` 可以对组件使用内联样式
