### ISSUE TITLE
atSwipeAction 当数据层级过深，侧滑无效

### ISSUE THREAD

**Issue by peng8934763** [NervJS/taro-ui#403]
**问题描述**
数据结构是个多层嵌套list，map数组 return对象 atSwipeAction的时候，侧滑效果无效，也有其他人遇到此类问题

**复现步骤**

补充信息提供了Demo
**期望行为**
正常侧滑效果

**报错信息**
没有报错，就是滑动失效

**系统信息**
👽 Taro v1.2.8

  Taro CLI 1.2.8 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.5.0 - ~/.nvm/versions/node/v8.13.0/bin/npm

**补充信息**

[demo.zip](https://github.com/NervJS/taro-ui/files/2873753/demo.zip)

**Comment by SzHeJason** [comment]
Taro UI 是什么版本？ 应该在 2.0.0 修复了

**Comment by peng8934763** [comment]
> 修复

**Comment by peng8934763** [comment]
> Taro UI 是什么版本？ 应该在 2.0.0 修复了
我的版本是1.5.4

**Comment by peng8934763** [comment]
我的版本是1.5.4，我先升级到1.5.4看看是否已经修复了，然后再来回复一下

**Comment by peng8934763** [comment]
@SzHeJason 我先升到2.0.0，再来回复一下

**Comment by SzHeJason** [comment]
duplicate #336

**Comment by SzHeJason** [comment]
没有复现出群里反馈的消息 且  提问者没有留下任何示例 
若 提问者看到该消息请 @我
