### ISSUE TITLE
AtNavBar 不支持小程序吗？

### ISSUE THREAD

**Issue by hyacinthus** [NervJS/taro-ui#405]
还以为可以在小程序隐藏导航栏，统一用 AtNavBar 。

试了一下好像并不会适应小程序的头部，包括躲避顶部的系统状态栏和右上角的关闭按钮。

难道只是提供一个 H5 的替代？ 要写条件用的？

其实有很多小程序都是自己实现的头部导航，这样可以在导航里放用户或者设置按钮，还是很好的。

**Comment by koppthe** [comment]
功能上是支持的，但视觉上，NavBar 是针对 H5 设计的，并不是小程序的 NavBar。微信小程序、支付宝小程序、百度小程序的 NavBar 设计规范都不一样，要如何统一呢？
另外你说的很多小程序都是自己实现的头部导航，这一点不同意哦。。

**Comment by hyacinthus** [comment]
哈哈，我说的是很多，不是大多~
想要适配各种刘海屏应该会稍微难一点。
不过最有用的场景就是扫描或者从群里进入一个详情页面，在navbar里显示一个Home按钮。 还有就是功能比较简单的应用，只要主页面和设置，就可以把设置放在navbar。

比较著名的是大辉的抽奖助手，NavBar就是自己写的。。

**Comment by koppthe** [comment]
AtNavBar 提供的是一个比较通用的 UI 组件，并不会区分 H5 和各类小程序做视觉上的差异化处理，所以你提的应用场景更适合自己写 NavBar。

**Comment by hyacinthus** [comment]
好吧，谢谢。
