### ISSUE TITLE
AtModal标题和按钮中的中文文字在h5显示异常

### ISSUE THREAD

**Issue by xinconan** [NervJS/taro-ui#407]
**问题描述**
照着文档写的简化使用，标题和按钮中的中文文字在h5被转码了，weapp正常显示

**复现步骤**

```js
<AtModal
          isOpened={showModal}
          title='最终到手'
          cancelText=''
          confirmText='确认'
          onConfirm={this.hideModal}
          content={result}
        />
```

**期望行为**
中文显示正常

**报错信息**
![image](https://user-images.githubusercontent.com/8479810/53059513-ff824180-34f1-11e9-81a6-b89ac4f7049d.png)

**系统信息**
 - Taro 版本 [v.1.2.12]
 - Taro UI 版本 [v.2.0.0]
 - 报错平台 [h5]

**Comment by koppthe** [comment]
taro 版本升级到 v1.2.13 即可
