### ISSUE TITLE
升级了最新版的 taro-ui，小程序的体积变大不小啊~ 有什么办法可以优化一下吗？

### ISSUE THREAD

**Issue by jswxwxf** [NervJS/taro-ui#408]
<img width="236" alt="2019-02-20 10 55 25" src="https://user-images.githubusercontent.com/1768767/53063534-6d813580-34ff-11e9-997b-f513649f8b51.png">

这是从 1.5.1 升级到 2.0.0 之后打包后小程序的大小变化 。

**Comment by koppthe** [comment]
可以试试按需引入，只引入用到的组件样式，taro 最好也升级到最新的版本

**Comment by jswxwxf** [comment]
taro 已经升到最新版了，至于按需引入，怎么做啊~ 能举个例子吗？

**Comment by xuhom** [comment]
在样式里引入
@import "~taro-ui/dist/style/components/tabs.scss";
脚本里应该也可以独立引入

**Comment by koppthe** [comment]
@jswxwxf  组件 js 会按需打包的，这个不用单独处理，组件样式的话，你可以按需引入需要的样式文件，例如：（记得升级 taro 版本）
```scss
@import "~taro-ui/dist/style/components/button.scss";
```

**Comment by jswxwxf** [comment]
嗯…… 看起来是个大工程，我还是先不升级吧，不过光css就要大好几百k吗？……

**Comment by koppthe** [comment]
不至于，得看看你打包之后的文件包含哪些内容了
