### ISSUE TITLE
组件库无法配置自适应尺寸

### ISSUE THREAD

**Issue by 704826318** [NervJS/taro-ui#411]
**问题描述**

刚开始用这个版本taro是发现自适应寸尺有问题，750的设计稿在实际项目中应用结果要小一半尺寸,
配置上我自己做了调整，但taro-ui无法适应，官方好像也没有尺寸配置功能，

```
  designWidth: 375,
  deviceRatio: {
    '640': 2.34 / 2,
    '750': 1,
    '828': 1.81 / 2,
    '375': 1 / 2
  }
```

这样配置之后taro-ui所有组件都普遍偏大

**系统信息**

 - Taro 版本 1.2.13
 - Taro UI 版本 ^2.0.0-beta.2
 - 报错平台 h5

**Comment by koppthe** [comment]
taro-ui 是按 750 的尺寸做的，既然你的设计稿也是 750， 为什么把 designWidth 设置成 375 呢？

**Comment by 704826318** [comment]
> taro-ui 是按 750 的尺寸做的，既然你的设计稿也是 750， 为什么把 designWidth 设置成 375 呢？

https://github.com/NervJS/taro/issues/1968
taro框架默认的750尺寸有问题所以我才改的，这是之前版本的问题，不知道为什么现在还有

**Comment by koppthe** [comment]
你用默认的配置，会出现什么问题？

**Comment by 704826318** [comment]
> 你用默认的配置，会出现什么问题？

用默认配置会出现比原设计稿的尺寸大一倍的问题

**Comment by jimczj** [comment]
此问题是 Taro 问题，此 issue 关闭

**Comment by dmwin72015** [comment]
自家的东西，尽然不兼容，好烦呦！

**Comment by zuibunan** [comment]
> 此问题是 Taro 问题，此 issue 关闭

@luckyadam 如何解决呢？

**Comment by crazyair** [comment]
> 此问题是 Taro 问题，此 issue 关闭

taro 要设置 375 而 taro ui 要 750，这两不能共存
