### ISSUE TITLE
taro ui 是否只支持模版是.scss的项目,.less模版的项目不支持呢

### ISSUE THREAD

**Issue by jinyindu** [NervJS/taro-ui#412]
**问题描述**

**复现步骤**

```js
// 这里可以贴代码
```

**期望行为**

**报错信息**

**系统信息**

**补充信息**

**Comment by jinyindu** [comment]
taro ui 是否只支持模版是.scss的项目,.less模版的项目不支持呢

**Comment by jinyindu** [comment]
less文件中引入以下报错
@import "~taro-ui/dist/style/components/image-picker.scss";

**Comment by koppthe** [comment]
less 文件当然没法引入 scss 文件，你可以改成在 js 里面引入
```
import 'taro-ui/dist/style/components/image-picker.scss'
```
