### ISSUE TITLE
You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by vurtnr** [NervJS/taro-ui#413]
**问题描述**
小程序端一切正常，dev:h5时报错，错误如下：
![image](https://user-images.githubusercontent.com/8241528/53155931-1eb7c680-35f9-11e9-9d8d-5778c7b039cb.png)

**复现步骤**
代码中并未引入countdown组件，编写完小程序端后，yarn dev:h5出现该错误

**期望行为**
h5端正常运行

**报错信息**
![image](https://user-images.githubusercontent.com/8241528/53156013-53c41900-35f9-11e9-807a-6fcdfd497515.png)

**系统信息**

 - Taro 版本 [e.g. v.1.2.13]
 - Taro UI 版本 [e.g. v.2.0.0]
 - 报错平台 [h5]
具体依赖信息如下：
Taro CLI 1.2.12 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.2.0 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.13 => 1.2.13
      @tarojs/components: 1.2.13 => 1.2.13
      @tarojs/plugin-babel: 1.2.13 => 1.2.13
      @tarojs/plugin-csso: 1.2.13 => 1.2.13
      @tarojs/plugin-less: 1.2.13 => 1.2.13
      @tarojs/plugin-sass: ^1.2.13 => 1.2.13
      @tarojs/plugin-uglifyjs: 1.2.13 => 1.2.13
      @tarojs/redux: 1.2.13 => 1.2.13
      @tarojs/redux-h5: 1.2.13 => 1.2.13
      @tarojs/router: 1.2.13 => 1.2.13
      @tarojs/taro: 1.2.13 => 1.2.13
      @tarojs/taro-alipay: 1.2.13 => 1.2.13
      @tarojs/taro-h5: 1.2.13 => 1.2.13
      @tarojs/taro-swan: 1.2.13 => 1.2.13
      @tarojs/taro-tt: 1.2.13 => 1.2.13
      @tarojs/taro-weapp: 1.2.13 => 1.2.13
      @tarojs/webpack-runner: 1.2.13 => 1.2.13
      eslint-config-taro: 1.2.12 => 1.2.12
      eslint-plugin-taro: 1.2.12 => 1.2.12
      nervjs: ^1.3.9 => 1.3.12
    npmGlobalPackages:
      typescript: 3.0.3

**Comment by koppthe** [comment]
写代码之前，先看文档哈
https://taro-ui.aotu.io/#/docs/quickstart
https://taro-ui.aotu.io/#/docs/questions

增加配置项：
```
h5: {
  esnextModules: ['taro-ui']
}
```
