### ISSUE TITLE
打包之后taro-ui的样式丢失，开发模式下一切正常

### ISSUE THREAD

**Issue by kucy** [NervJS/taro-ui#415]
![wx20190221-094721](https://user-images.githubusercontent.com/13210798/53137540-1d1cdd00-35be-11e9-9478-6b9ffa79ea25.png)
![wechatimg48](https://user-images.githubusercontent.com/13210798/53137541-1d1cdd00-35be-11e9-839a-ddbf95458c90.jpeg)
![wechatimg44](https://user-images.githubusercontent.com/13210798/53137543-1db57380-35be-11e9-9906-c1ed0b843e5e.jpeg)
![wechatimg45](https://user-images.githubusercontent.com/13210798/53137544-1e4e0a00-35be-11e9-9409-cd7a6d0d365f.jpeg)
![wechatimg43](https://user-images.githubusercontent.com/13210798/53137546-1e4e0a00-35be-11e9-9dc2-95a7b6e51d6c.jpeg)

**Comment by koppthe** [comment]
已修复，麻烦升级 v2.0.1 版本

**Comment by kucy** [comment]
> 已修复，麻烦升级 v2.0.1 版本

taro-ui 升级到2.0.1 ，问题并没有解决

**Comment by koppthe** [comment]
确定 taro v1.2.13 ，taro-ui v2.0.1？

**Comment by koppthe** [comment]
麻烦删了 node_modules 重新安装吧，你可能还是用的旧版本。样式没打包进去是因为原先的 `sideEffects` 配置错误，这个问题已经修复了的

**Comment by kucy** [comment]
貌似问题是我没运行过weapp版本，所以没装sass-plugin。一直dev和build的h5版本。后来试了跑了下weapp版本。提示需要安装sass-plugin.装完后h5版本打包正常了
