### ISSUE TITLE
taro-ui 的按需引入 的疑惑？

### ISSUE THREAD

**Issue by JoMartinezZhu** [NervJS/taro-ui#416]
taro-ui 从 1.5.0 更新到 2.0.1 后 样式全部错乱，只有 按照官网说明 的 “按需引入”，
![image](https://user-images.githubusercontent.com/43346131/53233618-c9e38100-36c8-11e9-9056-ffc877cfa651.png)
才会 还原 。
目前 taro-ui 官网 在使用 每个组件的是有 都要 引入 其相应的 样式文件嘛？

**补充信息**

**Comment by koppthe** [comment]
麻烦看一下「快速上手」那一章的文档哈

**Comment by JoMartinezZhu** [comment]
> 麻烦看一下「快速上手」那一章的文档哈

这是又跟新了吧！我之前并没有这样使用呀！

**Comment by koppthe** [comment]
2.0 做了样式抽离，所以使用方式有变更，你只需要在入口文件引入 index.scss 就好了

**Comment by JoMartinezZhu** [comment]
> 2.0 做了样式抽离，所以使用方式有变更，你只需要在入口文件引入 index.scss 就好了

你这是全局的引入呀

**Comment by koppthe** [comment]
嗯嗯，如果要按需引入，目前只支持手动引入需要的组件样式文件，例如你刚开头截图的那样。如果要自动按需引入样式文件，得 taro 那边写个 loader 处理

**Comment by zhangfu-git** [comment]
使用了less，引入全局样式无效
