### ISSUE TITLE
使用list组件时，小程序额外信息图片没有重写样式，按照小程序默认图片样式渲染

### ISSUE THREAD

**Issue by JokerLoLgrey** [NervJS/taro-ui#418]
**问题描述**
使用list组件时，小程序额外信息图片没有重写样式，按照小程序默认图片样式渲染，
使用徽标组件和list组件时，图片又发生偏移

**复现步骤**
```js
<AtList>
            <AtListItem title='标题文字' />
            <AtListItem title='标题文字' arrow='right' />
             <AtListItem
                title='标题文字'
                extraThumb='http://img10.360buyimg.com/jdphoto/s72x72_jfs/t5872/209/5240187906/2872/8fa98cd/595c3b2aN4155b931.png'
                />
          </AtList>      
```
```js
 <AtList>
            <AtListItem title='标题文字' />
            <AtListItem title='标题文字' arrow='right' />
            <AtBadge value={10} maxValue={99}>
              <AtListItem
                title='标题文字'
                extraThumb='http://img10.360buyimg.com/jdphoto/s72x72_jfs/t5872/209/5240187906/2872/8fa98cd/595c3b2aN4155b931.png'
                />
            </AtBadge>
          </AtList>     
```

**期望行为**
可以结合徽标使用，列表组件图片正确显示

**报错信息**
这是列表组件使用额外图片时

![image](https://user-images.githubusercontent.com/33446705/53256943-041e4400-3704-11e9-9c06-c124d9046cfd.png)

这是配合徽标时

![image](https://user-images.githubusercontent.com/33446705/53256042-f23ba180-3701-11e9-9dff-ac8337e8815f.png)

**系统信息**
报错平台：微信小程序

![image](https://user-images.githubusercontent.com/33446705/53257027-2adc7a80-3704-11e9-925e-9045482b0cb5.png)

**补充信息**

**Comment by koppthe** [comment]
AtBadge 不支持包裹 AtListItem

**Comment by JokerLoLgrey** [comment]
> AtBadge 不支持包裹 AtListItem

第一个图片没有样式怎么解决呢？？就是额外信息图片样式是默认的

**Comment by koppthe** [comment]
已修复，会跟周四的版本发
