### ISSUE TITLE
希望list组件能够增加extraText和node的自定义样式属性

### ISSUE THREAD

**Issue by 743834110** [NervJS/taro-ui#419]
希望能够支持自定义描述信息和详细信息属性中的样式，有些时候是不希望信息换行或者以省略号显示。
有如： 
![image](https://user-images.githubusercontent.com/30767963/53284577-3aee6b80-3791-11e9-8309-557d05a976bd.png)

**Comment by koppthe** [comment]
你可以看看「自定义主题」那一章去覆写样式

**Comment by 743834110** [comment]
那行，我试试
