### ISSUE TITLE
AtPagination发现问题，total无法注入，导致无法使用

### ISSUE THREAD

**Issue by richwxd** [NervJS/taro-ui#42]
### 重现步骤
数据
` {"code":1,"message":"success","data":{"total":6,"list":[{"id":1,"factory_name":"ABC公司","terminal_no":"ZD70","type_name":"D机器","model_name":"QZJ","vin":"00000000000000001","serial_no":"CAR01","sale_status":"00"},{"id":2,"factory_name":"ABC公司","type_name":"A机器","model_name":"PDJ","vin":"00000000000000002","serial_no":"CAR02","sale_status":"00"},{"id":3,"factory_name":"ABC公司","type_name":"C机器","model_name":"TTJ","vin":"00000000000000003","serial_no":"CAR03","sale_status":"00"},{"id":4,"factory_name":"ABC公司","type_name":"E机器","model_name":"ZZJ","vin":"00000000000000004","serial_no":"CAR04","sale_status":"00"},{"id":5,"factory_name":"ABC公司","type_name":"B机器","model_name":"YLJ","vin":"00000000000000005","serial_no":"CAR05","sale_status":"00"},{"id":6,"factory_name":"ABC公司","type_name":"F机器","model_name":"WJJ","vin":"00000000000000006","serial_no":"CAR06","sale_status":"00"}],"page_num":1,"page_size":6,"size":6,"start_row":0,"end_row":5,"pages":1,"pre_page":0,"next_page":0,"is_first_page":true,"is_last_page":true,"has_previous_page":false,"has_next_page":false,"navigate_pages":8,"navigatepage_nums":[1],"navigate_first_page":1,"navigate_last_page":1,"first_page":1,"last_page":1}}`
![image](https://user-images.githubusercontent.com/22185826/44966653-0979ad80-af6f-11e8-8707-c97826f54acf.png)
![image](https://user-images.githubusercontent.com/22185826/44966755-a1779700-af6f-11e8-8253-5b3f790fc6c5.png)

赋值部分是在Taro.request的then里面，和渲染部分的代码
[https://user-images.githubusercontent.com/22185826/44966653-0979ad80-af6f-11e8-8707-c97826f54acf.png](url)
[https://user-images.githubusercontent.com/22185826/44966755-a1779700-af6f-11e8-8253-5b3f790fc6c5.png](url)

### 依赖的版本号

taro-ui: 1.1.0

### 预期结果
页数和翻页行为正确

### 实际结果
渲染部分，total没进去，结果整个都不正确了。因为total问题，换页的方法没法继续了，不知道是不是采坑了

**Comment by cos2004** [comment]
试试把相关数据都用变量存起来，然后把变量传进去，比如：const total = list.length

**Comment by richwxd** [comment]
当测试数据为0的时候，即total = 0时，页面时这样的
![image](https://user-images.githubusercontent.com/22185826/44977733-5e331d80-af9b-11e8-9c34-4cd4e753f39e.png)
带上数据，一样是这样的，页面总数算不对，下一页，上一页的计算不正确
![image](https://user-images.githubusercontent.com/22185826/44978008-3bedcf80-af9c-11e8-9e03-db90df363404.png)

**Comment by limichange** [comment]
确认下，传进去的都是数字？

**Comment by SzHeJason** [comment]
@richwxd 可以把taro的版本提供下吗

**Comment by cos2004** [comment]
@richwxd 已经修复了，今天晚点会发布

**Comment by richwxd** [comment]
ok，我晚上看一下

**Comment by cos2004** [comment]
@richwxd  1.1.3已发布。不过total传值依然要像上面说的先用变量存起来再传到组件里，这个是taro的问题，正在修复

**Comment by cos2004** [comment]
@richwxd 1.1.3已发布。不过 total 等 props 传值依然要像上面说的先用变量存起来再传到组件里，这个是taro的问题，正在修复

**Comment by richwxd** [comment]
已经试过了，还是不行啊，current到时候对了，total的值计算pages 还是不对， 一共6条数据，下方显示这样: 
![image](https://user-images.githubusercontent.com/22185826/45100886-e3196500-b15c-11e8-8210-3fbb17a02d6e.png)
变量方式：
![image](https://user-images.githubusercontent.com/22185826/45100932-f5939e80-b15c-11e8-82b2-8adff7c2fc61.png)

**Comment by richwxd** [comment]
其实如果开放设置总页数，是不是就不会出现这个错误了。调用者自己计算总页数，组件负责计算边界。这个问题是不是就解决了

**Comment by richwxd** [comment]
完整代码
`import Taro from '@tarojs/taro'
import {View, Text} from '@tarojs/components'
import {AtPagination, AtList, AtListItem} from 'taro-ui'

import './dbg.scss'
import {get as getGlobalData, set as setGlobalData} from "../../global/global_data";

const INIT_FORM = {
  office_id: '',
  type_id: '',
  model_id: '',
  keyword: '',
  sale_status: '00',

  // 分页页码
  page_no: 1,
  page_size: 20
}

const INIT_PAGE = {
  list: [],
  total: 0,
  page_size: 0,
  page_num: 0,
  pages: 0,
  has_previous_page: false,
  has_next_page: false
}

export default class DebugList extends Taro.Component {
  static defaultProps = {
    props: 'props'
  }

  config = {
    navigationBarTitleText: '列表'
  }

  constructor(props) {
    super(props)
    this.state = {
      // 查询条件
      searchForm: INIT_FORM,

      // 页面数据
      pageData: INIT_PAGE
    }
  }

  componentDidMount() {
    this.handleSearch()
  }

  componentWillUnmount() {
  }

  handleInput = (fieldName, value) => {
    const form = Object.assign(
      ...INIT_FORM,
      {[fieldName]: value}
    )

    this.setState({searchForm: form})
  }

  onPage(data) {
    console.log('pagination: ', data)
  }

  handleSearch() {
    const token = getGlobalData('accountInfo').token
    // console.log('------------ token: ' + token)
    const form = this.state.searchForm
    console.log('------------ searchForm: ' + JSON.stringify(form))
    Taro.request({
      url: 'http://127.0.0.1/api/list',
      method: 'GET',
      data: form,
      header: {
        'Accept': 'application/json;charset=UTF-8',
        'X-App-Platform': 'miniwx',
        'Authorization': 'Bearer ' + token
      }
    }).then((res) => {
      if (res.data.code != 1) {
        if (res.data.code == 401) {
          const msg = res.data.message ? res.data.message : '登录数据过期，请重新登录! '
          Taro.showModal({
            title: '警告！',
            content: msg,
            showCancel: false
          }).then(() => {
            Taro.redirectTo({
              url: '/pages/login/login'
            })
          })
        } else {
          Taro.showToast({
            title: '查询不成功: ' + res.data.message,
            icon: 'none',
            duration: 3000
          })
        }
      } else {
        const page = Object.assign(
          ...INIT_PAGE,
          {
            list: res.data.data.list,
            total: res.data.data.total,
            page_num: res.data.data.page_num,
            has_previous_page: res.data.data.has_previous_page,
            has_next_page: res.data.data.has_next_page,
            pages: res.data.data.pages
          }
        )
        this.setState({pageData: page}, () => {
          console.log('-----------state total: ' + this.state.pageData.total)
        })
      }
    }).catch(error => {
      console.log(error)
    })
  }

  render() {
    const list = this.state.pageData.list
    const total = list ? list.length : 0
    const pageSize = this.state.pageData.page_size
    const current = this.state.pageData.page_num

    console.log('----render total: ' + total)
    console.log('----render current: ' + current)

    return (
      <View className='page'>
        <View pageName='wxapp-block'>
          {
            list.map(row => {
              return (
                <AtListItem
                  key={String(row.id)}
                  arrow='right'
                  note={row.model_name}
                  title={row.type_name + ': ' + row.serial_no}
                  extraText={row.office_name}
                />
              )
            })
          }
        </View>
        <AtPagination icon total={total} pageSize={pageSize}
          current={current} onPageChange={this.onPage}
        ></AtPagination>
      </View>
    )
  }
}

`

**Comment by cos2004** [comment]
page_size是0导致的

**Comment by richwxd** [comment]
应该不是 `const list = this.state.pageData.list
    const total = list ? list.length : 0
    const pageSize = this.state.searchForm.page_size
    const current = this.state.searchForm.page_no

    console.log('----render pageSize: ' + pageSize)
    console.log('----render total: ' + total)
    console.log('----render current: ' + current)
`

以上代码修改完成后，出现
![image](https://user-images.githubusercontent.com/22185826/45197002-9e431a80-b291-11e8-8720-b5a231b6ea63.png)
