### ISSUE TITLE
希望navbar支持小程序顶栏自定义模式

### ISSUE THREAD

**Issue by JokerLoLgrey** [NervJS/taro-ui#420]
希望navbar支持小程序顶栏自定义模式，

**这个功能解决了什么问题？**

因为小程序不支持监听返回，和不支持返回的显示和隐藏，并且单独的navbar浪费页面位置
故希望navbar支持小程序自定义导航栏，

**你期望的功能是怎样的？**

可以通过多穿一个参数，比如type之类的，支持小程序自定义导航栏的高度， 由于支付宝小程序和h5不支持或不需要调整高度，可以让支付宝小程序直接不显示，h5显示正常高度

**补充信息**
自定义模式下，navbar会显示在最顶部，而影响页面样式
![image](https://user-images.githubusercontent.com/33446705/53287854-d3e6ac00-37bc-11e9-95a3-502b3aca2925.png)

**Comment by koppthe** [comment]
各个小程序 NavBar 的视觉规范都不同，用一套 UI 规范来适配各端不太合理。所以这个需求还是建议自己实现吧，taro-ui 增加 NavBar 的初衷是补齐 H5 端缺失的组件

**Comment by JokerLoLgrey** [comment]
> 各个小程序 NavBar 的视觉规范都不同，用一套 UI 规范来适配各端不太合理。所以这个需求还是建议自己实现吧，taro-ui 增加 NavBar 的初衷是补齐 H5 端缺失的组件
好吧，那关闭这个issue吧
