### ISSUE TITLE
AtInput placeholder 乱码

### ISSUE THREAD

**Issue by zhang14725804** [NervJS/taro-ui#421]
（1）package.json如下
![_20190224112036](https://user-images.githubusercontent.com/15354910/53294673-07115580-3826-11e9-8028-c9996f268a8d.png)
（2）npm run dev:weapp 编译小程序正常
（3）npm run dev:h5 编译H5乱码

     <AtInput placeholder='请输入预计报价'>万元</AtInput>
     <AtInput placeholder='客户经理联系方式（选填）'></AtInput>

![_20190224112333](https://user-images.githubusercontent.com/15354910/53294695-8b63d880-3826-11e9-92b8-536c9e1b9b17.png)

**Comment by koppthe** [comment]
升级 taro 至最新版本，1.2.11 会有这个问题

**Comment by zhang14725804** [comment]
重新cnpm isntall -g @tarojs/cli@1.2.11
然后重新taro init app就好了
