### ISSUE TITLE
在支付宝小程序运行时报错

### ISSUE THREAD

**Issue by tanwenchao** [NervJS/taro-ui#422]
![92643b1d-8048-4cca-920e-5423e9b1643c](https://user-images.githubusercontent.com/17673324/53385147-68692e00-39b8-11e9-9761-46f99783728e.png)

index.js 引入了 AtButton组件
Taro v1.2.14
taro-ui 最新版
node v10.11.0

**Comment by koppthe** [comment]
taro-ui 具体的版本号呢

**Comment by tanwenchao** [comment]
2.0.1

**Comment by koppthe** [comment]
无法重现，麻烦重现编译或者把 taro 升级到最新版本试试？
