### ISSUE TITLE
h5 预览报错

### ISSUE THREAD

**Issue by shaodahong** [NervJS/taro-ui#423]
执行 yarn dev:h5
```js
ℹ️  Listening at http://127.0.0.1:10086/

监听文件修改中...

🙅   Failed to compile.

./node_modules/taro-ui/dist/h5/components/countdown/index.js 105:11
Module parse failed: Unexpected token (105:11)
You may need an appropriate loader to handle this file type.
|     } = this.state;
| 
>     return <View className={classNames({
|       'at-countdown': true,
|       'at-countdown--card': isCard
```

版本

```
"taro-ui": "^2.0.1"
"@tarojs/cli": "1.2.14",
```

**Comment by koppthe** [comment]
麻烦重新看看「快速上手」一章的文档，需要增加一个配置项 `esnextModules`

**Comment by sananiki** [comment]
加了也是报这样的错

**Comment by shaodahong** [comment]
@sananiki 我加了可以了，你发下配置看看，是不是写错了地方

**Comment by sananiki** [comment]
> @sananiki 我加了可以了，你发下配置看看，是不是写错了地方

module.exports = {
  env: {
    NODE_ENV: '"development"'
  },
  defineConstants: {
  },
  weapp: {},
  h5: {
    esnextModules: ['taro-ui']
  }
}

**Comment by shaodahong** [comment]
@sananiki 我也是这样加的，不过是加到 `config/index.js` 中的

**Comment by sananiki** [comment]
> @sananiki 我也是这样加的，不过是加到 `config/index.js` 中的

我dev,index.prod都加了，还是谢谢你了，我再查下

**Comment by maskwang** [comment]
@sananiki 解决了嘛？  我加了配置， 也同样报错。。

**Comment by bigbigqiang** [comment]
加了配置 taro-ui 版本号 2.0.2, h5预览样式乱掉，微信小程序正常
