### ISSUE TITLE
部分安卓手机企业微信无法正常渲染组件

### ISSUE THREAD

**Issue by arronlovepudding** [NervJS/taro-ui#425]
为什么taro-ui在部分安卓手机的企业微信中样式会失效？
测试环境：华为麦芒RNE-AL00 企业微信版本号 2.7.2

**Comment by koppthe** [comment]
你确认一下微信的基础库版本是否在 v2.2.3+

**Comment by arronlovepudding** [comment]
> 你确认一下微信的基础库版本是否在 v2.2.3+
版本号是2.6.0

**Comment by koppthe** [comment]
不是调试基础库，是在小程序管理平台设置的线上基础库哦？

**Comment by arronlovepudding** [comment]
线上基础版本库设置到了2.2.4了，我在本地预览调试的应该和线上无关吧？

**Comment by slevp** [comment]
目测可能是企业微信安卓内嵌的微信基础版本库低于2.2.3。

**Comment by koppthe** [comment]
这个问题比较难办，因为微信小程序的 globalClass 特性需要基础库版本在 2.2.3+，然而部分安卓版本的企业微信基础库低于 2.2.3 ，所以样式不生效。目前两个解决方案：
1. 等待官方修复
2. taro-ui 降级到 v1.5.3 版本，但该版本存在一些 bugs

**Comment by arronlovepudding** [comment]
> 这个问题比较难办，因为微信小程序的 globalClass 特性需要基础库版本在 2.2.3+，然而部分安卓版本的企业微信基础库低于 2.2.3 ，所以样式不生效。目前两个解决方案：
> 
> 1. 等待官方修复
> 2. taro-ui 降级到 v1.5.3 版本，但该版本存在一些 bugs

好的 ，感谢！ 我们暂时放弃了taro-ui！ 期待你们能更加完美！
