### ISSUE TITLE
build:h5样式失效

### ISSUE THREAD

**Issue by vurtnr** [NervJS/taro-ui#431]
**问题描述**
按照快速上手在app.js中引入了scss，dev:h5 一切正常，打包之后样式全部失效。

**复现步骤**
build:h5
**期望行为**
build:h5 后 样式正常

**报错信息**

**系统信息**
 - Taro 版本 [e.g. v.1.2.12]
 - Taro UI 版本 [e.g. v.2.0.0]
 - 报错平台 [h5]

**补充信息**

**Comment by koppthe** [comment]
麻烦把 taro-ui 升级到 v2.0.1 试试？

**Comment by bigbigqiang** [comment]
`"dependencies": {
    "@tarojs/components": "1.2.21",
    "@tarojs/mobx": "1.2.21",
    "@tarojs/mobx-h5": "1.2.21",
    "@tarojs/mobx-rn": "1.2.21",
    "@tarojs/rn-runner": "1.2.21",
    "@tarojs/router": "1.2.21",
    "@tarojs/taro": "1.2.21",
    "@tarojs/taro-alipay": "1.2.21",
    "@tarojs/taro-h5": "1.2.21",
    "@tarojs/taro-swan": "1.2.21",
    "@tarojs/taro-tt": "1.2.21",
    "@tarojs/taro-weapp": "1.2.21",
    "@tarojs/with-weapp": "^1.2.22",
    "mobx": "4.8.0",
    "nerv-devtools": "^1.3.9",
    "nervjs": "^1.3.9",
    "taro-ui": "^2.0.2"
  },`
npm run dev:h5 样式乱掉，已配置 esnextModules
`h5: {
    publicPath: '/',
    staticDirectory: 'static',
    esnextModules: ['taro-ui'],
    module: {
      postcss: {
        autoprefixer: {
          enable: true,
          config: {
            browsers: [
              'last 3 versions',
              'Android >= 4.1',
              'ios >= 8'
            ]
          }
        },
        cssModules: {
          enable: false, // 默认为 false，如需使用 css modules 功能，则设为 true
          config: {
            namingPattern: 'module', // 转换模式，取值为 global/module
            generateScopedName: '[name]__[local]___[hash:base64:5]'
          }
        }
      }
    }
  }`

**Comment by blackcatpolice** [comment]
白搭，dev模式浏览器表现挺好的，我现在用的3.0.17版本。依旧如此。
用官方taro-ui模板测试的。效果还是白搭。
dev模式
![image](https://user-images.githubusercontent.com/4312114/100562422-afefbd00-32f6-11eb-82d0-12539b353bca.png)
build 后打开
![image](https://user-images.githubusercontent.com/4312114/100562451-c0a03300-32f6-11eb-9a55-e7364f99b0d3.png)
