### ISSUE TITLE
无法给微信小程序自定义组件本身添加class

### ISSUE THREAD

**Issue by ccqgithub** [NervJS/taro-ui#434]
**问题描述**

使用taro时，如果用了taro-ui这种自定义组件，不能给自定义组件添加class，className会传到自定义组件的根元素，这与小程序原生不一致，在小程序中不能通过class控制组件本身的样式。

比如一个View里面放入两个AtButton，在微信小程序里给AtButton组件本身加`flex:1`只会应用到`at-button`里面的根元素，而不是`at-button`本身。

在Taro也提了个，不知道是哪边的问题，就两边都提了个：https://github.com/NervJS/taro/issues/2293

**复现步骤**

比如引入taro-ui的button组件时，编译出来后是以自定义组件at-button的形式引入的。

编译后：
```
"usingComponents": {
    "at-button": "../../npm/taro-ui/dist/weapp/components/button/index",
    "at-action-sheet": "../../npm/taro-ui/dist/weapp/components/action-sheet/index"
  },
```

如果用taro：

```jsx
import { AtButton, AtActionSheet, AtActionSheetItem } from 'taro-ui';

<AtButton className="test">确定</AtButton>
```

编译出来后是这种： `<at-button><view>确定</view></at-button>`,  class 丢失;

但如果用微信小程序原生：

```
<at-button class="test">确定</at-button>
```

编译出来后仍是`<at-button class="test"><view>确定</view></at-button>`, class 存在。

**期望行为**

希望能在微信小程序给组件本身添加class，好控制组件本身的位置，flex等

这种情况，是否可以有一个专门的属性来控制，比如`componentClassName`？

直接用`class`的话编译出来好像是正确的，但是react里不支持`class`保留字，eslint也报错。

**报错信息**

**系统信息**

 - 操作系统: macOS High Sierra 10.13.1
 - Taro 版本 v1.2.13
 - Taro UI 版本 v2.0.1
 - 报错平台 weapp

**Comment by jimczj** [comment]
不要用 class,使用 className

**Comment by ccqgithub** [comment]
@jimczj 你没看清楚我说的意思，拿`AtButton`来说，className 最终会应用到自定义组件`at-button`里面的`View`元素上，无法给`at-button`本身添加class。

微信小程序给自定义组件添加class是应用在组件本身的，不是组件里面的根元素的。

**Comment by ccqgithub** [comment]
@jimczj 出现这个问题的原因是h5和小程序对于自定义组件的表现不一样

小程序外面会多一层自定义组件标签，比如: `at-button`,  而h5里面是直接渲染根元素！

**Comment by dyyliao123** [comment]
有解决吗，怎么改不了taro-ui里面的样式

**Comment by Lemonreds** [comment]
同问
