### ISSUE TITLE
Picker 文档有误

### ISSUE THREAD

**Issue by Dithub2016** [NervJS/taro-ui#435]
**问题描述**
地址： https://taro-ui.aotu.io/#/docs/picker
其中，多列选择器：mode = multiSelector 的参数一列，
文档上写 onColumnchange， 实际为 onColumnChange，
onColumnchange 只在小程序端生效，
onColumnChange 则在两端都有效

两端的事件 event.type 也是不一致的,
h5 端为 columnChange,
小程序端为 columnchange，
虽然没影响，但也说一下

**期望行为**
修复文档描述问题

**Comment by Garfield550** [comment]
@Dithub2016 帮你把文档找到了，你可以抽空改一下，官方会感谢你的帮助的， https://github.com/NervJS/taro-ui/blob/dev/docs/markdown/picker.md

**Comment by koppthe** [comment]
这里的 Picker 用的是 `@taro/components` 的，参数以 taro 文档为准哈：https://nervjs.github.io/taro/docs/components/forms/picker.html

Taro UI 的文档是需要修复一下，感谢提醒~
