### ISSUE TITLE
安装组件  taro-ui 出错，无法正常安装

### ISSUE THREAD

**Issue by heroSoft205** [NervJS/taro-ui#437]
**安装taro-ui出错**
1、先初始化项目 taro init myApp
2、安装组件  npm install taro-ui
然后出现错误
E:\taro\myApp>npm install taro-ui
npm WARN tar ENOENT: no such file or directory, open 'E:\taro\myApp\node_modules\.staging\fsevents-8aaccbb2\node_modules\minimist\.travis.yml'
npm WARN @webpack-contrib/schema-utils@1.0.0-beta.0 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-middleware@3.4.0 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\_chokidar@2.1.2@chokidar\node_modules\fsevents):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\taro\myApp\node_modules\.staging\fsevents-8aaccbb2\node_modules\aproba' -> 'E:\taro\myApp\node_modules\.staging\aproba-0d300e72'

npm ERR! path E:\taro\myApp\node_modules\_color-convert@1.9.3@color-convert\node_modules\color-name
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'E:\taro\myApp\node_modules\_color-convert@1.9.3@color-convert\node_modules\color-name' -> 'E:\taro\myApp\node_modules\_color-convert@1.9.3@color-convert\node_modules\color-name'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mi\AppData\Roaming\npm-cache\_logs\2019-03-02T01_18_16_179Z-debug.log
这是怎么回事？有人遇到过没？求帮忙！感谢
版本信息：
Taro v1.2.14
  Taro CLI 1.2.14 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.0 - D:\Program Files\nodejs\node.EXE
      npm: 6.8.0 - D:\Program Files\nodejs\npm.CM

**Comment by Garfield550** [comment]
color-convert 包需要的依赖 color-name 不存在，可能是你的网络出错导致没有下载完成，重试一下。
https://github.com/Qix-/color-convert/blob/master/package.json
https://github.com/colorjs/color-name
另外根据 color-convert 的 issue 记录，可能还存在你的 lockfile 出问题的情况，请按照 issue 里提供的方案尝试解决一下：
https://github.com/Qix-/color-convert/issues/44

**Comment by koppthe** [comment]
@heroSoft205 包安装的问题，如果 npm 不行，就换 cnpm 试试，再不行挂个代理试试哈
