### ISSUE TITLE
Modal组件编译错误

### ISSUE THREAD

**Issue by ccqgithub** [NervJS/taro-ui#440]
### Taro UI 版本信息

2.0.1

### 问题描述

Modal组件编译出来后样式不对, 发现缺少了一层`at-modal__container`

### 复现步骤

```
import { 
  AtModal, 
  AtModalContent, 
} from 'taro-ui';

<AtModal isOpened>
          <AtModalContent>
            <View>
              这里是正文内容，欢迎加入京东凹凸实验室
              这里是正文内容，欢迎加入京东凹凸实验室
              这里是正文内容，欢迎加入京东凹凸实验室
            </View>
          </AtModalContent>
        </AtModal>
```

编译出来后样式不对，经检查缺少了container
```
<at-modal isOpened="{{true}}" __triggerObserer="{{ _triggerObserer }}">
            <at-modal-content __triggerObserer="{{ _triggerObserer }}">
                <view>这里是正文内容，欢迎加入京东凹凸实验室这里是正文内容，欢迎加入京东凹凸实验室这里是正文内容，欢迎加入京东凹凸实验室</view>
            </at-modal-content>
        </at-modal>
```

### 复现代码

```
import { 
  AtModal, 
  AtModalContent, 
} from 'taro-ui';

<AtModal isOpened>
          <AtModalContent>
            <View>
              这里是正文内容，欢迎加入京东凹凸实验室
              这里是正文内容，欢迎加入京东凹凸实验室
              这里是正文内容，欢迎加入京东凹凸实验室
            </View>
          </AtModalContent>
        </AtModal>
```

### 报错信息

![image](https://user-images.githubusercontent.com/1654761/53776754-f5b8ff00-3f31-11e9-9c62-a02fe5314ce9.png)

### 系统信息

Taro CLI 1.2.15 environment info:
    System:
      OS: macOS High Sierra 10.13.1
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm

**Comment by koppthe** [comment]
没有重现，有可复现的 Demo 不？

**Comment by ccqgithub** [comment]
@koppthe https://github.com/ccqgithub/taro-bug-demo.git

**Comment by ccqgithub** [comment]
不好意思，看错了，好像样式的问题~
