### ISSUE TITLE
AtInputNumber 

### ISSUE THREAD

**Issue by Clear2** [NervJS/taro-ui#444]
### Taro UI 版本信息

2.0.0

### 问题描述

例如: 参数 min=1, max=6, 使用输入框无法输入 2, 3, 4, 5

### 复现步骤

输入 2, 3, 4

### 复现代码

   <AtInputNumber
                width={74}
                min={1}
                max={6}
                step={1}
                value={this.state.value}
                onChange={this.handleUpdate.bind(this)}
              />

### 报错信息

会直接输出最大值

### 系统信息

taro-ui

**Comment by koppthe** [comment]
taro 版本呢？
