### ISSUE TITLE
强烈建议！可以改进一下所有的input组件吗？

### ISSUE THREAD

**Issue by zjjjjjjjjjjd** [NervJS/taro-ui#446]
现在所有的input组件value都是必填，通过onchange更新state来实现输入。
但是，但是，但是！对于很多老爷机而言（如：iphone6s），微信的setData频繁渲染会造成更新延时，这其中包括了输入和删除，高频次（对老爷机而言）调用setData就会出现输入延迟和删除延迟的诡异现象！
taro-ui的组件不加value虽然不影响输入，但是会造成focus时placeholder消失不掉，这在原生input是不会出现的。所以原生input可以不加value，仅在onchange中用一个全局字段记录当前value值就好了，这样可以避免每输入一个字符渲染一次，照顾到特殊机型。

**Comment by xzedx** [comment]
我也遇到这个问题了。。。

**Comment by SzHeJason** [comment]
我们内部讨论下哈

**Comment by zjjjjjjjjjjd** [comment]
@SzHeJason 不好意思，这个issues其实有点描述不准确。我一开始是想针对搜索组件提出的，因为我后来发现普通的taro-ui的input组件是不会存在这个问题的（可以和微信的input一样使用），但是我挺喜欢搜索这个组件的，所以应该说是希望可以改进一下搜索这个组件
