### ISSUE TITLE
ActivityIndicator 活动指示器文档错误

### ISSUE THREAD

**Issue by liuweiGL** [NervJS/taro-ui#451]
**问题描述**
按照 [ActivityIndicator 活动指示器](https://taro-ui.aotu.io/#/docs/activityindicator)文档按需引入样式，loading 不展示。

**复现步骤**
无

**期望行为**

```
@import "~taro-ui/dist/style/components/activity-indicator.scss";

```
可以出现 loading。

**报错信息**

无

**系统信息**

```
Taro CLI 1.2.15 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.13.0 - D:\nodejs\node.EXE
      npm: 6.4.1 - D:\nodejs\npm.CMD

```

**补充信息**

应该还要引入：

```

@import '~taro-ui/dist/style/components/loading.scss';

```

**Comment by koppthe** [comment]
可以提个 PR~

**Comment by KingGanZeng** [comment]
是由于样例中title写成了中文字符的单引号
```
<AtActionSheet isOpened cancelText='取消' title=‘头部标题可以用通过转义字符换行’>
...
```
把这句改成
```
<AtActionSheet isOpened cancelText='取消' title='头部标题可以用通过转义字符换行'>
```

**Comment by liuweiGL** [comment]
> 可以提个 PR~

😂 我还没提过 PR ，需要看下。

**Comment by liuweiGL** [comment]
> 是由于样例中title写成了中文字符的单引号
> 
> ```
> <AtActionSheet isOpened cancelText='取消' title=‘头部标题可以用通过转义字符换行’>
> ...
> ```
> 把这句改成
> 
> ```
> <AtActionSheet isOpened cancelText='取消' title='头部标题可以用通过转义字符换行'>
> ```
> 就可以了

我看 `activity-indicator.scss` 文件中并没有引入 `loading.scss` 文件哦，所以要 `loading` 效果需要手动引入。

**Comment by SzHeJason** [comment]
#453
