### ISSUE TITLE
taro-ui组件样式引入无效

### ISSUE THREAD

**Issue by labike** [NervJS/taro-ui#454]
快速上手上写的是什么玩意啊

按照快速上手上的按需引入组件样式 样式加载不出来

比如我
```
import {AtDrawer} from 'taro-ui'
<AtDrawer />
```
我在atdrawer.scss中按需引入`AtDrawer`的样式
```
@import '~taro-ui/dist/.../atdrawer.scss'
```
无效

难道我必须在atdrawer.js中手动引入`../../node-modules/taro-ui/...../atdrawer.scss`吗？
<img width="779" alt="屏幕快照 2019-03-09 下午5 36 05" src="https://user-images.githubusercontent.com/15871933/54069845-c1c53d00-4295-11e9-9b90-1ce5eec5df1c.png">
<img width="416" alt="屏幕快照 2019-03-09 下午5 36 17" src="https://user-images.githubusercontent.com/15871933/54069846-c1c53d00-4295-11e9-92bd-9839b4427759.png">

**Comment by 15768716486** [comment]
同样的问题，怎么解决呢

**Comment by koppthe** [comment]
1. 你的 `atdrawer.scss` 文件是哪里来的？
2. 你是在自定义组件里面使用 taro-ui 的组件吗？
3. globalClass 相关的知识需要了解一下

https://taro-ui.aotu.io/#/docs/customizetheme

**addGlobalClass 这个 API 只对 Page 上的 class 起作用。换言之，如果在自定义的组件中使用 taro-ui，是无法在自定义组件内部通过 全局样式类 的方式去更改组件样式的。**

**Comment by labike** [comment]
@15768716486 
全局app.scss里面导入'taro/index.scss'

**Comment by zhang14725804** [comment]
更新版本之后按需引入样式消失
![image](https://user-images.githubusercontent.com/15354910/60730922-cdd9b680-9f78-11e9-9047-c5bcc9267703.png)
