### ISSUE TITLE
taro-ui按需引入样式不起作用

### ISSUE THREAD

**Issue by labike** [NervJS/taro-ui#455]
```
--AtDrawer
  --index.js
  --index.scss
```
我按照快速入门里面按需引入的方式在`index.scss`中引入了
![scss](https://segmentfault.com/img/bVbpyCN?w=832&h=128)

然后在index.js中引入了`AtDrawer`组件
![组件](https://segmentfault.com/img/bVbpyCR?w=1558&h=310)

但是样式并没有加载出来

**Comment by labike** [comment]
按需引入在当前的组件的scss里面引入不起作用, 但是在全局`app.scss`中引入
```
@import "~taro-ui/dist/style/index.scss";
```
组件的样式可以加载出来

**Comment by koppthe** [comment]
你是在 page 的样式里面按需引入的不？

**Comment by labike** [comment]
@koppthe 我是在当前组件的样式里面引入的
```
----Menu
    ----index.js
    ----index.scss
```

index.js里引入了`AtDrawer`组件
```
<View>
  <AtDrawer />
  ....
</View>
```
index.scss里引入了
```
@import '~taro-ui/.../drawer.scss'
@import '~taro-ui/.../list.scss'
```

**Comment by koppthe** [comment]
在自定义组件里面引入 taro-ui 的样式是不生效的，这是微信小程序 globalClass 的限制，组件的样式必须在 app.css 或者页面样式中引入哈

**Comment by labike** [comment]
@koppthe 
组件的样式必须在 app.css 引入： 指的是全局的app.scss中引入吗?
页面样式中引入是指比如在`Menu.js`这样
```
import 'taro-ui/..../drawer.scss'
```
引入吗?

**Comment by koppthe** [comment]
只要在非自定义组件里面引入就行，微信小程序组件使用 WebComponent 实现的，组件之间样式是隔离的。

**Comment by labike** [comment]
@koppthe 谢谢！

**Comment by zhang14725804** [comment]
更新版本之后按需引入样式消失
![image](https://user-images.githubusercontent.com/15354910/60730922-cdd9b680-9f78-11e9-9047-c5bcc9267703.png)

**Comment by justsso** [comment]
> 更新版本之后按需引入样式消失
> ![image](https://user-images.githubusercontent.com/15354910/60730922-cdd9b680-9f78-11e9-9047-c5bcc9267703.png)

这个问题我也遇到了，也有可能是开发者工具的调试工具版本太低造成的～你试试～
