### ISSUE TITLE
标题前的竖条如何添加

### ISSUE THREAD

**Issue by glazec** [NervJS/taro-ui#460]
### Taro UI 版本信息

2.0.1

### 问题描述

在官方文档的展示里，每个标题前都有一个竖着的小蓝条；在官方的小程序中，也有这个小蓝条。如何添加这个小蓝条？

### 复现步骤

NA

### 复现代码

NA

### 报错信息

NA

### 系统信息

  Taro CLI 1.2.15 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.1 - C:\Program Files\nodejs\node.EXE
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

### 补充信息

![image](https://user-images.githubusercontent.com/22890026/54168173-8314bb80-442a-11e9-918a-383d457e8734.png)

**Comment by koppthe** [comment]
这是很基础的 CSS 问题吧。实现的方式很多，你按你喜好的方法加就好了，Demo 用的是 `::before`
