### ISSUE TITLE
searchbar 组件的实现有问题

### ISSUE THREAD

**Issue by atzcl** [NervJS/taro-ui#462]
搜索框内输入文字的过程中，字与`placeholder` 会重叠:
正常：
![image](https://user-images.githubusercontent.com/28823188/54184481-be25f600-44e1-11e9-9a57-69b28da0489f.png)

异常：
![image](https://user-images.githubusercontent.com/28823188/54184495-ca11b800-44e1-11e9-9641-542844662047.png)

原因是 searchbar 组件的 placeholder 是自己用 Text 实现的，这里可能要做一下处理

**Comment by wxv** [comment]
把初始值设置为空字符串试一下在试下。

**Comment by atzcl** [comment]
@wxv value 本来就是空的，这是 placeholder 的问题，因为 taro-ui 是自己实现的 placeholder，并不是使用原生 input 组件的 placeholder 属性，原因应该是为了更好地实现动效

**Comment by shaodahong** [comment]
是有这个问题

**Comment by shaodahong** [comment]
#485

**Comment by wxv** [comment]
@atzcl 你是什么版本，我在加上给属性设置初始值之后placeholder 就隐藏了。


> Taro v1.2.16
  Taro CLI 1.2.16 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.2 - D:\tools\nodejs\node.EXE
      Yarn: 1.13.0 - D:\tools\yarn\bin\yarn.CMD
      npm: 6.4.1 - D:\tools\nodejs\npm.CMD

**Comment by shaodahong** [comment]
@wxv 这个和 `value` 没关系，是输入中文候选词的时候没有触发 `onInput` 导致和 `placeholder` 重影呢，我提了个 `pr` 在 `onFocus` 的时候暂时吧 `placeholder` 置为空

**Comment by atzcl** [comment]
@shaodahong 我在本地的改法也是这样，但是感觉不太优雅，还是看下官方的回复吧

**Comment by shaodahong** [comment]
@atzcl 这个就是小程序本身的限制，我看支付宝的扩展组件就是这么做的

**Comment by wxv** [comment]
@shaodahong 我这边placeholder是隐藏的
![placeholder](https://user-images.githubusercontent.com/46241577/54688176-1ac78780-4b58-11e9-93fe-6bad9d8a5b3d.jpg)

**Comment by atzcl** [comment]
@wxv 真实输入值是会隐藏，看 [components/search-bar/index.js#L60](https://github.com/NervJS/taro-ui/blob/dev/src/components/search-bar/index.js#L60) 代码就知道了，但是也正因为是这里的处理，才会导致我说的那个问题，因为 placeholder 是由 search-bar 组件在 input 聚焦并且有值的时候，才会隐藏掉，而如果当输入法还处于联想侯词时，并没有实际的值输出，就会导致我截图二的情况，你按照我截图二的做法就可以重现了

**Comment by shaodahong** [comment]
GIF 有点大，加载下

![a5c650177f7d3f7013c051c1e9c462a9](https://user-images.githubusercontent.com/14831261/54693674-fb355c80-4b61-11e9-99b8-e5758dce3af4.gif)

**Comment by atzcl** [comment]
@shaodahong 直接在聚焦的时候直接把整个 placeholder 都隐藏的做法感觉不太好，我是当聚焦开始时，在动效处理完后，再把 search-bar 组件内部的 placeholder 交由 input 原生去处理，这样体验才会更好

**Comment by wxv** [comment]
@atzcl @shaodahong 哈哈，我用的android，在ios因为输入法的问题有这种情况。

**Comment by atzcl** [comment]
@wxv 我的就是安卓，，，官方说这个问题后期会优化的~

**Comment by shaodahong** [comment]
@wxv 输入法也有一部分问题， GIF 是 iOS 自带的输入法，我用的百度输入法是没有问题的

**Comment by wxv** [comment]
@shaodahong 我想没用原生的placeholder是因为动画效果吧

**Comment by shaodahong** [comment]
@wxv 恩，原生的性能方面有优势，扩展性差了点
