### ISSUE TITLE
SearchBar不支持数字模式

### ISSUE THREAD

**Issue by kennylbj** [NervJS/taro-ui#464]
### 这个功能解决了什么问题？

当前只能支持文字，但是Input有数字模式

### 你期望的功能是怎样的？

增加一个```type='number'```属性

**Comment by kennylbj** [comment]
应该要把Input组件的type暴露出来

**Comment by jimczj** [comment]
能输入文字跟数字吧

**Comment by kennylbj** [comment]
我的意思是需要有专门的键盘，支持输入数字模式，微信原生组件就可以。
微信原生组件：type= number|text| idcard| digit，显示的键盘会不同。
![image](https://user-images.githubusercontent.com/6435874/54861611-09a09580-4d67-11e9-9c62-344647938222.png)

对于一些场景，只需要输入数字或者身份证的，最好能够提供对应的键盘输入。

**Comment by kennylbj** [comment]
taro-ui searchBar里默认使用type='text'作为类型了，希望能够暴露出这个属性

**Comment by jimczj** [comment]
设置为 text 能够输入文字跟数字呀

**Comment by jimczj** [comment]
设置为 text 能够输入文字跟数字呀

**Comment by kennylbj** [comment]
设置成text确实能输入文字和数字，但是如果要输入数字，还要用户切换一次，影响体验。
如果type设置为number的时候，展示的是数字键盘。这种情况下更方便输入。。。

原生input组件就支持这个特性。

**Comment by jimczj** [comment]
作为一个搜索框，肯定是要支持同时输文字和数字的，只输数字的情况很少，而且组件使用到了 confirm-type zhe g这个属性，该属性只对 type=text 生效，所以决定不提供 type 属性对开放。
![image](https://user-images.githubusercontent.com/13499146/54867979-5bc2d480-4dc2-11e9-8c9c-c32298da8750.png)

**Comment by kennylbj** [comment]
某些场景确实只需要使用到数字作为搜索，例如这个搜索框只负责搜索数字ID。
如果有number选项，能够提供给开发者一些更加切合业务场景的选择。

**Comment by Yangzhedi** [comment]
@jimczj  我感觉暴露出input component 更好

**Comment by kennylbj** [comment]
@jimczj 能否再审查考虑一下？这个场景我觉得蛮适用的

**Comment by jimczj** [comment]
@kennylbj 可以，那就加上吧

**Comment by yishaoZhang** [comment]
初次使用SearchBar, 搜索button不展示时,  input框不居中, 另外, 真机测试输入的内容上半部分被遮挡, 是个例吗??

**Comment by kennylbj** [comment]
@yishaoZhang v2.1.0版本的SearchBar有Bug，我通过手动覆盖css解决的。源码里用``PX``来做单位，导致padding出问题了。

```css
.at-search-bar {
    &__input {
      // fix taro-ui issue
      padding: 12px 74px;
    }
    // remove divider
    &::after {
      border: none;
    }
  }
```

**Comment by Garfield550** [comment]
![IMG_1698](https://user-images.githubusercontent.com/3471836/65827208-60f96280-e2c2-11e9-8fc7-44eecc1fdbc9.PNG)
