### ISSUE TITLE
Input框在输入法为联想状态，无法获取onchage的值，但是用户并不选择联想词，只是确认了，onchage并没有取到值。

### ISSUE THREAD

**Issue by ruralist-siyi** [NervJS/taro-ui#465]
### Taro UI 版本信息

2.0.2

### 问题描述

就是输入用户名：xxxxx时， 因为系统自带键盘默认大都带英文单词联想输入，就是这个xxx会带有下划线，但是如果你直接确认，提交。值已经填入，但是onchange并不会记录正确的值。

### 复现步骤

1. 输入框Input onchange事件。
2. 输入英文。
3. 提交。获取的值为空。

### 复现代码

  <AtInput
              clear
              name='loginAccount'
              title='账号'
              type='text'
              placeholder='请输入账号'
              adjustPosition={true}
              onChange={this.handleAccountChange}
            />
handleAccountChange = (value) => {
    console.log(value);
    this.setState({
      loginAccount: value
    })
  };

### 报错信息

获取不到正确值。

### 系统信息

 Taro CLI 1.2.16 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.10.0 - ~/.nvm/versions/node/v11.10.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v11.10.0/bin/npm

**Comment by jimczj** [comment]
应该是依赖到 Taro 的问题，请使用 Taro 自带的组件，试试是否有此问题
