### ISSUE TITLE
AtRate组件 onChange参数类型应为baseEvent，现在为number

### ISSUE THREAD

**Issue by DJGS** [NervJS/taro-ui#466]
### Taro UI 版本信息

1.5.4

### 问题描述

AtRate组件 onChange参数类型应为baseEvent，现在为number

### 复现步骤

1. 使用组件<AtRate value={formField.score} onChange={this.onScoreChange}/>
2.  传入函数 onScoreChange(value) { console.log(number) }
3.  value 值为number

### 复现代码

1. 使用组件<AtRate value={formField.score} onChange={this.onScoreChange}/>
2.  传入函数 onScoreChange(value) { console.log(number) }
3.  value 值为number

### 报错信息

ts参数类型报错

### 系统信息

1.2.2

**Comment by jimczj** [comment]
升级最新版本

**Comment by DJGS** [comment]
好的
