### ISSUE TITLE
按照官方教程构造taro ui出现错误状态码-4058

### ISSUE THREAD

**Issue by yuckyb** [NervJS/taro-ui#467]
![image](https://user-images.githubusercontent.com/33855371/54252450-d7807e00-4585-11e9-8980-3ae80ad657a6.png)

npm ERR! path F:\me\taroRtk\node_modules\adjust-sourcemap-loader\node_modules\camelcase
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall access
npm ERR! enoent ENOENT: no such file or directory, access 'F:\me\taroRtk\node_modules\adjust-sourcemap-loader\node_modules\camelcase'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2019-03-13T03_36_56_735Z-debug.log
PS F:\me\taroRtk>

**Comment by koppthe** [comment]
依赖没装好，重新 npm install 或者 cpm install，再或者 yarn 一下

**Comment by yuckyb** [comment]
还是不行

**Comment by jimczj** [comment]
@yuckyb 没写权限，自己处理下，安装 npm 包的问题，没什么好讲的
