### ISSUE TITLE
SearchBar placeholder 长度超过2时，无法对齐

### ISSUE THREAD

**Issue by kennylbj** [NervJS/taro-ui#468]
### Taro UI 版本信息

2.0.2

### 问题描述

在使用SearchBar组件时，如果placeholder过长，其内容将无法对齐。
![image](https://user-images.githubusercontent.com/6435874/54266526-85098680-45b2-11e9-96f6-54e958ec4133.png)
![image](https://user-images.githubusercontent.com/6435874/54266556-9357a280-45b2-11e9-920c-a9a563807860.png)

### 复现步骤

placeholder较长

### 复现代码

```js
<AtSearchBar
 placeholder='较长的placeholder'
 value={searchValue}
 onChange={this.handleChange}
/>
```

### 报错信息

无

### 系统信息

Taro v1.2.8

  Taro CLI 1.2.8 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.2.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm

**Comment by kennylbj** [comment]
请问什么时候release

**Comment by koppthe** [comment]
本周四之前

**Comment by kennylbj** [comment]
期待发布
