### ISSUE TITLE
AtTabsPane is not defined

### ISSUE THREAD

**Issue by sussertod891015** [NervJS/taro-ui#47]
### 重现步骤
![image](https://user-images.githubusercontent.com/10465307/45027462-06b4b080-b074-11e8-8587-e326ac52016c.png)

![image](https://user-images.githubusercontent.com/10465307/45027490-1df39e00-b074-11e8-9ad1-96a3813e85a5.png)

![image](https://user-images.githubusercontent.com/10465307/45027504-2a77f680-b074-11e8-9dda-c1bcdd620029.png)

### 依赖的版本号
Node 的版本: 10.9.0
Taro 的版本：1.0.0-beta.23
Taro-UI 的版本：1.1.1

### 预期结果
正常运行

### 实际结果
![image](https://user-images.githubusercontent.com/10465307/45027586-6448fd00-b074-11e8-8be2-2088892c013c.png)

**Comment by jimczj** [comment]
你好，根据你提供的信息，我们这边都无法复现问题。建议编译成 h5 试试，是否有报错。重启微信开发者工具，重启电脑

**Comment by SzHeJason** [comment]
@sussertod891015 查看一下为什么 AtTabsPane 会打黄色波浪

**Comment by sussertod891015** [comment]
@SzHeJason 
![image](https://user-images.githubusercontent.com/10465307/45068687-45417e00-b0fb-11e8-80a8-ed8c10004821.png)

黄色波浪线是因为找不到定义的地方吧

**Comment by jimczj** [comment]
@sussertod891015 AtTabsPane 可以根据内容撑出来，你要自己确保内容确实有高度。 可以参考https://github.com/NervJS/taro-ui-demo 的代码

**Comment by sussertod891015** [comment]
@jimczj  我看到font-size:0这个设置了。官网的demo貌似因为这个有点问题，自己写了个button可以正常显示了。 另外我把整个项目重新安装了一遍，小程序也不在报错了，感谢帮助。
