### ISSUE TITLE
使用Picker处理多列选择器使用onChange为什么不能一次改变每一列

### ISSUE THREAD

**Issue by infipink** [NervJS/taro-ui#473]

**Comment by koppthe** [comment]
没太懂你的问题

**Comment by infipink** [comment]
> 没太懂你的问题
下面是我写在onChange里的方法，是不是这么写有问题
this.setState({
       service: [this.state.services[0][e.detail.value[0]],
                    this.state.services[1][e.detail.value[1]],
                    this.state.services[2][e.detail.value[2]]
                    ]
    })

**Comment by jimczj** [comment]
请重新清楚描述你的问题，否则此 issue 将关闭
