### ISSUE TITLE
你好，我使用taro-ui的导航栏组件出现问题

### ISSUE THREAD

**Issue by mdddj** [NervJS/taro-ui#476]
![QQ截图20190317210556](https://user-images.githubusercontent.com/29020213/54491322-94f9d100-48f8-11e9-9c70-05ab19b96728.png)

它有如下提示
`Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.`

**Comment by koppthe** [comment]
麻烦重新安装一下依赖
