### ISSUE TITLE
AtTabs嵌套自定义AtModal，AtModal总出现在第一个AtTabsPane中

### ISSUE THREAD

**Issue by KingGanZeng** [NervJS/taro-ui#477]
### Taro UI 版本信息

2.0.2

### 问题描述

我使用AtTabs做了两个AtTabsPane，每一个AtTabsPane下有相同的自定义组件，自定义组件中包含AtModal
点击按钮触发AtModal，弹出框总出现在第一个AtTabsPane

### 复现步骤

1、切换到第二个AtTabsPane
2、点击按钮触发AtModal
3、AtModal没有出现在第二个AtTabsPane中
4、切换回第一个AtTabsPane，发现AtModal

### 复现代码

```
// 布局代码
<AtTabs
  current={this.state.current}
  tabList={tabList}
  onClick={this.handleClick.bind(this)}
>
  <AtTabsPane 
          current={this.state.current}
          index={0}
   >
    <CategoryList> // 自定义组件
      /** 
      **  <Button /> // 按钮触发AtModal
      **  <AtModal />
      */
    </CategoryList>
  </AtTabsPane>
  <AtTabsPane
          current={this.state.current}
          index={0}
  >
    <CategoryList> // 自定义组件
      /** 
      **  <Button /> // 按钮触发AtModal
      **  <AtModal />
      */
    </CategoryList>
  </AtTabsPane>
</AtTabs>
```

### 报错信息

无报错信息，但显示不符合预期。
期望：
点击第一个AtTabsPane中的button，AtModal出现在当前AtTabsPane中，
点击第二个AtTabsPane中button，AtModal出现在第二个AtTabsPane中

### 系统信息

👽 Taro v1.2.8

  Taro CLI 1.2.8 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.8.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm

**Comment by koppthe** [comment]
试试把 AtModal 移到最外层，不要放 AtTabs 里面？

**Comment by KingGanZeng** [comment]
@koppthe 放在外面没有问题了，不知道是不是和AtModal的位置有关？

**Comment by koppthe** [comment]
嗯嗯，目前这个版本会跟 AtModal 位置有关，但最好的方式还是 `taro-ui` 这边优化一下

**Comment by KingGanZeng** [comment]
@koppthe ok 谢啦

**Comment by KirySen** [comment]
@KingGanZeng 遇到了同样的问题 但是无法把AtModal放置在Tabs之外 您怎么处理这个问题?

**Comment by KirySen** [comment]
@koppthe 现在还不支持 有什么办法吗?
