### ISSUE TITLE
AtGrid绑定onClick回调函数的参数问题

### ISSUE THREAD

**Issue by kenphil** [NervJS/taro-ui#479]
### Taro UI 版本信息

1.4.0

### 问题描述

很多组件例如AtGrid中的onClick事件中的回调函数中的参数在年前返回的是item的data，现在是个e对象，并且第二个参数index无法获取到

### 复现步骤

AtGrid, AtTabs, AtModal中的onConfirm等等...

### 复现代码

<AtGrid data={data} onClick={this.itemClick.bind(this)}/>

itemClick(item, index) {
    console.log(item, index)
}

### 报错信息

item {..., currentTarget: {dataset: {eHandleclickAA: {某一条数据}}, ...}
index NaN

### 系统信息

Taro v1.1.1

**Comment by koppthe** [comment]
参数变更应该是跟 taro 版本有关系，麻烦升级到最新版本的 taro 和 taro-ui

**Comment by kenphil** [comment]
谢谢，解决
