### ISSUE TITLE
范围选择器onChange返回数据异常

### ISSUE THREAD

**Issue by yuanwyj** [NervJS/taro-ui#481]
### Taro UI 版本信息

2.0.2

### 问题描述

范围选择器AtRange组件，在拖动的回调函数onChange中返回的数组异常，当拖动slider一定距离之后数组中的前后位置对调了

### 复现步骤

1、 按需引入的方式引入AtRange
2、如下代码使用该组件

### 复现代码

            <AtRange
              value={[200,500]}
              min={0}
              max={3000}
              blockSize={18}
              sliderStyle='border:2px solid rgba(255,97,103,1);box-shadow: none;'
              trackStyle='background-color: #FF6167; height:4px'
              railStyle='height: 4px;border-radius: 4px;'
              onChange={this.handleChange.bind(this)}
            />

  handleChange(value) {
    console.log(value);
    this.setState({
      priceRange: value
    })
  }

### 报错信息

未报错

### 系统信息

 Taro v1.2.13

  Taro CLI 1.2.13 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.6.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.8.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.13 => 1.2.13 
      @tarojs/components: 1.2.13 => 1.2.13 
      @tarojs/plugin-babel: 1.2.13 => 1.2.13 
      @tarojs/plugin-csso: 1.2.13 => 1.2.13 
      @tarojs/plugin-sass: 1.2.13 => 1.2.13 
      @tarojs/plugin-uglifyjs: 1.2.13 => 1.2.13 
      @tarojs/redux: 1.2.13 => 1.2.13 
      @tarojs/redux-h5: 1.2.13 => 1.2.13 
      @tarojs/rn-runner: 1.2.13 => 1.2.13 
      @tarojs/router: 1.2.13 => 1.2.13 
      @tarojs/taro-alipay: 1.2.13 => 1.2.13 
      @tarojs/taro-h5: 1.2.13 => 1.2.13 
      @tarojs/taro-swan: 1.2.13 => 1.2.13 
      @tarojs/taro-tt: 1.2.13 => 1.2.13 
      @tarojs/taro-weapp: 1.2.13 => 1.2.13 
      @tarojs/webpack-runner: 1.2.13 => 1.2.13 
      eslint-config-taro: 1.2.13 => 1.2.13 
      eslint-plugin-taro: 1.2.13 => 1.2.13 
    npmGlobalPackages:
      typescript: 3.0.3

**Comment by yuanwyj** [comment]
我好像找到问题了，源码:
  triggerEvent (funcName) {
    const { aX, bX } = this.state
    const a = Math.round((aX / 100) * this.deltaValue)
    const b = Math.round((bX / 100) * this.deltaValue)
    const result = [a, b].sort()

    if (funcName === 'onChange') {
      this.props.onChange(result)
    } else if (funcName === 'onAfterChange') {
      this.props.onAfterChange(result)
    }
  }

这个函数中const result = [a, b].sort()，这句对结果进行排序导致了数组元素顺序不对

**Comment by jimczj** [comment]
AtRange 返回一个范围，这个范围是从小到大的，这个没错哦，就是预期行为

**Comment by yuanwyj** [comment]
> AtRange 返回一个范围，这个范围是从小到大的，这个没错哦，就是预期行为

是要从小到大排序没错，但是这个sort()函数用的有些问题，我是这么写的
 sortNum(a, b) {
    return a-b
  }

**Comment by yuanwyj** [comment]
> AtRange 返回一个范围，这个范围是从小到大的，这个没错哦，就是预期行为

是要从小到大排序没错，但是这个sort()函数用的有些问题，我是这么写的
sortNum(a, b) {
return a-b
}   
 const result = [a, b].sort( this.sortNum )
从而解决了这个问题
