### ISSUE TITLE
import taro-ui 出现 module not found 

### ISSUE THREAD

**Issue by RGXMG** [NervJS/taro-ui#49]
### 重现步骤
* 安装taro-ui之后
*  引入taro-ui
![qq 20180905155710](https://user-images.githubusercontent.com/36947182/45079470-396ab180-b125-11e8-89a3-44680c2147b2.png)
* 使用
![qq 20180905160228](https://user-images.githubusercontent.com/36947182/45079883-2b696080-b126-11e8-8f5d-983fc22ea927.png)
* dev:h5模式下报错
![qq 20180905160005](https://user-images.githubusercontent.com/36947182/45079513-599a7080-b125-11e8-9227-6dff7b6ac60a.png)

### 依赖的版本号

* Node 的版本： 8.0.11
* Taro: 1.0.0-beta.23
* Taro-UI :1.1.1

**Comment by SzHeJason** [comment]
估计是你使用了 less 作为样式编译~

**Comment by RGXMG** [comment]
是的，我是采用了less，而没有用sass

**Comment by SzHeJason** [comment]
@RGXMG 你好这个问题解决了吗

**Comment by SzHeJason** [comment]
暂时关闭 如有问题 欢迎反馈
