### ISSUE TITLE
受控组件只能在page中使用吗，否则无法使用state?

### ISSUE THREAD

**Issue by terryjim** [NervJS/taro-ui#491]

**Comment by terryjim** [comment]
主页面：
<View >
<Remote/>
</View>

Remote组件：
export default class Remote extends Component {  
    constructor(props) {
        super(props);
        this.state = {
            current: 0       }
…………
Remote定义的state无法获取

**Comment by jimczj** [comment]
该问题与 taro-ui 无关，且不符合规范，此 issue 关闭

**Comment by terryjim** [comment]
???

**Comment by jimczj** [comment]
@terryjim 这种问题请去 Taro 那里提问，且注意提问格式和代码粘贴格式
