### ISSUE TITLE
taro刚初始化的项目，npm install taro-ui会报错

### ISSUE THREAD

**Issue by clearlove520** [NervJS/taro-ui#492]
pm ERR! path e:\myThreeApp\node_modules\_node-sass@4.11.0@node-sass\node_modules\cross-spawn\node_modules\.bin\which.cmd
npm ERR! code EEXIST
npm ERR! Refusing to delete e:\myThreeApp\node_modules\_node-sass@4.11.0@node-sass\node_modules\cross-spawn\node_modules\.bin\which.cmd: ..\..\..\_which@1.3.1@which\bin\which symlink target is not controlled by npm e:\myThreeApp\node_modules\_node-sass@4.11.0@node-sass\node_modules\cross-spawn\node_modules\which
npm ERR! File exists: e:\myThreeApp\node_modules\_node-sass@4.11.0@node-sass\node_modules\cross-spawn\node_modules\.bin\which.cmd
npm ERR! Move it away, and try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-03-20T08_05_15_988Z-debug.log

**Comment by so-diao** [comment]
手动装一下node-sass看看。

**Comment by jimczj** [comment]
使用 cnpm 按照呗
