### ISSUE TITLE
引入某些组件编译出现乱码

### ISSUE THREAD

**Issue by tombsmrliu** [NervJS/taro-ui#495]
错误情况如图：编译到imagepicker开始出现乱码。
![image](https://user-images.githubusercontent.com/15997530/54800503-443dfb80-4c9d-11e9-9fd9-71ff98707794.png)

**Comment by jimczj** [comment]
Taro 什么版本，升级 Taro 吧

**Comment by tombsmrliu** [comment]
版本是2.0.1

**Comment by tombsmrliu** [comment]
更新到最新的2.0.2还是有乱码

> Taro 什么版本，升级 Taro 吧
