### ISSUE TITLE
AtTabs和Swiper一起使用，报错，单独使用没问题

### ISSUE THREAD

**Issue by hlwen** [NervJS/taro-ui#497]
### Taro UI 版本信息

2.0.2

### 问题描述

在h5 中，AtTabs和Swiper一起使用，报错整个页面用不了

### 复现步骤

1.AtTabs和Swiper放在一个页面使用
2.单独是用都是正常的

### 复现代码

在页面使用： 
 <AtTabs
            current={current}
            scroll
            tabList={Category}
            onClick={this.handleClick}
          >
          </AtTabs>
        </View>
        <View style={{position: 'relative'}} className="header">
          <Swiper
            className='test-h'
            indicatorColor='#999'
            indicatorActiveColor='#333'
            circular
            indicatorDots
            autoplay
          >
            {Sowing && Sowing.map((i, n) => (
              <SwiperItem key={n}>
                <Background url={i.pic}/>
              </SwiperItem>
            ))
            }

报错代码位置
xport default class AtTabs extends AtComponent {
  constructor() {
    super(...arguments);
    this.state = {
      _scrollLeft: '',
      _scrollTop: '',
      _scrollIntoView: ''
    };
    this._tabId = isTest() ? 'tabs-AOTU2018' : uuid();
    // 触摸时的原点
    this._touchDot = 0;
    // 定时器
    this._timer = null;
    // 滑动时间间隔
    this._interval = 0;
    // 是否已经在滑动
    this._isMoving = false;
  }

  updateState = idx => {
    if (this.props.scroll) {
      // 标签栏滚动
      switch (ENV) {
        case Taro.ENV_TYPE.WEAPP:
        case Taro.ENV_TYPE.ALIPAY:
        case Taro.ENV_TYPE.SWAN:
          this.setState({
            _scrollIntoView: `tab${idx - 1}`
          });
          break;

        case Taro.ENV_TYPE.WEB:
          {
            const index = Math.max(idx - 1, 0);
            const prevTabItem = this.tabHeaderRef.childNodes[index];
            this.setState({
              _scrollTop: prevTabItem.offsetTop,
              _scrollLeft: prevTabItem.offsetLeft
            });
            break;
          }

        default:
          console.warn('AtTab 组件在该环境还未适配');
          break;
      }
    }
  };

### 报错信息

index.js?ff21:47 Uncaught (in promise) TypeError: Cannot read property 'offsetTop' of undefined
    at AtTabs._this.updateState (index.js?ff21:47)
    at AtTabs.componentDidMount (index.js?ff21:128)
    at eval (index.js?1e21:1583)
    at errorCatcher (index.js?1e21:1481)
    at eval (index.js?1e21:1582)
    at Array.forEach (<anonymous>)
    at flushMount (index.js?1e21:1578)
    at updateComponent (index.js?1e21:1665)
    at Route.forceUpdate (index.js?1e21:1761)
    at eval (index.esm.js?eb04:2519)

### 系统信息

 Taro CLI 1.2.20 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.11.0 - ~/.nvm/versions/node/v10.11.0/bin/node
      Yarn: 1.12.3 - ~/.nvm/versions/node/v10.11.0/bin/yarn
      npm: 6.8.0 - ~/.nvm/versions/node/v10.11.0/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.20 => 1.2.20 
      @tarojs/components: 1.2.20 => 1.2.20 
      @tarojs/plugin-babel: 1.2.20 => 1.2.20 
      @tarojs/plugin-csso: 1.2.20 => 1.2.20 
      @tarojs/plugin-less: 1.2.20 => 1.2.20 
      @tarojs/plugin-sass: 1.2.20 => 1.2.20 
      @tarojs/plugin-uglifyjs: 1.2.20 => 1.2.20 
      @tarojs/redux: 1.2.20 => 1.2.20 
      @tarojs/redux-h5: 1.2.20 => 1.2.20 
      @tarojs/rn-runner: 1.2.20 => 1.2.20 
      @tarojs/router: 1.2.20 => 1.2.20 
      @tarojs/taro: 1.2.20 => 1.2.20 
      @tarojs/taro-alipay: 1.2.20 => 1.2.20 
      @tarojs/taro-h5: 1.2.20 => 1.2.20 
      @tarojs/taro-swan: 1.2.20 => 1.2.20 
      @tarojs/taro-tt: 1.2.20 => 1.2.20 
      @tarojs/taro-weapp: 1.2.20 => 1.2.20 
      @tarojs/webpack-runner: 1.2.20 => 1.2.20 
      eslint-config-taro: 1.2.20 => 1.2.20 
      eslint-plugin-taro: 1.2.20 => 1.2.20 
      nervjs: ^1.3.0 => 1.3.9

**Comment by Garfield550** [comment]
你好，Taro-UI 2.2.4 无法复现

![image](https://user-images.githubusercontent.com/3471836/67740560-329dad00-fa51-11e9-9b9d-5d4742b346d2.png)

```jsx
import Taro from '@tarojs/taro'
import { View, Swiper, SwiperItem, Image } from '@tarojs/components'
import { AtTabs, AtTabsPane } from 'taro-ui'
import DocsHeader from '../../components/doc-header'
import './index.scss'

export default class Index extends Taro.Component {
  config = {
    navigationBarTitleText: 'Taro UI'
  }
  constructor () {
    super(...arguments)
    this.state = {
      current1: 0,
      current2: 0,
      current3: 0,
      current4: 0,
      current5: 0,
      // Swiper
      current: 1,
      duration: 500,
      interval: 2000,
      isCircular: false,
      isAutoplay: true,
      hasIndicatorDots: true,
      imgUrls: [
        'https://img10.360buyimg.com/babel/s700x360_jfs/t25855/203/725883724/96703/5a598a0f/5b7a22e1Nfd6ba344.jpg!q90!cc_350x180',
        'https://img11.360buyimg.com/babel/s700x360_jfs/t1/4776/39/2280/143162/5b9642a5E83bcda10/d93064343eb12276.jpg!q90!cc_350x180',
        'https://img14.360buyimg.com/babel/s700x360_jfs/t1/4099/12/2578/101668/5b971b4bE65ae279d/89dd1764797acfd9.jpg!q90!cc_350x180'
      ]
    }
  }
  handleClick (stateName, value) {
    this.setState({
      [stateName]: value
    })
  }
  render () {
    const { current1, current2, current3, current4, current5 } = this.state
    const tabList1 = [{ title: '标签页1' }, { title: '标签页2' }, { title: '标签页3' }]
    const tabList2 = [
      { title: '标签页1' },
      { title: '标签页2' },
      { title: '标签页3' },
      { title: '标签页4' },
      { title: '标签页5' },
      { title: '标签页6' }
    ]
    // Swiper
    const { current, isAutoplay, duration, isCircular, interval, hasIndicatorDots, imgUrls } = this.state

    return (
      <View className='page'>
        <DocsHeader title='Tabs 标签页'></DocsHeader>

        <View className='doc-body'>
          {/* 基础用法 */}
          <View className='panel'>
            <View className='panel__title'>等宽标签栏</View>
            <View className='panel__content'>
              <Swiper
                indicatorColor='#999'
                indicatorActiveColor='#333'
                current={current}
                duration={duration}
                interval={interval}
                circular={isCircular}
                autoplay={isAutoplay}
                indicatorDots={hasIndicatorDots}
              >
                {
                  imgUrls.map((item, idx) => (
                    <SwiperItem key={idx}>
                      <Image src={item} className='slide-image' width='355' height='150' />
                    </SwiperItem>
                  ))
                }
              </Swiper>
              <AtTabs swipeable={false} current={current1} tabList={tabList1} onClick={this.handleClick.bind(this, 'current1')}>
                <AtTabsPane current={current1} index={0} >
                  <View>
                    <Swiper
                      indicatorColor='#999'
                      indicatorActiveColor='#333'
                      current={current}
                      duration={duration}
                      interval={interval}
                      circular={isCircular}
                      autoplay={isAutoplay}
                      indicatorDots={hasIndicatorDots}
                    >
                      {
                        imgUrls.map((item, idx) => (
                          <SwiperItem key={idx}>
                            <Image src={item} className='slide-image' width='355' height='150' />
                          </SwiperItem>
                        ))
                      }
                    </Swiper>
                  </View>
                  <View className='tab-content'>标签页一的内容</View>
                </AtTabsPane>
                <AtTabsPane current={current1} index={1}>
                  <View className='tab-content'>标签页二的内容</View>
                </AtTabsPane>
                <AtTabsPane current={current1} index={2}>
                  <View className='tab-content'>标签页三的内容</View>
                </AtTabsPane>
              </AtTabs>
            </View>
          </View>
        </View>
      </View>
    )
  }
}

```
