### ISSUE TITLE
Flex布局无效

### ISSUE THREAD

**Issue by grubxy** [NervJS/taro-ui#50]
taro 1.0.0-beta.21
taro-ui 1.1.0

Flex布局无效

已配置：
if (process.env.TARO_ENV === "weapp") {
  require("taro-ui/dist/weapp/css/index.css")
} else if (process.env.TARO_ENV === "h5") {
  require("taro-ui/dist/h5/css/index.css")
}

![_20180905161432](https://user-images.githubusercontent.com/1298241/45080268-1a6d1f00-b127-11e8-90a2-3882588fa831.png)

**Comment by SzHeJason** [comment]
可以把完整的代码贴出来吗？

**Comment by grubxy** [comment]
应该是和目录有关，写到components里面就无效了。有这个要求？

![_20180905180704](https://user-images.githubusercontent.com/1298241/45086749-82773180-b136-11e8-99d3-df667ff8dc42.png)

**Comment by SzHeJason** [comment]
我估计是因为你在component内部没有引用 
```js
if (process.env.TARO_ENV === "weapp") {
require("taro-ui/dist/weapp/css/index.css")
} else if (process.env.TARO_ENV === "h5") {
require("taro-ui/dist/h5/css/index.css")
}
```
这行代码，因为小程序里面 组件内部的样式 是不会被外部影响的

**Comment by grubxy** [comment]
感谢已经解决。
