### ISSUE TITLE
字节跳动小程序中报错 Bad attr tt:if

### ISSUE THREAD

**Issue by ghyzx** [NervJS/taro-ui#503]
用npm run dev:tt 命令 生成字节跳动小程序后，用其开发者工具打开，报错 Bad attr tt:if ，微信小程序和支付宝小程序是ok的。
从报错信息推测，可能是AtGrid组件有问题。
![tt](https://user-images.githubusercontent.com/5229158/55271007-4af1f180-52e1-11e9-9eb5-c80fde998ca7.png)

附： "taro-ui": "^2.0.2"

 taro info
👽 Taro v1.2.22
  Taro CLI 1.2.22 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.10.0 - /usr/local/bin/node
      Yarn: yarn install v0.27.5
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.36s. - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm

**Comment by koppthe** [comment]
字体跳动小程序还没开始适配哈🤣

**Comment by ghyzx** [comment]
@koppthe  可有相应的适配计划 或 时间安排？方便透露一下不？

**Comment by jimczj** [comment]
字节跳动适配等待排期，相关 issue 先关闭
