### ISSUE TITLE
AtInput组件的onChange事件中设置value属性，只改变一次

### ISSUE THREAD

**Issue by TonyLiuYan** [NervJS/taro-ui#504]
AtInput组件的onChange事件中设置value属性，只改变一次
目的是为了监听用户的输入，在不满足条件的情况下，文本框不显示输入的内容，
比如：文本框类型为number类型，限制用户输入的值不得大于1000，当用户输入999时，再输入一个9这个时候判断数字大于1000，文本框需要仍显示999，
通过在onChange中改变state的对应的值，只在第一次发生了改变
伪代码如下

```

  change = e => {
    this.setState({ value: "0000" });
  };
  render() {
    return (
      <View className="index">
        <AtInput value={this.state.value} onChange={this.change} />
      </View>
    );
  }
```

**Comment by koppthe** [comment]
麻烦按 Issue 模板重新编辑一下吧，至少得提供 taro 和 taro-ui 的版本号

**Comment by jimczj** [comment]
在 onChange 函数 return "0000" 就可以了，这是微信小程序改变输入框 value 的方法
