### ISSUE TITLE
AtFloatLayout里面放一个 AtTextarea ios上页面下拉可以看到文字内容

### ISSUE THREAD

**Issue by kalsolio** [NervJS/taro-ui#505]
**问题描述**
AtFloatLayout里面放一个 AtTextarea 
ios上页面下拉可以看到文字内容
AtTabBar fixed属性的时候   遮挡了一部分文字内容

 - 报错平台 [weapp]

**补充信息**

https://s17.aconvert.com/convert/p3r68-cdx67/ovheb-2b4yc.gif

![head-color](https://s17.aconvert.com/convert/p3r68-cdx67/ovheb-2b4yc.gif)

**Comment by kalsolio** [comment]
演示
![image](https://user-images.githubusercontent.com/14342288/55378443-90195c00-554b-11e9-9a77-d1294ec429c7.png)

**Comment by SzHeJason** [comment]
都是 404 页面~~
你看看是不是跟这个一样 #75
