### ISSUE TITLE
百度小程序里AtCalendar组件不能点选

### ISSUE THREAD

**Issue by meicx** [NervJS/taro-ui#506]
百度小程序中AtCalendar组件工作不了 日期不能点选 绑定的事件也没有触发
代码
<AtCalendar onSelectDate={() => {console.log("select")}} />
效果
![image](https://user-images.githubusercontent.com/19547619/55447862-2014df80-55f8-11e9-9d39-bd51b69f6dce.png)

**Comment by koppthe** [comment]
版本信息贴一下，麻烦按 Issue 模板提交问题哈
