### ISSUE TITLE
action-sheet body中定义scroll-view组件时候，scoll-view无法滚动。

### ISSUE THREAD

**Issue by RYUDEN** [NervJS/taro-ui#507]
**这个功能解决了什么问题？**

action-sheet body中定义scroll-view组件时候，scoll-view无法滚动。
会有场景是弹出的sheet中进行地址选择，当地址列表过长需要使用scroll-view来进行滚动选择。
该组件中阻止默认滚动事件，阻止了滚动。
**你期望的功能是怎样的？**

去掉阻止默认事件那一句。
**补充信息**

        taro-ui/src/components/action-sheet/index.js
      该文件 第57行，注释即可。

**Comment by koppthe** [comment]
这是特意加上去的，因为 ActionSheet 从交互上来说就不应该放 ScrollView
具体可查阅一下文档：https://developer.apple.com/design/human-interface-guidelines/ios/views/action-sheets/

**Comment by soakit** [comment]
import 'default-passive-events';
可以解决
