### ISSUE TITLE
AtToast提前close

### ISSUE THREAD

**Issue by GrasFishs** [NervJS/taro-ui#509]
**问题描述**

AtToast尽管isOpened属性还是true时，到了默认duration时就会自动close
**复现步骤**

``` tsx
state = {
  show: true
}
componentDIdMount(){
   setTimeout(()=>{
     this.setState({show:false});
   }, 4000);
}

render(){
   // 3000ms后就close了
   return <AtToast isOpened={this.state.show} status="loading" />
}
```
**期望行为**

isOpend开启,duration没有设置的情况下，close根据isOpened判断
**报错信息**

未设置duration时，isOpened在duration更长的时间后设为false会提前退出。
**系统信息**

 - Taro 版本 [1.2.4]
 - Taro UI 版本 [2.0.2]
 - 报错平台 [weapp]

**补充信息**

**Comment by SzHeJason** [comment]
需要把 duration 设置成 0 即可 ，绝大部分的应用场景都是 会自动消息 所以默认就是自动消息的
