### ISSUE TITLE
AtInput 事件返回当前事件 event

### ISSUE THREAD

**Issue by b1ngx** [NervJS/taro-ui#515]
**这个功能解决了什么问题？**

组件：
- AtInput

事件：
 - onChange
 - onFocus
- onBlur
返回值：输入框当前值 value

**你期望的功能是怎样的？**

返回值：输入框当前事件 event

**补充信息**

期望和小程序表现一致，以获取更详细的事件状态

**Comment by jimczj** [comment]
onChange 第二个参数可以获得 event
