### ISSUE TITLE
请问为什么在自定义组件中，为taro-ui组件设置className失效？

### ISSUE THREAD

**Issue by imageslr** [NervJS/taro-ui#517]
**问题描述**
我现在正在自定义一个组件，然后在页面中引用这个组件。该组件中，我引用了两个TaroUI的组件，并为它们设置className。我记得在页面中这种使用方式可行，但是在组建中，下面这段代码失效：

```js
export default class ReviewItem extends Component {
  static options = {
    addGlobalClass: true
  };
  render() {
    return (
      <View>
        <AtAvatar className='test' circle />
        <AtRate className='test' />
        <View className='test' style={{ backgroundColor: "black" }} />
      </View>
    );
  }
```

```css
.test {
  width: 64px;
  height: 64px;
}
```

其实际显示效果如下图：
![image](https://user-images.githubusercontent.com/17822028/55816981-132b4b00-5b26-11e9-9b83-7e89a5f7d512.png)

从wxml调试器中可以看到，三个组件均有test类，但是只有第三个`<View />`的test样式生效了，`AtAvatar`与`AtRate`均没有获取到test样式。请问这是为什么呢？
![image](https://user-images.githubusercontent.com/17822028/55817138-6d2c1080-5b26-11e9-85ff-4c0df887a962.png)
![image](https://user-images.githubusercontent.com/17822028/55817170-80d77700-5b26-11e9-90a8-5bdec7d8aa9b.png)

另外，以上test样式定义在`/components/review-item/index.scss`中，如果将其移动到引入ReviewItem组件的page的样式文件中，`AtAvatar`与`AtRate`的test样式会生效。

**Comment by imageslr** [comment]
或者我的问题是否可以表述成这样：

如果我想在我的自定义组件（非页面中）引用TaroUI的组件，我是否不能为TaroUI组件设置`className`属性？我只能通过`customStyle`控制TaroUI组件的样式吗？

**Comment by koppthe** [comment]
通过添加 `className` 去增加样式，只有部分组件是支持的，不建议使用这种方式去覆盖 `taro-ui` 的组件样式。具体样式覆盖的方式请查看「自定义主题」那一章的文档。

另外你说的样式不生效的问题，是因为微信小程序的 `globalClass`  只对 Page 上的 class 起作用，麻烦看一遍「自定义主题」这一章的文档：https://taro-ui.aotu.io/#/docs/customizetheme

> 可以了解一下 `Web Component` 和微信小程序的 `globalClass`

**Comment by imageslr** [comment]
非常感谢！我现在将组件的样式内容移动到'/styles/'目录下，可以生效了。

**Comment by kid1412621** [comment]
> 通过添加 `className` 去增加样式，只有部分组件是支持的，不建议使用这种方式去覆盖 `taro-ui` 的组件样式。具体样式覆盖的方式请查看「自定义主题」那一章的文档。
> 
> 另外你说的样式不生效的问题，是因为微信小程序的 `globalClass` 只对 Page 上的 class 起作用，麻烦看一遍「自定义主题」这一章的文档：https://taro-ui.aotu.io/#/docs/customizetheme
> 
> > 可以了解一下 `Web Component` 和微信小程序的 `globalClass`

AtFab 组件没开启 addGlobalClass 吗? 文档里面又说所有组件都开启了的 = = ,咋又是部分了, 来不及改代码,麻烦改下文档吧
[原文 ---- "Taro UI 的组件均开启了此特性"](https://taro-ui.aotu.io/#/docs/customizetheme)

**Comment by z-Listening** [comment]
> 非常感谢！我现在将组件的样式内容移动到'/styles/'目录下，可以生效了。

求详解！！一模一样的问题！styles是个什么目录？怎么生效的？？

**Comment by imageslr** [comment]
styles 是我存放全局样式的位置，我存在styles 的意思是我在 app.wxss里 import 这个样式文件。 app.wxss 是全局生效的，自然相当于是 `globalClass` 了。

**Comment by z-Listening** [comment]
> styles 是我存放全局样式的位置，我存在styles 的意思是我在 app.wxss里 import 这个样式文件。 app.wxss 是全局生效的，自然相当于是 `globalClass` 了。

明白啦~感谢^_^
我这儿也好使啦~我是在app.scss里全局引入的。一个道理，哈哈

**Comment by z-Listening** [comment]
> styles 是我存放全局样式的位置，我存在styles 的意思是我在 app.wxss里 import 这个样式文件。 app.wxss 是全局生效的，自然相当于是 `globalClass` 了。

明白啦，感谢^_^
我这儿也好使啦。我是在app.scss里全局引入的。一个道理，哈哈

**Comment by zhaiduo** [comment]
行是行，但是把自定义组件的样式放入全局，哪还有啥封装的意义...

**Comment by Dlop104** [comment]
> styles 是我存放全局样式的位置，我存在styles 的意思是我在 app.wxss里 import 这个样式文件。 app.wxss 是全局生效的，自然相当于是 `globalClass` 了。

解决了,谢谢
