### ISSUE TITLE
swipe-action组件滑动卡顿

### ISSUE THREAD

**Issue by so-diao** [NervJS/taro-ui#521]
**问题描述**

开发工具真机测试的情况下swipe-action组件卡顿或无反馈。
开发工具模拟器是正常的，官方微信小程序(Taro UI)线上版本也是正常的。
然而我下载taro ui仓库，真机测试swipe-action组件依然会卡。

**复现步骤**

1. 下载taro ui仓库，编译一份微信小程序代码
2. 开发工具启动真机测试
3. 手机上打开swipe-action组件测试

**报错信息**

![joc0t-ftm79](https://user-images.githubusercontent.com/24741025/55925858-968d8f00-5c41-11e9-9141-a22b411416a6.gif)

**系统信息**

 - Taro 版本 v1.2.22
 - Taro UI 版本 2.0.2
 - 报错平台 [weapp]
 - 设备 mi-6

**Comment by so-diao** [comment]
可以看到，有些无响应，有些会延迟。
但是同一部手机测试线上的taro ui小程序swipe-action组件却是很正常。

**Comment by so-diao** [comment]
又测试了一下，只有**开发工具->真机测试**的情况下才会有这种问题，**开发工具->预览**是正常的。

所以算是微信的问题？

**Comment by SzHeJason** [comment]
如果在真机体验下没问题就没问题了， 开发工具-真机测试 会在真机上开启 debug 工具，可能带来卡顿

**Comment by alesjia** [comment]
@so-diao 我在使用swipe-action的时候，如果同时只允许一个item 展开的时候。在安卓手机上经常会有item 滑动不开，不过iphone没有问题，不知道有没有解决方法？

**Comment by Ale-cc** [comment]
真机依旧是卡顿啊  没解决就close掉了



> 如果在真机体验下没问题就没问题了， 开发工具-真机测试 会在真机上开启 debug 工具，可能带来卡顿
