### ISSUE TITLE
AtListItem支持openType属性

### ISSUE THREAD

**Issue by kennylbj** [NervJS/taro-ui#522]
**这个功能解决了什么问题？**
当前AtListItem不支持传入openType属性，而微信小程序中，客服、反馈等页面只能通过Button传入openType来完成，希望列表也能支持这一属性。

**你期望的功能是怎样的？**
点击列表中的项，可以直接根据openType跳转。

**补充信息**
可能需要改变[Item](https://github.com/NervJS/taro-ui/blob/dev/src/components/list/item/index.js)的实现，用Button替代。

**Comment by koppthe** [comment]
如果要增加 openType 支持，得让 AtListItem 支持自定义元素，这块改动会比较大，有待评估

**Comment by kennylbj** [comment]
@koppthe 好的，我看了下源码，可能需要把Item改为用Button实现。

在业务方面，当前的AtListItem如果想要支持客服、反馈、分享、打开其他小程序等操作，只能通过navigateTo一个另做的页面，在该页面通过Button触发，体验可能不大好。

希望你们综合考虑一下。

**Comment by koppthe** [comment]
所以说要支持自定义元素嘛，AtListItem 应该只是一个容器，容器里面的内容由用户定。跟将 Item 改成 Button 是两回事哦

**Comment by DreamPWJ** [comment]
@kennylbj 这个非常常用，比如联系客服，意见反馈等

**Comment by kennylbj** [comment]
@DreamPWJ @koppthe 希望早点支持

**Comment by kennylbj** [comment]
请问有什么进度吗 @koppthe

**Comment by roymax** [comment]
在 AtList  上加一个 Button ，长宽设置为与AtListItem一样，透明，z-index 设置高于AtListItem ，验证通过。

JSX
```
<AtList hasBorder className='list-item'>
       <Button class='contact-button' openType='contact' ></Button>
       <AtListItem
              arrow='right'
              title='啫喱老师'
              iconInfo={{
                size:
                  25, color: '#78A4FA', value: 'message',
              }}
            ></AtListItem>
</AtList>
```

CSS
```
    .contact-button {
      display: inline-block;
      position: absolute;
      width: 100%;
      height: 100%;
      // background: salmon;
      opacity: 0;
      z-index: 99;
    }
```
