### ISSUE TITLE
引入样式

### ISSUE THREAD

**Issue by xuguanqun** [NervJS/taro-ui#528]
**问题描述**
三种引用方式都试了，组件正常引入了，但是没有样式。

**复现步骤**
app.js
import 'taro-ui/dist/style/index.scss' // 引入组件样式 - 方式一
app.scss
@import "~taro-ui/dist/style/index.scss"; // 引入组件样式 - 方式二
@import "~taro-ui/dist/style/components/button.scss"; // 引入所需的组件样式 - 方式三

**报错信息**
均无报错

**Comment by tomdyqin** [comment]
https://taro-ui.aotu.io/#/docs/customizetheme
同样的问题 我看这里解决了~
主要是 基础库要在2.2.3以上

**Comment by lduoduo** [comment]
> **问题描述**
> 三种引用方式都试了，组件正常引入了，但是没有样式。
> 
> **复现步骤**
> app.js
> import 'taro-ui/dist/style/index.scss' // 引入组件样式 - 方式一
> app.scss
> @import "~taro-ui/dist/style/index.scss"; // 引入组件样式 - 方式二
> @import "~taro-ui/dist/style/components/button.scss"; // 引入所需的组件样式 - 方式三
> 
> **报错信息**
> 均无报错

楼主问题解决了吗？我也遇到这个问题了，这个和基础库版本没关系吧？应该是taro工具copy的问题？

**Comment by xuguanqun** [comment]
import 'taro-ui/dist/weapp/css/index.css'
解决
