### ISSUE TITLE
请问浮动按钮怎么用？

### ISSUE THREAD

**Issue by zhou0818** [NervJS/taro-ui#532]
看了官方文档的按钮，有个浮动按钮，但是没找到用法。。。能给个简单用例吗？

**Comment by koppthe** [comment]
文档不是有写吗？

**Comment by zhou0818** [comment]
@koppthe
文档真的没有写啊，我看参数里面也没有这个的设置

**Comment by zhou0818** [comment]
@koppthe 
抱歉，找到了。。我一直在按钮那一页查看。关闭吧。。
