### ISSUE TITLE
微信小程序 AtButton size为small时，高度莫名多5px

### ISSUE THREAD

**Issue by imageslr** [NervJS/taro-ui#534]
如题，微信小程序中，设置AtButton size为small时，高度为35px，但是查看wxml发现其shadow-root中按钮高度只有30px。多出来的这5px导致我无法垂直居中按钮。请问这个问题是为什么呢？

**Comment by imageslr** [comment]
![image](https://user-images.githubusercontent.com/17822028/56190471-d9de6800-605c-11e9-900f-57b1e2164e12.png)

**Comment by imageslr** [comment]
只有一个button，依然是36px，请问是为什么呢？

![image](https://user-images.githubusercontent.com/17822028/56190647-380b4b00-605d-11e9-81d4-a15f37b24109.png)

**Comment by qfish** [comment]
~/taro-ui/dist/style/components/button.scss
.at-button {
  &--small {
    display: inline-block; // 这个样式导致的，覆盖成 flex
  }
}
