### ISSUE TITLE
AtSearchBar组件在真机上输入时出现文本被顶出的问题

### ISSUE THREAD

**Issue by wkl007** [NervJS/taro-ui#535]
### Taro UI 版本信息

2.1.0

### 问题描述

AtSearchBar组件在真机上输入时出现文本被顶出的问题

### 复现步骤

1.在页面中使用组件

2.通过手机真机预览

![真机预览](https://img-blog.csdnimg.cn/20190416190118387.jpg?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzM1ODQ0MTc3,size_16,color_FFFFFF,t_70)

### 复现代码

```javascript
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'
import { AtSearchBar } from 'taro-ui'

import './index.scss'

class Index extends Component {

  config = {
    navigationBarTitleText: '首页'
  }

  render () {
    return (
      <View className='index'>
        <AtSearchBar/>
      </View>
    )
  }
}

export default Index
```

### 报错信息

input中文本被顶出

### 系统信息

```powershell
👽 Taro v1.2.26

  Taro CLI 1.2.26 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.0 - D:\nodejs\node.EXE
      Yarn: 1.15.2 - C:\Users\wkl92\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - D:\nodejs\npm.CMD
```

**Comment by koppthe** [comment]
手机的机型是？

**Comment by wkl007** [comment]
@koppthe 华为p30，魅族iMax 6

**Comment by YangHeLi** [comment]
@koppthe iphone xmas 也有这样的问题 顶的没有那么严重

**Comment by kuailingmin** [comment]
这个问题怎么修改？我也碰到了

**Comment by Garfield550** [comment]
我感觉可能是 SearchBar 里的 Input 高度被定死在 30 像素的问题

https://github.com/NervJS/taro-ui/blob/b0cea8529c6d4bfd4c0ef04bbf171b3cfa84b810/src/components/search-bar/index.js#L106-L108

https://github.com/NervJS/taro-ui/blob/b63eb1aebb366046e3416ab806e76a6f3bddca43/src/style/components/search-bar.scss#L5

**Comment by BestMaster-YS** [comment]
我也出现了这个问题， 问题是 height 30px 但是 padding 为 12px 37px, 所以 修改 .at-search-bar__input 的  padding 和 line-height 就可以了

**Comment by wkl007** [comment]
```  
.at-search-bar__input {
    height: 64px !important;
    padding: 0 60px 0 60px;
}
```
