### ISSUE TITLE
Taro-ui 升级到2.0.2以上，微信小程序编译后css样式全部失效，退回到1.5.4正常

### ISSUE THREAD

**Issue by tmaccs** [NervJS/taro-ui#536]
**问题描述**

Taro-ui 升级到2.0.2以上，微信小程序编译后css样式全部失效，退回到1.5.4正常
**复现步骤**

```js
sudo cnpm install --save taro-ui@2.0.2
npx taro build --type weapp --watch
```
**期望行为**

升级到2.1.0能正常使用
**报错信息**

没有报错
**系统信息**

👽 Taro v1.2.26

  Taro CLI 1.2.26 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.14.0 - ~/.nvm/versions/node/v11.14.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v11.14.0/bin/npm
    npmPackages:
      @tarojs/components: 1.2.26 => 1.2.26
      @tarojs/plugin-babel: 1.2.26 => 1.2.26
      @tarojs/plugin-csso: 1.2.26 => 1.2.26
      @tarojs/plugin-sass: 1.2.26 => 1.2.26
      @tarojs/plugin-uglifyjs: 1.2.26 => 1.2.26
      @tarojs/router: 1.2.26 => 1.2.26
      @tarojs/taro: 1.2.26 => 1.2.26
      @tarojs/taro-alipay: 1.2.26 => 1.2.26
      @tarojs/taro-h5: 1.2.26 => 1.2.26
      @tarojs/taro-swan: 1.2.26 => 1.2.26
      @tarojs/taro-weapp: 1.2.26 => 1.2.26
      @tarojs/webpack-runner: 1.2.26 => 1.2.26
      eslint-config-taro: 1.2.26 => 1.2.26
      eslint-plugin-taro: 1.2.26 => 1.2.26
      nervjs: ^1.3.5 => 1.3.13
      react: ^16.6.3 => 16.8.6
**补充信息**

在issues里找到类似的问题[#389]([url](https://github.com/NervJS/taro-ui/issues/389))，但他出现在H5端，按照解决办法在config/index.js 添加一条配置esnextModules: ['taro-ui'] 没有解决问题。

**Comment by tmaccs** [comment]
2.1.0样式全部失效:
![屏幕快照 2019-04-17 上午2 12 25](https://user-images.githubusercontent.com/10339482/56234099-1dfe5680-60b7-11e9-9c9e-b324aca2cc12.png)

1.5.4正常:
![屏幕快照 2019-04-17 上午2 18 08](https://user-images.githubusercontent.com/10339482/56234109-25bdfb00-60b7-11e9-94ca-9b2d65bdf3d3.png)

**Comment by koppthe** [comment]
麻烦看一下「快速上手」的文档，谢谢~

**Comment by tmaccs** [comment]
> 麻烦看一下「快速上手」的文档，谢谢~
> 微信基础库版本设置了吗？

好吧，确实按照快速上手改了一下就好了，但是奇怪1.5.0的版本怎么就是正常的..

**Comment by Leadrive** [comment]
@tmaccs 我现在升级到2.2，也是碰到css失效问题，请问要改哪？

**Comment by tmaccs** [comment]
> @tmaccs 我现在升级到2.2，也是碰到css失效问题，请问要改哪？

照着快速上手文档，改一下就好了
