### ISSUE TITLE
AtFab在taro-ui中找不到

### ISSUE THREAD

**Issue by CalebFu** [NervJS/taro-ui#538]
**问题描述**

**复现步骤**

```js
// 这里可以贴代码
```

**期望行为**

**报错信息**

**系统信息**

**补充信息**

**Comment by koppthe** [comment]
升级到最新的版本哈

**Comment by CalebFu** [comment]
最新版本是2.1.0吗？还是没有啊，是不是移除了？

**Comment by CalebFu** [comment]
> 升级到最新的版本哈

最新版本是2.1.0吗？还是没有啊，是不是移除了？

**Comment by Mamba-working** [comment]
我也是的，更新到最新还是没有这个组件

**Comment by Joxon** [comment]
taro-ui@2.1.0，

在 "[...]/node_modules/_taro-ui@2.1.0@taro-ui/@types/index.d.ts"内，

只有AtFloatButton，没有AtFab

https://github.com/NervJS/taro-ui/blob/bdef8d0fc32c2ca9254172cef673b8115098dfca/%40types/index.d.ts#L49

**Comment by zhoucs624** [comment]
please referring to [here](https://github.com/NervJS/taro-ui/commit/c50d4eaa1b9343951bd5e2f6ed01c664abde6049)

**Comment by jimczj** [comment]
新版本已发布
