### ISSUE TITLE
AtCard 的 onClick 无法使用继承的组件 function

### ISSUE THREAD

**Issue by ly525** [NervJS/taro-ui#55]
parent 组件的 cardClick 没有被调用。
parent 和 child 组件代码 请参见 https://github.com/NervJS/taro/issues/563
taro 已经修正了这个bug，taro-ui 这边是否需要更新？

### 依赖的版本号

node: v8.9.3
taro:1.0.0-beta.25
taro-ui: 1.1.5

### 相关链接
https://github.com/NervJS/taro/issues/563

**Comment by SzHeJason** [comment]
所以这是一个依赖库 产生的问题吗？ 由于 taro-ui 打包的版本太低？

**Comment by ly525** [comment]
应该是 Taro 修正一部分关于 Component extend 的逻辑，但是 AtCard 没有根据Taro 修正的代码修正原来的逻辑导致的

**Comment by SzHeJason** [comment]
好的 已经定位到问题了 估计近期会发布新版本

**Comment by SzHeJason** [comment]
不好意思 这个要重新打开 解决方案存在一些问题 需要等待taro 支持

**Comment by ly525** [comment]
@SzHeJason 嗯，现在暂时是通过外层嵌套 view解决的，非常感谢。

**Comment by SzHeJason** [comment]
@ly525 在最新的 Taro@1.0.3 中已经修复
