### ISSUE TITLE
AtInput在设置默认value的情况下，placeholder依然存在

### ISSUE THREAD

**Issue by cuiyueshuai** [NervJS/taro-ui#551]
**问题描述**

AtInput在设置默认value的情况下，其中placeholder依然存在
**复现步骤**

```js
 <AtInput
            name='value'
            type='password'
            placeholder='密码'
            value={'000000'}
            onChange={(text) => this._handleChange(text, 'pwd')}
          />
```

**期望行为**
placeholder消失

**报错信息**

<img width="409" alt="image" src="https://user-images.githubusercontent.com/13741688/56716206-4c8dc880-676c-11e9-824c-7aca6028a0d2.png">

**系统信息**

taro-ui版本：v2.0.2
taro版本：v1.2.22
报错平台：weapp

**补充信息**

**Comment by MichaelGong** [comment]
官方文档是这么说的[Facepalm][Facepalm]：
![image](https://user-images.githubusercontent.com/11348074/56734093-87a3f200-6794-11e9-8cb9-b23a0ee6f8cc.png)

**Comment by han88829** [comment]
"taro-ui": "^2.0.1"
真机开发者工具使用AtSearchBar遇到同样问题

**Comment by jimczj** [comment]
升级到最新版本 Taro，Taro UI 没有此问题
