### ISSUE TITLE
AtModal content 字符串解析（H5）

### ISSUE THREAD

**Issue by chensiyuan12138** [NervJS/taro-ui#554]
**问题描述**

H5环境下，AtModal 组件传入 ‘content’ 字符串里存在‘\n’之类的，不能实现想得到效果

**复现步骤**

```js
// 这里可以贴代码
<AtModal
    isOpened={this.state.isOpened}
    title='购买说明'
    confirmText='知道了'
    content='lksdfkl\nfklsdlkf'
/>
```

**期望行为**

希望可以解析\n，\t之类的，或者提交一个临时的解决方案
**报错信息**

**系统信息**

 Taro CLI 1.2.22 environment info:
    System:
      OS: macOS High Sierra 10.13.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.4 - ~/.nvm/versions/node/v8.11.4/bin/node
      Yarn: 1.13.0 - ~/.nvm/versions/node/v8.11.4/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v8.11.4/bin/npm
    npmPackages:
      @tarojs/components: 1.2.22 => 1.2.22 
      @tarojs/plugin-babel: 1.2.22 => 1.2.22 
      @tarojs/plugin-csso: 1.2.22 => 1.2.22 
      @tarojs/plugin-sass: ^1.2.26 => 1.2.26 
      @tarojs/plugin-uglifyjs: 1.2.22 => 1.2.22 
      @tarojs/router: 1.2.22 => 1.2.22 
      @tarojs/taro: 1.2.22 => 1.2.22 
      @tarojs/taro-alipay: 1.2.22 => 1.2.22 
      @tarojs/taro-h5: ^1.2.22 => 1.2.22 
      @tarojs/taro-swan: 1.2.22 => 1.2.22 
      @tarojs/taro-tt: 1.2.22 => 1.2.22 
      @tarojs/taro-weapp: 1.2.22 => 1.2.22 
      @tarojs/webpack-runner: ^1.2.26 => 1.2.26 
      eslint-config-taro: 1.2.22 => 1.2.22 
      eslint-plugin-taro: 1.2.22 => 1.2.22 
      nervjs: ^1.3.9 => 1.3.13

**补充信息**

**Comment by giantss** [comment]
+1 求快速解决

![132121560147105_ pic](https://user-images.githubusercontent.com/13778798/59175931-f93fd000-8b89-11e9-9bf8-f8ad5b920a9b.jpg)

<img width="551" alt="image" src="https://user-images.githubusercontent.com/13778798/59175951-0a88dc80-8b8a-11e9-90bd-f4bb07074242.png">

**Comment by produmpling** [comment]
这里引出了另外的一个问题，虽然 content 是 string ，但是 其实可传递 <View></View> 这种的，但是你做了一个 \n replace 成<br/>的时候，那么就必须是string，导致原先设置了<View></View> 的导致js报错 @AwesomeDevin

**Comment by produmpling** [comment]
AwesomeDevin 这里引出了另外的一个问题，虽然 content 是 string ，但是 其实可传递` <View></View>`这种的，但是你做了一个 \n replace `<br/>` 成
的时候，那么就必须是string，导致原先设置了`<View></View>` 的导致js报错 @AwesomeDevin
