### ISSUE TITLE
AtTabBar 使用Taro.redirectTo 跳转AtTabBar 消失

### ISSUE THREAD

**Issue by Chad97** [NervJS/taro-ui#555]
**问题描述**

问题描述：使用AtTabBar fixed 点击Taro.redirectTo跳转路由后AtTabBar 消失了

**复现步骤**

```js
// 这里可以贴代码
```

**报错信息**

没有报错

**系统信息**

� Taro v1.2.26

  Taro CLI 1.2.26 environment info:
    System:
      OS: Windows 7
    Binaries:
      Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.15.2 - C:\Users\lp\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**补充信息**
例： 一个公共的AtTabBar ， 需要在每个页面都引入

如何能让这个公共的AtTabBar 只渲染一次， 像react那样所有页面调用，
而不是每个页面都引入一次，重复渲染一次，
路由是如何配置的呢？

**Comment by Garfield550** [comment]
这个是小程序自身限制导致的，自定义的 TabBar 页面跳转时会消失的问题属于正常现象

https://developers.weixin.qq.com/community/develop/doc/0000a0eacacf0056c4d790ba556400?highLine=%25E8%2587%25AA%25E5%25AE%259A%25E4%25B9%2589tabbar%25E8%25B7%25B3%25E8%25BD%25AC%25E6%25B6%2588%25E5%25A4%25B1

**Comment by Chad97** [comment]
> 这个是小程序自身限制导致的，自定义的 TabBar 页面跳转时会消失的问题属于正常现象
> 
> https://developers.weixin.qq.com/community/develop/doc/0000a0eacacf0056c4d790ba556400?highLine=%25E8%2587%25AA%25E5%25AE%259A%25E4%25B9%2589tabbar%25E8%25B7%25B3%25E8%25BD%25AC%25E6%25B6%2588%25E5%25A4%25B1
> 
> https://developers.weixin.qq.com/community/develop/doc/000a8e969982302fbd4881e3e56c00?highLine=%25E8%2587%25AA%25E5%25AE%259A%25E4%25B9%2589tabbar%25E8%25B7%25B3%25E8%25BD%25AC%25E6%25B6%2588%25E5%25A4%25B1
> 
> https://segmentfault.com/q/1010000016381216

好的我去尝试，尝试。感谢！
