### ISSUE TITLE
AtListItem extraText 点击事件 

### ISSUE THREAD

**Issue by leapcloudinc** [NervJS/taro-ui#557]
**这个功能解决了什么问题？**
有的 AtListItem 右边是购买，或者其他点击操作。但是现在点击整个 AtListItem 就执行click方法，小程序又没有 event.target.innerHTML 属性  。
**你期望的功能是怎样的？**

商品展示list，点击 extraText 才会相应事件
**补充信息**

**Comment by cuiyimeng** [comment]
请问你是如何获取到它点击的是那个LIstItem的
