### ISSUE TITLE
input 无法限制输入

### ISSUE THREAD

**Issue by neewbee** [NervJS/taro-ui#560]
**问题描述**
无法限制 input 的输入

**复现步骤**
1. 修改 input 组件的 handleInput 方法
 
```bash
  handleInput (stateName, value) {
    const regexp = /[^a-zA-Z]+/g;
    const newValue = value.replace(regexp, '');
    this.setState({
      [stateName]: newValue
    })
    return newValue
  }
```
2. input 应该无法输入 特殊字符

```js
// 这里可以贴代码
```

**期望行为**
无法输入特殊字符
**报错信息**
可以输入
**系统信息**
👽 Taro v1.2.20

  Taro CLI 1.2.20 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.15.1 - ~/.nvm/versions/node/v8.15.1/bin/node
      npm: 6.9.0 - ~/.nvm/versions/node/v8.15.1/bin/npm

**补充信息**

**Comment by Garfield550** [comment]
你好，你的写法有误，看这个问题
https://github.com/NervJS/taro/issues/2642#issuecomment-478988530

**Comment by neewbee** [comment]
没有吧，我 return 了这个 value 呀

**Comment by jimczj** [comment]
![image](https://user-images.githubusercontent.com/13499146/59430554-2358f280-8e15-11e9-9775-d57588df221e.png)
这个是可以的，如果不行试试升级版本

**Comment by xzedx** [comment]
不行呀，还是有这个问题，onBlur事件
