### ISSUE TITLE
无法获取AtTabs header高度

### ISSUE THREAD

**Issue by yangchendoit** [NervJS/taro-ui#561]
**问题描述**
使用`createSelectorQuery select`获取taro-ui 节点时 返回始终为null，自定义节点无问题

**复现步骤**
```
 let query = Taro.createSelectorQuery().in(that.$scope);
    query.select(".at-tabs__header").boundingClientRect();
    query.exec(res => {
    console.log(res);
    });
```

**期望行为**
能够获取

**报错信息**
![image](https://user-images.githubusercontent.com/27750211/56892153-4de32c00-6ab1-11e9-905f-c9fc093ef4a4.png)

**系统信息**

 - Taro 版本 1.2.26
 - Taro UI 版本 2.1.0
 - 报错平台 weapp

**Comment by jimczj** [comment]
封装的组件没办法获取，这是小程序的限制
