### ISSUE TITLE
能否添加瀑布流组件？ 

### ISSUE THREAD

**Issue by chairy11** [NervJS/taro-ui#562]
hi，我想使用瀑布流效果，本想使用Pinterest的[gestalt组件库(React)](https://pinterest.github.io/gestalt/#/Masonry)，但报错。后来翻ISSUE看到说Taro不支持第三方UI库。
那京东购物小程序也用到了瀑布流，你们会把这个抽成一个组件添加进Taro-UI吗？

**Comment by koppthe** [comment]
暂时没有这个计划，欢迎提 PR~
