### ISSUE TITLE
关于AtTabBar 和  app.js 中 config 下的 tabBar 配置问题

### ISSUE THREAD

**Issue by giantss** [NervJS/taro-ui#565]
作为一个react native开发者首先感谢Taro社区提供的开源资料。

我有些纳闷的是：看完 `AtTabBar`文档后并不是我想象中的 `TabBar`, 无论是原生开发中的 `tabBar` 还是react native中的`tabBar` ,我都无法理解您们AtTabBar的实现。为什么不能直接绑定页面呢，研究了半天最后还是使用了 `app.js`  中 `config` 下的 `tabBar` 配置。当然也有可能是我还有看懂如何使用AtTabBar实现页面绑定和切换，求指点迷津。

**Comment by koppthe** [comment]
我们是建议使用小程序原生的 TabBar ，`AtTabBar` 只是为了满足特殊情况下的自定义而增加的组件，仅仅是 UI 组件，跟原生的 TabBar 组件是有差异的。

**Comment by giantss** [comment]
好吧

**Comment by zicjin** [comment]
希望文档里能说明一下,我浪费了近一天时间在尝试怎么绑定到原生tabbar

**Comment by imkerberos** [comment]
我也花了好几天时间搞这个东西，文档里面说明一下吧。

**Comment by wxxcarl** [comment]
还好研究了一整晚之后就放弃了，墙裂建议在文档说明一下。

**Comment by Garfield550** [comment]
![image](https://user-images.githubusercontent.com/3471836/76380440-b6678e80-638d-11ea-8279-78f01f9fe29f.png)

https://taro-ui.aotu.io/#/docs/tabbar

**Comment by linshimao** [comment]
@Garfield550 跪了
我看的是假文档：https://taro-ui.jd.com/#/docs/tabbar
并没有这句话
