### ISSUE TITLE
H5端AtSwipeAction拉开无法固定，报错获取不到dom的width

### ISSUE THREAD

**Issue by Cicada7year** [NervJS/taro-ui#574]
**问题描述**

**复现步骤**

1. 不太清楚复现问题的步骤

**期望行为**

**报错信息**

![image](https://user-images.githubusercontent.com/31717528/57497984-8a622380-730c-11e9-95e1-b922006342e1.png)

**系统信息**

👽 Taro v1.2.26

  Taro CLI 1.2.26 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.1 - C:\Program Files\nodejs\node.EXE
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

 - Taro 版本 [e.g. v.1.2.26]
 - Taro UI 版本 [e.g. v.2.1.0]
 - 报错平台 [h5]

**补充信息**

**Comment by SzHeJason** [comment]
不好意思 这个问题很多人反馈 但是由于最近没时间去研究怎么重现 所以一直没解决  主要是我找不到复现代码 如果你们又复现代码的话 我随时可以帮你们解决

**Comment by yu86144** [comment]
是因为他们componentId传入了是id，应该是componentId，因为上面componentId里面才++， id是没加加，所以导致componentId重复了

**Comment by yu86144** [comment]
> 不好意思 这个问题很多人反馈 但是由于最近没时间去研究怎么重现 所以一直没解决
> 如果发出现该问题的coder们 提供复现代码的话 我随时可以帮你们解决

是因为他们componentId传入了是id，应该是componentId，因为上面componentId里面才++， id是没加加，所以导致componentId重复了

**Comment by SzHeJason** [comment]
@yu86144  你这边尝试 换成 componentId 就正常了吗？

**Comment by yu86144** [comment]
> @yu86144 你这边尝试 换成 componentId 就正常了吗？ ++id 实际上 id 也是会自增的

但是换成componentId 就没报错了

**Comment by SzHeJason** [comment]
@yu86144  好的 那我改下发个版本

**Comment by yu86144** [comment]
> @yu86144 好的 那我改下发个版本

id是有++， 但是render方法里面的id，还是默认初始值0，我刚才测试过了

**Comment by nicholasxuu** [comment]
这个问题还是存在，微信小程序里，
`delayQuerySelector(..., '#swipeActionOptions-${this.props.componentId}', ...)`的结果是`[null]`，然后`null.width`报错。

**Comment by noneorone** [comment]
> 这个问题还是存在，微信小程序里，
> `delayQuerySelector(..., '#swipeActionOptions-${this.props.componentId}', ...)`的结果是`[null]`，然后`null.width`报错。

支付宝小程序遇到这个问题了，您最后是怎么解决的？
