### ISSUE TITLE
AtInput type为phone, 验证电话号码长度不对

### ISSUE THREAD

**Issue by polofish** [NervJS/taro-ui#576]
**问题描述**
AtInput type为phone, 验证电话号码长度不对

**复现步骤**
<img width="853" alt="WX20190510-121000@2x" src="https://user-images.githubusercontent.com/22722049/57502047-82aa7b00-731c-11e9-80a5-88cc0fb6b4c2.png">
运行如下：
![WX20190510-120510](https://user-images.githubusercontent.com/22722049/57501993-48d97480-731c-11e9-8d18-c9b19a670528.png)

**期望行为**
正确判断手机号码位数

**报错信息**
![WX20190510-120510](https://user-images.githubusercontent.com/22722049/57501993-48d97480-731c-11e9-8d18-c9b19a670528.png)

**系统信息**
Taro v1.2.26
Taro UI: v2.1.0

  Taro CLI 1.2.26 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm

**Comment by jimczj** [comment]
长度 11 位不对吗

**Comment by LaughingZhu** [comment]
> 长度 11 位不对吗
现在好像判断的是值 < 10 ,不是位数

**Comment by polofish** [comment]
是的，长度判断错误

**Comment by polofish** [comment]
@jimczj 是的，长度判断错误

**Comment by polofish** [comment]
@LaughingZhu 对

**Comment by LaughingZhu** [comment]
@jimczj  求解决，项目在用🤒🤒

**Comment by jimczj** [comment]
@LaughingZhu 不清楚你们的问题，我这边是限制长度为 11，并没有限制位数。安卓手机h5 跟小程序都测试正常，可以输入完整都电话号码。而且我们没有设置提示信息，你这个提示信息是哪里来的

**Comment by polofish** [comment]
@jimczj 按照上面代码运行h5, 在谷歌浏览器中访问。就能出现该效果

**Comment by jimczj** [comment]
@polofish 我这边一只是使用谷歌浏览器，你应该是插件影响了吧

**Comment by polofish** [comment]
@jimczj 
我今天升级了一些版本如下，这个问题不存在了。
  taro-ui 2.2.0

  Taro CLI 1.3.0 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.0 => 1.3.0
      @tarojs/cli: 1.3.0 => 1.3.0
      @tarojs/components: 1.3.0 => 1.3.0
      @tarojs/plugin-babel: 1.3.0 => 1.3.0
      @tarojs/plugin-csso: 1.3.0 => 1.3.0
      @tarojs/plugin-less: 1.3.0 => 1.3.0
      @tarojs/plugin-sass: 1.3.0 => 1.3.0
      @tarojs/plugin-uglifyjs: 1.3.0 => 1.3.0
      @tarojs/redux: 1.3.0 => 1.3.0
      @tarojs/redux-h5: 1.3.0 => 1.3.0
      @tarojs/rn-runner: 1.3.0 => 1.3.0
      @tarojs/router: 1.3.0 => 1.3.0
      @tarojs/taro: 1.3.0 => 1.3.0
      @tarojs/taro-alipay: 1.3.0 => 1.3.0
      @tarojs/taro-h5: 1.3.0 => 1.3.0
      @tarojs/taro-swan: 1.3.0 => 1.3.0
      @tarojs/taro-tt: 1.3.0 => 1.3.0
      @tarojs/taro-weapp: 1.3.0 => 1.3.0
      @tarojs/webpack-runner: 1.3.0 => 1.3.0
      eslint-config-taro: 1.3.0 => 1.3.0
      eslint-plugin-taro: 1.3.0 => 1.3.0
      nervjs: ^1.4.0 => 1.4.0
      react-native: 0.59.3 => 0.59.3

**Comment by Yunlong2cn** [comment]
## 复现步骤
```
<AtInput name='myPhone' title='您的电话' type='phone' placeholder='请输入您的电话' value={this.state.myPhone} onChange={() => {}}/>
```
## 执行结果
![image](https://user-images.githubusercontent.com/1751219/59983695-4bd2bf00-9655-11e9-8364-6c05909692a5.png)
## 环境
```
"taro-ui": "^2.2.1"
```
