### ISSUE TITLE
Taro UI的组件可以用在非taro框架的react页面中吗？

### ISSUE THREAD

**Issue by guozefei** [NervJS/taro-ui#577]
如题

**Comment by jimczj** [comment]
Taro 目前不支持此编译选项，无法支持

**Comment by guxingke201** [comment]
[Nerv 提供了比 React 更好的浏览器兼容性和更高的性能，与此同时也不会放弃 React 庞大的生态系统。兼容 React 生态系统是我们开发 Nerv 的重要目标之一。](https://nervjs.github.io/docs/guides/switching-to-nerv.html)
试过几个脚手架，只是改了别名，都不能用。构建正常，运行报异常。做这个实验的目的是想用taro-ui，可惜的是，连nervjs这关都过不来

![image](https://user-images.githubusercontent.com/8326941/60417834-ffb6ea00-9c13-11e9-8d92-e539403bdbc0.png)

**Comment by chenyulun** [comment]
taro-ui不能在h5的react里面使用，用react方式编写的意义是什么
