### ISSUE TITLE
TabBar 建议

### ISSUE THREAD

**Issue by jiangzeyin** [NervJS/taro-ui#58]
### 依赖的版本号

taro 1.0.0-beta.24 

taro-ui 1.1.5

### 预期结果

希望图标能自定义，最好能使用http 

### 实际结果
只能使用  AtIcon 控件相关的
### 相关链接

https://taro-ui.aotu.io/#/docs/tabbar

**Comment by jimczj** [comment]
https://github.com/NervJS/taro-ui/issues/36
