### ISSUE TITLE
AtSearchBar 的onClear 没有任何反应

### ISSUE THREAD

**Issue by wuweijian1997** [NervJS/taro-ui#581]
**问题描述**
搜索栏组件 的 onClear 清理输入框内容不生效，点击搜索框右边的x没有任何反应。
开发者工具和安卓还有ios都没有生效

```js
  handleSearchClear = () => {
    console.log("清理");
    this.setState(() => ({
      searchKey: ""
    }))
  };

 <AtSearchBar
          value={searchKey}
          onClear={this.handleSearchClear}
          onChange={this.handleChangeSearchKey}
        />
```

**期望行为**
找到解决的办法

**报错信息**

**系统信息**
� Taro v1.2.26

  Taro CLI 1.2.26 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3 - D:\APP\NODEJS\node.EXE
      Yarn: 1.15.2 - D:\APP\YARN\bin\yarn.CMD
      npm: 6.4.1 - D:\APP\NODEJS\npm.CMD

**Comment by jimczj** [comment]
Taro UI 版本是多少，Taro UI 2.0.3 起支持这个事件哦

**Comment by wuweijian1997** [comment]
我的问题，已经找到问题所在了，padding给多了，把x给覆盖了，点不到那个清除的x
