### ISSUE TITLE
AtInput 不触发 onChange 的问题

### ISSUE THREAD

**Issue by xPixv** [NervJS/taro-ui#583]
**问题描述**
某些情况下，AtInput 不自动触发 onChange 事件

**复现步骤**
比较隐秘的 Bug，只在真机上才能复现

![image](https://user-images.githubusercontent.com/9652227/57973739-2e6c5e80-79e0-11e9-9c92-58fa71bd221a.png)

上面是在 Taro UI 的 Demo 小程序里测试的截图（真机环境：Android 9，WeChat 7.0.4）

可以看到，输入完后，没有触发 AtInput 的 onChange 事件，导致右边的清除 X 按钮都没显示出来。
真实项目中问题就是，用英文输入法输入完成后，直接点其它地方，AtInput 组件失去焦点，没有触发 onChange，导致无法获取用户输入。
这个问题集中出现在使用英文输入法 或者 中文输入法锁定了大写，输入完成后直接失去焦点的情况。

在使用微信小程序官方的 `小程序实例`中，Input 组件没有此问题。所以 Bug 出在 Taro 或 Taro UI。

**期望行为**
正确处理 onChange 事件

**报错信息**
无

**系统信息**

 - Taro 版本 1.2.26
 - Taro UI 版本 2.1.0
 - 报错平台 weapp

**补充信息**
可能相关的 issue:  #465 #323 

我认为这是一个 100% 可复现的 Bug，希望团队能充分考虑一下，谢谢~

**Comment by xPixv** [comment]
还有一个被关掉的 issue 也是这个问题 #195

**Comment by xPixv** [comment]
测试代码：
```tsx
<AtInput
  clear
  name='username'
  title='用户名：'
  type='text'
  placeholder='请输入用户名'
  value={username}
  onChange={this.handleUsernameChange.bind(this)}
  onBlur={this.handleUsernameBlur.bind(this)}
/>
```

```ts
handleUsernameChange(value, event) {
    console.log('onChange')
    console.log(value)
    console.log(event)
    return value
  }

  handleUsernameBlur(value, event){
    console.log('onBlur')
    console.log(value)
    console.log(event)
  }
```

真机测试的 Log 截图：
![image](https://user-images.githubusercontent.com/9652227/57974394-e0f4ef00-79e9-11e9-981e-4218e1c4c595.png)

输入过程中没有触发 onChange，输入完成失去焦点时触发了 onBlur，在 onBlur 中得到了刚输入的 `test` value

**Comment by xPixv** [comment]
目前应急处理办法就是在 onBlur 也 setState 一下，以防万一  ┑(￣Д ￣)┍

希望开发团队能尽快解决，谢谢~ <3

**Comment by hz251** [comment]
iOS没问题，安卓手机无法触发onChang

**Comment by giantss** [comment]
+1 h5上不能触发 onChange事件

`"@tarojs/taro": "1.3.0-beta.6",`

**Comment by jimczj** [comment]
已修复，目前修复方式是 onBlur 的时候调用一次 onChange

**Comment by xPixv** [comment]
好粗暴的解法 😂

**Comment by FloaJa** [comment]
2021年了, 我这里onChange会莫名其妙的自己触发神了
