### ISSUE TITLE
AtModal不兼容Taro新版本

### ISSUE THREAD

**Issue by ctcx** [NervJS/taro-ui#584]
代码
```
<AtModal isOpened={modalOpened} onClose={ _ => this.setState({ modalOpened:false }) }>
          <AtModalHeader>修改密码</AtModalHeader>
          <AtModalContent>
            <Form onSubmit={this.onSubmit} >
            <AtInput name='oldpwd' title='旧密码' type='password' maxLength='16' placeholder='旧密码' value={ '' } />
            <AtInput name='newpwd' title='新密码' type='password' maxLength='16' placeholder='新密码' value={ '' } />
            <Button className='at-button at-button--normal at-button--primary'>提交</Button>
            </Form>
          </AtModalContent>
        </AtModal>
```

**报错信息**
`
VM5316:1 thirdScriptError
isRenderAction is not defined;at App onError function;at api nextTick callback function
ReferenceError: isRenderAction is not defined
    at AtModal._createData (http://127.0.0.1:56060/appservice/npm/taro-ui/dist/weapp/components/modal/index.js:136:7)
    at doUpdate (http://127.0.0.1:56060/appservice/npm/@tarojs/taro-weapp/dist/index.js:3242:22)
    at updateComponent (http://127.0.0.1:56060/appservice/npm/@tarojs/taro-weapp/dist/index.js:3219:5)
    at http://127.0.0.1:56060/appservice/npm/@tarojs/taro-weapp/dist/index.js:2696:15
    at http://127.0.0.1:56060/appservice/__dev__/WAService.js:1:102400
    at Function.pl (http://127.0.0.1:56060/appservice/__dev__/WAService.js:1:545814)
    at http://127.0.0.1:56060/appservice/__dev__/WAService.js:1:102400
    at http://127.0.0.1:56060/appservice/__dev__/WAService.js:1:90596
`

**系统信息**
👽 Taro v1.3.0-beta.3

  Taro CLI 1.3.0-beta.3 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.1.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/components: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/mobx: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/mobx-h5: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/mobx-rn: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/plugin-babel: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/plugin-csso: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/plugin-sass: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/plugin-uglifyjs: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/rn-runner: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/router: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/taro: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/taro-alipay: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/taro-h5: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/taro-swan: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/taro-weapp: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/webpack-runner: 1.3.0-beta.3 => 1.3.0-beta.3 
      eslint-config-taro: 1.3.0-beta.3 => 1.3.0-beta.3 
      eslint-plugin-taro: 1.3.0-beta.3 => 1.3.0-beta.3 
      nervjs: ^1.4.0-beta.3 => 1.4.0-beta.4 
    npmGlobalPackages:
      typescript: 3.1.5

**Comment by joomecow** [comment]
很多组件都不兼容taro新版本，发现AtNoticebar，AtGrid，AtTabBar都有问题

**Comment by xPixv** [comment]
附议。

已经退回到 Taro 1.2.26 版本了

**Comment by jimczj** [comment]
Taro 正式版本 1.3.6 可正常使用，麻烦用这个版本到 Taro 吧
