### ISSUE TITLE
增强ScrollView：下拉刷新与上拉加载更多

### ISSUE THREAD

**Issue by flappyBug** [NervJS/taro-ui#585]
## 这个功能解决了什么问题？

下拉刷新和上拉加载更多在很多场景都是用得到的，关于下拉刷新微信官方推荐的做法是*使用页面的滚动，而不是 scroll-view*。但是从交互上来说，下拉刷新与上拉加载更多应该是scrollview的表现，而且在scroll-view不在最上方的时候，会带着上方的banner一起下拉，感觉怪怪的。
## 你期望的功能是怎样的？

[这是我查到的体验比较完善的原生小程序实现](https://github.com/ianho/xing-weapp-component)，下拉刷新在开发工具中无法体验，需用真机。
## 效果演示
![ezgif-1-d87c863e7eb5](https://user-images.githubusercontent.com/8416130/58030996-23d1d680-7b52-11e9-92b1-a32707a55c8f.gif)

**Comment by jimczj** [comment]
这个使用 scroll-view 都可以实现吧

**Comment by gjjbase** [comment]
怎么实现的？

**Comment by Rahim-Chan** [comment]
[长列表解决方案](https://github.com/Rahim-Chan/taro-listview)

**Comment by imkerberos** [comment]
对啊，到底怎么才能下拉刷新？ 萌新求教。设置了 EnableReferesher 也没什么效果， 文档也很少。

**Comment by 54853315** [comment]
> 对啊，到底怎么才能下拉刷新？ 萌新求教。设置了 EnableReferesher 也没什么效果， 文档也很少。

可以用onRefresherRefresh，不过就算redux数据拿到了，页面刷新了，scrollWithAnimation的动画效果不知道怎么去……反正loading就一直滁在那儿。

**Comment by Ale-cc** [comment]
> > 对啊，到底怎么才能下拉刷新？ 萌新求教。设置了 EnableReferesher 也没什么效果， 文档也很少。
> 
> 可以用onRefresherRefresh，不过就算redux数据拿到了，页面刷新了，scrollWithAnimation的动画效果不知道怎么去……反正loading就一直滁在那儿。

---
参考社区得到解决方案：
① 绑定loading
`const [loading, setLoading] = useState(false);`
②绑定onFresh
`const onRefresherRefresh = useCallback(() => {
    setLoading(true) // 
    getList(); // 异步获取数据
  }, []);`
③异步更新数据的时候loading设置为false
`const getList = () => {
  api.post(url, params).then(()=>{
    setLoading(false);
  }).catch(()=>{
    setLoading(false);
  })
}`
④render里渲染：
`<ScrollView
        scrollY
        refresherTriggered={loading}
        refresherEnabled={true}
        onRefresherRefresh={onRefresherRefresh}
        className="cinemaOverview-ft"
      ></ScrollView>`
