### ISSUE TITLE
AtTextarea 的typescript声明有一个错误

### ISSUE THREAD

**Issue by ooxx87** [NervJS/taro-ui#588]
**问题描述**
AtTextarea  中onBlur事件，在typescript中定义时错些成了obBlur

**复现步骤**
AtTextarea  中onBlur事件，在typescript中定义时错些成了obBlur

**期望行为**
typescript 将obBlur修正为onBlur

**报错信息**
![image](https://user-images.githubusercontent.com/39373576/58073504-4d801180-7bd5-11e9-8d1c-8c16549e7446.png)
![image](https://user-images.githubusercontent.com/39373576/58073508-507b0200-7bd5-11e9-9bab-36dac6f3d687.png)

**系统信息**
Taro UI 版本 [v2.1]

**Comment by jimczj** [comment]
问题已修复
