### ISSUE TITLE
Atinput组件placeholder在安卓机的小程序中显示与输入的值重叠

### ISSUE THREAD

**Issue by yaqunliu** [NervJS/taro-ui#589]
**问题描述**

Atinput组件placeholder在安卓机的小程序中显示与输入的值抖动性的重叠
**复现步骤**

<FormItem icon='contact'>
            <AtInput
              title='联系人'
              value={bindSiteInfo.userName}
              placeholder='必填项'
            />
          </FormItem>
使用安卓机扫描微信开发者工具上的预览二维码，进去小程序，在这个输入框中输入文件会与placeholder重叠显示

**期望行为**

不抖动重叠
**报错信息**

输入文字，光标切换到别的输入框，再切回这个输入框，文字会抖动并且placeholder重叠

**系统信息**

**补充信息**

**Comment by jimczj** [comment]
这个是微信小程序的问题，无法解决
