### ISSUE TITLE
TabBar能否替换小程序tabBar?

### ISSUE THREAD

**Issue by grubxy** [NervJS/taro-ui#59]

**Comment by SzHeJason** [comment]
Taro UI 提供 TabBar 主要是服务在小程序上 可以自定义 TabBar 和 提供 H5 的TabBar功能， 至于能否替换，答案肯定是可以的，主要是也无需求需不需要替换的问题

**Comment by grubxy** [comment]
如何实现微信原生的这种效果，多个页面之间来回切换Tab，而不用重新加载TabBar？

**Comment by SzHeJason** [comment]
暂时实现不了这种效果 除非你是同一个页面使用不同组件来构成应用(SPA) 个人是不推荐这种方式的 TabBar 的主要意义还是为了实现  `h5` 与 `小程序` 保持一致

**Comment by grubxy** [comment]
感谢了解了。
