### ISSUE TITLE
AtGrid 数据问题

### ISSUE THREAD

**Issue by lisong996** [NervJS/taro-ui#594]
**问题描述**
AtGrid weapp无法渲染，h5渲染没有问题

**复现步骤**

```js
 const data = [
      {
        image:
          'https://img12.360buyimg.com/jdphoto/s72x72_jfs/t6160/14/2008729947/2754/7d512a86/595c3aeeNa89ddf71.png',
        value: '待付款'
      },
      {
        image:
          'https://img20.360buyimg.com/jdphoto/s72x72_jfs/t15151/308/1012305375/2300/536ee6ef/5a411466N040a074b.png',
        value: '待收货'
      },
      {
        image:
          'https://img10.360buyimg.com/jdphoto/s72x72_jfs/t5872/209/5240187906/2872/8fa98cd/595c3b2aN4155b931.png',
        value: '已发货'
      },
      {
        image:
          'https://img12.360buyimg.com/jdphoto/s72x72_jfs/t10660/330/203667368/1672/801735d7/59c85643N31e68303.png',
        value: '售后'
      }
    ]

  <AtGrid hasBorder={false} columnNum={4} data={data} />
```

**报错信息**
![TIM截图20190523091636](https://user-images.githubusercontent.com/18183233/58218940-84703780-7d3b-11e9-8512-c191cbe64e08.png)

**系统信息**
 Taro CLI 1.3.0-beta.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 11.9.0 - F:\nodejs\node.EXE
      npm: 6.5.0 - F:\nodejs\npm.CMD

**补充信息**
![TIM截图20190523091806](https://user-images.githubusercontent.com/18183233/58218982-b4b7d600-7d3b-11e9-94e2-27975c45ba15.png)

**Comment by lisong996** [comment]
应该是打包问题，删除dist/weapp后重新生成N次之后问题解决

**Comment by xierenyuan** [comment]
- - 应该不是打包的问题 我以出现呢 是命中 eslint 规则
![image](https://user-images.githubusercontent.com/7599351/60524434-20b83180-9d1f-11e9-857d-ce90615749e5.png)
