### ISSUE TITLE
关于<AtInput>组件的需求

### ISSUE THREAD

**Issue by sinianzhiren** [NervJS/taro-ui#6]
### 预期结果
eg:  132 3345 4597 
### 实际结果
eg: 13233454597

**Comment by jimczj** [comment]
该功能要实现，需要动态加空格，需要设置 `type='text'`，这样系统呼出的不是数字键盘，对用户体验很不友好，所以不准备支持。用户如果需要，可以自己定义类型为 `type='text'`，并监听 `onChange` 实现

**Comment by sinianzhiren** [comment]
对于这种可以禁用自动拉起android或者iOS 的键盘吗，拉起自己写的一个模拟键盘可以吗

**Comment by jimczj** [comment]
这个成本有点高而且功能并不是痛点，暂不准备支持
