### ISSUE TITLE
关于SerachBar组件基础用法的input框内在苹果6s和x上面都是不垂直居中，字体显示不完整

### ISSUE THREAD

**Issue by 1Crazy** [NervJS/taro-ui#600]
关于SerachBar组件基础用法的input框内在苹果6s和x上面都是不垂直居中，字体显示不完整

**Comment by 1Crazy** [comment]
感谢

**Comment by chengxgit** [comment]
这个是
.at-search-bar__input{
   padding: $at-search-bar-placeholder-padding 
}
$at-search-bar-placeholder-padding ：12PX
这个属性的上下内边距引用的值不对 上下内边距过大 

在全局样式中添加一下下面样式就可以用了：
.at-search-bar__input{
   padding: 2PX 37PX
}

**Comment by 1Crazy** [comment]
正常了，感谢
