### ISSUE TITLE
npm 的 @types 与 Github 里的不符

### ISSUE THREAD

**Issue by Lizhooh** [NervJS/taro-ui#601]
@luckyadam

**问题描述**

npm 的 @types 与 Github 里的不符，npm 里的 @types 有类型错误，我看到 17 天前就改了，但是没有发布新的版本，导致 npm 上的 @types 还是旧的代码。麻烦修复一下！

```js
    "taro-ui": "^2.1.0",
```

**复现步骤**

![da3](https://user-images.githubusercontent.com/19299088/58368090-9cea7880-7f1a-11e9-9a6d-86c532d272b3.png)

**期望行为**

**报错信息**

**系统信息**

**补充信息**

**Comment by jimczj** [comment]
已发版
