### ISSUE TITLE
希望部分组件的props的类型也可以支持ReactNode

### ISSUE THREAD

**Issue by wkeylin** [NervJS/taro-ui#603]
### 这个功能解决了什么问题？

很多组件的props都只是string类型，如果要对其进行样式更改，虽然可以用自定义样式进行覆盖，但是如果要更改dom结构，这个组件就无法使用，比如需要加一个图标。

### 你期望的功能是怎样的？

希望部分组件的props的类型也可以支持ReactNode，组件的适用范围也可以更加宽广

**Comment by jimczj** [comment]
这个是 Taro 支持不了，小程序能力问题
