### ISSUE TITLE
ImagePikcer 参数 multiple count 无效

### ISSUE THREAD

**Issue by juxiaowei** [NervJS/taro-ui#605]
**问题描述**

**复现步骤**

```js
<AtImagePicker
                  length={1}
                  count={1}
                  files={value['cover']}
                  onChange={this.onChangeImage.bind(this)}
                />
```

**期望行为**

H5 可以单选
**报错信息**

**系统信息**

Taro v1.3.0-beta.4

  Taro CLI 1.3.0-beta.4 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.9.0 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.2.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/components: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/plugin-babel: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/plugin-csso: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/plugin-sass: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/plugin-uglifyjs: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/redux: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/redux-h5: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/router: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/taro: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/taro-alipay: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/taro-h5: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/taro-swan: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/taro-tt: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/taro-weapp: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/webpack-runner: 1.3.0-beta.5 => 1.3.0-beta.5
      eslint-config-taro: 1.3.0-beta.5 => 1.3.0-beta.5
      eslint-plugin-taro: 1.3.0-beta.5 => 1.3.0-beta.5
      nervjs: ^1.4.0-beta.3 => 1.4.0-beta.4
    npmGlobalPackages:
      typescript: 3.2.2

**补充信息**

**Comment by clearloop** [comment]
same problem

**Comment by jimczj** [comment]
发现 Taro.chooseImage 设置 count 参数无效，需要等待 Taro 修复

**Comment by iooops** [comment]
这个过这么久了有进展么 到现在还是这样

**Comment by jackvvv** [comment]
都2023年了，这么明显的bug还不修复吗？
