### ISSUE TITLE
taro UI 2.1.0预览H5编译警告

### ISSUE THREAD

**Issue by jyjey** [NervJS/taro-ui#606]
监听文件修改中...

⚠️  Compiled with warnings.

./node_modules/@tarojs/taro-h5/src/taro/index.js 26:13-22
" 'nervjs' does not contain an export named 'createRef'.

./node_modules/@tarojs/taro-h5/src/taro/index.js 32:15-26
" 'nervjs' does not contain an export named 'useCallback'.

./node_modules/@tarojs/taro-h5/src/taro/index.js 27:13-22
" 'nervjs' does not contain an export named 'useEffect'.

./node_modules/@tarojs/taro-h5/src/taro/index.js 28:19-34
" 'nervjs' does not contain an export named 'useLayoutEffect'.

./node_modules/@tarojs/taro-h5/src/taro/index.js 33:11-18
" 'nervjs' does not contain an export named 'useMemo'.

./node_modules/@tarojs/taro-h5/src/taro/index.js 29:14-24
" 'nervjs' does not contain an export named 'useReducer'.

./node_modules/@tarojs/taro-h5/src/taro/index.js 31:10-16
" 'nervjs' does not contain an export named 'useRef'.

./node_modules/@tarojs/taro-h5/src/taro/index.js 30:12-20
" 'nervjs' does not contain an export named 'useState'.

👽 Taro v1.3.0-beta.5

  Taro CLI 1.3.0-beta.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3 - D:\workTool\nodejs\node.EXE
      Yarn: 1.13.0 - C:\Users\ACE\AppData\Roaming\npm\yarn.CMD
      npm: 6.9.0 - C:\Users\ACE\AppData\Roaming\npm\npm.CMD

         "dependencies": {
		"@tarojs/components": "1.3.0-beta.5",
		"@tarojs/mobx": "1.3.0-beta.5",
		"@tarojs/mobx-h5": "1.3.0-beta.5",
		"@tarojs/mobx-rn": "1.3.0-beta.5",
		"@tarojs/router": "1.3.0-beta.5",
		"@tarojs/taro": "1.3.0-beta.5",
		"@tarojs/taro-alipay": "1.3.0-beta.5",
		"@tarojs/taro-h5": "1.3.0-beta.5",
		"@tarojs/taro-swan": "1.3.0-beta.5",
		"@tarojs/taro-weapp": "1.3.0-beta.5",
		"ali-oss": "^6.1.0",
		"urlsafe-base64": "^1.0.0",
		"decimal.js": "^10.0.1",
		"mobx": "^5.5.2",
		"nerv-devtools": "^1.3.9",
		"nervjs": "^1.3.9",
		"taro-ui": "^2.1.0"
	},
	"devDependencies": {
		"@tarojs/plugin-babel": "1.3.0-beta.5",
		"@tarojs/plugin-csso": "1.3.0-beta.5",
		"@tarojs/plugin-sass": "1.3.0-beta.5",
		"@tarojs/plugin-uglifyjs": "1.3.0-beta.5",
		"@tarojs/webpack-runner": "1.3.0-beta.5",
		"@types/react": "^16.4.6",
		"@types/webpack-env": "^1.13.6",
		"babel-eslint": "^8.2.3",
		"babel-plugin-transform-class-properties": "^6.24.1",
		"babel-plugin-transform-decorators-legacy": "^1.3.4",
		"babel-plugin-transform-jsx-stylesheet": "^0.6.5",
		"babel-plugin-transform-object-rest-spread": "^6.26.0",
		"babel-preset-env": "^1.6.1",
		"eslint": "^4.19.1",
		"eslint-config-taro": "1.3.0-beta.5",
		"eslint-plugin-import": "^2.12.0",
		"eslint-plugin-react": "^7.8.2",
		"eslint-plugin-taro": "1.3.0-beta.5",
		"eslint-plugin-typescript": "^0.12.0",
		"typescript": "^3.0.1"
	}

**Comment by jyjey** [comment]
有人帮忙看一下吗？虽然能用但是感觉很不好

**Comment by jimczj** [comment]
升级到最新版 Taro 吧，最新版没有 warning，此 issue 忽略
