### ISSUE TITLE
全局引入taro-ui，查看编译文件在index.wxss文件中有css，但是在页面上没有css

### ISSUE THREAD

**Issue by JasonJie** [NervJS/taro-ui#607]
全局引入taro-ui，查看编译文件在index.wxss文件中有css，但是在页面上没有css

**Comment by jimczj** [comment]
如果使用按需引用，需要自行引入 scss
![image](https://user-images.githubusercontent.com/13499146/59335617-85d7c300-8d2f-11e9-98f3-d2da73128ff1.png)

**Comment by zhang14725804** [comment]
更新版本之后按需引入样式消失
![image](https://user-images.githubusercontent.com/15354910/60730922-cdd9b680-9f78-11e9-9047-c5bcc9267703.png)
