### ISSUE TITLE
1.3.0 beta5中使用AtSwipeAction 运行时报错

### ISSUE THREAD

**Issue by flashermaster** [NervJS/taro-ui#611]
**问题描述**
原先使用1.2.24编译通过的小程序，在升级taro到1.3.0beta5后，编译通过，但是运行时报错，报错的是AtSwipeAction组件，而且在首页并没有使用到该组件就报错了。

**复现步骤**
在页面引入AtSwipeAction
import { AtSwipeAction } from "taro-ui"
然后调用。
运行时报错。

**期望行为**
展现首页

**报错信息**
TypeError: (0 , _index.genCompid) is not a function
    at AtSwipeAction._createData (index.js:294)
    at Object.createComponent (index.js:3571)
    at index.js:344
    at require (WAService.js:1)
    at <anonymous>:473:7
    at HTMLScriptElement.scriptLoaded (appservice?t=1559137600763:8523)
    at HTMLScriptElement.script.onload (appservice?t=1559137600763:8535)

**系统信息**
👽 Taro v1.3.0-beta.5

  Taro CLI 1.3.0-beta.5 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v8.11.3/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.2.26 => 1.2.26 
      @tarojs/components: ^1.1.4 => 1.2.26 
      @tarojs/plugin-babel: ^1.2.4 => 1.2.26 
      @tarojs/plugin-csso: 1.1.4 => 1.1.4 
      @tarojs/plugin-sass: 1.1.4 => 1.1.4 
      @tarojs/plugin-uglifyjs: 1.1.4 => 1.1.4 
      @tarojs/router: ^1.1.4 => 1.2.26 
      @tarojs/taro: 1.1.4 => 1.1.4 
      @tarojs/taro-h5: 1.1.4 => 1.1.4 
      @tarojs/taro-weapp: ^1.2.4 => 1.2.26 
      @tarojs/webpack-runner: 1.1.4 => 1.1.4 
      eslint-config-taro: 1.1.4 => 1.1.4 
      eslint-plugin-taro: 1.1.4 => 1.1.4 

 - Taro UI 版本 [2.1.0]
 - 报错平台 [weapp]

**Comment by dinggaihua** [comment]
+1

**Comment by WangxinsHub** [comment]
+1

**Comment by wwwwei0** [comment]
1.3升级了很多东西导致与1.2很多不兼容，详情可见 [这里](https://www.oschina.net/news/107436/taro-1-3-released)
另外开发小组正在忙618年中大庆[re](https://github.com/NervJS/taro-ui/issues/592#issuecomment-496052066
)
