### ISSUE TITLE
AtRate 更新trao 后不显示

### ISSUE THREAD

**Issue by ziermu** [NervJS/taro-ui#614]
import {AtIcon,AtRate,AtToast} from 'taro-ui'

export default class GoodsInfo extends Component {
  config= {
    navigationBarTitleText: '商品详情',
  }
  constructor (props) {
    super(props)
    this.state = {
    }
  }
  componentDidMount () {
  }
  render () {
    return (
      <View className='goodsInfo'>
         <View className='storeInfo'><AtRate value={4} /><View>店铺评分</View></View>
      </View>
    )
  }
}

Taro 版本：Taro v1.3.0-beta.5
Taro-UI版本：2.1.0

rato 代码
import Taro from '@tarojs/taro-h5';
import Nerv from "nervjs";
import { View, Text } from '@tarojs/components';
import PropTypes from 'prop-types';
import classNames from 'classnames';
import AtComponent from "../../common/component";

export default class AtRate extends AtComponent {
  constructor() {
    super(...arguments);
    if (process.env.NODE_ENV === 'test') {
      Taro.initPxTransform({ designWidth: 750 });
    }
  }

  handleClick() {
    this.props.onChange(...arguments);
  }

  render() {
    const {
      customStyle,
      className,
      value,
      max,
      size,
      margin
    } = this.props;

    const iconStyle = {
      marginRight: Taro.pxTransform(margin)
    };
    const starIconStyle = {
      fontSize: size ? `${size}px` : ''

      // 生成星星颜色 className 数组，方便在jsx中直接map
    };const classNameArr = [];
    const floorValue = Math.floor(value);
    const ceilValue = Math.ceil(value);
    for (let i = 0; i < max; i++) {
      if (floorValue > i) {
        classNameArr.push('at-rate__icon at-rate__icon--on');
      } else if (ceilValue - 1 === i) {
        classNameArr.push('at-rate__icon at-rate__icon--half');
      } else {
        classNameArr.push('at-rate__icon at-rate__icon--off');
      }
    }

    return <View className={classNames('at-rate', className)} style={customStyle}>
        {classNameArr.map((cls, i) => <View className={cls} key={i} style={iconStyle} onClick={this.handleClick.bind(this, i + 1)}>
            <Text className="at-icon at-icon-star-2" style={starIconStyle}></Text>
            <View className="at-rate__left">
              <Text className="at-icon at-icon-star-2" style={starIconStyle}></Text>
            </View>
          </View>)}
      </View>;
  }
}

AtRate.defaultProps = {
  isTest: false,
  customStyle: '',
  className: '',
  size: 0,
  value: 0,
  max: 5,
  margin: 5,
  onChange: () => {}
};

AtRate.propTypes = {
  customStyle: PropTypes.oneOfType([PropTypes.object, PropTypes.string]),
  className: PropTypes.oneOfType([PropTypes.array, PropTypes.string]),
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  value: PropTypes.number,
  max: PropTypes.number,
  margin: PropTypes.number,
  onChange: PropTypes.func
};

**Comment by ziermu** [comment]
![微信图片_20190531143551](https://user-images.githubusercontent.com/46949224/58686485-85474000-83b1-11e9-9b4b-446da9cb30b5.png)
![1559284622(1)](https://user-images.githubusercontent.com/46949224/58686524-97c17980-83b1-11e9-856e-0a0dd0de493f.png)

**Comment by karchinkong** [comment]
解决了吗 我也是这样

**Comment by jimczj** [comment]
如果是使用了按需引用，需要引入 AtIcon,AtRate 这两个的样式

**Comment by jimczj** [comment]
![image](https://user-images.githubusercontent.com/13499146/59332019-e8c55c00-8d27-11e9-9bb9-e9d9c661934e.png)

**Comment by ziermu** [comment]
将所有项目都重新安装一遍，都更到最新，最好用淘宝镜像安装



------------------ 原始邮件 ------------------
发件人: "KARCHINKONG"; 
发送时间: 2019年6月10日(星期一) 中午11:46
收件人: "NervJS/taro-ui";
抄送: "ziermu"<3263238184@qq.com>;"Author";
主题: Re: [NervJS/taro-ui] AtRate 更新trao 后不显示 (#614)




解决了吗 我也是这样
 
&mdash;

**Comment by jrackTao** [comment]
taro update project

升级至 1.3.4 ，解决

**Comment by zhang14725804** [comment]
升级到1.3.5之后，按需引入组件样式又消失了

**Comment by zhang14725804** [comment]
![image](https://user-images.githubusercontent.com/15354910/60730887-bd294080-9f78-11e9-8389-118f12d5ac29.png)
更新版本之后按需引入样式消失

**Comment by KirySen** [comment]
我是放在View里面会出错  放在最外层就显示正常
`<View className={styles.right}>
              <Text>老师评分</Text>
              <AtRate value={data.courseEvaluation.star} size={13}/>
            </View>`
