### ISSUE TITLE
Nerv和 Taro 是什么关系，是否可以编译IE8支持！

### ISSUE THREAD

**Issue by appbest** [NervJS/taro-ui#617]
**这个功能解决了什么问题？**

Nerv 的案例与文档太少了，是否可与Taro合并，编译支持IE8的PC网页版本。

**你期望的功能是怎样的？**

PC版本网站应用兼容

**补充信息**

**Comment by jimczj** [comment]
该问题与本仓库无关，可以去 Taro 咨询
