### ISSUE TITLE
AtImagePicker onImageClick事件不响应的问题

### ISSUE THREAD

**Issue by stephen7729** [NervJS/taro-ui#621]
### Taro UI 版本信息

2.1.0

### 问题描述

AtImagePicker  使用 onImageClick事件，事件不响应，且无报错信息

### 复现步骤

1、增加onImageClick配置事件打断点
2、点击控件增加图片
3、不进断点

### 复现代码

<AtImagePicker
              multiple
              count={9}
              length={3}
              files={this.state.form.files}
              onImageClick={this.onImageClick.bind(this)}
            />

### 报错信息

 无

### 系统信息

无

**Comment by jimczj** [comment]
onImageClick 是点击已添加的图片的回调事件，不是增加图片控件事件回调，增加图片监听 onChange 就好了
