### ISSUE TITLE
taro-ui的AtMessage组件失效

### ISSUE THREAD

**Issue by StephenOo** [NervJS/taro-ui#623]
windows 10
taro 1.2.26
taro-ui 2.1.0

完全按照官方文档的demo，taro-ui的AtMessage并不生效

**Comment by BensonEu** [comment]
我也遇到同样的问题，H5

**Comment by StephenOo** [comment]
> 我也遇到同样的问题，H5

我这边是小程序，完全按照官方文档的demo来的，但是效果没有

**Comment by wangyijun03** [comment]
仔细检查一下，也许漏掉了atmessage标签没有写
