### ISSUE TITLE
AtInput h5中使用输入报错

### ISSUE THREAD

**Issue by giantss** [NervJS/taro-ui#626]
### Taro UI 版本信息

2.1.0

### 问题描述

只要一输入就报错：  Uncaught DOMException: Failed to set the 'selectionStart' property on 'HTMLInputElement': The input element's type ('number') does not support selection.

### 复现步骤

非常容易浮现

### 复现代码

 <View className='at-row at-row__direction--column at-row__align--center'>
       <AtInput
         type='phone'
         border={false}
         placeholder='请输入手机号码'
         onChange={this.inputChange}
       />
      </View>

### 报错信息

Uncaught DOMException: Failed to set the 'selectionStart' property on 'HTMLInputElement': The input element's type ('number') does not support selection.

### 系统信息

Taro CLI 1.3.0-beta.6 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.10.0 - /usr/local/bin/node
      Yarn: yarn install v0.24.5

**Comment by jimczj** [comment]
麻烦升级一下 Taro 到最新版本

**Comment by jimczj** [comment]
@giantss 升级版本后有没有解决问题

**Comment by jimczj** [comment]
该问题是 Taro 基础库问题，之前修复过，麻烦升级下 Taro
