### ISSUE TITLE
AtRate value设置后无法展示相对应的评分星星数

### ISSUE THREAD

**Issue by karchinkong** [NervJS/taro-ui#627]
**问题描述**
使用AtRate组件无法显示对应组件的内容 星星无法展示

**复现步骤**
<AtRate
  value={3}
 ></AtRate>
页面出现如下图
![image](https://user-images.githubusercontent.com/16110331/59171105-0d78d280-8b74-11e9-88ee-eff2e4181406.png)

**期望行为**
能像demo一样展示组件内容
![image](https://user-images.githubusercontent.com/16110331/59171006-96433e80-8b73-11e9-880a-cfe9ddf3ce14.png)

**报错信息**
无报错信息

**系统信息**
 - 操作系统 : os系统 10.14.1
 - 微信开发者工具基础库 : 2.7.1
 - Taro 版本 : "1.3.0-beta.4"
 - Taro UI 版本  :  "^2.1.0"
 - 报错平台  : weapp

**Comment by jrackTao** [comment]
怎么解决的

**Comment by jrackTao** [comment]
升级至 1.3.4 ，解决
