### ISSUE TITLE
表情组件

### ISSUE THREAD

**Issue by haoyinag** [NervJS/taro-ui#630]
### 这个功能解决了什么问题？

集成表情，发现写个表情好困难哦，或者把攻略分享出来也行鸭

### 你期望的功能是怎样的？

能不能出个组件，就像你们扫码体验的那个button组件进去之后的taro客服那个聊天，能不能把这个新增为组件！？

**Comment by jimczj** [comment]
这种组件一般不会集成到 UI 组件库哦，有需要可以自己实现一遍然后开源

**Comment by haoyinag** [comment]
@jimczj 就是不知道怎么实现啊

**Comment by haoyinag** [comment]
@jimczj 还有我发现你们那个客服聊天的表情居然是跟微信聊天的同步的，想问下是怎么实现的
