### ISSUE TITLE
Calender组件 小程序环境打包报错

### ISSUE THREAD

**Issue by zhangzhenfei** [NervJS/taro-ui#631]
Taro UI 版本信息
2.1.0

问题描述
Calender组件 小程序环境运行报错

复现步骤
![image](https://user-images.githubusercontent.com/6110215/59274670-65572c80-8c8d-11e9-9212-e523d42bbe84.png)

系统信息
Taro CLI 1.3.0-beta.8 environment info:
System:
OS: macOS 10.14.1
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 10.10.0 - /usr/local/bin/node
Yarn: yarn install v0.24.5

补充信息

**Comment by koppthe** [comment]
升级到 v2.2.0 试试？
