### ISSUE TITLE
AtSearchBar组件输入中文时不会触发onChange事件

### ISSUE THREAD

**Issue by gatinul** [NervJS/taro-ui#632]
**问题描述**
AtSearchBar组件输入中文时不会触发onChange事件
**复现步骤**
```js

onSearch (value) {
    console.log(value)
    this.setState({
      value: value ? value.trim(): ''
    })
  }
             <AtSearchBar
                value={this.state.value}
                onChange={this.onSearch.bind(this)}
                onActionClick={this.onActionClick.bind(this)}
              />
```

**期望行为**
期望输入中文 可以触发onChange
**报错信息**

**系统信息**

 Taro CLI 1.3.0-beta.6 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.10.0 - /usr/local/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 2.5.3
 - 报错平台 [h5]

**Comment by jimczj** [comment]
版本信息是什么，我这边使用 Taro 1.3.0，Taro UI 2.2.0，正常可输入，安卓手机
