### ISSUE TITLE
imagePicker这个警告处理下

### ISSUE THREAD

**Issue by brucecodezone** [NervJS/taro-ui#635]
**问题描述**

编译时imagePicker出现警告
**复现步骤**

```js
编译  组件文件  node_modules/taro-ui/dist/weapp/components/image-picker/index.js
建议修改：使用循环的 index 变量作为 key 是一种反优化。参考：https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-array-index-key.md
-----
  82 |     return <View className={rootCls} style={customStyle}>
  83 |       {matrix.map((row, i) => (
> 84 |         <View className='at-image-picker__flex-box' key={i}>
     |                                                         ^
  85 |           {row.map((item, j) => (
  86 |             item.url
  87 |               ? <View className='at-image-picker__flex-item' key={(i * length) + j}>
编译  组件文件  node_modules/taro-ui/dist/index.js
```

**期望行为**

没有警告信息
**报错信息**

**系统信息**

**补充信息**

**Comment by lyf103104** [comment]
编译  组件文件  node_modules/taro-ui/dist/weapp/components/timeline/index.js
建议修改：使用循环的 index 变量作为 key 是一种反优化。参考：https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-array-index-key.md
-----
  40 |
  41 |       return (
> 42 |         <View className={classNames(itemRootClassName)} key={index}>
     |                                                             ^^^^^
  43 |           <View className='at-timeline-item__tail'></View>
  44 |           <View className={classNames(dotClass)}>
  45 |             {icon && <Text className={iconClass}></Text>}


===============================================================


编译  组件文件  node_modules/taro-ui/dist/weapp/components/pagination/index.js

ESLint(taro/duplicate-name-of-state-and-props) 错误：this.state.current 与 this.props.current重复可能会导致渲染结不如意料之中的结果。
-----
  23 |     const maxPage = getMaxPage(Math.ceil(total / pageSize))
  24 |     this.state = {
> 25 |       current,
     |       ^^^^^^^
  26 |       maxPage,
  27 |       pickerRange: createPickerRange(maxPage),
  28 |     }


===============================================================
"taro-ui": "^2.2.0"
Taro v1.3.0
===============================================================
希望处理一下。

**Comment by zhangchenna** [comment]
我也遇到这情况修改本地配置不起作用
