### ISSUE TITLE
请问大佬Taro-ui的Noticebar 通告栏计划支持修改字体颜色和背景色吗？谢谢！

### ISSUE THREAD

**Issue by zhou1992zg** [NervJS/taro-ui#64]

**Comment by zhou1992zg** [comment]
貌似现在ui有跟新自定义样式，不知道能不能实现啊？

**Comment by cos2004** [comment]
用.at-noticebar类名在你的页面样式做样式覆盖就好（小程序基础库>=2.2.3）

**Comment by zhou1992zg** [comment]
现在我想修改Taro UI 的AtTabBar里的默认行高
原因是因为AtTabBar编译后在H5端样式和小程序端显示不一样
这是H5端
![2018-09-19 9 10 18](https://user-images.githubusercontent.com/29066081/45725131-e0eae800-bbeb-11e8-88e6-ac8e3b1961a9.png)
这是小程序端
![2018-09-19 9 59 40](https://user-images.githubusercontent.com/29066081/45726655-c5371000-bbf2-11e8-92bc-52d3d5c63c54.png)
找到相关的class  为 at-tab-bar__icon 
在index.scss文件中加入
`.at-tab-bar__icon {
    line-height: 10PX;
}`
样式有改变！
但是您说的.at-noticebar类名方法是这样吗？

**Comment by zhou1992zg** [comment]
@cos2004

**Comment by jimczj** [comment]
@zhou1992zg 你提问的了两个问题，对应不同都组件，所以你现在都问题是？

**Comment by jimczj** [comment]
@zhou1992zg  为什么要用 . at-noticebar 去改  AtTabBar 的样式。。。 审查下 AtTabBar 对应的类名，进行覆盖就行

**Comment by zhou1992zg** [comment]
好吧！

**Comment by zhou1992zg** [comment]
但是有一个问题 在组件当前的scss怎么也修改不了AtTabBar的样式，
要去引用组件的页面的scss中才能修改，

**Comment by zhou1992zg** [comment]
但是有一个问题 在组件当前的scss怎么也修改不了AtTabBar的样式，
要去引用组件的页面的scss中才能修改，
比如：我这次就只能去index.scss中修改
