### ISSUE TITLE
taro升级1.3版本后,组件AtButton设置open-type='getUserInfo'时，无法成功调取用户授权页面

### ISSUE THREAD

**Issue by luuwang** [NervJS/taro-ui#640]
**问题描述**

**复现步骤**

<AtButton type='primary' open-type='getUserInfo' onGetUserInfo={this.handleGetuserInfo}>授权</AtButton>

handleGetuserInfo = (e) => {
    console.log(e)
}

```js
// 这里可以贴代码
```

**期望行为**

修复该问题

**报错信息**

点击按钮没有反应，也没有报错信息。

**系统信息**

Taro ui 版本 2.2.0

Taro CLI 1.3.0 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.16.0 - ~/.nvm/versions/node/v10.16.0/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm

**补充信息**

**Comment by jimczj** [comment]
麻烦升级到 Taro 1.3.6 版本
