### ISSUE TITLE
List extraText值为0时的显示问题

### ISSUE THREAD

**Issue by xiafengaha** [NervJS/taro-ui#641]
**问题描述**
List列表组件中，extraText值为Number 0时，显示会有异常。
**复现步骤**

```js
// 这里可以贴代码
let num = 0;
<AtList hasBorder={false}>
 <AtListItem extraText={num}></AtListItem>
</AtList>
```

**期望行为**
看了源代码，发现extraText的判断为extraText要么就没有，有就必须为string类型的。
而0的话在js里面可以是布尔类型的。所以当用户传值进入组件时，是否可以统一处理，转化成组件需要的类型。

**报错信息**

**系统信息**

**补充信息**

**Comment by koppthe** [comment]
extraText 参数传值应该是 String 类型，但是由组件再做一层处理也不是不行，可以考虑加一下
