### ISSUE TITLE
Noticebar跑马灯组件安卓9没问题，安卓8.0的系统会显示不全

### ISSUE THREAD

**Issue by wuweijian1997** [NervJS/taro-ui#643]
**问题描述**
Noticebar跑马灯组件在安卓8.0的手机上滚动一半就会闪烁消失重新跑，安卓9的手机上没有问题，微信开发者工具也可以正常滚动。

**复现步骤**
8.0的手机，跑马灯组件

```js
     <AtNoticebar single marquee>
           嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻 嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻嘻
          </AtNoticebar>
```

**期望行为**
期望正常滚动

**报错信息**

**系统信息**
👽 Taro v1.2.26

  Taro CLI 1.2.26 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3 - D:\APP\NODEJS\node.EXE
      Yarn: 1.15.2 - D:\APP\YARN\bin\yarn.CMD
      npm: 6.4.1 - D:\APP\NODEJS\npm.CMD

**补充信息**
可能是安卓系统版本原因，试过好几个8.几的安卓手机，都是滚动个开头-》闪烁-》重新开始。
我的9.0系统可以正常滚动

**Comment by koppthe** [comment]
是指在微信小程序中有问题吗？

**Comment by wuweijian1997** [comment]
> 是指在微信小程序中有问题吗？

是的，是在微信小程序，好像不是操作系统的原因。我的小米9可以，别人的荣耀好像不行，操作系统都是9.0

**Comment by wuweijian1997** [comment]
![7e0c98362026ea3be8279987e79ee2fd](https://user-images.githubusercontent.com/29529286/59811554-00f73580-933d-11e9-8e98-923c87bcafcf.gif)
三星s7效果如上，后面还有很多，也没触发生命周期函数，

**Comment by koppthe** [comment]
明白了，谢谢反馈哈，近期会修复这个问题

**Comment by wuweijian1997** [comment]
> 明白了，谢谢反馈哈，近期会修复这个问题

你好，这个bug修复了吗？

**Comment by yang302** [comment]
ios 13系统也会有问题，第一次进入组件滚动很慢，数据越长，滚动越慢，返回再次进入就正常了
