### ISSUE TITLE
用Taro写h5的时候，AtInput遇到的相关问题

### ISSUE THREAD

**Issue by linkjd** [NervJS/taro-ui#65]
一、在输入拼音的键盘下，此时我输入第二个r的时候，出现了r r
比如，输入第一个r，input显示r，再输入第二个r时，input显示rr r
![wechatimg29](https://user-images.githubusercontent.com/12538981/45609783-ee895c00-ba8b-11e8-908b-307288af33a1.jpeg)
二、当type不是‘text’的时候，maxlength无法限制长度

**Comment by jimczj** [comment]
> 当 type 不是‘text’的时候，maxlength 无法限制长度
这个已经反馈基础组件同学修复问题

输入 r 时出现rr的问题，目前无法复现，手机型号跟输入法提供下

**Comment by linkjd** [comment]
手机型号就是iOS系统的手机，输入法就如上图的输入法（用真机测试时出现）

**Comment by jimczj** [comment]
@linkjd 好的，已复现问题，这些是 h5 基础库的问题，已联系相关同学修复

**Comment by gmDreamer** [comment]
H5版本，AtInput  onChange  事件中，输入中文在中间插入中文文字，每次修改会导致光标都跳动到文本的最后，切换中文输入法，字体拼音也会输入到文本框，目前发现H5版 AtInput  onchange事件在IOS问题太多，体验非常差。希望大神尽快修改

**Comment by jimczj** [comment]
基础库问题，升级到最新版 Taro 可解决
