### ISSUE TITLE
taro打包时无法把taro-ui的组件打包进去

### ISSUE THREAD

**Issue by zhangyu1818** [NervJS/taro-ui#655]
**问题描述**
taro打包时taro ui的组件总是无法打包

**期望行为**
正常打包

![报错截图](https://s2.ax1x.com/2019/06/24/Zkc89e.jpg)

**系统信息**

  Taro CLI 1.3.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.10.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

   Taro-ui: 2.2.0

**补充信息**
其他的组件也有概率打包不了，打包时无报错，只有taro ui里没有解构props的警告

**Comment by koppthe** [comment]
在项目根目录下执行 `taro info` 看看详细的版本信息

**Comment by zhangyu1818** [comment]
> 在项目根目录下执行 `taro info` 看看详细的版本信息

```
D:\zxapp>taro info
� Taro v1.3.1


  Taro CLI 1.3.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.10.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

```

**Comment by koppthe** [comment]
信息没有这么少的，麻烦升级 taro 相关的依赖，然后全局的 cli 版本跟项目的版本保持一致
