### ISSUE TITLE
 taro-ui 中 SearchBar 这个组件使用不了

### ISSUE THREAD

**Issue by YouMaster930615** [NervJS/taro-ui#660]
**问题描述**

按照官网的步骤将 SearchBar 引入之后 ，终端一直提示缺少~taro-ui/dist/style/components/search-bar.scss  这个包 然后就不断提示下载，知道崩溃

**复现步骤**

1. 下载 taro-ui  使用 cnpm install taro-ui --save
2. 页面引入 
        1）   import { AtSearchBar } from 'taro-ui'
        2）  @import "~taro-ui/dist/style/components/search-bar.scss";
                @import "~taro-ui/dist/style/components/button.scss";
                @import "~taro-ui/dist/style/components/icon.scss";
        3）  <AtSearchBar
                    value={this.state.value}
                    onChange={this.onChange.bind(this)}
                />

**期望行为**

帮忙查看一下问题出现在哪里
**报错信息**

**系统信息**

taro-ui 版本号为: v1.3.0-beta.3

**补充信息**

**Comment by koppthe** [comment]
重新安装一下 `taro-ui` 到最新版本，taro 版本也更新一下。

**Comment by YouMaster930615** [comment]
@import "~taro-ui/dist/style/components/search-bar.scss";
@import "~taro-ui/dist/style/components/button.scss";
@import "~taro-ui/dist/style/components/icon.scss";

这段代码只要一放上去  终端就回继续提示 缺少...包 更新中  然后就是终端崩溃

**Comment by koppthe** [comment]
你是在哪个文件里面引入的？

**Comment by YouMaster930615** [comment]
我有一个 test.tsx 文件 然后这里引入的

**Comment by koppthe** [comment]
🙂文档仔细阅读一下~
如果你要在 JS 里面引入 SCSS 文件的话，得换一种写法：
```
import "taro-ui/dist/style/components/search-bar.scss"
```
