### ISSUE TITLE
AtTabBar内调用AtBadge，提示类型错误

### ISSUE THREAD

**Issue by aoxiang78** [NervJS/taro-ui#671]
使用以下代码：提示错误类型
`<AtTabBar
          fixed
          tabList={[
            {title: '自定义图标', iconPrefixClass: 'fa-icon', iconType: 'a'},
            {title: '拍照', iconType: 'camera'},
            {title: '文件夹', iconType: 'folder', text: '100', max: 99}
          ]}
          onClick={this.handleClick.bind(this)}
          current={this.state.current}
        />`
信息信息
`Failed prop type: Invalid prop `maxValue` of type `string` supplied to `AtBadge`, expected `number`.`

查看代码后发现，AtTabBar在调用AtBadge时传入一个空字符，引发的。
`maxValue={(item.iconType || item.image) ? '' : item.max}`

**Comment by wvit** [comment]
我也遇到这个问题了  改为maxValue={(item.iconType || item.image) ? 99 : item.max} 即可解决

**Comment by divasatanica** [comment]
看起来 pr 已经合并了，是还没发布这个更改吗，2.2.1 版本的代码传的仍然是空字符串。
