### ISSUE TITLE
在window环境下安装taro-ui出错

### ISSUE THREAD

**Issue by alesjia** [NervJS/taro-ui#675]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\_chokidar@2.1.6@chokidar\node_modules\fsevents):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\TaroProjects\myApp\node_modules\.staging\fsevents-d24f547d\node_modules\abbrev' -> 'E:\TaroProjects\myApp\node_modules\.staging\abbrev-83bac562'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\_chokidar@2.1.6@chokidar\node_modules\fsevents):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\TaroProjects\myApp\node_modules\.staging\fsevents-d24f547d\node_modules\abbrev' -> 'E:\TaroProjects\myApp\node_modules\.staging\abbrev-83bac562'

npm ERR! path E:\TaroProjects\myApp\node_modules\string-width\node_modules\emoji-regex
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'E:\TaroProjects\myApp\node_modules\string-width\node_modules\emoji-regex' -> 'E:\TaroProjects\myApp\node_modules\string-width\node_modules\emoji-regex'
npm ERR! enoent This is related to npm not being able to find a file.

package.json

{
  "name": "myApp",
  "version": "1.0.0",
  "private": true,
  "description": "first",
  "templateInfo": {
    "name": "default",
    "typescript": false,
    "css": "sass"
  },
  "scripts": {
    "build:weapp": "taro build --type weapp",
    "build:swan": "taro build --type swan",
    "build:alipay": "taro build --type alipay",
    "build:tt": "taro build --type tt",
    "build:h5": "taro build --type h5",
    "build:rn": "taro build --type rn",
    "dev:weapp": "npm run build:weapp -- --watch",
    "dev:swan": "npm run build:swan -- --watch",
    "dev:alipay": "npm run build:alipay -- --watch",
    "dev:tt": "npm run build:tt -- --watch",
    "dev:h5": "npm run build:h5 -- --watch",
    "dev:rn": "npm run build:rn -- --watch"
  },
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@tarojs/components": "1.3.4",
    "@tarojs/router": "1.3.4",
    "@tarojs/taro": "1.3.4",
    "@tarojs/taro-alipay": "1.3.4",
    "@tarojs/taro-h5": "1.3.4",
    "@tarojs/taro-swan": "1.3.4",
    "@tarojs/taro-tt": "1.3.4",
    "@tarojs/taro-weapp": "1.3.4",
    "nervjs": "^1.4.0",
    "nerv-devtools": "^1.4.0"
  },
  "devDependencies": {
    "@types/react": "^16.4.6",
    "@types/webpack-env": "^1.13.6",
    "@tarojs/plugin-babel": "1.3.4",
    "@tarojs/plugin-csso": "1.3.4",
    "@tarojs/plugin-sass": "1.3.4",
    "@tarojs/plugin-uglifyjs": "1.3.4",
    "@tarojs/webpack-runner": "1.3.4",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-jsx-stylesheet": "^0.6.5",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-eslint": "^8.2.3",
    "eslint": "^5.16.0",
    "eslint-config-taro": "1.3.4",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-import": "^2.12.0",
    "stylelint": "9.3.0",
    "stylelint-config-taro-rn": "1.3.4",
    "stylelint-taro-rn": "1.3.4",
    "eslint-plugin-taro": "1.3.4"
  }
}

**Comment by jimczj** [comment]
建议使用 cnpm，或 yarn 安装，科学上网
