### ISSUE TITLE
组件在重新render的时候报错了

### ISSUE THREAD

**Issue by canfoo** [NervJS/taro-ui#679]
**问题描述**
通过taro init 初始化一个项目，并在页面内引入taro-ui的 AtIcon 组件，当改变state或者props时候重新render当前页面时候，控制台就会报错：“TypeError: Cannot read property 'extraProps' of undefined”。

**复现步骤**
js 代码
```
class Index extends Component {
  config = {
    navigationBarTitleText: '首页'
  }
  constructor(props) {
    super(props)
    this.state = {
      num: 1
    }
  }
  add() {
    this.setState({
      num: this.state.num + 1
    })
  }
  render () {
    return (
      <View className='index'>
        <Button className='add_btn' onClick={this.add}>+</Button>
        <View><Text>{this.state.num} </Text></View>
        <AtIcon value='chevron-right' size='50' color='#000'></AtIcon>
      </View>
    )
  }
}
```

**期望行为**
点击+ 页面正常加1

**报错信息**
点击 + 报错 “Cannot read property 'extraProps' of undefined;at api nextTick callback function
TypeError: Cannot read property 'extraProps' of undefined”

![image](https://user-images.githubusercontent.com/16999086/60604149-a1436480-9de9-11e9-86e1-b1ded080332b.png)

**系统信息**
Taro CLI 1.3.3 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm

 - Taro 版本 [v.1.3.3]
 - Taro UI 版本 v.2.2.1]
 - 报错平台 [weapp]

**补充信息**
如果把上述js 代码中的 AtIcon 组件隐藏掉则页面就正常。经验证，只要引入任一taro-ui的组件，在重新render的时候都会发生以上报错信息。

**Comment by jimczj** [comment]
经测试在 Taro 1.3.3 版本有问题，升级到 1.3.6 无报错，麻烦升级下吧
