### ISSUE TITLE
建议 Avatar 组件的 size 属性支持直接设定大小

### ISSUE THREAD

**Issue by xPixv** [NervJS/taro-ui#686]
### 这个功能解决了什么问题？

更灵活地使用头像组件

### 你期望的功能是怎样的？

`<AtAvatar circle size='25px' text='凹凸实验室'></AtAvatar>`，可以直接在 size 属性中添加大小，而不仅仅局限于 large, normal, small。
曾经有人提出过自定义功能 #62，虽然可以通过覆盖样式实现，但是不够方便，不能开箱即用。
希望能支持设定大小

**Comment by jimczj** [comment]
考虑到可以使用 customStyle 自定义大小，此特性不纳入考虑

**Comment by xPixv** [comment]
好吧，提出这个特性是考虑到 antd 的 Avatar 是支持这一功能的：https://ant.design/components/avatar-cn/#API
taro ui 觉得没必要就不强求啦~
