### ISSUE TITLE
按钮分享

### ISSUE THREAD

**Issue by justLearner** [NervJS/taro-ui#688]
**这个功能解决了什么问题？**
分享无法动态传值：
当是 list 页面 分享 item 无法拿到 name 值。

**你期望的功能是怎样的？**
<AtButton openType='share' data-name='123'>分享商品</AtButton>
  onShareAppMessage(opt) {
    console.log(opt) //这里获取不到 name
  }
希望可以允许动态传值，当分享 list 页面的 item 的时候，可以动态的带一个 name。 

**补充信息**

**Comment by jimczj** [comment]
可以将数据挂载在state，或 this 对象中

**Comment by justLearner** [comment]
触发分享是 openType 这个属性，如果对 button 另外增加click事件是在 onShareAppMessage 执行过之后

**Comment by jimczj** [comment]
具体请详细查看微信小程序的文档，这里只是增加属性而已，你可以将需要的数据挂载在 state 中，在 onShareAppMessage 中使用。
https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/share.html#%E4%BD%BF%E7%94%A8%E6%8C%87%E5%BC%95
