### ISSUE TITLE
taro-ui 样式没有生效

### ISSUE THREAD

**Issue by chenerzhang** [NervJS/taro-ui#691]
**问题描述**

直接在 app.scss 中引入 @import "~taro-ui/dist/style/index.scss";
但是没有生效

**复现步骤**

```js
// 这里可以贴代码
import Taro, { Component } from '@tarojs/taro';
import { View, Text, Input } from '@tarojs/components';
import { AtTabs, AtTabsPane, AtButton } from 'taro-ui';
import './index.scss';

export default class Index extends Component {
  constructor(...args) {
    super(...args);
    this.state = {
      current: 0
    };
  }

  config = {
    navigationBarTitleText: '首页'
  }

  componentWillMount () { }

  componentDidMount () { }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  handleClick (value) {
    this.setState({
      current: value
    });
  }

  render () {
    return (
      <View className='index'>
        <AtButton>按钮</AtButton>
        <AtTabs
          current={this.state.current}
          scroll
          height='200px'
          tabDirection='vertical'
          tabList={[
            { title: '标签页1' },
            { title: '标签页2' },
            { title: '标签页3' },
            { title: '标签页4' },
            { title: '标签页5' },
            { title: '标签页6' },
          ]}
          onClick={this.handleClick.bind(this)}
        >
          <AtTabsPane tabDirection='vertical' current={this.state.current} index={0}>
            <View style='font-size:18px;text-align:center;height:200px;'>标签页一的内容</View>
          </AtTabsPane>
          <AtTabsPane tabDirection='vertical' current={this.state.current} index={1}>
            <View style='font-size:18px;text-align:center;height:200px;'>标签页二的内容</View>
          </AtTabsPane>
          <AtTabsPane tabDirection='vertical' current={this.state.current} index={2}>
            <View style='font-size:18px;text-align:center;height:200px;'>标签页三的内容</View>
          </AtTabsPane>
          <AtTabsPane tabDirection='vertical' current={this.state.current} index={3}>
            <View style='font-size:18px;text-align:center;height:200px;'>标签页四的内容</View>
          </AtTabsPane>
          <AtTabsPane tabDirection='vertical' current={this.state.current} index={4}>
            <View style='font-size:18px;text-align:center;height:200px;'>标签页五的内容</View>
          </AtTabsPane>
          <AtTabsPane tabDirection='vertical' current={this.state.current} index={5}>
            <View style='font-size:18px;text-align:center;height:200px;'>标签页六的内容</View>
          </AtTabsPane>
        </AtTabs>
      </View>
    );
  }
}

// app.scss 里引入了 @import "~taro-ui/dist/style/index.scss";
```

**期望行为**

样式可以正确显示

**报错信息**

样式没有正确显示

**系统信息**

Taro v1.3.6

  Taro CLI 1.3.6 environment info:
    System:
      OS: OS X El Capitan 10.11.6
      Shell: 5.0.8 - /bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.6 => 1.3.6
      @tarojs/components: 1.3.6 => 1.3.6
      @tarojs/plugin-babel: 1.3.6 => 1.3.6
      @tarojs/plugin-csso: 1.3.6 => 1.3.6
      @tarojs/plugin-sass: 1.3.6 => 1.3.6
      @tarojs/plugin-uglifyjs: 1.3.6 => 1.3.6
      @tarojs/router: 1.3.6 => 1.3.6
      @tarojs/taro-alipay: 1.3.6 => 1.3.6
      @tarojs/taro-swan: 1.3.6 => 1.3.6
      @tarojs/taro-tt: 1.3.6 => 1.3.6
      @tarojs/taro-weapp: 1.3.6 => 1.3.6
      @tarojs/webpack-runner: 1.3.6 => 1.3.6
      eslint-config-taro: 1.3.6 => 1.3.6
      eslint-plugin-taro: 1.3.6 => 1.3.6
      nerv-devtools: ^1.4.0 => 1.4.3
Taro-ui: 2.2.1
报错平台：微信小程序
微信开发者工具版本：1.02.1907052

**补充信息**

![image](https://user-images.githubusercontent.com/10590533/60902068-a305a000-a2a1-11e9-819a-691fba5d4367.png)

**Comment by JonChanGit** [comment]
我也碰到这个问题了，请问是怎么解决的

**Comment by JonChanGit** [comment]
原来要改这个 啊，官网看了半天没看到，看了半天的ISSUE才发现的
![image](https://user-images.githubusercontent.com/20020550/62386065-586a0180-b589-11e9-9b50-54525efbc242.png)

**Comment by koppthe** [comment]
官网的「快速上手」和「常见问题」都有说明哈

**Comment by FrankFan** [comment]
@koppthe   百度小程序也遇到了同样的问题，样式不生效。

但是文档里没有说明，百度小程序需要用的基础库版本是多少？ 

望回复，谢谢

**Comment by koppthe** [comment]
@FrankFan  百度小程序之前没有使用 Web Component 的规范，所以不需要设置基础库的操作。样式不生效的问题，我今天定位一下🤦‍♀️

**Comment by hutusi** [comment]
这个问题真是个坑，感谢 @JonChanGit 的解决办法。
