### ISSUE TITLE
AtCountdown组件，申请加一个只有分钟和秒数的模式

### ISSUE THREAD

**Issue by candyAndBella** [NervJS/taro-ui#693]
AtCountdown组件，现在有时分秒的模式，建议加一个只有分钟和秒数的模式。
如果只是5分钟或者30分钟倒计时，没必要显示小时呀。
就像去支付的时候，支付的按钮上有一个30分钟的倒计时，按钮宽度小的话，也显示不了时分秒这么长呀

**Comment by lsqy** [comment]
已添加isShowHour这个配置项，下次版本发布即可生效。

**Comment by lsqy** [comment]
新版本已发布，更新依赖即可，最新版本为`v2.2.1`

**Comment by candyAndBella** [comment]
感谢大神！！！！比心♥♥♥
