### ISSUE TITLE
tag动态点击更改激活状态异常

### ISSUE THREAD

**Issue by PlutoCA** [NervJS/taro-ui#694]
### Taro UI 版本信息

2.2.1

### 问题描述

active={this.state.active === tag} 想动态更新激活状态，但是点击无效，样式被改变成默认的样式（我的是circle 点击后 变成初始）

### 复现步骤

点击

### 复现代码

```
export default class SelectStrip extends PureComponent<Props, State> {
  constructor(...args: any) {
    super(...args);
    this.state = {
      active: '',
    };
    this.onClick = this.onClick.bind(this);
  }

  onClick = (item : any) => {
    console.log(item, this.state.active, this.props.tags);
    this.setState({
      active: item.name,
    });
  }

  render() {
    const { tags, title } = this.props;

    if (!Array.isArray(tags)) {
      return false;
    }
    return (
      <View className="select_strip--box">
        <Text className="title">{title || ''}</Text>
        {tags.map((tag, index) => (
          <View className="tag_box" key={arrayKey(index)}>
            <AtTag name={tag} type="primary" onClick={this.onClick} circle active={this.state.active === tag}>{tag}</AtTag>
          </View>
        ))}
      </View>
    );
  }
}
```

### 报错信息

无

### 系统信息

Taro v1.3.2
  Taro CLI 1.3.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.8.0 - C:\Program Files\nodejs\npm.CMD

### 补充信息

测试好像只有在map里面有问题，单独点击好像没问题

**Comment by PlutoCA** [comment]
我这边看 似乎是因为 我这边每次生成的Key不同 然后导致 taro渲染的时候重新把组件渲染了一遍

**Comment by lsqy** [comment]
我这边试了下，代码中为什么会有一个arrayKey的引用呢？我这边去除了arrayKey以后试了下可以正常切换tag的选中状态
<img width="736" alt="屏幕快照 2019-07-20 下午11 41 25" src="https://user-images.githubusercontent.com/18533232/61580777-04522c80-ab48-11e9-979c-8edb5ce39234.png">

**Comment by lsqy** [comment]
@PlutoCA 你那边看到后，尽快给一个答复
