### ISSUE TITLE
可以在已有的小程序项目中引用taro-ui吗

### ISSUE THREAD

**Issue by ioth5** [NervJS/taro-ui#7]
如果可以在已有的小程序项目中引用taro-ui，建议更新一下相关使用文档

**Comment by koppthe** [comment]
是指在非 Taro 项目的小程序中使用 taro-ui 吗？

**Comment by ioth5** [comment]
是的

**Comment by jimczj** [comment]
目前我们 Taro 框架组在尝试将 Taro 代码 直接编译成微信小程序原生引用方式的代码，如果这个特性完成，理论上可以做到这一点，但目前不支持 
相关 issue https://github.com/NervJS/taro-ui/issues/10

**Comment by iceMusic** [comment]
> 目前我们 Taro 框架组在尝试将 Taro 代码 直接编译成微信小程序原生引用方式的代码，如果这个特性完成，理论上可以做到这一点，但目前不支持 相关 issue #10

请问现在有实现这个功能吗？
