### ISSUE TITLE
AtGrid中使用iconInfo报错“TS2741: Property 'value' is missing in type 'Element' but required in type 'AtIconBaseProps'”

### ISSUE THREAD

**Issue by LoveXiaoLiu** [NervJS/taro-ui#702]
版本：taro-ui（2.2.1），tarojs/taro（1.3.9）

报错详情如下：
![image](https://user-images.githubusercontent.com/16411017/61426036-90e3cb80-a94b-11e9-99d1-b78ab7f65d91.png)

**Comment by koppthe** [comment]
写法不对，可以参考官网的 DEMO：
https://github.com/NervJS/taro-ui/blob/dev/src/pages/layout/grid/index.js
