### ISSUE TITLE
AtTabBar在微信小程序中点击抛出错误“Warning: Failed prop type: Invalid prop `maxValue` of type `string` supplied to `AtBadge`, expected `number`.”

### ISSUE THREAD

**Issue by wvit** [NervJS/taro-ui#703]
**问题描述**

**复现步骤**

```js
// 这里可以贴代码
```

**期望行为**

**报错信息**

**系统信息**

**补充信息**

**Comment by vinurs** [comment]
我也遇到了这个问题

**Comment by q8938036** [comment]
我也遇到了，解决了吗？

**Comment by hick** [comment]
我也遇到了这个问题,  点击 tabbar 任意选项,  第一次点会这样, 后续不会再出现, 除非重启小程序. 跟这个貌似是一个事  https://github.com/NervJS/taro-ui/issues/704

**Comment by dcrysg** [comment]
同问，如何解决呢？Warning: Failed prop type: Invalid prop `maxValue` of type `string` supplied to `AtBadge`, expected `number`.

**Comment by suning007** [comment]
我临时将dist/npm/taro-ui/dist/weapp/components/tab-bar/index.js下的174行"maxValue": item.$original.iconType || item.$original.image ? '' : item.$original.max改为"maxValue": item.$original.iconType || item.$original.image ? 0 : item.$original.max
原因是AtBadge中的maxValue仅支持number类型，在tabbar中默认值却为''
