### ISSUE TITLE
AtBadge maxValue PropType问题

### ISSUE THREAD

**Issue by zcc19910524** [NervJS/taro-ui#704]
**问题描述**
AtTabBar 中的这一段代码 
`<View>
              <AtBadge
                dot={(item.iconType || item.image) ? false : !!item.dot}
                value={(item.iconType || item.image) ? null : item.text}
                maxValue={(item.iconType || item.image) ? null : item.max}
              >
                <View className='at-tab-bar__title' style={titleStyle}>
                  {item.title}
                </View>
              </AtBadge>
            </View>`
maxValue 可能是null
AtBadge的PropType中是number 会出现warning

**Comment by lsqy** [comment]
将`null`换成0即可

**Comment by lsqy** [comment]
将`null`换成0即可 @zcc19910524
