### ISSUE TITLE
对AtButton不能在父容器居中的问题？

### ISSUE THREAD

**Issue by zhou1992zg** [NervJS/taro-ui#71]
我在项目中使用了AtButton按钮
并且给按钮一个View父级元素，于是在小程序端编译后的代码显示为：
<img width="704" alt="2018-09-20 9 24 05" src="https://user-images.githubusercontent.com/29066081/45790347-f5e07d80-bcb6-11e8-8511-a58f7e1f232d.png">
给父元素width:100%; text-align:center;结果按钮（小程序端）未局中，H5端居中显示；
换一种方式：
给.at-button--small（AtButton的className）margin：0 auto；position：static；还是未能实现居中
请大佬帮忙解决一下。目前是用给.at-button--small {margin-left: 270px!important;}实现居中显示的
谢谢！

**Comment by jimczj** [comment]
使用 flex 居中咯

**Comment by cos2004** [comment]
看一下你的小程序基础库版本是否大于等于 2.2.3，如果是的话用 small 按钮的父容器用 text-align 是可以居中的

**Comment by deepcoldy** [comment]
@zhou1992zg 建议你试一下customStyle这个属性，虽然文档中没写，但是已经支持了。
![image](https://user-images.githubusercontent.com/10922642/45821076-ebf06600-bd1a-11e8-9055-770918d3fc29.png)
