### ISSUE TITLE
ImagePicker组件ts属性缺少count

### ISSUE THREAD

**Issue by jekorx** [NervJS/taro-ui#712]
**问题描述**
tsx中引入AtImagePicker组件并使用时，提示AtImagePickerProps确实count属性，Taro-UI组件源码中确实包含count属性，image-picker.d.ts中AtImagePickerProps缺少count属性，但不影响打包使用。

**复现步骤**
![1](https://user-images.githubusercontent.com/17465469/61778675-c3049a00-ae31-11e9-9f9c-38ab474a1db4.png)

**期望行为**
image-picker.d.ts中AtImagePickerProps，增加count属性。

**报错信息**
不能将类型“{ multiple: false; files: { url: string; }[]; length: number; count: number; mode: "aspectFill"; showAddBtn: boolean; onChange: (imgs: any[]) => void; onImageClick: (index: number) => void; }”分配给类型“IntrinsicAttributes & IntrinsicClassAttributes<Component<AtImagePickerProps, any, any>> & Readonly<AtImagePickerProps> & Readonly<{ children?: ReactNode; }>”。
  类型“IntrinsicAttributes & IntrinsicClassAttributes<Component<AtImagePickerProps, any, any>> & Readonly<AtImagePickerProps> & Readonly<{ children?: ReactNode; }>”上不存在属性“count”。

**系统信息**
$ taro info
👽 Taro v1.3.0
  Taro CLI 1.3.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.13.0 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 5.1.0 - ~\AppData\Local\Yarn\bin\npm.CMD

**补充信息**
Taro-UI版本 2.2.0

**Comment by briefguo** [comment]
是的，类型描述文件缺失了属性
