### ISSUE TITLE
微信小程序，部分手机上class自动添加前缀

### ISSUE THREAD

**Issue by Qiu800820** [NervJS/taro-ui#72]
使用Taro-UI 的AtModel模态框做了一个对话框，模拟器预览一切正常  iPhone 7P上显示样式错误，手机远程调试发现class被加上前缀。
![tim 20180920111023](https://user-images.githubusercontent.com/7494629/45793967-ef5a0200-bcc6-11e8-8960-6f8fb8248d60.png)
![tim 20180920111259](https://user-images.githubusercontent.com/7494629/45793973-f2ed8900-bcc6-11e8-82d7-d992f06b6028.png)

### 重现步骤
iPhone 7P 真机预览

### 依赖的版本号
操作系统: [e.g. Windows 10]
Taro 版本 1.0.1
Node.js 版本 [e.g. v8.11.3]

**Comment by SzHeJason** [comment]
@Qiu800820  自动添加的前缀会影响样式吗？

**Comment by SzHeJason** [comment]
可以忽略 是正常行为 微信本身加上去 估计是用来实现现样式作用域的

**Comment by Qiu800820** [comment]
但只出现在部分手机，如果我想自定义Taro-UI 自带样式的话， 这样就会出现问题，因为无法正确定位元素

**Comment by SzHeJason** [comment]
@Qiu800820 目前自定义的样式无法工作？ 真机的前缀应该与开发无关
