### ISSUE TITLE
taro升级1.3.12版本后,组件AtButton设置open-type='getUserInfo'时，无法成功调取用户授权页面

### ISSUE THREAD

**Issue by summer-yyyn** [NervJS/taro-ui#731]
### Taro UI 版本信息

2.2.1

### 问题描述

taro升级1.3.12版本后,组件AtButton设置open-type='getUserInfo'时，无法成功调取用户授权页面

### 复现步骤

<AtButton type='primary' open-type="getUserInfo" onGetUserInfo={this.onGotUserInfo}>登录</AtButton>
点击后进不到执行函数里

### 复现代码

<AtButton type='primary' open-type="getUserInfo" onGetUserInfo={this.onGotUserInfo}>登录</AtButton>

onGotUserInfo (e) {
    console.log(123)
}

### 报错信息

无

### 系统信息

👽 Taro v1.3.12

  Taro CLI 1.3.12 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
      Yarn: 1.17.3 - ~/.nvm/versions/node/v12.4.0/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v12.4.0/bin/npm

**Comment by koppthe** [comment]
参数名是 `openType`，不是 `open-type`
