### ISSUE TITLE
Atinput，设置了confirmType，不生效

### ISSUE THREAD

**Issue by candyAndBella** [NervJS/taro-ui#732]
### Taro UI 版本信息

2.2.0

### 问题描述

Atinput设置了confirmType，不生效，安卓手机上还是显示‘换行’

### 复现步骤

引用AtInput，设置confirmType属性

### 复现代码

<AtInput className='mySearch' value={searValue} confirmType='完成' placeholder='关键字/位置/酒店名' onChange={this.onChangeSear.bind(this)} onConfirm={this.onConfirmSear} border={false}  />

### 报错信息

无报错

### 系统信息

  Taro CLI 1.2.26 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.1 - D:\program\nodejs\node.EXE
      npm: 6.9.0 - D:\program\nodejs\npm.CMD

**Comment by koppthe** [comment]
微信小程序还是 H5？
