### ISSUE TITLE
AtActivityIndicator为什么没有显隐状态的属性

### ISSUE THREAD

**Issue by zhangyongjieo** [NervJS/taro-ui#733]
**问题描述**
AtActivityIndicator没有能够控制显示与隐藏loding的属性

**复现步骤**

**期望行为**
希望可以有控制显隐的属性

**报错信息**
无

**系统信息**
 - Taro UI 版本 [ v.2.2.1]

**补充信息**
mintUI可以通过JS控制loding的显隐，ant-design有控制loading显隐的属性

**Comment by gaorubin1990** [comment]
基本是个成熟的ui库的loading都可以设置显隐，连这个属性都没有的话这个组件存在的意义是什么？
