### ISSUE TITLE
searchBar真机卡顿

### ISSUE THREAD

**Issue by changeyan** [NervJS/taro-ui#735]
searchbar除了去除了底部横线外，未作任何改动。

build及dev模式测试，在微信开发工具内预览不卡顿，真机( iPhone X ，其他机型暂未测试 )卡顿

![无标题](https://user-images.githubusercontent.com/29328494/62799338-228dc580-bb13-11e9-890c-39b48fbd2bea.png)

Taro版本 ：1.3.10
微信开发工具版本 ：Stable v1.02.1907160
iPhone X 系统版本：12.4
微信版本：7.0.5

**Comment by changeyan** [comment]
![无标题](https://user-images.githubusercontent.com/29328494/62799311-13a71300-bb13-11e9-8053-69539c6a3dd4.png)

**Comment by koppthe** [comment]
是指动画卡顿吗？

**Comment by changeyan** [comment]
> 是指动画卡顿吗？

是的，动画卡顿，动画有果冻感，但是开发工具内并没有出现，非常流畅

**Comment by changeyan** [comment]
> 是指动画卡顿吗？

但是刚刚发现，问题又奇怪地消失了。其实在之前的时候发生过类似的事情，但是我没有在意这个问题，总是重新编译重新预览好多次还是会卡顿，希望关注一下这方面的问题，感谢回复，祝 O2 更好

**Comment by koppthe** [comment]
小程序的动画性能不好，会存在卡顿的问题，所以下个版本可能会将动画去掉

**Comment by changeyan** [comment]
> 小程序的动画性能不好，会存在卡顿的问题，所以下个版本可能会将动画去掉

了解！但完全去掉动画又会感觉生硬些，相信可以有更好的方案😄，感谢回复，祝O2更好！

**Comment by Jetereting** [comment]
请问是怎么把 底部横线 去掉的，带着底部横线好难看

**Comment by changeyan** [comment]
试出来的，忘了是哪个了

**Comment by changeyan** [comment]
试出来的，具体哪个忘了
