### ISSUE TITLE
picker 设置时间跨度

### ISSUE THREAD

**Issue by liuyunzyj** [NervJS/taro-ui#740]
期望官方增加时间跨度属性：现在时间跨度为1分钟，期望这个时间跨度由用户设置

![image](https://user-images.githubusercontent.com/40293335/63005085-66375500-beae-11e9-9777-45c0d5aef3a1.png)

**Comment by liuyunzyj** [comment]
期望官方能快速发布，项目急着用

**Comment by koppthe** [comment]
这个是小程序原生组件，Taro UI 没有做封装哈

**Comment by liuyunzyj** [comment]
那意思就是需要自己自定义写一个了？官方能出一个这样的组件吗？

**Comment by koppthe** [comment]
小程序原生组件不支持的话，需要自己实现一个
