### ISSUE TITLE
AtSearchBar组件onActionClick事件第一次点击页面会刷新，并且阻止不了，会导致render渲染两次

### ISSUE THREAD

**Issue by emptycitys** [NervJS/taro-ui#741]
**问题描述**

**复现步骤**

```js
// 这里可以贴代码
```

**期望行为**

**报错信息**

**系统信息**

**补充信息**

**Comment by promiseLC** [comment]
外面使用AtForm 包裹一下,并且 最后加一个 AtInput ,把AtInput 隐藏掉就好了
