### ISSUE TITLE
小程序自定义头部该盖住不了AtTextarea组件

### ISSUE THREAD

**Issue by emptycitys** [NervJS/taro-ui#753]
**问题描述**

**复现步骤**

```js
// 这里可以贴代码
```

**期望行为**

**报错信息**

**系统信息**

**补充信息**

![WechatIMG3](https://user-images.githubusercontent.com/35291465/63322778-cc145880-c356-11e9-9513-cc6c3737f07d.jpeg)

**Comment by koppthe** [comment]
小程序原生组件的层级是最高的，如果用 Textarea 而不是 AtTextarea ，会存在一样的问题吗？

**Comment by emptycitys** [comment]
我用cover-view解决了
