### ISSUE TITLE
AtImagePicker定义文件没有更新

### ISSUE THREAD

**Issue by zhangyifei007** [NervJS/taro-ui#757]
**问题描述**

**复现步骤**

![image](https://user-images.githubusercontent.com/37685299/63416220-a019d580-c431-11e9-8248-bd6136a3ec70.png)

```js
// 这里可以贴代码
```

**期望行为**

sizeType
sourceType
添加到定义文件中
**报错信息**

**系统信息**

**补充信息**

**Comment by koppthe** [comment]
本周的版本会更新，谢谢反馈~
