### ISSUE TITLE
AtButton 不支持icon

### ISSUE THREAD

**Issue by pssgo** [NervJS/taro-ui#76]
### 重现步骤
![image](https://user-images.githubusercontent.com/16378134/45865881-88654780-bdb1-11e8-8fe5-db073b2dbc6e.png)

官网实例的AtButton 是可以支持配置icon的
```js
<AtButton icon='clock' type='primary' size='normal'>按钮文案</AtButton>
```

### 依赖的版本号
- Node 10.0
- Taro 1.0.1
- Taro-ui 1.2.1

### 预期结果
支持使用icon
### 实际结果
不支持
### 相关链接
[taro-ui](https://taro-ui.aotu.io/#/docs/button)

**Comment by cos2004** [comment]
不好意思，这是刚开始规划时候会支持，后来由于一些问题暂不支持，只支持一个 loading 态的 icon。请留意后面的规划吧

**Comment by tourze** [comment]
这个需求应该很多人有吧，建议官方重新加入规划~

**Comment by kenberkeley** [comment]
+1 （该 issue 应该保持 open）
