### ISSUE TITLE
AtInput  type="number" 时，返回的值为 string ,应该为 number 才对吧

### ISSUE THREAD

**Issue by Dolov** [NervJS/taro-ui#763]
**问题描述**
AtInput type="number" 时，返回的值为 string

**复现步骤**
<AtInput type="number" />

```js
   onChange = value => {
       console.log(typeof value)
   }
   <AtInput onChange={this.onChange} type="number" />
```

**期望行为**
如果 type=number  则返回值为 number 类型

**报错信息**

**系统信息**

**补充信息**

**Comment by koppthe** [comment]
HTML 的规范就是这样的哈，即使 `type="number"`，`input` 获取的值也还是 `string`
参考链接：https://html.spec.whatwg.org/multipage/input.html#number-state-(type%3Dnumber)

**Comment by facedan** [comment]
我也遇到了同样的问题

**Comment by Tzng** [comment]
我觉得为了方便，还是组件内把值转换一下类型吧。。。
