### ISSUE TITLE
AtInput在失去焦点时onchange还会多触发一次，求解决办法。。。

### ISSUE THREAD

**Issue by emptycitys** [NervJS/taro-ui#767]
**问题描述**

**复现步骤**

```js
// 这里可以贴代码
```

**期望行为**

**报错信息**

**系统信息**

**补充信息**

**Comment by koppthe** [comment]
麻烦提供一下完整的信息吧

**Comment by emptycitys** [comment]
在input失去焦点时，我有在onchange函数里打印console啊，会执行，
