### ISSUE TITLE
ImagePicker 在h5环境下，点击添加，会出现照片库中显示没有图片

### ISSUE THREAD

**Issue by GPWiOS** [NervJS/taro-ui#768]
```js
<AtImagePicker
 className='img-picker'
mode='aspectFill'
files={imageFiles}
count={1}
length={3}
showAddBtn={imageFiles.length < 3}
sizeType={['compressed']}
onChange={this.selectImages.bind(this)}
onFail={this.selectImageFail.bind(this)}
></AtImagePicker>	
```

**期望行为**
h5环境下，可以正常添加图片
**报错信息**
![image](https://user-images.githubusercontent.com/15536539/63909556-afaea500-ca55-11e9-8361-9a4ebeb05391.png)

**系统信息**
Taro CLI 1.3.11 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.15.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.11 => 1.3.11 
      @tarojs/components: 1.3.11 => 1.3.11 
      @tarojs/plugin-babel: 1.3.11 => 1.3.11 
      @tarojs/plugin-csso: 1.3.11 => 1.3.11 
      @tarojs/plugin-sass: 1.3.11 => 1.3.11 
      @tarojs/plugin-uglifyjs: 1.3.11 => 1.3.11 
      @tarojs/redux: 1.3.11 => 1.3.11 
      @tarojs/redux-h5: 1.3.11 => 1.3.11 
      @tarojs/router: 1.3.11 => 1.3.11 
      @tarojs/taro: 1.3.11 => 1.3.11 
      @tarojs/taro-alipay: 1.3.11 => 1.3.11 
      @tarojs/taro-h5: 1.3.11 => 1.3.11 
      @tarojs/taro-swan: 1.3.11 => 1.3.11 
      @tarojs/taro-tt: 1.3.11 => 1.3.11 
      @tarojs/taro-weapp: 1.3.11 => 1.3.11 
      @tarojs/webpack-runner: 1.3.11 => 1.3.11 
      eslint-config-taro: 1.3.11 => 1.3.11 
      eslint-plugin-taro: 1.3.11 => 1.3.11 
      nerv-devtools: ^1.4.0 => 1.4.3 
      nervjs: ^1.4.0 => 1.4.3 
      stylelint-config-taro-rn: 1.3.11 => 1.3.11 
      stylelint-taro-rn: 1.3.11 => 1.3.11

**Comment by koppthe** [comment]
试试新建一个 html，只放一个 <input type="file" /> ，测试一下是否能正确打开有照片的目录？
