### ISSUE TITLE
Taro UI  表单组件什么时候支持  AtInput 之外的其他组件数据提交？

### ISSUE THREAD

**Issue by zhou1992zg** [NervJS/taro-ui#77]

**Comment by jimczj** [comment]
需要1.4 版本后再规划

**Comment by jimczj** [comment]
将组件内的用户输入的值提交。由于小程序组件化的限制，要触发 onSubmit，必须使用 AtButton 且设置 formType='submit'，onSubmit 事件获得的 event 中的 event.detail.value 始终为空对象，开发者要获取数据，可以自行在页面的 state 中获取

https://taro-ui.aotu.io/#/docs/form
