### ISSUE TITLE
AtCountDown 组件的类型文件缺少 isShowHour 类型

### ISSUE THREAD

**Issue by xunmi1** [NervJS/taro-ui#777]
### Taro UI 版本信息

2.2.2

### 问题描述

`AtCountDown` 组件对应的 `d.ts`， 缺少对 `isShowHour` 参数的类型定义

> @types/countdown.d.ts -> `AtCountDownProps`

### 复现步骤

当在 TS 的项目中使用 `AtCountDown` 组件时，语法检测提示 `isShowHour` 的没有定义

### 复现代码

```html
<AtCountdown isShowHour={false} />
```

### 报错信息

```
TS2322: Type '{ isShowHour: boolean; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<AtCountDownProps, any, any>> & Readonly<AtCountDownProps> & Readonly<{ children?: ReactNode; }>'.
```

### 系统信息

System:
  OS: Windows 10

Binaries:
  Node: 10.16.3
  Yarn: 1.17.3
  npm: 6.9.0

**Comment by lsqy** [comment]
已修复，待发布新版本的时候更新即可，给你带来的不便深感抱歉，下次会注意这种类似的规范问题
