### ISSUE TITLE
富文本和地图组件

### ISSUE THREAD

**Issue by Dolov** [NervJS/taro-ui#778]
### 这个功能解决了什么问题？

你好，在 Taro-ui 文档中没有找到富文本编辑和地图组件，请问以后会支持这两个组件么，在不支持的情况下，有没有什么合适的推荐方案呢

### 你期望的功能是怎样的？

你好，在 Taro-ui 文档中没有找到富文本编辑和地图组件，请问以后会支持这两个组件么，在不支持的情况下，有没有什么合适的推荐方案呢

### 补充信息

你好，在 Taro-ui 文档中没有找到富文本编辑和地图组件，请问以后会支持这两个组件么，在不支持的情况下，有没有什么合适的推荐方案呢

**Comment by koppthe** [comment]
1. 富文本编辑？Taro UI 提供的是基础组件，富文本编辑应该是独立组件了，建议自行实现哈~
如果是展示富文本，可以使用 `RichText` 组件
https://taro-docs.jd.com/taro/docs/components/base/rich-text.html

2. 地图组件：https://taro-docs.jd.com/taro/docs/components/maps/map.html

**Comment by Dolov** [comment]
> 1. 富文本编辑？Taro UI 提供的是基础组件，富文本编辑应该是独立组件了，建议自行实现哈~
>    如果是展示富文本，可以使用 `RichText` 组件
>    https://taro-docs.jd.com/taro/docs/components/base/rich-text.html
> 2. 地图组件：https://taro-docs.jd.com/taro/docs/components/maps/map.html

多谢哈，
我看到小程序中已经有了 editor 组件了 ，taro 现在是否已经支持了呢？
https://developers.weixin.qq.com/miniprogram/dev/component/editor.html
