### ISSUE TITLE
可以增加datetimepicker、Carousel(slide show)这些组件莫

### ISSUE THREAD

**Issue by wakaryry** [NervJS/taro-ui#79]
原生IOS开发者一枚，偶尔用vue，本来准备用mpvue来做小程序开发的。突然发现了taro，准备用来做小程序和RN。

以前也没有正式用过RN，不知道一些组件库是不是提供这些组件。

不过在原生开发中，日期选择，banner slider这些都是很常见的组件。

Thx。

**Comment by koppthe** [comment]
Carousel 的组件是有的，可查看文档：https://nervjs.github.io/taro/docs/components/viewContainer/swiper.html

日期选择器有计划做，但目前优先级比较低，详情可以看我们的开发计划：https://github.com/NervJS/taro-ui/blob/dev/PLANS.md
