### ISSUE TITLE
当TaroUI的组件的子组件是自己定义组件时，自己定义组件中使用TaroUI的样式失效。

### ISSUE THREAD

**Issue by oxygen-xx** [NervJS/taro-ui#795]
**问题描述**
我在AtTabsPane中，套用了我自己定义的组件。<ValueCardList></ValueCardList>
<AtTabsPane><ValueCardList></ValueCardList></AtTabsPane>
结果，ValueCardList中的所有内容显示是没有问题的，但用到TaroUI样式的地方，失效了，不起作用。比如at-row, at-article__info等全失效了。但我已经全局的引入了TaroUI了，并且在其它的一级页面是好用的。
这时候，只有在ValueCardList中，再次重复引入@import "~taro-ui/dist/style/index.scss";才能让子组件的样式好用。

**报错信息**
TaroUI的样式在嵌套自己定义组件中，失效。

**系统信息**
 - Taro 版本 [1.3.18]
 - Taro UI 版本 [2.2.2]
 - 报错平台 [weapp]

1111

**Comment by yinLiangDream** [comment]
请问子组件加了 addGlobalClass: true 这个属性吗
