### ISSUE TITLE
小程序构建出错

### ISSUE THREAD

**Issue by limichange** [NervJS/taro-ui#8]
### 重现步骤
安装最新版taro-ui
### 依赖的版本号

taro-ui 1.0.0
taro 1.0.0-beta.18
### 预期结果
正常引入
### 实际结果
![image](https://user-images.githubusercontent.com/1947344/44695463-dd10ed80-aaa5-11e8-8122-16f0f8e19e59.png)

**Comment by koppthe** [comment]
已修复，taro beta.18 打包有点小问题，暂时切换回了 beta.17  (https://github.com/NervJS/taro-ui/commit/7549d8c3f0446edae6039557c52d1257111a61a8)
