### ISSUE TITLE
model如何加入自己得自定义组件

### ISSUE THREAD

**Issue by cuiyimeng** [NervJS/taro-ui#813]
**这个功能解决了什么问题？**

我不知道如何自定义model中得内容
**你期望的功能是怎样的？**

自定义model中得内容
**补充信息**

**Comment by Garfield550** [comment]
可以参考 [AtModel  文档](https://taro-ui.aotu.io/#/docs/modal)一般用法一节：

```jsx
<AtModal isOpened>
  <AtModalHeader>标题</AtModalHeader>
  <AtModalContent>
    这里是正文内容，欢迎加入京东凹凸实验室
    这里是正文内容，欢迎加入京东凹凸实验室
    这里是正文内容，欢迎加入京东凹凸实验室
  </AtModalContent>
  <AtModalAction> <Button>取消</Button> <Button>确定</Button> </AtModalAction>
</AtModal>
```

也可以参考 Taro-UI 示例小程序中的代码：

```jsx
<AtModal
  isOpened={isOpened1}
  onClose={this.closeModal.bind(this, 1, 'Modal被关闭了')}
>
  <AtModalHeader>标题</AtModalHeader>
  <AtModalContent>
    <View className='modal-content'>
      这里是正文内容，欢迎加入京东凹凸实验室
      这里是正文内容，欢迎加入京东凹凸实验室
      这里是正文内容，欢迎加入京东凹凸实验室
    </View>
  </AtModalContent>
  <AtModalAction>
    <Button onClick={this.closeModal.bind(this, 1, '点击了取消')}>
      取消
    </Button>
    <Button onClick={this.closeModal.bind(this, 1, '点击了确定')}>
      确定
    </Button>
  </AtModalAction>
</AtModal>
```

示例源码地址：https://github.com/NervJS/taro-ui/blob/dev/src/pages/action/modal/index.js

**Comment by cuiyimeng** [comment]
但是我需要自己写css样式对吗?我已经使用此方法,但是发现样式全部消失了

**Comment by cuiyimeng** [comment]
> 可以参考 [AtModel 文档](https://taro-ui.aotu.io/#/docs/modal)一般用法一节：
> 
> ```js-jsx
> <AtModal isOpened>
>   <AtModalHeader>标题</AtModalHeader>
>   <AtModalContent>
>     这里是正文内容，欢迎加入京东凹凸实验室
>     这里是正文内容，欢迎加入京东凹凸实验室
>     这里是正文内容，欢迎加入京东凹凸实验室
>   </AtModalContent>
>   <AtModalAction> <Button>取消</Button> <Button>确定</Button> </AtModalAction>
> </AtModal>
> ```
> 
> 也可以参考 Taro-UI 示例小程序中的代码：
> 
> ```js-jsx
> <AtModal
>   isOpened={isOpened1}
>   onClose={this.closeModal.bind(this, 1, 'Modal被关闭了')}
> >
>   <AtModalHeader>标题</AtModalHeader>
>   <AtModalContent>
>     <View className='modal-content'>
>       这里是正文内容，欢迎加入京东凹凸实验室
>       这里是正文内容，欢迎加入京东凹凸实验室
>       这里是正文内容，欢迎加入京东凹凸实验室
>     </View>
>   </AtModalContent>
>   <AtModalAction>
>     <Button onClick={this.closeModal.bind(this, 1, '点击了取消')}>
>       取消
>     </Button>
>     <Button onClick={this.closeModal.bind(this, 1, '点击了确定')}>
>       确定
>     </Button>
>   </AtModalAction>
> </AtModal>
> ```
> 
> 示例源码地址：https://github.com/NervJS/taro-ui/blob/dev/src/pages/action/modal/index.js

但是我需要自己写css样式对吗?我已经使用此方法,但是发现样式全部消失了
