### ISSUE TITLE
Input组件增加是否为必填项参数

### ISSUE THREAD

**Issue by fernandoxu** [NervJS/taro-ui#814]
**这个功能解决了什么问题？**

必填项左边显示*,非必填不显示
**你期望的功能是怎样的？**
![image](https://user-images.githubusercontent.com/20871468/66636324-90ee2180-ec43-11e9-9432-d81250aecef3.png)

![image](https://user-images.githubusercontent.com/20871468/66636430-c561dd80-ec43-11e9-8baf-c492baee6d69.png)

**Comment by huiruo** [comment]
> **这个功能解决了什么问题？**
> 
> 必填项左边显示*,非必填不显示
> **你期望的功能是怎样的？**
> ![image](https://user-images.githubusercontent.com/20871468/66636324-90ee2180-ec43-11e9-9432-d81250aecef3.png)
> 
> ![image](https://user-images.githubusercontent.com/20871468/66636430-c561dd80-ec43-11e9-8baf-c492baee6d69.png)

//添加伪类
.at-input__title:before{
  content: "*";
  color: #f56c6c;
  margin-right: 4px;
}
