### ISSUE TITLE
AtForm h5没办法触发submit事件？

### ISSUE THREAD

**Issue by zongyan86** [NervJS/taro-ui#817]
**问题描述**
[问题描述：Form h5可以提交，但是用了AtForm h5 submit没有响应，事件不会触发]

**复现步骤**
[复现问题的步骤]
1.官方demo直接单页调试

**报错信息**

无报错信息，也不触发submit事件

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by AwesomeDevin** [comment]
https://taro-ui.aotu.io/#/docs/form  #380  已修复,麻烦尝试更新taro-ui版本至v2.2.3后再试试

**Comment by zongyan86** [comment]
刚获取taroUI最新版本，测试了下简单文本框提交，可以触发到该事件了！谢谢




------------------ 原始邮件 ------------------
发件人: "Devin"<notifications@github.com>;
发送时间: 2019年10月15日(星期二) 下午2:56
收件人: "NervJS/taro-ui"<taro-ui@noreply.github.com>;
抄送: "许宗彦"<378588579@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [NervJS/taro-ui] AtForm h5没办法触发submit事件？ (#817)




Closed #817.

**Comment by zongyan86** [comment]
似乎只有arInput能支持表单提交，其他空间都没有耶。  reset事件能触发，event打印为undefined


------------------ 原始邮件 ------------------
发件人: "Devin"<notifications@github.com>;
发送时间: 2019年10月15日(星期二) 下午2:56
收件人: "NervJS/taro-ui"<taro-ui@noreply.github.com>;
抄送: "许宗彦"<378588579@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [NervJS/taro-ui] AtForm h5没办法触发submit事件？ (#817)




Closed #817.

**Comment by AwesomeDevin** [comment]
谢谢反馈，晚点排查一下

**Comment by AwesomeDevin** [comment]
刚刚测试了一下，其它表单控件没问题，可以支持的
```js
constructor () {
    super(...arguments)
    this.state = {
      value: []
    }
  }
  handleChange (value) {
    this.setState({
      value
    })
  }
  onSubmit (event) {
    console.log(this.state.value)
  }
  onReset (event) {
    this.setState({
      value: [],
    })
  }
  render () {
    return (
      <AtForm
        onSubmit={this.onSubmit.bind(this)}
        onReset={this.onReset.bind(this)}
      >
        <AtCheckbox
          options={[
            { label: 'iPhone X', value: 'iPhone X' },
            { label: 'HUAWEI P20', value: 'HUAWEI P20' }
          ]}
          selectedList={this.state.value}
          onChange={this.handleChange.bind(this, 'value')}
        />
        <AtButton formType='submit'>提交</AtButton>
        <AtButton formType='reset'>重置</AtButton>
      </AtForm>
    )
  }
```

**Comment by zongyan86** [comment]
https://github.com/NervJS/taro-ui/issues/743


兄弟，这个问题能解决吗？大致什么时候能解决。难道要自己再写个H5的上传组件，这样就太麻烦了

**Comment by Garfield550** [comment]
> #743 兄弟，这个问题能解决吗？大致什么时候能解决。难道要自己再写个H5的上传组件，这样就太麻烦了

ImagePicker 的 Files 就是 `Taro.chooseImage()` 的返回结果。

H5 的 `chooseImage` 实现直接返回的是 `Blob Web API` 的结果，是一个 `blob:http://file` 形式的链接，如果硬给 Blob 链接拼接文件后缀，如：`blob:http://file.png` 会造成无法访问文件。

H5 的 `chooseImage` 实现比小程序的 `chooseImage` 在 `file` 字段里多返回一个 `type`，大概长这样：

```json
{
    "file": {
        "path": "blob:http://file",
        "size": 8192,
        "type": "image/png"
    },
    "url": "blob:http://file"
}
```

你可以根据 MIME Type 手动在 `Taro.uploadFile()` 里拼接一个带后缀的文件名出来。

**Comment by zongyan86** [comment]
如图所示，主要是后端根本就接不到文件耶。








------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Garfield Lee"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月29日(星期二) 下午2:24
收件人:&nbsp;"NervJS/taro-ui"<taro-ui@noreply.github.com&gt;;
抄送:&nbsp;"许宗彦"<378588579@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [NervJS/taro-ui] AtForm h5没办法触发submit事件？ (#817)



 
#743 兄弟，这个问题能解决吗？大致什么时候能解决。难道要自己再写个H5的上传组件，这样就太麻烦了
  
ImagePicker 的 Files 就是 Taro.chooseImage() 的返回结果。
 
H5 的 chooseImage 实现直接返回的是 Blob Web API 的结果，是一个 blob:http://file 形式的链接，如果硬给 Blob 链接拼接文件后缀，如：blob:http://file.png 会造成无法访问文件。
 
H5 的 chooseImage 实现比小程序的 chooseImage 在 file 字段里多返回一个 type，大概长这样：
 {     "file": {         "path": "blob:http://file",         "size": 8192,         "type": "image/png"     },     "url": "blob:http://file" }
 
你可以根据 MIME Type 手动在 Taro.uploadFile() 里拼接一个带后缀的文件名出来。

**Comment by Garfield550** [comment]
@zongyan86 你的图没有了，然后就是建议在 ImagePicker 的 onChange 事件打印一下日志，看看那些 "blob:http://file" 链接能不能在你的浏览器打开

详情参考 https://developer.mozilla.org/en-US/docs/Web/API/Blob https://developer.mozilla.org/en-US/docs/Web/API/File

**Comment by zongyan86** [comment]
您没理解我的意思，blob:http://file h5端是能访问没错。因为是本地blob。


但是onChange调用接口，后端是取不到这张图片的，小程序是可以取到图片。&nbsp;


 //图片上传
  onFileChange (files, operationType) {
    if (operationType === 'remove') {
      this.setState({
        files
      })
    }

    if (operationType === 'add') {
      console.log(Taro.getStorageSync('token'))
      const file = files[files.length - 1]
      Taro.uploadFile({
        url:
          process.env.TARO_ENV === 'h5'
            ? '/sb/equipmentException/uploadFile'
            : Config.BASE_URL + '/sb/equipmentException/uploadFile',
        name: 'file',
        filePath: file.url,
        formData: {
          file: files
        },
        header: {
          Authorization:
            Taro.getStorageSync('token') || this.props.user.otb.token
        },
        success: resp =&gt; {
          let json = JSON.parse(resp.data)
          file.path = json.data.path
          file.url = json.data.url
          this.setState({
            files
          })
        }
      })
    }
  }




h5端的请求报文：
------WebKitFormBoundaryOdKqZIgE9v6Xx6zu Content-Disposition: form-data; name="file" [object Object],[object Object],[object Object],[object Object] ------WebKitFormBoundaryOdKqZIgE9v6Xx6zu Content-Disposition: form-data; name="file"; filename="file-1572331264984" Content-Type: image/png PNG  IHDRÈÈ­X®sRGB®ÎébKGDÿÿÿ&nbsp;½§	pHYstIMEÛ:øÛIDATxÚí{pTUÇ¿Ý~%é<Háa@	áä1ADDwÕYtVÝÚÚ-Ý©uwk«¦fkªvö¯u&amp;8&gt;PAGÁE@åAä¡¼;¹ý¾ûG7ï¾Ý÷ÜÓçÞûûTuQEõ½ç¦û÷»çû;÷Û¿cÑ(0&gt;ö &nbsp; ÀùØëwLró<`








------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Garfield Lee"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月29日(星期二) 下午2:35
收件人:&nbsp;"NervJS/taro-ui"<taro-ui@noreply.github.com&gt;;
抄送:&nbsp;"许宗彦"<378588579@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [NervJS/taro-ui] AtForm h5没办法触发submit事件？ (#817)




@zongyan86 你的图没有了，然后就是建议在 ImagePicker 的 onChange 事件打印一下日志，看看那些 "blob:http://file" 链接能不能在你的浏览器打开
 
详情参考 https://developer.mozilla.org/en-US/docs/Web/API/Blob https://developer.mozilla.org/en-US/docs/Web/API/File

**Comment by Garfield550** [comment]
@zongyan86 
那可能这是 `Taro.uploadFile` 这个 API 的问题了。
然后请求报文看上去也没太大问题，也许是你们后端没做好。

**Comment by zongyan86** [comment]
不是后端没做好，因为小程序能接收到图片没问题。我也调通了。
但是，h5后端接到的就是一堆奇怪的东东。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Garfield Lee"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月29日(星期二) 下午2:47
收件人:&nbsp;"NervJS/taro-ui"<taro-ui@noreply.github.com&gt;;
抄送:&nbsp;"许宗彦"<378588579@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [NervJS/taro-ui] AtForm h5没办法触发submit事件？ (#817)




@zongyan86
 那可能这是 Taro.uploadFile 这个 API 的问题了。
 然后请求报文看上去也没太大问题，也许是你们后端没做好。

**Comment by Garfield550** [comment]
@zongyan86 https://github.com/NervJS/taro/issues/4650 这是 Taro 那边 关于 HT5 uploadFile API 遇到 Blob 后端不认识问题的人 你可以跟他聊聊。

**Comment by zongyan86** [comment]
好的 ，我找他聊聊，你们分工还挺明确的啊 哈哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Garfield Lee"<notifications@github.com&gt;; 
发送时间: 2019年10月29日(星期二) 下午2:51
收件人: "NervJS/taro-ui"<taro-ui@noreply.github.com&gt;; 
抄送: "许宗彦"<378588579@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [NervJS/taro-ui] AtForm h5没办法触发submit事件？ (#817)




@zongyan86 NervJS/taro#4650 这是 Taro 那边 关于 HT5 uploadFile API 遇到 Blob 后端不认识问题的人 你可以跟他聊聊。
