### ISSUE TITLE
taro-ui 组件修改后，重新更新修改内容被覆盖

### ISSUE THREAD

**Issue by kapbook-caizhehao** [NervJS/taro-ui#822]
**问题描述**
背景：微信小程序，因业务需求修改了taro-ui组件【scss文件修改(样式修改)】【js文件修改(功能修改)】
问题：
1.重新更新taro-ui组件会将修改内容覆盖。
2.因taro-ui组件安装在node_modules文件夹下；在多人同时开发时，如一人更改其本地taro-ui组件，但更改内容无法commit给其他开发者，导致代码不统一。
![image](https://user-images.githubusercontent.com/38315632/67185132-bcc59000-f417-11e9-8719-504edf5ba04b.png)

**期望行为**
在使用taro-ui开发时，更新taro-ui修改内容不被覆盖，且多人开发时能保证代码统一。

**Comment by Garfield550** [comment]
如果涉及到了功能更改又有代码共享需求的话，建议将相关组件的代码拷贝至本地，更换组件名称并自己进行封装。
