### ISSUE TITLE
AtIcon 在Taro 1.0.4 下报错

### ISSUE THREAD

**Issue by changjunhao** [NervJS/taro-ui#84]
### 依赖的版本号

 node 10.11.0
Taro 1.0.4
Taro-UI  1.2.2
### 实际结果
<img width="933" alt="2018-09-27 11 41 48" src="https://user-images.githubusercontent.com/7688639/46122379-e9c26600-c24a-11e8-9ef4-746029fe3438.png">

**Comment by Hhpon** [comment]
我也遇到这个问题了

**Comment by HuMoran** [comment]
我没直接用AtIcon这个组件都报错了，不知道哪个组件内部引用了
