### ISSUE TITLE
input的clear清除问题

### ISSUE THREAD

**Issue by xxyGoTop** [NervJS/taro-ui#840]
受控组件时，input点击clear按钮时，会触发onChange事件同时也会触发失焦事件里的onChange，此时e.detail.value获取到的依然是输入值的值而不是空，导致点击两次才会清空value

```js
const [val, setVal] = useStae('')
// setVal是异步的
onChange = (value) => {
   setVal(value)
   return value
} 
```
组件源码问题
```js
  onBlur = event => {
    this.props.onBlur(event.target.value, event)
    // fix # 583 AtInput 不触发 onChange 的问题
    this.props.onChange(event.target.value, event)
  }
```

**Comment by sunbohao** [comment]
还是没有解决呀
```js
if (!event || event.type === 'input'){
```
只能这样做一下判断了

**Comment by pengtaoman** [comment]
private handleClearValue = (event: ITouchEvent): void => {
    this.inputClearing = true
    this.props.onChange?.('', event)
  }

          {clear && value && (
            <View className='at-input__icon' onTouchEnd={this.handleClearValue}>
              <Text className='at-icon at-icon-close-circle at-input__icon-close'></Text>
            </View>
          )}

这段源码不生效
