### ISSUE TITLE
严重错误 prop type `name` is invalid Taro 1.0.4 Taro-UI 1.2.2

### ISSUE THREAD

**Issue by upbill** [NervJS/taro-ui#85]
### 重现步骤
Failed prop type: AtInput: prop type `name` is invalid;
Failed prop type: Invalid prop `maxlength` of type `string` supplied to `AtInput`, expected `number`.
### 依赖的版本号
Taro 1.0.4
Taro-UI 1.2.2

**Comment by jimczj** [comment]
请展示代码

**Comment by jimczj** [comment]
name 的错误确实是bug，maxlength 需要传数字 `{100}`，而不是字符串`‘100’`

**Comment by upbill** [comment]
<AtInput name='verifyCode' editable title='验证码' type='text' maxlength='6' placeholder='输入短信验证码' value={this.state.verifyCode} onChange={this.handleInput}>

<AtInput editable  border title='手机号' type='phone' clear placeholder='请输入手机号码' value={this.state.mobile} onChange={this.handleInput}>

必须加editable 否则 input disabled状态

**Comment by canaanjin** [comment]
同样遇到了`prop type 'name' is invalid `的错误
目前还不知道会有什么影响
希望可以尽快解决
还有希望可以出一个类似小程序中的`Picker`的组件
