### ISSUE TITLE
Taro UI 是否能够支持Taro 文档提到的外部样式类？

### ISSUE THREAD

**Issue by arvinxx** [NervJS/taro-ui#860]
### 这个功能解决了什么问题？

taro ui 针对 page 可以采用全局样式类的方式进行样式覆盖。而当其组件以组件被使用时，我们无法采用全局样式类的方式覆盖原有样式。

相关问题 ： https://github.com/NervJS/taro-ui/issues/517 、 https://github.com/NervJS/taro-ui/issues/66

> P.S. addGlobalClass 这个 API 只对 Page 上的 class 起作用。换言之，如果在自定义的组件中使用 taro-ui，是无法在自定义组件内部通过 全局样式类 的方式去更改组件样式的。

官方问题解释

> #### 自定义样式为什么没有生效（H5 生效，微信小程序没生效）？
> taro-ui 自定义样式覆盖小程序组件样式使用到了 globalClass 这个微信小程序特性，由于微信小程序的限制，自定义的样式需要在 page 页面内使用，不能基于第三方组件再进行一层封装，这样做样式会无效。并且确保小程序调试基础库在 v2.2.3 以上。

所以是否有可能利用组件的外部样式类实现自定义组件中的taro-ui 样式覆盖？从而满足三方组件封装的需求

### 你期望的功能是怎样的？

约定一个 props 字段 `component-style` 用于接入taro UI 作为第三方组件封装时需要引入或覆盖的样式，例如下述所示

```jsx
/* AtInput.js */
export default class AtInput extends Component {
  static externalClasses = ['component-style']

  render () {
    return <View className="component-style">这段文本的颜色由组件外的 class 决定</View>
  }
}
/* MyInput.js */
export default class MyPage extends Component {
  render () {
    return <AtInput component-style="red-text" />
  }
}
/* MyInput.scss */
.red-text {
  color: red;
}
```

**Comment by Garfield550** [comment]
Taro UI 基于 Taro 2 及以下的版本支持到今年 6 月结束，所以这种需要重构大部分组件的功能暂时不计划在内了。

Taro UI  3 会基于 Taro 3，Taro 3 也不支持外部样式类。

**Comment by shineSnow** [comment]
不要做KPI项目啊
