### ISSUE TITLE
AtInputNumber input无法触发change事件

### ISSUE THREAD

**Issue by streamBamboo** [NervJS/taro-ui#862]
![微信图片_20191119180318](https://user-images.githubusercontent.com/29224540/69137031-eb0dbc80-0af6-11ea-96c2-1b89851fc044.png)
![微信图片_20191119180324](https://user-images.githubusercontent.com/29224540/69137033-eba65300-0af6-11ea-94ed-3cb31bc88607.png)
![微信图片_20191119180329](https://user-images.githubusercontent.com/29224540/69137034-eba65300-0af6-11ea-96cd-81862731b08f.png)

根据一图 AtInputNumber设置了最大值限制,在input框直接输入并没有触发change事件,二图是change事件,三图显示的是结果

**Comment by tl1994** [comment]
AtTextarea, AtInput的onChange事件好像也不行了

**Comment by Garfield550** [comment]
微信开发者工具基础库版本是 2.9.3 吗？

**Comment by tl1994** [comment]
嗯，对的

**Comment by streamBamboo** [comment]
@Garfield550 对

**Comment by tl1994** [comment]
才试了下，微信开发工具低版本基础库，就没有问题

**Comment by streamBamboo** [comment]
@tl1994 .....

**Comment by Garfield550** [comment]
是的，最近微信基础库 2.9.3 出现 input 事件无法触发的问题。

**Comment by streamBamboo** [comment]
好吧   那我关闭issue吧

**Comment by dreamthen** [comment]
@Garfield550 麻烦问一下，咱这个2.9.3的基库，什么时候能兼容？

**Comment by Garfield550** [comment]
@dreamthen 基础库问题需要等微信修复，不属于 Taro 和 Taro UI 的范围

**Comment by dreamthen** [comment]
@Garfield550 好的，谢谢
