### ISSUE TITLE
AtTextarea组件的onChange事件无法触发

### ISSUE THREAD

**Issue by XSnowHoly** [NervJS/taro-ui#870]
**问题描述**

按照官方文档使用AtTextarea组件无法触发onChange事件

**复现步骤**

```js
// 这里可以贴代码

function Address() {
const [addressDetail, setAddressDetail] = useState('');

function addressDetailChange(event) {
    console.log('详细地址修改', event);
    setAddressDetail(event.target.value);
  }

return (
   <View> 
     <AtTextarea
          value={addressDetail}
          onChange={addressDetailChange}
          maxLength={200}
          placeholder='填写详细地址...'
      />
  </View>
)
}

```

**期望行为**

可以正常触发onChange事件

**报错信息**

![image](https://user-images.githubusercontent.com/25945988/69517155-dc0f8a00-0f8e-11ea-81b4-7c9553e3b410.png)

**系统信息**

Taro v1.3.25
Taro UI v2.2.4
平台 weapp

**补充信息**

**Comment by yanaice** [comment]
same here : 同样在这里

"taro-ui": "2.2.2"
"@tarojs/taro": "1.3.19",

**Comment by zhangfu-git** [comment]
@yanaice  微信调试基础库设置为2.9.4，正常触发onChange
