### ISSUE TITLE
Picker 组建导入项目后，没有样式

### ISSUE THREAD

**Issue by remainsu** [NervJS/taro-ui#876]
Picker 组建按照官网上的方式导入到项目之后，没有任何样式。  需要怎么处理呢？

**Comment by wleven** [comment]
遇到同样问题，全局引入样式后 picker 没有样式

**Comment by wleven** [comment]
@remainsu 老哥解决了吗

**Comment by remainsu** [comment]
@wleven    有人告诉我，这个就是没有样式，需要自己写。   我已经放弃taro了  。。。。

**Comment by wleven** [comment]
@remainsu 好吧 谢老哥

**Comment by yoonzm** [comment]
还要再引入一遍组件的样式才起作用

**Comment by MrChen2016-08-27** [comment]
我查看 Wxml 然后解决了。
可以把input组件相关的class放置在 picker 中的 View 上来达到表单样式统一协调：

`
<Picker mode='selector'
                                    range={typeSelector}
                                    value={form.type}
                                    onChange={(e) => this.onChangeFormField('type', e.detail.value)}>
                                    <View className='at-input picker'>
                                        <Text className="at-input__title picker-label">样品类型</Text>
                                        <Text className="at-input__input">xxxxx</Text>
                                    </View>
</Picker>
`

然后再指定 '.picker-label' 的样式，这里我用的是 less

`
.picker{
    .picker-label{
        display: inline-block;
    }
}
`

**Comment by liyanging** [comment]
> @wleven 有人告诉我，这个就是没有样式，需要自己写。 我已经放弃taro了 。。。。

不支持less。真心用起来不爽啊
