### ISSUE TITLE
QQ 小程序部分组件表现异常

### ISSUE THREAD

**Issue by arvinxx** [NervJS/taro-ui#880]
### Taro UI 版本信息

2.2.4

### 问题描述

将原本正常的微信小程序直接移植到 QQ 上，部分 Taro-UI 组件报错。目前会报错的组件有Rate、List（我自己用到的，其他不确定）

### 复现步骤

 1. 运行 taro build --type qq 
2. 打开 QQ 小程序开发者工具查看

### 复现代码

无需复现代码，个人认为是兼容性问题

### 报错信息
```
VM20:202 thirdScriptError
nextTick is not defined; [Component] Property Observer Error @ npm/taro-ui/dist/weapp/components/rate/index#observer
ReferenceError: nextTick is not defined
    at H.observer (http://127.0.0.1:56685/appservice/npm/@tarojs/taro-qq/dist/index.js:1:24894)
    at Function.r.safeCallback (http://127.0.0.1:56685/appservice/__dev__/QLogic.js:1:575057)
    at e.protoFunc.<anonymous> (http://127.0.0.1:56685/appservice/__dev__/QLogic.js:1:666287)
    at r.doUpdates (http://127.0.0.1:56685/appservice/__dev__/QLogic.js:1:679701)
    at t.applyProperties (http://127.0.0.1:56685/appservice/__dev__/QLogic.js:1:737581)
    at Function.value (http://127.0.0.1:56685/appservice/__dev__/QLogic.js:1:763889)
    at d.value (http://127.0.0.1:56685/appservice/__dev__/QLogic.js:1:762982)
    at http://127.0.0.1:56685/appservice/__dev__/QLogic.js:1:765911
    at Array.forEach (<anonymous>)
    at http://127.0.0.1:56685/appservice/__dev__/QLogic.js:1:765889VM20:202 thirdScriptError
```
### 系统信息

👽 Taro v1.3.26

  Taro CLI 1.3.26 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.26 => 1.3.26 
      @tarojs/components: 1.3.26 => 1.3.26 
      @tarojs/plugin-babel: 1.3.25 => 1.3.25 
      @tarojs/plugin-csso: 1.3.25 => 1.3.25 
      @tarojs/plugin-less: 1.3.25 => 1.3.25 
      @tarojs/plugin-uglifyjs: 1.3.25 => 1.3.25 
      @tarojs/redux: 1.3.26 => 1.3.26 
      @tarojs/redux-h5: 1.3.26 => 1.3.26 
      @tarojs/router: 1.3.26 => 1.3.26 
      @tarojs/taro: 1.3.26 => 1.3.26 
      @tarojs/taro-alipay: 1.3.26 => 1.3.26 
      @tarojs/taro-h5: 1.3.26 => 1.3.26 
      @tarojs/taro-qq: ^1.3.26 => 1.3.26 
      @tarojs/taro-swan: 1.3.26 => 1.3.26 
      @tarojs/taro-tt: 1.3.26 => 1.3.26 
      @tarojs/taro-weapp: 1.3.26 => 1.3.26 
      @tarojs/webpack-runner: 1.3.25 => 1.3.25 
      eslint-config-taro: 1.3.25 => 1.3.25 
      eslint-plugin-taro: 1.3.25 => 1.3.25 
      nerv-devtools: ^1.4.0 => 1.5.5 
      nervjs: ^1.4.0 => 1.5.5 
      stylelint-config-taro-rn: 1.3.25 => 1.3.25 
      stylelint-taro-rn: 1.3.25 => 1.3.25

**Comment by xhwgood** [comment]
老哥，我taro-ui也是V2.2.4，微信正常，QQ就有些不正常，是不是都只能额外写个QQ的版本？
