### ISSUE TITLE
没有类似小程序中的Picker组件吗

### ISSUE THREAD

**Issue by canaanjin** [NervJS/taro-ui#89]

**Comment by koppthe** [comment]
用基础组件库的 Picker https://nervjs.github.io/taro/docs/components/forms/picker.html

**Comment by canaanjin** [comment]
@koppthe 
可是在form表单中改css才勉强做到这种效果
![image](https://user-images.githubusercontent.com/12317236/46191048-8c044b80-c328-11e8-8c4a-ebaa9ad785a6.png)
![image](https://user-images.githubusercontent.com/12317236/46190989-5b241680-c328-11e8-9352-e3bc3cf3f073.png)
![image](https://user-images.githubusercontent.com/12317236/46191009-6a0ac900-c328-11e8-8dae-a4728a9d6a5a.png)
