### ISSUE TITLE
taro-ui2.2.4日历bug

### ISSUE THREAD

**Issue by wxquan** [NervJS/taro-ui#890]
月份左右滑动样式错误

**Comment by wxquan** [comment]
问题描述
   日历组件切换月份，UI乱掉了。
复现步骤
   添加日历组件，npm run dev:h5 左右进行滑动，发现页面UI乱了。
期望行为
   切换月份时，UI不变。
报错信息

系统信息
    操作系统及版本：MacOs 版本Mojave
    Node版本：v12.13.1
    Npm版本：6.12.1
    taro-ui版本: 2.2.4
补充信息
    2.2.3版本看应该是没有问题

**Comment by Bruce-zxy** [comment]
操作系统：Window 7
浏览器版本：Chrome 79
Taro-CLI 版本：1.3.27
Taro-UI 版本：2.2.4

【复现步骤】
1、按正常操作从Taro-UI导入AtCalendar组件
![image](https://user-images.githubusercontent.com/22904758/70859486-50ff2f80-1f4f-11ea-9590-16d62a6603cd.png)

2、按正常操作调用AtCalendar组件
![image](https://user-images.githubusercontent.com/22904758/70859477-2b722600-1f4f-11ea-994f-41f03c5c64e9.png)

3、保存文件以后即可在浏览器中查看到AtCalendar组件，并且发现在【左右滑动】以及【点击左右箭头】后日历样式会发生异常
![test8](https://user-images.githubusercontent.com/22904758/70859503-9a4f7f00-1f4f-11ea-9cea-4654c4647cc0.gif)

**Comment by ZhangJianFFFF** [comment]
![image](https://user-images.githubusercontent.com/50258938/70891183-b4f22880-2021-11ea-847f-8d8267a081ec.png)
这是官方taroui的组件示例也有问题

**Comment by ZhangJianFFFF** [comment]
这是官方taroui的组件示例也有问题
![image](https://user-images.githubusercontent.com/50258938/70891367-11edde80-2022-11ea-8860-eda6c76f84fa.png)

**Comment by zongyan86** [comment]
解决了吗？啥时候升级？

**Comment by ZhangJianFFFF** [comment]
> 解决了吗？啥时候升级？

没有  回退到taro-ui2.2.2版本就没问题

**Comment by zongyan86** [comment]
> > 解决了吗？啥时候升级？
> 
> 没有 回退到taro-ui2.2.2版本就没问题

额，2.2.3和2.2.4解决了不少bug，蛋疼。

**Comment by ZhangJianFFFF** [comment]
> > > 解决了吗？啥时候升级？
> > 
> > 
> > 没有 回退到taro-ui2.2.2版本就没问题
> 
> 额，2.2.3和2.2.4解决了不少bug，蛋疼。

你可以试一下2.2.3  我是直接退到2.2.2没试过2.2.3不知道有没有问题

**Comment by zongyan86** [comment]
不行的，我本来就是2.2.3




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ZhangJianFFFF"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月14日(星期二) 下午3:27
收件人:&nbsp;"NervJS/taro-ui"<taro-ui@noreply.github.com&gt;;
抄送:&nbsp;"许宗彦"<378588579@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [NervJS/taro-ui] taro-ui2.2.4日历bug (#890)



   
解决了吗？啥时候升级？
  
没有 回退到taro-ui2.2.2版本就没问题
  
额，2.2.3和2.2.4解决了不少bug，蛋疼。
  
你可以试一下2.2.3  我是直接退到2.2.2没试过2.2.3不知道有没有问题

**Comment by ZhangJianFFFF** [comment]
> 不行的，我本来就是2.2.3
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"ZhangJianFFFF"<notifications@github.com&gt;; 发送时间:&nbsp;2020年1月14日(星期二) 下午3:27 收件人:&nbsp;"NervJS/taro-ui"<taro-ui@noreply.github.com&gt;; 抄送:&nbsp;"许宗彦"<378588579@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [NervJS/taro-ui] taro-ui2.2.4日历bug (#890) 解决了吗？啥时候升级？ 没有 回退到taro-ui2.2.2版本就没问题 额，2.2.3和2.2.4解决了不少bug，蛋疼。 你可以试一下2.2.3 我是直接退到2.2.2没试过2.2.3不知道有没有问题 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

那就没有办法了o((⊙﹏⊙))o
