### ISSUE TITLE
AtSteps 一直报key 没有正确设置， 看官方文档 也没有讲key 如何设置。

### ISSUE THREAD

**Issue by anryzhang** [NervJS/taro-ui#897]
**这个功能解决了什么问题？**
AtSteps 一直报key 没有正确设置， 看官方文档 也没有讲key 如何设置。
当前taro 版本是 1.3.29；报错如下：
./npm/taro-ui/dist/weapp/components/steps/index.wxml
 wx:key="$original.title" does not look like a valid key name (did you mean wx:key="title" ?)

**你期望的功能是怎样的？**
应该如何传key?

问题出现的版本环境：
平台： 微信小程序
开发者工具版本：1.02.1911180
tarojs/Cli: 1.3.29
nodejs :v10.16.0
yarn : 1.19.1

代码片段： 官方1.3.29的代码片段就会报如上问题

**Comment by Garfield550** [comment]
需要等 Taro 修复

**Comment by anryzhang** [comment]
AtTabs  也有如上问题

**Comment by anryzhang** [comment]
问题出现的版本环境： 
平台： 微信小程序
开发者工具版本：1.02.1911180
tarojs/Cli: 1.3.29
nodejs :v10.16.0
yarn : 1.19.1

**Comment by Garfield550** [comment]
需要等 Taro 修复，建议等待

**Comment by zcSkr** [comment]
在Taro里面你用的key是 obj.key 取值的方式，你写let key = obj.key再赋值就不报警告了。

**Comment by Garfield550** [comment]
是的，不过最好还是由编译器自动解决这个问题。所以等 Taro 这边修复吧。

**Comment by anryzhang** [comment]
> 在Taro里面你用的key是 obj.key 取值的方式，你写let key = obj.key再赋值就不报警告了。

const steps = [
    {title:'步骤1' },
    {title:'步骤2' },
    {title:'步骤3' }
  ];

<AtSteps
            className='stepsBox'
            current={current}
            onChange={(e)=>setCurrent(e)}
            items={steps}
          />
如上代码， 你说的这个， 没有在map 里，key是加不上的吧？谢谢

**Comment by Garfield550** [comment]
试一下 Taro 1.3.33 吧
