### ISSUE TITLE
小程序怎么自定义样式？

### ISSUE THREAD

**Issue by JieSwift** [NervJS/taro-ui#9]
如题，taro-ui在小程序中怎么自定义样式。

**Comment by jimczj** [comment]
可以自定义的部分样式，`props`会提供参数；能够嵌套的组件，自己在子组件定义样式。如果您觉得哪些组件需要开放自定义样式参数，可以提出来，我们会审核看看是否合理来决定是否开放接口

**Comment by JieSwift** [comment]
比如Tabs header只有那一种样式，满足不了我们现在的需求。不可以用className覆盖之前的样式么。

**Comment by jimczj** [comment]
现在目前不可以，我们将进一步尝试，如果方案可行，将会放出此功能

**Comment by JieSwift** [comment]
好的。

**Comment by hyhweb** [comment]
在小程序里面，AtForm组件的padding-left样式怎样重置？

**Comment by jimczj** [comment]
@hyhweb 近期将会增加样式覆盖功能

**Comment by hyhweb** [comment]
最好className也可以实现对组件的样式重置或者追加。

**Comment by jimczj** [comment]
@hyhweb 请展示代码，检查是否在 js 文件 引入 scss 文件

**Comment by hyhweb** [comment]
确实是没有在js文件引入scss导致的。非常多谢。

**Comment by chinawzc** [comment]
AtNoticebar的样式需要定制化

**Comment by koppthe** [comment]
@chinawzc 参考「自定义主题」一章的文档试试吧
