### ISSUE TITLE
image-picker 组件 length 为 0 的时候内存泄漏了

### ISSUE THREAD

**Issue by Go7hic** [NervJS/taro-ui#901]
**问题描述**
image-picker组件 length设置为 0 的时候内存泄漏了。
导致内存泄漏的代码在 https://github.com/NervJS/taro-ui/blob/dev/src/components/image-picker/index.js#L12
```
Math.ceil(length / col)
```
`Math.ceil(1 / 0) ` 凉凉...

**复现步骤**

```js
// 这里可以贴代码
```

**期望行为**

你们比我更专业 ，怎么改你们说了算

**报错信息**

**系统信息**

**补充信息**

**Comment by SyuTingSong** [comment]
`Math.ceil(1/0)`会得到`Infinity`
