### ISSUE TITLE
AtImagePickerProps与taro hooks兼容性问题

### ISSUE THREAD

**Issue by yeeing** [NervJS/taro-ui#902]
**问题描述**

AtImagePickerProps与taro hooks兼容性问题
**复现步骤**

```js
// 这里可以贴代码
const [state,setState]=Taro.useState([])
<AtImagePicker onChange={(files)=>setState(files)}></AtImagePicker>
```

**期望行为**

是否应当将类型定义修改，还是我的使用方法有误。
**报错信息**

类型“Object[]”的参数不能赋给类型“SetStateAction<never[]>”的参数。
  不能将类型“Object[]”分配给类型“never[]”。
    不能将类型“Object”分配给类型“never”。
      "Object" 类型可分配给极少数其他类型。是否想要改用“任意”类型?
**系统信息**

**补充信息**

interface AtImagePickerProps extends AtComponent {
  files: File[]

  mode?: 'scaleToFill' | 'aspectFit' | 'aspectFill' | 'widthFix' | 'top' | 'bottom' | 'center' | 'left' | 'right' | 'top left' | 'top right' | 'bottom left' | 'bottom right'

  showAddBtn?: boolean

  multiple?: boolean

  length?: number

  count?: number

  sizeType?: string[]

  sourceType?: string[]

  onChange: (files: Array<Object>, operationType: string, index: number) => void

  onImageClick?: (index: number, file: Object) => void

  onFail?: (message: string) => void
}

**Comment by Garfield550** [comment]
组件定义里的 `Object` 类型应该改为更确定的类型，但是 `useState` 在 TS 下最好显示指定类型，比如 `const [isOpend, setIsOpend] = useState<boolean>(false);`，特别是在 State 类型为数组或者是复杂对象这种难以自动推导的类型上。

**Comment by yeeing** [comment]
> 组件定义里的`Object`类型应该替换为更确定的类型，但是`useState`在TS下最好显示指定类型，例如`const [isOpend, setIsOpend] = useState<boolean>(false);`，特别是在State类型为数组或是复杂对象这种难以自动推导的类型上。

如果使用const state=Taro.useState<Object[]>()时
不能将类型“Object[]”分配给类型“File[]”。
  "Object" 类型可分配给极少数其他类型。是否想要改用“任意”类型?
    Property 'url' is missing in type 'Object' but required in type 'File'.
因为 props.files使用的interface是files: File[]所以定义类型也会报错。。。。。。

**Comment by Garfield550** [comment]
因为确实 `onChange` 的首个参数错了，应该从 `Object[]` 改成 `File[]`
