### ISSUE TITLE
AtInput 在失去焦点时会触发onChane事件

### ISSUE THREAD

**Issue by jianhao** [NervJS/taro-ui#903]
**问题描述**
AtInput 在失去焦点时会触发onChane事件

**复现步骤**
1、在输入框输入内容
2、失去焦点，会发现onChange事件又被触发了
```js
import Taro from '@tarojs/taro'
import { AtInput } from 'taro-ui'

export default class Index extends Taro.Component {
  constructor () {
    super(...arguments)
    this.state = {
      value: ''
    }
  }
  handleChange (value) {
    console.log('change事件', value);
    this.setState({
      value
    })
    // 在小程序中，如果想改变 value 的值，需要 `return value` 从而改变输入框的当前值
    return value
  }
  render () {
    return (
      <AtInput
        name='value'
        title='标准五个字'
        type='text'
        placeholder='标准五个字'
        value={this.state.value}
        onChange={this.handleChange.bind(this)}
      />
    )
  }
}
```

**期望行为**
失去焦点时不触发onChange事件

**系统信息**
⇒  taro info
👽 Taro v1.3.18
   Taro-UI v2.2.2

  Taro CLI 1.3.18 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.18 => 1.3.18 
      @tarojs/components: 1.3.18 => 1.3.18 
      @tarojs/plugin-babel: 1.3.18 => 1.3.18 
      @tarojs/plugin-csso: 1.3.18 => 1.3.18 
      @tarojs/plugin-less: 1.3.18 => 1.3.18 
      @tarojs/plugin-sass: ^1.3.18 => 1.3.18 
      @tarojs/plugin-uglifyjs: 1.3.18 => 1.3.18 
      @tarojs/redux: 1.3.18 => 1.3.18 
      @tarojs/redux-h5: 1.3.18 => 1.3.18 
      @tarojs/router: 1.3.18 => 1.3.18 
      @tarojs/taro: 1.3.18 => 1.3.18 
      @tarojs/taro-alipay: 1.3.18 => 1.3.18 
      @tarojs/taro-h5: 1.3.18 => 1.3.18 
      @tarojs/taro-swan: 1.3.18 => 1.3.18 
      @tarojs/taro-tt: 1.3.18 => 1.3.18 
      @tarojs/taro-weapp: 1.3.18 => 1.3.18 
      @tarojs/webpack-runner: 1.3.18 => 1.3.18 
      eslint-config-taro: 1.3.18 => 1.3.18 
      eslint-plugin-taro: 1.3.18 => 1.3.18 
      nerv-devtools: ^1.4.0 => 1.4.4 
      nervjs: ^1.4.0 => 1.4.4 
      stylelint-config-taro-rn: 1.3.18 => 1.3.18 
      stylelint-taro-rn: 1.3.18 => 1.3.18 

**补充信息**
虽然之前有同学已经提出了这个问题 https://github.com/NervJS/taro-ui/issues/767 ，但似乎官方的同学没有重视，所以我在这里再次提出希望能得到关注，尽快解决这个bug。

**Comment by jianhao** [comment]
可以通过onChange事件的event的type来判断是否是blur事件，然后做些处理，入下
```
  handleChange = (value, e) => {
    if(e.type === 'blur')return // 失焦不要触发onchange事件
    this.setState({ value })
    return value
  }

```

**Comment by Garfield550** [comment]
这个是为了解决 #583 刻意做的行为，如果有什么更好的解决方案可以一起来讨论下，暂时就关闭了。

**Comment by FloaJa** [comment]
哦, 原来根源在这呢, 我说onChange怎么莫名其妙的触发

**Comment by ghost** [comment]
> 可以通过onChange事件的event的type来判断是否是blur事件，然后做些处理，如下：
> 
> ```
>   handleChange = (value, e) => {
>     if(e.type === 'blur')return // 失焦不要触发onchange事件
>     this.setState({ value })
>     return value
>   }
> ```

e 是输入的值，哪有type?
