### ISSUE TITLE
按照文档使用，可是经常报这个错误，请解释一下这是为什么？ 

### ISSUE THREAD

**Issue by fumengdegithub** [NervJS/taro-ui#906]
jsEnginScriptError . Component is not found in path

**Comment by lsqy** [comment]
确认下你的`taro-cli`的版本是否与`taro-ui`依赖的`taro`的版本号一致，否则就会出现运行不起来的问题，具体可参考[环境及依赖检测](http://taro-docs.jd.com/taro/docs/GETTING-STARTED.html#%E7%8E%AF%E5%A2%83%E5%8F%8A%E4%BE%9D%E8%B5%96%E6%A3%80%E6%B5%8B)
