### ISSUE TITLE
编译小程序时taro-ui报错，无法找到正确路径

### ISSUE THREAD

**Issue by s2265681** [NervJS/taro-ui#907]
**问题描述**

**复现步骤**

```js
// 这里可以贴代码
```

**期望行为**

**报错信息**

VM836:1 jsEnginScriptError
Component is not found in path "npm/taro-ui/dist/weapp/components/button/index" (using by "pages/me/me");onAppRoute
Error: Component is not found in path "npm/taro-ui/dist/weapp/components/button/index" (using by "pages/me/me")

**系统信息**

**补充信息**

**Comment by Garfield550** [comment]
重复 Issue #908
