### ISSUE TITLE
taro编译小程序总报错，不能使用taro-ui的组件，提示找不到路径

### ISSUE THREAD

**Issue by s2265681** [NervJS/taro-ui#908]
**问题描述**

taro编译小程序总报错，不能使用taro-ui的组件，提示找不到路径
**复现步骤**

```js
// 这里可以贴代码
```

**期望行为**

**报错信息**

![image](https://user-images.githubusercontent.com/41536679/71538214-40dd4c00-2962-11ea-8815-27f2c5e0f251.png)

**系统信息**

**补充信息**

**Comment by Garfield550** [comment]
Taro CLI 版本多少

**Comment by s2265681** [comment]
> Taro CLI 版本多少
是这个吗
taro -v
Taro v2.0.0-beta.12

**Comment by Garfield550** [comment]
beta 版有很多问题，等 Taro 发布正式版吧，我看到你也在 Taro 那边也提了 Issue，先关注一下那边等说法吧。

**Comment by Garfield550** [comment]
如果着急的话使用 Taro 1.3.32 及以上版本先开发

**Comment by s2265681** [comment]
> 如果着急的话使用 Taro 1.3.32 及以上版本先开发
这个版本怎么切换呢

**Comment by Garfield550** [comment]
推荐你使用给你的项目添加一个开发依赖的方式，这样可以避免受到全局安装的 CLI 影响。

1. 在你的项目里运行 `npm install @tarojs/cli@1.3.33 --save-dev` 或者 `yarn add -D @tarojs/cli@1.3.33`

2. 之后的开发都使用 `npm run dev:weapp` 或者 `yarn dev:weapp` 来编译。

如果你想让全局版本都降级的话，需要运行 `npm install -g @tarojs/cli@1.3.33` 或者 `yarn global add @tarojs/cli@1.3.33`

**Comment by s2265681** [comment]
> 推荐你使用给你的项目添加一个开发依赖的方式，这样可以避免受到全局安装的 CLI 影响。
> 
> 1. 在你的项目里运行 `npm install @tarojs/cli@1.3.33 --save-dev` 或者 `yarn add -D @tarojs/cli@1.3.33`
> 2. 之后的开发都使用 `npm run dev:weapp` 或者 `yarn dev:weapp` 来编译。
> 
> 如果你想让全局版本都降级的话，需要运行 `npm install -g @tarojs/cli@1.3.33` 或者 `yarn global add @tarojs/cli@1.3.33`

好的  解决了  非常的感谢
问题就是出在我用的新版本太新了吗，用的测试版

**Comment by Garfield550** [comment]
测试版还不稳定，不过欢迎提出各种测试版的问题
