### ISSUE TITLE
NavBar 导航栏 以及 TabBar 标签栏 问题

### ISSUE THREAD

**Issue by wjjesse** [NervJS/taro-ui#91]
### 重现步骤
在页面中引用 NavBar 导航栏 以及 TabBar 标签栏 当NavBar固定在顶部, TabBar固定在底部的时候,中间的视图会被这两个组件遮盖住

### 依赖的版本号

"@tarojs/taro": "^1.0.3"
"taro-ui": "^1.2.2"

### 预期结果
希望在使用 NavBar 导航栏 以及 TabBar 标签栏 并NavBar固定在顶部, TabBar固定在底部的时候,中间的视图不会被这两个组件遮盖住

**Comment by koppthe** [comment]
这个需要你自己处理一下的，组件只是 fixed 了，底下的视图区域需要自己设置一个 margin 或 padding。
