### ISSUE TITLE
AtInput 的placeholder不显示 title不生效

### ISSUE THREAD

**Issue by s2265681** [NervJS/taro-ui#912]
**问题描述**

**复现步骤**

```js
// 这里可以贴代码
```

**期望行为**

**报错信息**

**系统信息**

**补充信息**

**Comment by s2265681** [comment]
已解决   又是版本问题

**Comment by cjzgitHub** [comment]
请问使用的哪个版本的taro-ui.   我这边有一个苹果12也不现实input的placeholder
