### ISSUE TITLE
H5端的Calendar组件切换后显示有问题。

### ISSUE THREAD

**Issue by hsl947** [NervJS/taro-ui#915]
![image](https://user-images.githubusercontent.com/18359814/71609536-3d48ff80-2bc4-11ea-8631-2ba2605592c5.png)

连续点击上一月下一月，日期没清空，一直累加了。
官方demo也有这个问题。

**Comment by q364237398** [comment]
遇到和你一样的问题，看源码中listGroup[1].list 的值又没问题，所以不知道为啥会没清楚掉

**Comment by q364237398** [comment]
[https://github.com/NervJS/taro-ui/pull/913/commits/9adebbcb00854b835d048dff70e9a291e0443f85](url)

**Comment by q364237398** [comment]
https://github.com/NervJS/taro-ui/pull/913#issue-357963120
