### ISSUE TITLE
AtNoticebar speed参数无效

### ISSUE THREAD

**Issue by rowthan** [NervJS/taro-ui#919]
### Taro UI 版本信息

2.2.4

### 问题描述

speed参数无效「字节跳动小程序」。看了下源码，其中没有针对 字节跳动 做speed的处理？

### 复现步骤

<AtNoticebar marquee icon='volume-plus' speed={100}>
          {broadcastContent}
        </AtNoticebar>
其中 broadcastContent 为动态内容，会不断增加

### 复现代码

`
<AtNoticebar marquee icon='volume-plus' speed={100}>
          {broadcastContent}
        </AtNoticebar>
`

### 报错信息

动画速度会越来越快

### 系统信息

Taro v2.0.0-beta.13

**Comment by Garfield550** [comment]
应该是还没有适配字节跳动小程序，如果感兴趣研究一下的话，欢迎提一个 PR。
