### ISSUE TITLE
现在支持RN吗？

### ISSUE THREAD

**Issue by hellotiger** [NervJS/taro-ui#92]

**Comment by koppthe** [comment]
暂时还不支持，得10月底才开始适配

**Comment by xueyida** [comment]
你好，什么时候支持RN,最近我们可能要用taro-ui,或者有身体替代ui库吗，要在手机端、ios、安卓使用

**Comment by jimczj** [comment]
@xueyida 目前暂时没有计划，市面上目前没有看到其他可替代 ui 库

**Comment by kenberkeley** [comment]
![image](https://user-images.githubusercontent.com/13287948/48754451-d204dc80-ece5-11e8-88e8-6b9f4a7808a3.png)

所以目前还是在调研状态？

**Comment by jimczj** [comment]
不支持，RN 不准备支持了

**Comment by xueyida** [comment]
@jimczj  不是开玩笑的吧?  -_-！！！

**Comment by kenberkeley** [comment]
呃。。。这样的话 taro 支持 RN 的意义就少了很多。。。因为目前小程序和 H5 都用了 taro-ui，本来还指望着 RN 也能支持。。。

**Comment by kenberkeley** [comment]
目前还不存在同时支持 H5/小程序/RN 的 UI 组件库，希望 taro-ui 可以继续努力

**Comment by hezll** [comment]
19年快过去半年了。支持rn的计划开始了么

**Comment by hezll** [comment]
哪怕不支持rn，跟隔壁dcloud那样，支持web app 也行啊。

**Comment by zhangzhenfei** [comment]
哪怕不支持rn，跟隔壁dcloud那样，支持web app 也行啊。

**Comment by smartsimba** [comment]
19年都过完了，还不支持RN呢。官方大大什么时候支持RN啊？？
