### ISSUE TITLE
Taro-ui 组件绑定事件 event对象找不到

### ISSUE THREAD

**Issue by sunflower-tc** [NervJS/taro-ui#923]
### Taro UI 版本信息

2.0.2

### 问题描述

在使用AtInputNumber组件时候绑定了事件event对象，用来处理事件冒泡。更新项目时候，event对象找不到。

### 复现步骤

1.添加taro-ui
2.引入 AtInputNumber
3.onChange={this.handleChangeTest.bind(this)
4.方法中找不到event对象

### 复现代码

组件代码
<AtInputNumber
        min={0}
        max={10}
        step={1}
        value={this.state.count}
        onChange={this.handleChangeTest.bind(this)}
    />
绑定事件：
 handleChangeTest (value,e){
      console.log('value',value)
      console.log('e',e)
}

### 报错信息

e undefined
![image](https://user-images.githubusercontent.com/15952571/72048936-dda3d000-32f8-11ea-88ac-cf93551bdd4c.png)

### 系统信息

 Taro CLI 1.3.27 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.14.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.25 => 1.3.27 
      @tarojs/components: 1.3.25 => 1.3.27 
      @tarojs/plugin-babel: 1.3.25 => 1.3.27 
      @tarojs/plugin-csso: 1.3.25 => 1.3.27 
      @tarojs/plugin-sass: 1.3.25 => 1.3.27 
      @tarojs/plugin-uglifyjs: 1.3.25 => 1.3.27 
      @tarojs/redux: 1.3.25 => 1.3.27 
      @tarojs/redux-h5: 1.3.25 => 1.3.27 
      @tarojs/rn-runner: 1.3.25 => 1.3.27 
      @tarojs/router: 1.3.25 => 1.3.27 
      @tarojs/taro: 1.3.25 => 1.3.27 
      @tarojs/taro-alipay: 1.3.25 => 1.3.27 
      @tarojs/taro-h5: 1.3.25 => 1.3.27 
      @tarojs/taro-swan: 1.3.25 => 1.3.27 
      @tarojs/taro-tt: 1.3.25 => 1.3.27 
      @tarojs/taro-weapp: 1.3.25 => 1.3.27 
      @tarojs/webpack-runner: 1.3.25 => 1.3.27 
      eslint-config-taro: 1.3.25 => 1.3.27 
      eslint-plugin-taro: 1.3.25 => 1.3.27 
      nervjs: ^1.5.5 => 1.5.6

**Comment by Garfield550** [comment]
![image](https://user-images.githubusercontent.com/3471836/75168934-a3847580-5762-11ea-9d21-8253c893fdd6.png)
