### ISSUE TITLE
button组件在钉钉小程序异常

### ISSUE THREAD

**Issue by yuwanlin** [NervJS/taro-ui#925]
**问题描述**
下载taroui源码编译后再钉钉小程序上跑，button组件可以正常显示在钉钉小程序上，但是长按后背景色会变成灰色（微信小程序正常）。并且编译后的button在钉钉小程序中多出很多不需要的属性（微信小程序的属性）。

**期望**
期望长按button后背景不变成灰色。

**Comment by Garfield550** [comment]
Taro UI 还没有适配钉钉，如果有意向的话，可以帮忙适配一下，提一个 PR。

**Comment by yuwanlin** [comment]
> Taro UI 还没有适配钉钉，如果有意向的话，可以帮忙适配一下，提一个 PR。

好的。我关掉issue。
