### ISSUE TITLE
taro-ui目前兼容375设计图吗?后期有计划兼容375设计图吗??

### ISSUE THREAD

**Issue by yuckyb** [NervJS/taro-ui#928]
目前发现taro-ui不兼容375设计稿,后续会兼容吗?

**Comment by yanglongji** [comment]
刚好也碰到这个问题  可以参考 https://taro-ui.jd.com/#/docs/customizetheme
覆写一些  $hd 这个变量   他默认是2        375 的 这改成 1 就行

**Comment by dmwin72015** [comment]
> 刚好也碰到这个问题 可以参考 https://taro-ui.jd.com/#/docs/customizetheme
> 覆写一些 $hd 这个变量 他默认是2 375 的 这改成 1 就行

有的项目是less，这个怎么覆盖？？
