### ISSUE TITLE
Toast  不能通过修改isOpened值主动关闭，只能等待duration后才关闭

### ISSUE THREAD

**Issue by JveGuo** [NervJS/taro-ui#93]
### 重现步骤
Toast 轻提示 不能通过修改isOpened值主动关闭，只能等待duration后才关闭
### 依赖的版本号

node 8.12.0  taro 1.0.5 taro-ui 1.2.2
### 预期结果
数据加载完成 修改isOpened ，关闭loading toast 
### 实际结果
修改isOpened 不能能关闭toast

**Comment by SzHeJason** [comment]
[fix: 修复 types 缺少关键词 和 toast 无法自动关闭](https://github.com/NervJS/taro-ui/commit/bb0bfff3cd5366e62adb790ea555677a308b58b0) 这里应该修复了 建议更新试一下
