### ISSUE TITLE
AtForm里 AtInput与AtSwitch 字体大小不一致

### ISSUE THREAD

**Issue by eruca** [NervJS/taro-ui#936]
AtSwitch 里title字体的大小是被写死的28rpx，那么就和AtInput默认不一致，怎么解决？

**Comment by Garfield550** [comment]
https://github.com/NervJS/taro-ui/blob/dev/src/style/variables/default.scss#L406-L407

更改 `$at-switch-title-size` 变量。

**Comment by Garfield550** [comment]
在页面的样式文件里修改 AtSwitch 对应的全局变量可以修改字体大小，并且不会影响到其他页面。

```scss
$at-switch-title-size: 32px;
$at-switch-title-color: red;

@import "~taro-ui/dist/style/components/switch.scss";
```

![image](https://user-images.githubusercontent.com/3471836/77225050-abd7a100-6ba6-11ea-8e6f-a36b371c83f0.png)

**Comment by Garfield550** [comment]
我也做了一个示例项目，你可以参考下：https://github.com/Garfield550/taro-ui-troubleshooting/tree/issue-936

**Comment by yuezonglun** [comment]
> 在页面的样式文件里修改 AtSwitch 对应的全局变量可以修改字体大小，并且不会影响到其他页面。
> 
> ```css-scss
> $at-switch-title-size: 32px;
> $at-switch-title-color: red;
> 
> @import "~taro-ui/dist/style/components/switch.scss";
> ```
> 
> ![image](https://user-images.githubusercontent.com/3471836/77225050-abd7a100-6ba6-11ea-8e6f-a36b371c83f0.png)

我按需设置12px，依然没有起作用，switch还是那么大

**Comment by yuezonglun** [comment]
> > 在页面的样式文件里修改 AtSwitch 对应的全局变量可以修改字体大小，并且不会影响到其他页面。
> > ```
> > $at-switch-title-size: 32px;
> > $at-switch-title-color: red;
> > 
> > @import "~taro-ui/dist/style/components/switch.scss";
> > ```
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/3471836/77225050-abd7a100-6ba6-11ea-8e6f-a36b371c83f0.png)
> 
 @Garfield550  我按需设置12px，依然没有起作用，switch还是那么大

**Comment by Garfield550** [comment]
@yuezonglun 你按照我上面的示例项目的方式写了吗？

![image](https://user-images.githubusercontent.com/3471836/77411722-ce142d80-6df7-11ea-9cdb-17d67cd50ad5.png)

**Comment by Garfield550** [comment]
建议 clone 一下示例的仓库然后运行一下

**Comment by yuezonglun** [comment]
@Garfield550 你那是修改的title的字体和颜色，我需要修改的是Switch的大小
![image](https://user-images.githubusercontent.com/19408097/77413558-7fb45e00-6dfa-11ea-9c77-1f55e00642d9.png)

**Comment by Garfield550** [comment]
@yuezonglun 那麻烦一开始说清楚哟。新开一个 Issue 聊这个问题吧，这个是讲字体的。

**Comment by yuezonglun** [comment]
> 新开一个问题聊这个问题吧，这个是讲字体的。@yuezonglun那麻烦一开始说清楚哟。

https://github.com/NervJS/taro-ui/issues/990#
