### ISSUE TITLE
AtButton 支持 data-xxx

### ISSUE THREAD

**Issue by zhangxuyang-web** [NervJS/taro-ui#938]
**这个功能解决了什么问题？**

我在子组件中的分享按钮，要触发父组件的 onShareAppMessage 事件，子组件需同时传出分享的数据，原生 button 可使用属性 data-xxx 绑定数据，在 onShareAppMessage 的回调中拿到 dataset 等数据。
目前是拿不到数据的：
![image](https://user-images.githubusercontent.com/52990953/73604979-4a964700-45d3-11ea-90e3-d5690117a422.png)

**你期望的功能是怎样的？**

// component
<AtButton openType="share" data-share-info={ {xxx} }>分享</AtButton>
// father page
onShareAppMessage(res){
     const shareInfo = res.target,dataset.shareInfo
}

**补充信息**

**Comment by Garfield550** [comment]
这个问题似乎是 AtButton 没有把 `data-` 类属性传给内部的 Button 造成的，由于 `data-` 是不可确定的，所以一种方式是使用 rest property 语法，但是 Taro 2 暂时还不支持这种方式，所以可能暂时等 Taro 那边修复，建议先用 Button 顶替一下。

> this.props 不支持使用 rest property 语法，请把每一个 prop 都单独列出来

**Comment by Garfield550** [comment]
暂时先关闭掉了。
