### ISSUE TITLE
在支付宝小程序中使用Calendar 日历UI发生错位

### ISSUE THREAD

**Issue by lancerfox** [NervJS/taro-ui#939]
**问题描述**
在支付宝小程序中使用Calendar 日历UI发生错位
**复现步骤**
下载taro-ui-demo源码 或（重新创建新项目，安装taro-ui），正确编译，在支付宝开发工具上预览和iphonex支付宝中预览，左右滑动高度UI正常，点击日期切换按钮，高度不断的加大

**期望行为**
高度不会因为点击了日期转换按钮而不断的加大

**报错信息**

![image](https://user-images.githubusercontent.com/16282919/73645829-08443700-46b3-11ea-8ac9-d3b02446bdb7.png)

**系统信息**
操作系统：win10,
运行环境：支付宝小程序开发工具和真机iphoneX支付宝中
"dependencies": {
		"@tarojs/components": "2.0.2",
		"@tarojs/components-qa": "2.0.2",
		"@tarojs/router": "2.0.2",
		"@tarojs/taro": "2.0.2",
		"@tarojs/taro-alipay": "2.0.2",
		"@tarojs/taro-h5": "2.0.2",
		"@tarojs/taro-qq": "2.0.2",
		"@tarojs/taro-quickapp": "2.0.2",
		"@tarojs/taro-rn": "2.0.2",
		"@tarojs/taro-swan": "2.0.2",
		"@tarojs/taro-tt": "2.0.2",
		"@tarojs/taro-weapp": "2.0.2",
		"mini-antui": "^0.4.35",
		"nerv-devtools": "^1.5.6",
		"nervjs": "^1.5.6",
		"taro-ui": "^2.2.4"
	},

**Comment by Garfield550** [comment]
taro-ui-demo 的代码很久没有更新了，试试 Clone 本项目然后运行一下？

**Comment by lancerfox** [comment]
> taro-ui-demo 的代码很久没有更新了，试试 Clone 本项目然后运行一下？

重新创建新项目，安装taro-ui依旧存在该问题
