### ISSUE TITLE
AtList className 属性类型定义

### ISSUE THREAD

**Issue by cncolder** [NervJS/taro-ui#940]
**问题描述**
AtList 类型定义中没有 className 属性, 事实上是支持的.

**复现步骤**

```tsx
<AtList className="x" />
```

**期望行为**

**报错信息**

**系统信息**

 - Taro 版本 2.0.2
 - Taro UI 版本 2.0.4
 - 报错平台 weapp

**补充信息**

**Comment by Garfield550** [comment]
`AtList` 的属性继承了 `AtComponent`，所以 `className` 不存在是不应该的，建议在 `node_modules` 里查看一下这两个的定义是否存在，或者删除 `node_modules` 重装一下。

https://github.com/NervJS/taro-ui/blob/7c154083b19522948e8195ee1b9cdae606b40c89/%40types/list.d.ts#L10
