### ISSUE TITLE
引入taro-ui后, 一直停在 正在编译

### ISSUE THREAD

**Issue by kscript** [NervJS/taro-ui#941]
### Taro UI 版本信息

2.2.4

### 问题描述

taro项目可以正常工作, 但只要引入taro-ui的组件后, 就一直停留在 正在编译

### 复现步骤

根据下面的系统信息, 创建新taro项目, 引入taro-ui, 运行命令dev:weapp

### 复现代码

无

### 报错信息

没有报错, 卡在了正在编译

### 系统信息

Taro CLI 2.0.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.8.0 - D:\Program Files (x86)\node-v10.8.0-win-x64\node.EXE
      Yarn: 1.13.0 - D:\Program Files (x86)\node-v10.8.0-win-x64\yarn.CMD
      npm: 6.2.0 - D:\Program Files (x86)\node-v10.8.0-win-x64\npm.CMD

### 补充信息

猜测可能是运行环境问题

**Comment by Garfield550** [comment]
试试 Taro 2.0.5？
