### ISSUE TITLE
在taro next中无法编译

### ISSUE THREAD

**Issue by Singloo** [NervJS/taro-ui#947]
Taro  3.0.0-alpha.1
Taro-ui  2.2.4

按要求在`app.tsx`中引入了
`import 'taro-ui/dist/style/index.scss';`
但是编译不通过
`
Module not found: Can't resolve './style/index.scss' in './node_modules/taro-ui/dist/weapp'
`

taro-ui暂时不支持next版本吗?

**Comment by vinurs** [comment]
升级到taro.next也是遇到了这个问题

**Comment by Garfield550** [comment]
还没有适配，基本方式就是按照 Taro 3 的迁移文档把所有组件都改一下。

**Comment by vinurs** [comment]
有版本计划时间吗？next版本挺好的，但是迁移过来现在就卡在taro-ui上面

**Comment by Garfield550** [comment]
会努力跟进的。

**Comment by eugle** [comment]
Taro v3.0.0-alpha.3也遇到了这个问题

**Comment by wsz7777** [comment]
什么时候可以改完是个大问题啊

**Comment by conkyliu** [comment]
顶起来

**Comment by broven** [comment]
https://github.com/NervJS/taro/issues/5460

**Comment by broven** [comment]
可以出一个计划, 动员一起改起来

**Comment by XQDD** [comment]
> 来自Taro开发交流群`@Goodman`

taro-ui 问题，修复方法

package.json更新依赖：taro-ui: NervJS/taro-ui#next
```json
{
"dependencies": { "taro-ui": "NervJS/taro-ui#next" }
}
```

复制 cp -r ./node_modules/taro-ui/src ./src/taro-ui

修改 config/index.js
```
alias: {
  "taro-ui": path.resolve(__dirname, '../src/taro-ui'),
  "nervjs": path.resolve(__dirname, '../node_modules/react')
}
```

**Comment by conkyliu** [comment]
> ./node_modules/taro-ui/src
只有一个文件哦
![image](https://user-images.githubusercontent.com/26617741/74908173-181c8480-53f0-11ea-874c-e0ee45cefe25.png)

**Comment by vinurs** [comment]
> > 来自Taro开发交流群`@Goodman`
> 
> taro next的taro-ui 问题，临时修复方法
> 
> package.json更新依赖：taro-ui: NervJS/taro-ui#next
> 
> ```json
> {
> "dependencies": { "taro-ui": "NervJS/taro-ui#next" }
> }
> ```
> 
> 复制 cp -r ./node_modules/taro-ui/src ./src/taro-ui
> 
> 修改 config/index.js
> 
> ```js
> const path = require('path')
> const config = {
>   alias: {
>     "taro-ui": path.resolve(__dirname, '../src/taro-ui'),
>     "nervjs": path.resolve(__dirname, '../node_modules/react')
>   },
> }
> ```

我试了一下，确实是可以用的，不过AtCalendar这个组件报
```
Module not found: Can't resolve 'dayjs' in 'src/taro-ui/components/calendar'
```
暂时先注释掉了这个组件

**Comment by conkyliu** [comment]
> > > 来自Taro开发交流群`@Goodman`
> > 
> > 
> > taro next的taro-ui 问题，临时修复方法
> > package.json更新依赖：taro-ui: NervJS/taro-ui#next
> > ```json
> > {
> > "dependencies": { "taro-ui": "NervJS/taro-ui#next" }
> > }
> > ```
> > 
> > 
> > 复制 cp -r ./node_modules/taro-ui/src ./src/taro-ui
> > 修改 config/index.js
> > ```js
> > const path = require('path')
> > const config = {
> >   alias: {
> >     "taro-ui": path.resolve(__dirname, '../src/taro-ui'),
> >     "nervjs": path.resolve(__dirname, '../node_modules/react')
> >   },
> > }
> > ```
> 
> 我试了一下，确实是可以用的，不过AtCalendar这个组件报
> 
> ```
> Module not found: Can't resolve 'dayjs' in 'src/taro-ui/components/calendar'
> ```
> 
> 暂时先注释掉了这个组件

执行  `npm i dayjs` 就可以了

**Comment by vinurs** [comment]
dev:weapp的时候是可以的，但是在yarn build:weapp的时候taro-ui好像没有被编译进去，是额外要配置什么吗？

**Comment by TtTRz** [comment]
按照临时修复方法修复后，按照之前的配置自定义主题是不是会失效。好像要直接把自定义配置要加在迁移出来的taro-ui的index.scss才会生效

**Comment by weixiaoyi** [comment]
以上做法有问题，可看这个 [https://github.com/NervJS/taro-ui/issues/973](url)

**Comment by supermavericks** [comment]
@vinurs install 报错，库被删了吧

**Comment by vinurs** [comment]
> @vinurs install 报错，库被删了吧

😂不知道，这个库更新太慢了，我已经不用taro了，改用uni-app了

**Comment by GarfieldLucy** [comment]
beta.5 还没有修复吗哭唧唧了

**Comment by TechQuery** [comment]
以下版本打包正常：
```JSON
{
    "dependencies": {
        "@tarojs/taro": "3.0.2",
        "react": "^16.10.0",
        "taro-ui": "^3.0.0-alpha.3"
    }
}
```

**Comment by ningkaikok** [comment]
> > @vinurs install 报错，库被删了吧
> 
> 😂不知道，这个库更新太慢了，我已经不用taro了，改用uni-app了
简直机智。taro做个复杂点的应用问题太多了
