### ISSUE TITLE
下个版本的发布时间？

### ISSUE THREAD

**Issue by Anberm** [NervJS/taro-ui#949]
### 这个功能解决了什么问题？

距离上个版本的发布已经过去很长一段时间，在社区的功能请求与bug修复也一直有进行，希望能有个大概的下个版本发布时间点

### 你期望的功能是怎样的？

希望有个计划时间表

**Comment by Garfield550** [comment]
已经在 Milestone 里写了。

**Comment by Anberm** [comment]
> 已经在 Milestone 里写了。

好的，谢谢
