### ISSUE TITLE
tslint -p . --type-check执行类型检查错误

### ISSUE THREAD

**Issue by Thinking80s** [NervJS/taro-ui#950]
**问题描述**

![image](https://user-images.githubusercontent.com/338079/74811608-cced6d80-532c-11ea-9ec7-c0be2954ee0c.png)

**复现步骤**

```js
// 这里可以贴代码
```

**期望行为**

**报错信息**

**系统信息**

**补充信息**

**Comment by Thinking80s** [comment]
![image](https://user-images.githubusercontent.com/338079/74813219-f6f45f00-532f-11ea-9467-a7f00e65be30.png)

**Comment by Thinking80s** [comment]
版本问题"@tarojs/components": "2.0.0","taro-ui": "2.2.1"指定版本

**Comment by Garfield550** [comment]
没有复现，Taro UI 更新到 2.3.0 试一下吧，MovableArea CoverImage 都是 Taro 的组件，可能你需要重新去 Taro 提一下问题。
