### ISSUE TITLE
【严重】Taro-ui 微信小程序input真机表现(设值)异常

### ISSUE THREAD

**Issue by zaleer** [NervJS/taro-ui#951]
Taro UI 版本信息
2.2.4

问题描述
微信小程序中 Atinput 的value， 当setState时候，在【真机】表现下要不就失效，要不就是有延迟设值异常。详情见代码（注: 微信开发模拟工具无问题，请在微信开发工具中 真机调试)

复现步骤
1). 输入一个值后直接点击重置按钮，会出现没反应 
2). 输入一个值后，首先让键盘自动滑下，再次点击重置，会出现 延迟至少3秒以上清空的结果
3).输入框输入值过快，会时不时闪到上个状态的值
复现代码

```
export default class Index extends Component {
  constructor() {
    super(...arguments);
    this.state = {
      value: ""
    };
  }
  handleChange(value) {
    this.setState({
      value
    });
  }
  onSubmit(event) {
    console.log(event);
  }
  onReset(event) {
    console.log(event);
    this.setState({ value: "" });
  }
  render() {
    return (
      <AtForm
        onSubmit={this.onSubmit.bind(this)}
        onReset={this.onReset.bind(this)}
      >
        <AtInput
          name="value"
          title="文本"
          type="text"
          placeholder="单行文本"
          value={this.state.value}
          onChange={this.handleChange.bind(this)}
        />
        <AtButton formType="submit">提交</AtButton>
        <AtButton formType="reset">重置</AtButton>
      </AtForm>
    );
  }
}
```

报错信息
无

系统信息
macos, iphonex

补充信息

**Comment by Limuyang1013** [comment]
我遇到了一模一样的问题，响应state非常慢

**Comment by Limuyang1013** [comment]
我找到解决方案了 https://github.com/NervJS/taro/issues/4532#issue-498109983  不要用onChange，用onInput吧

**Comment by zaleer** [comment]
现在项目没人管了吗

**Comment by Garfield550** [comment]
测试了一下，复现了，问题可能是因为 Taro 的 `triggerEvent` 造成了延迟更新状态问题。

https://github.com/NervJS/taro-ui/blob/d14bd848194d765651c36cc4190ffdcefb0f665a/src/components/button/index.tsx#L63-L79

**Comment by zaleer** [comment]
@Garfield550  那这个问题是列在解决计划中吗？?

**Comment by Garfield550** [comment]
抱歉可能要推后了，我试了一下小程序自定义的 Button 组件即使添加 `behaviors: ['wx://form-field']` 也不能触发 `submit` 和 `reset`

**Comment by zaleer** [comment]
现在是指的微信小程序组件本身也存在这个BUG吗？

**Comment by Garfield550** [comment]
我觉得可能要放弃 AtButton 的 formType 支持，微信文档里明确说了 Button 组件以任何形式包装成自定义组件都无法触发 formType 的任何行为，vant-weapp 也没有支持 formType。

AtButton 之所以能触发是给 AtButton 组件包了一个 Form，然后通过 triggerEvent 的方式触发 AtButton 里 Form 的事件，所以存在一些通信延迟。

**Comment by Garfield550** [comment]
暂时无法处理这个问题，后期可能会取消 AtButton 的 formType 支持。

**Comment by zlyyyy** [comment]
兄弟，有解决方法吗
