### ISSUE TITLE
[bug] Range value改变有时不触发reRender

### ISSUE THREAD

**Issue by jsonz1993** [NervJS/taro-ui#952]
__VERSION__:
```
taro: v2.0.3
taro-ui:2.2.4
```

Range组件有时候改变value属性不触发reRender，原因是Range组件这里判断有问题[/components/range/index.tsx#L96](https://github.com/NervJS/taro-ui/blob/dev/src/components/range/index.tsx#L96)

```jsx 
const [value, update] =  useState([0,50])

setTimeout(() => update([0,30]), 1000)

<AtRange value={value} />
```

**Comment by Garfield550** [comment]
我测试了 Class 组件和 Hooks 写法，都没有复现。

你可以 Clone 一下这个仓库试一下 https://github.com/Garfield550/test-taro-ui-range 。

**Comment by jsonz1993** [comment]
提了个pr 你看下，点击按钮，只有Text变了，Range没变
[https://github.com/Garfield550/test-taro-ui-range/pull/1](https://github.com/Garfield550/test-taro-ui-range/pull/1)
