### ISSUE TITLE
可以不使用Taro，只使用Taro-ui来写H5吗？

### ISSUE THREAD

**Issue by zwl1619** [NervJS/taro-ui#955]
请教一下，可以不使用Taro，只使用Taro-ui来写H5吗？

**Comment by Garfield550** [comment]
不可以，Taro UI 和 Taro 是强依赖性的 。

**Comment by chenyulun** [comment]
@Garfield550 我以为taro-ui可以在h5的react里面使用，那react的方式写小程序的意义变的没那么重要了
