### ISSUE TITLE
 npm run dev:weapp 报错

### ISSUE THREAD

**Issue by CQKylin** [NervJS/taro-ui#957]
错误信息：ENOENT: no such file or directory, open '/Users/***/web/taro-demo/node_modules/@tarojs/components/dist/@tarojs/taro-h5'

环境：
taro: 2.0.5
taro-ui: 2.2.4
H5是正常的

**问题描述**

**复现步骤**

```js
// 这里可以贴代码
```

**期望行为**

**报错信息**

**系统信息**

**补充信息**

**Comment by Garfield550** [comment]
`@tarojs/components` 找不到的话，你需要去 Taro 提这个问题。
