### ISSUE TITLE
触发form表单submit有问题

### ISSUE THREAD

**Issue by ZhyThomas** [NervJS/taro-ui#96]
### 重现步骤
      onSubmit(e){
           console.log(111,e)
      }
              <AtForm
                    onSubmit={this.onSubmit.bind(this)}
                    onReset={this.onReset.bind(this)}
                    reportSubmit
                >
                    <AtInput
                        name='value1'
                        title='文本'
                        type='text'
                        placeholder='单行文本'
                        value={this.state.value1}
                        onChange={this.handleChange.bind(this)}
                    />
                    <AtButton formType='submit' >确定</AtButton>
                </AtForm>

### 依赖的版本号

Node版本号:8.9.3   Taro版本：1.0.0-beta.26    Taro-UI版本：1.2.1
### 预期结果
     点击确定按钮，应触发onSubmit
### 实际结果
    没有触发

**Comment by ZhyGiHub** [comment]
![image](https://user-images.githubusercontent.com/29219116/46253846-32cb2200-c4b8-11e8-9b5b-19eeca67847d.png)
taro-ui的不触发，taro的触发

**Comment by ZhyThomas** [comment]
好吧，应该是微信的问题

**Comment by cos2004** [comment]
开发者工具的展示问题，实际上节点应该是在 form 里面的

**Comment by jimczj** [comment]
经测试，小程序的组件化方案有问题，封装过的input 组件跟 form 组件嵌套，不会触发onSubmit 等等事件，我们将删除 form 组件，并增加说明。使用 AtInput 组件，跟 form 组件配合也有问题，这些都是小程序组件化方案引发的问题

**Comment by jimczj** [comment]
最新版 form 组件说明
![image](https://user-images.githubusercontent.com/13499146/47277395-ac0af000-d5f2-11e8-98d3-cab4f3a7aa18.png)

**Comment by wlancer1** [comment]
我也遇到不触发提交事件的问题

**Comment by kid1412621** [comment]
> 经测试，小程序的组件化方案有问题，封装过的 input 组件跟 form 组件嵌套，不会触发 onSubmit 等等事件，我们将删除 form 组件，并增加说明。使用 AtInput 组件，跟 form 组件配合也有问题，这些都是小程序组件化方案引发的问题

那现在的文档也没说要废弃 Form 组件啊？To be specific ，是 Form 组件 还是 AtForm 组件？？？

**Comment by zongyan86** [comment]
这是什么垃圾控件。。文档没写不会触发啊。。浪费了半天，无语。。AtForm官方demo h5根本都没办法触发submit事件

**Comment by 580** [comment]
以前用v2.1可以用。这次用3.0 alpha 发现报错，一直以为是自己的问题，因为自2.1后没有碰过TaroUI。也是仔细检查了好久上来翻一下issue，才发现好多个相关的issues。

**Comment by Aysnine** [comment]
所以这个 Form 有几把用？不管理 values，不提供 validate，reset 也是自己写，现在连 event 都抛不出来

![image](https://user-images.githubusercontent.com/10137653/92395276-a91d3800-f155-11ea-8bc2-65c8e6db4023.png)

**Comment by UphkcRNqmafQWcSSSSSS** [comment]
> 所以这个 Form 有几把用？不管理 values，不提供 validate，reset 也是自己写，现在连 event 都抛不出来
> 
> ![image](https://user-images.githubusercontent.com/10137653/92395276-a91d3800-f155-11ea-8bc2-65c8e6db4023.png)

哈哈
