### ISSUE TITLE
同步或异步无法控制AtSwitch开关 

### ISSUE THREAD

**Issue by soymikey** [NervJS/taro-ui#961]
"taro-ui": "^2.2.4"

<AtSwitch border={false}
              isSwitch
              color='#006dcc'
              checked={checked}
              title={checked ? '状态:在线' : '状态:下线'}
              onChange={this.handleStatusChange.bind(this)}
            />

handleStatusChange(value) {

   this.setState({checked:false})

  }

当我点击switch的时候，把checked 重新设置成false。 但是switch按钮显示还是开起来的。 是什么原因呀？ 不是应该一直是false 吗？

**Comment by Garfield550** [comment]
> 该组件为受控组件，开发者能通过 checked 来初始化组件开关状态，切换开关时会触发 onChange 函数

虽然有点绕，但是用法可以参考 https://github.com/Garfield550/taro-ui-troubleshooting/tree/issue-961
