### ISSUE TITLE
IOS 端 支付宝打开H5 页面，View、Button等组件连续点击，响应速度会突然变慢，存在卡顿现象

### ISSUE THREAD

**Issue by sam-plus** [NervJS/taro-ui#963]
### Taro UI 版本信息

2.0.0

### 问题描述

IOS 端H5 页面中，View、Button等组件连续点击，响应速度会变慢，存在卡顿

### 复现步骤

1、打开支付，支付宝扫码进入H5页面。
2、连续点击 "按钮1：View test"区域。可以适当停顿和更换点击区域。连续点击几十到上百次后，会发现点击的触发出现卡顿的现象。

### 复现代码

import Taro, { Component, Config } from '@tarojs/taro'
import { View, Button } from '@tarojs/components'
import './index.styl'

interface testPageState {
  num: number
  num1: number
}

export default class Index extends Component<{}, testPageState> {
    public constructor() {
    super(...arguments)
    this.state = {
      num: 0,
      num1: 0
    }
  }
  public testTaroViewZFB() {
    this.setState({
      num: this.state.num   1
    });
  }
  public testTaroButtonZFB() {
    this.setState({
      num1: this.state.num1   1
    });
  }

  render () {
    return (
      <View className='index'>
        <View>view:{this.state.num}</View>
        <View onClick={() => this.testTaroViewZFB()} style="background: green; height: 100px; width: 100%;">按钮1：View test</View>
        <View>button:{this.state.num1}</View>
        <Button onClick={() => this.testTaroButtonZFB()} style="background: green; height: 100px; width: 100%; textAligin: center;">按钮2：Button test</Button>
      </View>
    )
  }
}

### 报错信息

没有报错信息

### 系统信息

Taro v2.0.5

### 补充信息

手机型号、系统、版本： iPhone 6s、IOS、13.3.1
运行项目： 通过taro init myApp 生成的简单demo
安卓系统无法复现。

**Comment by Garfield550** [comment]
你提错位置了，View 和 Button 都是 Taro 那边的组件。

`import { View, Button } from '@tarojs/components'`
