### ISSUE TITLE
AtTabBar current属性报错类型不匹配

### ISSUE THREAD

**Issue by LerLxl** [NervJS/taro-ui#964]
![image](https://user-images.githubusercontent.com/49472459/75767063-21f1a080-5d7d-11ea-9e48-744e2f4ee3ff.png)
![image](https://user-images.githubusercontent.com/49472459/75767071-26b65480-5d7d-11ea-9fe1-740237d46e84.png)
![image](https://user-images.githubusercontent.com/49472459/75767089-2e75f900-5d7d-11ea-972e-ab6f98ab654d.png)
![image](https://user-images.githubusercontent.com/49472459/75767099-333aad00-5d7d-11ea-8739-355601dbeb94.png)

**Comment by Garfield550** [comment]
贴完整代码

**Comment by Garfield550** [comment]
你用的 TypeScript 就要把所有需要的类型都声明出来。 https://github.com/Garfield550/taro-ui-troubleshooting/tree/issue-964
