### ISSUE TITLE
input type=number可以输入string

### ISSUE THREAD

**Issue by alukaa** [NervJS/taro-ui#965]
### Taro UI 版本信息

2.2.4

### 问题描述

如题

### 复现步骤

如题

### 复现代码

如题

### 报错信息

无

### 系统信息

 Taro v2.0.4

  Taro CLI 2.0.4 environment info:
    System:
      OS: Linux 4.19 Debian GNU/Linux 9 (stretch) 9 (stretch)
      Shell: 4.4.12 - /bin/bash
    Binaries:
      Node: 13.8.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.6 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.0.4 => 2.0.4
      @tarojs/components-qa: 2.0.4 => 2.0.4
      @tarojs/mini-runner: 2.0.4 => 2.0.4
      @tarojs/redux: 2.0.4 => 2.0.4
      @tarojs/redux-h5: 2.0.4 => 2.0.4
      @tarojs/router: 2.0.4 => 2.0.4
      @tarojs/taro: 2.0.4 => 2.0.4
      @tarojs/taro-alipay: 2.0.4 => 2.0.4
      @tarojs/taro-h5: 2.0.4 => 2.0.4
      @tarojs/taro-qq: 2.0.4 => 2.0.4
      @tarojs/taro-quickapp: 2.0.4 => 2.0.4
      @tarojs/taro-rn: 2.0.4 => 2.0.4
      @tarojs/taro-swan: 2.0.4 => 2.0.4
      @tarojs/taro-tt: 2.0.4 => 2.0.4
      @tarojs/taro-weapp: 2.0.4 => 2.0.4
      @tarojs/webpack-runner: 2.0.4 => 2.0.4
      eslint-config-taro: 2.0.4 => 2.0.4
      eslint-plugin-taro: 2.0.4 => 2.0.4
      nerv-devtools: ^1.5.5 => 1.5.6
      nervjs: ^1.5.5 => 1.5.6
      stylelint-config-taro-rn: 2.0.4 => 2.0.4
      stylelint-taro-rn: 2.0.4 => 2.0.4

**Comment by alukaa** [comment]
![image](https://user-images.githubusercontent.com/8164389/75888029-ab7c9d80-5e65-11ea-8f6f-db5e15411671.png)

**Comment by marlti7** [comment]
bug没修复吧 怎么就关了？

**Comment by Cyrusky** [comment]
垃圾
