### ISSUE TITLE
请问taro组件文档是怎么建立的？

### ISSUE THREAD

**Issue by summerhll** [NervJS/taro-ui#966]
目前我也想写一个Taro组件库,并为它配备一个文档。但是我不知道要怎么生成文档，想在这里请教下思路，谢谢

**Comment by Garfield550** [comment]
就只是每个组件都用 Markdown 写文档，然后用 Markdown-it 生成 HTML。
个人建议使用 Docusaurus 这种简单的框架来做文档。
