### ISSUE TITLE
Range 位置计算问题

### ISSUE THREAD

**Issue by jsonz1993** [NervJS/taro-ui#969]
版本:
```
taro: 2.0.5
taro-ui: 2.3.0
```

[demo](https://github.com/jsonz1993/test-taro-ui-range/tree/compute-pos)

AtRange只会在componentDidMount的时候计算width与left
如果CDM的时候，父级没有展示出来(dispay:none,pos:a && left:-999px等等)，会取不到预想的值，从而导致组件不正常

**Comment by Garfield550** [comment]
不使用 `isForceUpdatePos` 做开关，总是在 `componentWillReceiveProps` 生命周期里更新属性会有什么影响吗？

**Comment by jsonz1993** [comment]
理论上没影响
就是怕如果有大量的 props change可能会有性能影响（几率不大
做开关最大的初衷是为了不影响现有的使用情况

**Comment by Garfield550** [comment]
我觉得影响不大，可以不用 `isForceUpdatePos`

**Comment by jsonz1993** [comment]
可以啊，那我改一下，这样更方便
