### ISSUE TITLE
AtButton onGetUserInfo多次执行问题

### ISSUE THREAD

**Issue by upbill** [NervJS/taro-ui#97]
### 重现步骤
AtButton type='secondary' open-type='getUserInfo' onGetUserInfo={this.getUserInfo}>按钮</AtButton
![image](https://user-images.githubusercontent.com/9735062/46254370-d1f41780-c4c0-11e8-9ffd-c8988ccd75d8.png)

这是点一次按钮的console, 跑了多次 是我哪里写的不对, 还是bug呢

### 依赖的版本号
Node v10.，Taro 1.0.7，Taro-UI 1.2.3

**Comment by cos2004** [comment]
不能复现，可升级最高版本试试。同时注意检查一下你的代码逻辑是否有可能有执行两次的可能
