### ISSUE TITLE
Drawer 组件 与tabBar在层级上存在冲突

### ISSUE THREAD

**Issue by Zane0816** [NervJS/taro-ui#971]
### Taro UI 版本信息

2.3.0

### 问题描述

Drawer 组件 与tabBar在层级上存在冲突
Chrome 上预览正常

### 复现步骤

1.在 APP的config里设置 tabBar
2.在index 页面添加一个AtDrawer组件
3.显示AtDrawer组件

### 复现代码

无

### 报错信息

无

### 系统信息

 Taro CLI 2.0.5 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.5.0 - /usr/local/bin/node
      Yarn: 1.22.0 - ~/.yarn/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 2.0.5 => 2.0.5 
      @tarojs/cli: 2.0.5 => 2.0.5 
      @tarojs/components: 2.0.5 => 2.0.5 
      @tarojs/components-qa: 2.0.5 => 2.0.5 
      @tarojs/mini-runner: 2.0.5 => 2.0.5 
      @tarojs/mobx: 2.0.5 => 2.0.5 
      @tarojs/mobx-h5: 2.0.5 => 2.0.5 
      @tarojs/router: 2.0.5 => 2.0.5 
      @tarojs/taro: 2.0.5 => 2.0.5 
      @tarojs/taro-alipay: 2.0.5 => 2.0.5 
      @tarojs/taro-h5: 2.0.5 => 2.0.5 
      @tarojs/taro-qq: 2.0.5 => 2.0.5 
      @tarojs/taro-quickapp: 2.0.5 => 2.0.5 
      @tarojs/taro-swan: 2.0.5 => 2.0.5 
      @tarojs/taro-tt: 2.0.5 => 2.0.5 
      @tarojs/taro-weapp: 2.0.5 => 2.0.5 
      @tarojs/webpack-runner: 2.0.5 => 2.0.5 
      eslint-config-taro: 2.0.5 => 2.0.5 
      eslint-plugin-taro: 2.0.5 => 2.0.5 
      nervjs: ^1.5.6 => 1.5.6 

### 补充信息

期望:AtDrawer能在 tabBar 之上
实际:AtDrawer在 tabBar 之下

**Comment by Garfield550** [comment]
很抱歉，不能修复这个问题。通过你的描述，你应该用的是小程序原生 TabBar 吧？小程序原生 TabBar 因为是原生组件，层级是最高的，所以无论页面的元素有多高的 z-index 都不能覆盖小程序原生 TabBar。

引用微信论坛的一句话：
> tabbar是客户端原生的，位于最顶层目前没办法覆盖。如果需要覆盖目前建议自己定制一个tabbar

参考：https://developers.weixin.qq.com/community/develop/doc/000ee4ccd6cfa8a67da76bad251000

![image](https://user-images.githubusercontent.com/3471836/77292571-89b35f80-6d1b-11ea-9376-487b39364e77.png)

**Comment by Garfield550** [comment]
另外 H5 没有问题是因为这个 TabBar 是用 WeUI 样式模拟的 TabBar
![image](https://user-images.githubusercontent.com/3471836/77293430-42c66980-6d1d-11ea-847e-25ad5d367f8b.png)
