### ISSUE TITLE
next分支ts编译结果被复制到项目后报错

### ISSUE THREAD

**Issue by weixiaoyi** [NervJS/taro-ui#973]
项目是最新版taro next apha5.0  ,引入taro ui报错，我试着clone下来taro ui仓库切到next分支，准备用它的编译结果直接复制到项目里来用

1.在src目录执行tsc编译命令
![image](https://user-images.githubusercontent.com/12164278/76147124-05829a80-60d4-11ea-98ac-262a3221e820.png)

2. 编译结果生成到lib文件夹，目前看有482个errors, 令人捉急
![image](https://user-images.githubusercontent.com/12164278/76147153-4b3f6300-60d4-11ea-9b7e-3b0b354f52c0.png)

3.把lib文件夹复制到项目一个新的目录taro_ui,  作为本地依赖使用，报错
![image](https://user-images.githubusercontent.com/12164278/76147179-935e8580-60d4-11ea-9cad-f4c89273eab3.png)

![image](https://user-images.githubusercontent.com/12164278/76147162-76c24d80-60d4-11ea-86b8-14f197240ac8.png)

**Comment by Garfield550** [comment]
Nerv 没有 TS 类型，所以还没改好

**Comment by weixiaoyi** [comment]
> Nerv 没有 TS 类型，所以还没改好

老哥，赶紧搞一个可以用的分支啊，来不及了啊

**Comment by Garfield550** [comment]
最近人手不太够，感兴趣的话可以提 PR 一起来。

**Comment by weixiaoyi** [comment]
> Nerv 没有 TS 类型，所以还没改好

报错原因找到了，是typescript编译出来的结果 target是commonjs，没法被taro导入
![image](https://user-images.githubusercontent.com/12164278/76158208-6cdd3080-614e-11ea-8988-42579b985dd4.png)
把上面三个注释掉，编译到lib, 然后手动把styles复制到lib 就可以啦

**Comment by Garfield550** [comment]
Taro UI 用 `build:component` script 编译，不是 `tsc`
