### ISSUE TITLE
Shall we untag "beta" and "next" on npm?

### ISSUE THREAD

**Issue by Gerhut** [NervJS/taro-ui#975]
**问题描述**
There are "beta" and "next" tags on npm w/ the version earlier than the "latest" version, which may confuse app developers.

**复现步骤**
1. Go to <http://registry.npmjs.org/taro-ui>
2. Scroll down to `dist-tags` field
3. See error

```json
{"latest":"2.3.0","beta":"2.0.0-beta.3","next":"2.0.0-beta.2"}
```

**期望行为**
No "beta" nor "next" tags if there is no plan to release new beta versions.

**报错信息**
N/A

**系统信息**
N/A

**补充信息**
These commands may help you guys with permissions:

```shell
npm dist-tag rm taro-ui beta
npm dist-tag rm taro-ui next
```

Really appreciate!

**Comment by Garfield550** [comment]
removed
