### ISSUE TITLE
AtInput的props.value在render过程中不能设置改变

### ISSUE THREAD

**Issue by 303394539** [NervJS/taro-ui#980]
### Taro UI 版本信息

2.3.0

### 问题描述

AtInput不能通过props.value属性改变wxml中input的value属性，输入框内的值没有改变

### 复现步骤

通过state.value绑定AtInput的props.value属性

### 复现代码

this.setState({
  value: 123
});
<AtInput value={this.state.value} />

### 报错信息

没有错误

### 系统信息

Taro CLI 2.0.6 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.19.0 - ~/.nvm/versions/node/v10.19.0/bin/node
      npm: 6.13.4 - ~/.nvm/versions/node/v10.19.0/bin/npm

**Comment by Garfield550** [comment]
> 该组件为受控组件，开发者需要通过 onChange 事件来更新 value 值变化，value 与 onChange 函数必填。在小程序中，如果想改变 value 的值，需要 return value 从而改变输入框的当前值

https://taro-ui.aotu.io/#/docs/input

**Comment by 303394539** [comment]
2.3.0 在onChange return也会同样的情况，比如限制输入小数点后2位，已经return了，但是输入框显示还是用户输入的多小数位内容，并没有转换，相同的代码，回退到2.2.4版本恢复正常。

**Comment by Garfield550** [comment]
给一个复现用例吧

**Comment by 303394539** [comment]
import Taro, { Component, Config } from '@tarojs/taro';
import { View } from '@tarojs/components';
import { AtInput } from 'taro-ui';

export default class Index extends Component {
  config: Config = {
    navigationBarTitleText: '首页',
  };

  constructor(props) {
    super(props);
    this.state = {};
  }

  onChange = (v) => {
    const $v = v.slice(0, 2);
    console.log($v);
    return $v;
  }

  render() {
    return <AtInput onChange={this.onChange} />
  }
}

**Comment by 303394539** [comment]
<img width="549" alt="image" src="https://user-images.githubusercontent.com/1750965/76720647-5a7b7c00-6778-11ea-89f1-130c3cb787e9.png">
