### ISSUE TITLE
AtSwipeAction 左滑之后会立即关闭

### ISSUE THREAD

**Issue by 15201508996** [NervJS/taro-ui#982]
**问题描述**
企业微信 3.0.14(43356)
iphonexr  ios13.3.1
AtSwipeAction 左滑之后会立即关闭

**复现步骤**
左滑之后会立即关闭

**期望行为**
左滑之后不会立即关闭

**报错信息**
没有

**系统信息**
Taro CLI 1.3.4 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
      Yarn: 1.19.2 - ~/.nvm/versions/node/v10.17.0/bin/yarn
      npm: 6.11.3 - ~/.nvm/versions/node/v10.17.0/bin/npm
    npmPackages:
      @tarojs/components: 1.3.4 => 1.3.4 
      @tarojs/mobx: 1.3.4 => 1.3.4 
      @tarojs/mobx-h5: 1.3.4 => 1.3.4 
      @tarojs/mobx-rn: 1.3.4 => 1.3.4 
      @tarojs/plugin-babel: 1.3.4 => 1.3.4 
      @tarojs/plugin-csso: 1.3.4 => 1.3.4 
      @tarojs/plugin-less: ^1.3.20 => 1.3.37 
      @tarojs/plugin-sass: 1.3.4 => 1.3.4 
      @tarojs/plugin-uglifyjs: 1.3.4 => 1.3.4 
      @tarojs/rn-runner: 1.3.4 => 1.3.4 
      @tarojs/router: 1.3.4 => 1.3.4 
      @tarojs/taro: 1.3.4 => 1.3.4 
      @tarojs/taro-alipay: 1.3.4 => 1.3.4 
      @tarojs/taro-h5: 1.3.4 => 1.3.4 
      @tarojs/taro-swan: 1.3.4 => 1.3.4 
      @tarojs/taro-tt: 1.3.4 => 1.3.4 
      @tarojs/taro-weapp: 1.3.4 => 1.3.4 
      @tarojs/webpack-runner: 1.3.4 => 1.3.4 
      eslint-config-taro: 1.3.4 => 1.3.4 
      eslint-plugin-taro: 1.3.4 => 1.3.4 
      nerv-devtools: ^1.4.0 => 1.4.3 
      nervjs: ^1.4.0 => 1.4.3 
    npmGlobalPackages:
      typescript: 3.7.3

**Comment by 15201508996** [comment]
"taro-ui": "^2.2.1"

**Comment by Wkevin8** [comment]
taro-ui版本是：2.2.1

**Comment by Garfield550** [comment]
![image](https://user-images.githubusercontent.com/3471836/79043079-77985300-7c2f-11ea-878b-ae90be28b9d1.png)

Taro UI 2.3.2 和 Taro 1.3.40 没有复现，可否给个复现用例？
