### ISSUE TITLE
input-number 组件：在微信小程序中可以输入非数字或者不合法数字

### ISSUE THREAD

**Issue by Ivanwangcy** [NervJS/taro-ui#985]
### Taro UI 版本信息

2.3.1

### 问题描述

input-number 组件：在微信小程序中可以输入非数字或者不合法数字
在输入框中可以输入字母，汉字等非数字内容，导致内容非法

### 复现步骤

1. 直接输入字母1aa, 输入框取值就会是： 1aa，取值不是数字；
2. 从别处复制非数字内容“啊啊”，取值是汉字 “啊啊”;
输入非数字后，再点 ➕或者➖，输入框出现 NaN；

### 复现代码

input-number

### 报错信息

NaN

### 系统信息

Taro UI 2.3.1及以下版本

**Comment by Garfield550** [comment]
真机吗？模拟器能输入非数字是正常现象，另外我之前在 issue #965 问题里试过在组件的 `private onInput` 方法里限制只能输入 0-9 和 `.`，有一点点的性能问题出现，所以可能不会对里面的 Input 增加限制。AtInputNumber 有 `onChange`，也许可以试试在这个事件里限制一下。

**Comment by Ivanwangcy** [comment]
> 真机吗？模拟器能输入非数字是正常现象，另外我之前在 issue #965 问题里试过在组件的 `private onInput` 方法里限制只能输入 0-9 和 `.`，有一点点的性能问题出现，所以可能不会对里面的 Input 增加限制。AtInputNumber 有 `onChange`，也许可以试试在这个事件里限制一下。

真机上可以输入多个 `.`，1.2.3.44 ...，我提交了一个 PR 可以解决

**Comment by Garfield550** [comment]
感谢，确实如此

**Comment by Symous** [comment]
AtInput type='number' 在小程序中仍然可以输入字母等，h5正常；
