### ISSUE TITLE
尺寸偏大，switch 是否可以修改他的大小

### ISSUE THREAD

**Issue by yuezonglun** [NervJS/taro-ui#990]
![image](https://user-images.githubusercontent.com/19408097/77415545-9a3c0680-6dfd-11ea-8a87-e9c38c12b375.png)
希望可以自定义它的大小

**Comment by Garfield550** [comment]
通过这篇文章的方法改 https://juejin.im/post/5b051b1c6fb9a07aca7a8676

给你写了一个 Demo https://github.com/Garfield550/taro-ui-troubleshooting/tree/issue-990
![image](https://user-images.githubusercontent.com/3471836/77419054-c312ca80-6e02-11ea-8e22-cd1d5034b6b9.png)
