### ISSUE TITLE
把Taro UI官方示例代码开源一下吧，学习学习

### ISSUE THREAD

**Issue by yplove156** [NervJS/taro-ui#991]
**这个功能解决了什么问题？**

**你期望的功能是怎样的？**

**补充信息**

**Comment by gabryzhong** [comment]
文档的示例代码已经很清晰了,源码那么多行,更头更疼

**Comment by Garfield550** [comment]
示例 Demo 其实就在 src 文件夹，你可以使用 `dev:weapp` 之类的命令去编译查看。
