### ISSUE TITLE
typo ? bug

### ISSUE THREAD

**Issue by xgqfrms** [NervJS/taro-ui#992]
**问题描述**

**复现步骤**

```js
// 这里可以贴代码
```

**期望行为**

**报错信息**

**系统信息**

**补充信息**

***

# 🤣改变海拔高度

![image](https://user-images.githubusercontent.com/7291672/77454183-261c5580-6e33-11ea-8e6e-bc7cb8a2315c.png)

https://taro-ui.aotu.io/#/docs/fab

**Comment by Garfield550** [comment]
想象一下一个按钮漂浮在海面上，选中的时候会上浮，其实就是改变海拔高度的意思。
