### ISSUE TITLE
AtNoticebar 通告栏微信小程序跑马灯无法滚动显示

### ISSUE THREAD

**Issue by Ignorantforce** [NervJS/taro-ui#993]
**问题描述**
根据官网快速上手提示操作，首页index.jsx添加了官方示例代码
`<AtNoticebar marquee>
        这是 NoticeBar 通告栏，这是 NoticeBar 通告栏，这是 NoticeBar 通告栏
      </AtNoticebar>`

另外：h5调试可以正常显示跑马灯效果

**期望行为**
期望小程序能正常显示跑马灯效果

**报错信息**
没有报错

**系统信息**
taro v2.0.7
异常平台：weapp

**Comment by walker27** [comment]
noticebar.scss 中 编译出来的.at-noticebar--weapp .at-noticebar__content-inner  { animation: none } 覆盖了 .at-noticebar--marquee .at-noticebar__content-inner 导致最终渲染时用的animation值为none

**Comment by walker27** [comment]
> noticebar.scss 中 编译出来的.at-noticebar--weapp .at-noticebar__content-inner { animation: none } 覆盖了 .at-noticebar--marquee .at-noticebar__content-inner 导致最终渲染时用的animation值为none

不过也可能时因为noticeBar在小程序中不是使用css动效来完成marquee效果的，我看js源码里面走的是Taro.createAnimation来完成的。

**Comment by Garfield550** [comment]
Taro 2 的问题还是没修，我先用 lint 规则忽略好了
https://github.com/NervJS/taro/blob/3ea2ff6566f709789350591d1d138c2823133206/packages/taro-components/types/common.d.ts#L18-L19
