### ISSUE TITLE
taro-ui node_modules 目录改为软链接指向时，小程序提示Error: Component is not found in path 

### ISSUE THREAD

**Issue by languis** [NervJS/taro-ui#996]
**问题描述**
将 node_modules 改为软链接指向时能编译通过，但是小程序端报错

> 
> 
> 1. taro init
> 2. cnpm install taro-ui
> 3. mv node_modules node_modules.nosync          
> 4. ln -s node_modules.nosync node_modules       
> 5. npm run dev:weapp --watch             
> 

**期望行为**

**报错信息**
![image](https://user-images.githubusercontent.com/14243687/77722182-f5e9d800-7027-11ea-858e-daeba4239580.png)

**系统信息**
👽 Taro v2.0.7

  Taro CLI 2.0.7 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.5.0 - /usr/local/bin/node
      npm: 6.14.4 - /usr/local/bin/npm

 - Taro 版本 v2.0.7
 - Taro UI 版本 v2.3.1
 - 报错平台 weapp

**Comment by Garfield550** [comment]
不支持这样用，而且 Taro CLI 也不支持软链接的文件夹，就连 `yarn link` 过的也不行。
