### ISSUE TITLE
AtTextarea change 事件返回的不是event对象而是值

### ISSUE THREAD

**Issue by Yxliam** [NervJS/taro-ui#999]
**问题描述**
AtTextarea onChange 事件返回的是一个event对象，然后我更新了之后，直接返回的value，没有了event对象，导致生产出了问题

**Comment by Garfield550** [comment]
改了逻辑 https://taro-ui.aotu.io/#/docs/textarea

> 自 Taro UI 2.3.1 版本以后，AtTextarea 的 onChange 事件与 AtInput 保持一致，接收两个参数，函数签名为 onChange: (value: string, event?: CommonEvent | undefined) => void，不再需要使用 event.target.value 获取输入的值。

**Comment by ninetowns** [comment]
真的是太坑了，能这么改吗？？？ 谁没事总注意这个

**Comment by Garfield550** [comment]
以后有 Break 的修改会 bump 中间版本号，比如从 2.3.x 直接到 2.4.x

**Comment by ninetowns** [comment]
就像document.referrer，都知道是拼错了，但能改吗，而且这也不算bug，兼容方式也有很多
请团队充分考虑后再做这种修改

**Comment by Garfield550** [comment]
document.referrer 是哪个问题

**Comment by ninetowns** [comment]
![图片](https://user-images.githubusercontent.com/11746958/79311812-8c772e00-7f30-11ea-8252-21d2400c764a.png)
另外，从官网进去的文档并没有更新
https://taro-ui.jd.com/#/docs/textarea

**Comment by Garfield550** [comment]
Taro UI 的文档有两个站，一个是 taro-ui.aotu.io 另一个是 taro-ui.jd.com。

taro-ui.jd.com 的文档没有更新的问题已经反馈给相关人员了，可能是同步出了问题。
